# generate_batch_9.py
# Generates seed_books_batch_9.sql containing 500 unique book insert statements across 15 genres

from book_metadata_utils import get_rating, get_published_year
import json
import os

genres_data = {
    "Fiction": [
        ("White Teeth", "Zadie Smith", "9780375703867", "Two London WWII veterans Archie Jones and Samad Iqbal navigate multi-generational family complexities in North London."),
        ("On Beauty", "Zadie Smith", "9780143037743", "An Anglo-American liberal family in a New England college town collides with a conservative British art historian's family."),
        ("NW", "Zadie Smith", "9780143123934", "Four locals in Northwest London try to make adult lives outside their council estate childhood."),
        ("Swing Time", "Zadie Smith", "9780143111641", "Two brown girls dream of being dancers, but only one has talent while the other has ideas about black history."),
        ("The Fraud", "Zadie Smith", "9780593541982", "Scottish housekeeper Eliza Touchet follows the famous 19th-century Tichborne Claimant trial in Victorian England."),
        ("Grand Union", "Zadie Smith", "9780525558996", "A broad-ranging short story collection interweaving gender, race, class, and speculative futures."),
        ("The Sense of an Ending", "Julian Barnes", "9780307957122", "Retired Tony Webster revisits his teenage school memories when a diary bequest forces him to re-evaluate his past."),
        ("Flaubert's Parrot", "Julian Barnes", "9780679731375", "Retired doctor Geoffrey Braithwaite becomes obsessed with finding the stuffed parrot that inspired Gustave Flaubert."),
        ("England, England", "Julian Barnes", "9780375705502", "An eccentric entrepreneur builds a theme-park island containing mini versions of all English tourist icons."),
        ("Arthur & George", "Julian Barnes", "9780307263100", "Sir Arthur Conan Doyle investigates the real-life racial injustice case of Anglo-Indian solicitor George Edalji."),
        ("The Noise of Time", "Julian Barnes", "9780451493521", "A fictionalized portrait of Soviet composer Dmitri Shostakovich surviving Stalin's tyrannical demands."),
        ("Elizabeth Finch", "Julian Barnes", "9780593535431", "Neil reflects on his revered lecturer Elizabeth Finch and her obsession with Julian the Apostate."),
        ("Birdsong", "Sebastian Faulks", "9780679776819", "Stephen Wraysford experiences passionate love in pre-war France before surviving the hell of WWI Somme trenches."),
        ("Charlotte Gray", "Sebastian Faulks", "9780375705977", "A young Scottish woman parachutes into occupied France during WWII to rescue her downed RAF lover."),
        ("Girl at the Lion d'Or", "Sebastian Faulks", "9780679776826", "Anne Louvet arrives in a provincial French town in 1936, falling into a secretive affair with married veteran Charles."),
        ("Human Traces", "Sebastian Faulks", "9780375727467", "19th-century alienists Jacques Rebière and Thomas Midwinter build a pioneering psychiatric sanatorium in the Alps."),
        ("Snow Country", "Sebastian Faulks", "9781524711832", "Anton Nesbit travels to an Austrian sanatorium in 1914, connecting with tailor's daughter Lena."),
        ("Where My Heart Used to Beat", "Sebastian Faulks", "9780802124500", "Psychiatrist Robert Hendricks visits a remote Italian island in 1980 to interview aging WWII veteran Alexander Pereira."),
        ("Dinner at the Homesick Restaurant", "Anne Tyler", "9780449911593", "Pearl Tull raises three contrasting children alone in Baltimore after her husband abandons the family."),
        ("The Accidental Tourist", "Anne Tyler", "9780060920043", "Travel writer Macon Leary copes with his son's murder and marriage breakdown through eccentric dog trainer Muriel."),
        ("Breathing Lessons", "Anne Tyler", "9780449911616", "Maggie and Ira Moran take a single day road trip to a funeral, revealing their thirty-year marriage dynamics."),
        ("Ladder of Years", "Anne Tyler", "9780449910572", "Forty-year-old Delia Grinstead walks away from her family during a beach vacation, starting a new life in a small town."),
        ("A Spool of Blue Thread", "Anne Tyler", "9781101874271", "Four generations of the Whitshank family navigate secrets and love inside their beloved Baltimore home."),
        ("French Braid", "Anne Tyler", "9780593321096", "The Garrett family experiences quiet reckonings and distance across decades from 1959 to pandemic times."),
        ("Moon Tiger", "Penelope Lively", "9780241964200", "Dying historian Claudia Hampton narrates her bohemian life, WWII Cairo affair, and family history."),
        ("Passing On", "Penelope Lively", "9780241964217", "Middle-aged siblings Helen and Edward deal with the oppressive legacy of their deceased mother Dorothy."),
        ("Heat Wave", "Penelope Lively", "9780241964224", "Pauline watches her daughter's marriage unravel during a stifling summer at a cottage in the English countryside."),
        ("The Photograph", "Penelope Lively", "9780143034377", "Glyn discovers an old photograph showing his deceased wife Kath holding hands with his sister-in-law's husband."),
        ("How It All Began", "Penelope Lively", "9780143122173", "A street mugging breaks elderly Charlotte's hip, triggering a butterfly-effect chain reaction in multiple lives."),
        ("Family Album", "Penelope Lively", "9780143117568", "The Harper family raises six children in suburban London, keeping dark secrets beneath an ideal exterior."),
        ("Excellent Women", "Barbara Pym", "9780141188263", "Mildred Lathbury is a virtuous clergyman's daughter in 1950s London who gets drawn into neighbors' romantic drama."),
        ("Quartet in Autumn", "Barbara Pym", "9780141188287", "Four single elderly London office workers face retirement, loneliness, and quiet dignity."),
        ("Some Tame Gazelle", "Barbara Pym", "9780141188256", "Middle-aged sisters Belinda and Harriet live peacefully in an English village surrounded by local curates.")
    ],
    "Mystery": [
        ("Raven Black", "Ann Cleeves", "9780312944322", "Inspector Jimmy Perez investigates the strangulation murder of a teenage girl in snow-bound Shetland."),
        ("White Nights", "Ann Cleeves", "9780312384333", "During midsummer midnights in Shetland, an artist's exhibition leads to a body found hanging in a boathouse."),
        ("Red Bones", "Ann Cleeves", "9780312384340", "An archaeological dig on Whalsay uncovers human bones and triggers a mysterious fatal shooting."),
        ("Blue Lightning", "Ann Cleeves", "9780312384357", "Jimmy Perez returns to Fair Isle bird observatory where a prominent bird watcher is murdered."),
        ("Dead Water", "Ann Cleeves", "9781250047397", "Journalist Jerry Markham is found dead in a traditional fishing boat in Shetland's island community."),
        ("Thin Air", "Ann Cleeves", "9781250085818", "A group of old university friends visit Unst to celebrate a wedding, but one guest vanishes."),
        ("Cold Earth", "Ann Cleeves", "9781250143433", "A landslide on Shetland uncovers a dark-haired woman's body in a ruined croft."),
        ("Wild Fire", "Ann Cleeves", "9781250143464", "An English family moves to Shetland seeking a fresh start, only to find a young nanny hanging in their barn."),
        ("The Long Call", "Ann Cleeves", "9781250204448", "Detective Matthew Venn investigates a body found on a Devon beach with an albatross tattoo."),
        ("The Heron's Cry", "Ann Cleeves", "9781250204486", "Matthew Venn investigates an artist killed with a glass shard at an artisan rural trust."),
        ("The Raging Storm", "Ann Cleeves", "9781250204523", "A legendary adventurer's body is found in a lifeboat anchored off Greystone village during a gale."),
        ("Gallows View", "Peter Robinson", "9780060544256", "Inspector Alan Banks settles into North Yorkshire town Eastvale, investigating a voyeur and elderly woman's murder."),
        ("A Dedicated Man", "Peter Robinson", "9780060544263", "A wealthy local historian is found dead beneath a drystone wall in Yorkshire Dales."),
        ("A Necessary End", "Peter Robinson", "9780060544270", "A young police constable is stabbed during an anti-nuclear demonstration in Eastvale."),
        ("The Hanging Valley", "Peter Robinson", "9780060544287", "A hiker finds a corpse with a face destroyed by maggots in a valley near Swainsdale."),
        ("Past Reason Hated", "Peter Robinson", "9780060544294", "Caroline Hartley is found murdered in front of her fireplace on a snowy Yorkshire evening."),
        ("Wed Wednesday", "Peter Robinson", "9780060544300", "Inspector Banks investigates a woman murdered in an antique shop during an Eastvale heatwave."),
        ("Dry Bones That Dream", "Peter Robinson", "9780060544317", "A quiet accountant is shot execution-style in his home by two masked men."),
        ("In a Dry Season", "Peter Robinson", "9780380795246", "Drought drains a reservoir in Yorkshire, revealing the skeleton of a woman murdered in WWII."),
        ("Cold is the Grave", "Peter Robinson", "9780061098659", "Chief Constable Riddle hires Banks off-the-record to rescue his runaway daughter from London drug dens."),
        ("Close to Home", "Peter Robinson", "9780060544331", "Skeletons of two teenage boys who vanished in 1965 are discovered under an old garage foundation."),
        ("Playing with Fire", "Peter Robinson", "9780060544348", "Two arson fires on canal barges kill an artist and a squatter, launching a complex murder investigation."),
        ("The Mermaids Singing", "Val McDermid", "9780312961022", "Clinical psychologist Tony Hill and DI Carol Jordan hunt a serial killer torturing men in Bradfield."),
        ("Wire in the Blood", "Val McDermid", "9780312968397", "Tony Hill analyzes missing teenage girls across decades, realizing a famous celebrity is a serial killer."),
        ("The Last Temptation", "Val McDermid", "9780312984038", "Carol Jordan goes undercover in Euro-crime rings while Tony Hill tracks a killer targeting psychologists."),
        ("Torment of Others", "Val McDermid", "9780312338879", "A prostitute is murdered in the exact style of an incarcerated serial killer Derek Tyler."),
        ("Beneath the Bleeding", "Val McDermid", "9780312384371", "A star star footballer dies of ricin poisoning while a stadium explosion creates mass horror."),
        ("Fever of the Bone", "Val McDermid", "9780312614171", "Tony and Carol investigate teenagers lured via social networking sites to brutal murder sites."),
        ("The Retribution", "Val McDermid", "9781611880526", "Serial killer Jacko Vance escapes prison seeking bloody revenge against Tony Hill and Carol Jordan."),
        ("Cross and Burn", "Val McDermid", "9780802122674", "Tony Hill attempts to rebuild relations with Carol Jordan while a sniper terrorizes Bradfield."),
        ("Splinter the Silence", "Val McDermid", "9780802124579", "Women targeted by internet trolls commit apparent suicides that Tony suspects are murders."),
        ("Insidious Intent", "Val McDermid", "9780802127174", "A wedding killer targets single women at rural receptions, parking their cars with corpses inside."),
        ("How the Dead Speak", "Val McDermid", "9780802148100", "Human bones discovered at an old convent home reveal multiple bodies buried decades apart.")
    ],
    "Thriller": [
        ("The Bourne Identity", "Robert Ludlum", "9780553593549", "An amnesiac man pulled from the Mediterranean with bullet wounds discovers he possesses deadly assassin skills."),
        ("The Bourne Supremacy", "Robert Ludlum", "9780553263220", "Jason Bourne is forced out of retirement in Asia when an impostor assassin kills in his name."),
        ("The Bourne Ultimatum", "Robert Ludlum", "9780553287738", "Bourne faces his arch-nemesis Carlos the Jackal in a final high-stakes global confrontation."),
        ("The Holcroft Covenant", "Robert Ludlum", "9780553272420", "Noel Holcroft inherits $780 million Nazi trust funds meant for Holocaust reparations, uncovering a Fourth Reich plot."),
        ("The Chancellor Manuscript", "Robert Ludlum", "9780553260946", "Novelist Peter Chancellor uncovers a secret syndicate using J. Edgar Hoover's blackmail files."),
        ("The Matarese Circle", "Robert Ludlum", "9780553263237", "American CIA agent Scarlatti and Soviet KGB officer Taleniekov team up against an international assassin cabal."),
        ("The Parsifal Mosaic", "Robert Ludlum", "9780553252705", "State Department strategist Michael Havelock watches his lover shot as a double agent, only to find her alive."),
        ("The Aquitaine Progression", "Robert Ludlum", "9780553249002", "Lawyer Joel Vance uncovers a conspiracy of retired NATO generals plotting military takeover of Western nations."),
        ("The Icarus Agenda", "Robert Ludlum", "9780553273069", "Congressman Evan Kendrick rescues American hostages in Oman, becoming targeted by secret power brokers."),
        ("The Scarlatti Inheritance", "Robert Ludlum", "9780553266399", "Elizabeth Wyckham Scarlatti fights her ruthless son Heinrich who finances Hitler's rise to power."),
        ("The Osterman Weekend", "Robert Ludlum", "9780553266405", "John Tanner is told by the CIA that his close suburban friends are members of a Soviet assassination ring."),
        ("The Day of the Jackal", "Frederick Forsyth", "9780451155320", "A meticulous French OAS plot hires an anonymous English assassin code-named Jackal to kill Charles de Gaulle."),
        ("The Odessa File", "Frederick Forsyth", "9780553271980", "1963 German reporter Peter Miller tracks SS concentration camp commander Eduard Roschmann."),
        ("The Dogs of War", "Frederick Forsyth", "9780553269925", "Mining tycoon Sir James Shannon hires mercenary Cat Shannon to overthrow an African dictatorship."),
        ("The Devil's Alternative", "Frederick Forsyth", "9780553272444", "A Soviet wheat harvest failure leads to global nuclear crisis and a hijacked supertanker."),
        ("The Fourth Protocol", "Frederick Forsyth", "9780553251135", "KGB agent Valeri Petrofsky is sent to assemble a secret nuclear device near an American airbase in Britain."),
        ("The Negotiator", "Frederick Forsyth", "9780553283914", "Expert Quinn negotiates the release of the US President's kidnapped son in Oxfordshire."),
        ("Fist of God", "Frederick Forsyth", "9780553569704", "Major Mike Martin infiltrates Kuwait and Iraq during 1990 Gulf War to stop Saddam's supergun Qubth-ut-Allah."),
        ("Icon", "Frederick Forsyth", "9780553574609", "1999 Russia faces economic collapse, and ex-CIA officer Jason Monk works to stop fascist leader Igor Komarov."),
        ("Avenger", "Frederick Forsyth", "9780312997670", "Calvin Dexter, a Vietnam tunnel rat turned vigilante, tracks a billionaire's grandson murderer to South America."),
        ("The Afghan", "Frederick Forsyth", "9780451221834", "Ex-SAS officer Mike Martin impersonates a Taliban commander to foil an Al-Qaeda attack on an ocean liner."),
        ("The Kill List", "Frederick Forsyth", "9780451419460", "US counter-terrorist operative 'The Tracker' hunts an Islamic preacher inciting lone-wolf murders."),
        ("Raise the Titanic!", "Clive Cussler", "9780061004223", "Dirk Pitt must raise the sunken wreckage of RMS Titanic to recover rare defense mineral Byzantium."),
        ("Vixen 03", "Clive Cussler", "9780061004230", "Dirk Pitt discovers a 1954 military plane crash carrying lethal biological warfare canisters in a Colorado lake."),
        ("Night Probe!", "Clive Cussler", "9780061004247", "Dirk Pitt searches for a lost 1914 treaty that would merge Canada and the United States."),
        ("Deep Six", "Clive Cussler", "9780061004254", "A deadly nerve toxin paralyzes Alaska waters while the US President is brainwashed by a sinister Asian syndicate."),
        ("Cyclops", "Clive Cussler", "9780061004261", "Dirk Pitt investigates blimp crashes, Cuban revolutions, and a secret manned American moon base."),
        ("Treasure", "Clive Cussler", "9780061004278", "Dirk Pitt hunts the lost library of Alexandria while fighting an Islamic extremist plot in Mexico."),
        ("Dragon", "Clive Cussler", "9780061004285", "A rogue Japanese corporate empire places nuclear bombs in major Western sea ports."),
        ("Sahara", "Clive Cussler", "9780061004292", "Dirk Pitt investigates red tide pollution in the Niger river, discovering a 1865 Confederate ironclad in sand dunes."),
        ("Inca Gold", "Clive Cussler", "9780061004308", "Dirk Pitt rescues archaeologists in the Andes, fighting a international antiquities theft ring for Inca treasure."),
        ("Shock Wave", "Clive Cussler", "9780061004315", "Dirk Pitt stops diamond mogul Arthur Doss from destroying Antarctic marine life with acoustic mining waves."),
        ("Flood Tide", "Clive Cussler", "9780061004322", "Dirk Pitt battles Chinese smuggling kingpin Qin Shang who built a massive port facility in Louisiana bayous.")
    ],
    "Romance": [
        ("The Notebook", "Nicholas Sparks", "9780446605236", "Noah Calhoun reads his personal journal to dementia patient Allie Nelson in a coastal care facility."),
        ("A Walk to Remember", "Nicholas Sparks", "9780446608824", "Troubled teen Landon Carter falls in love with minister's daughter Jamie Sullivan, who holds a heartbreaking secret."),
        ("Message in a Bottle", "Nicholas Sparks", "9780446606813", "Theresa Osborne finds a washed-up love letter on a Cape Cod beach, tracking down grieving boat builder Garrett Blake."),
        ("The Rescue", "Nicholas Sparks", "9780446610391", "Volunteer fireman Taylor McAden rescues single mother Denise Holton and her speech-delayed son Kyle in a storm."),
        ("A Bend in the Road", "Nicholas Sparks", "9780446611862", "Widowed deputy Miles Ryan finds love with his son's teacher Sarah Andrews while seeking his wife's hit-and-run driver."),
        ("Nights in Rodanthe", "Nicholas Sparks", "9780446610049", "Adrienne Willis and Dr. Paul Flanner share a life-changing weekend in a North Carolina coastal inn."),
        ("The Guardian", "Nicholas Sparks", "9780446613439", "Young widow Julie Barenson receives a Great Dane puppy named Singer from her late husband, meeting contractor Richard."),
        ("The Wedding", "Nicholas Sparks", "9780446615860", "Wilson Lewis seeks Noah Calhoun's guidance to win back his wife Jane's heart after thirty years of marriage."),
        ("Three Weeks with My Brother", "Nicholas Sparks & Micah Sparks", "9780446695022", "Memoir detailing Nicholas and Micah's three-week global trip following family tragedies."),
        ("True Believer", "Nicholas Sparks", "9780446618151", "Skeptical NYC journalist Jeremy Marsh travels to Boone Creek to investigate ghost lights, falling for Lexie Darnell."),
        ("At First Sight", "Nicholas Sparks", "9780446698429", "Jeremy Marsh and Lexie Darnell navigate marriage, small-town life, and pregnancy complications."),
        ("Dear John", "Nicholas Sparks", "9780446698320", "Army Sergeant John Tyree falls for college student Savannah Curtis, but 9/11 events test their endurance."),
        ("The Choice", "Nicholas Sparks", "9780446618311", "Travis Parker and neighbor Gabby Holland share a Beaufort romance before a tragic accident poses a severe decision."),
        ("The Lucky One", "Nicholas Sparks", "9780446579933", "Marine Logan Thibault finds a photograph of a woman in Iraq, traveling to North Carolina to find Elizabeth."),
        ("The Last Song", "Nicholas Sparks", "9780446579957", "Seventeen-year-old Ronnie Miller spends summer with her estranged father in Wilmington, discovering piano and love."),
        ("Safe Haven", "Nicholas Sparks", "9780446547598", "Katie flees an abusive police husband to quiet Southport, falling for widower store owner Alex."),
        ("The Best of Me", "Nicholas Sparks", "9780446547635", "High school sweethearts Dawson Cole and Amanda Collier reunite in their hometown for a mentor's funeral."),
        ("The Longest Ride", "Nicholas Sparks", "9781455520657", "Ninety-year-old Ira Levinson's car crash story weaves alongside bull rider Luke and art student Sophia."),
        ("Two by Two", "Nicholas Sparks", "9781455526956", "Russell Clisby rebuilds his life as a single father after losing his job and marriage."),
        ("Every Breath", "Nicholas Sparks", "9781455586172", "North Carolina nurse Hope Anderson and Zimbabwean safari guide Tru Walls meet at Sunset Beach."),
        ("The Return", "Nicholas Sparks", "9781538728574", "Injured Navy doctor Trevor Benson returns to his grandfather's North Carolina cabin, falling for deputy Natalie."),
        ("Dreamland", "Nicholas Sparks", "9781538728628", "Musician Colby Mills falls for Morgan Morgan while single mother Beverly flees an abusive husband."),
        ("The Promise", "Danielle Steel", "9780440170792", "Architect Michael Hillyard and artist Nancy McAllister's marriage plans are severed by a car crash and a controlling mother."),
        ("Palomino", "Danielle Steel", "9780440167532", "Samantha Taylor recovers from divorce on a California horse ranch, finding love with wrangler Tate Jordan."),
        ("Remembrance", "Danielle Steel", "9780440173533", "Italian princess Serena Frederick flees WWII Europe for America, rebuilding her life after personal loss."),
        ("Changes", "Danielle Steel", "9780440111825", "TV news anchor Melanie Adams balances her career in New York and romance with LA heart surgeon Peter Hallam."),
        ("Full Circle", "Danielle Steel", "9780440126997", "Tana Roberts grows up through the sixties social turbulence, building a career as a prosecutor."),
        ("Family Album", "Danielle Steel", "9780440124993", "Hollywood actress Faye Price Adams becomes a director, raising five children through changing eras."),
        ("Wanderlust", "Danielle Steel", "9780440193296", "Audrey Driscoll travels the world in the 1930s, working with European refugees during WWII."),
        ("Kaleidoscope", "Danielle Steel", "9780440200925", "Three orphaned sisters separated after WWII tragic deaths are re-assembled by a family friend years later."),
        ("Zoya", "Danielle Steel", "9780440203872", "Russian countess Zoya flees the 1917 revolution to Paris and New York, surviving the Great Depression."),
        ("Star", "Danielle Steel", "9780440205203", "Crystal Wyatt grows up on a California ranch, rising to Hollywood stardom while loving veteran Spencer Hill."),
        ("Daddy", "Danielle Steel", "9780440206507", "Oliver Watson raises three children alone in suburban New York after his wife leaves to attend Harvard.")
    ],
    "Fantasy": [
        ("The Summer Tree", "Guy Gavriel Kay", "9780451458872", "Five Toronto university students are transported to the high fantasy world of Fionavar by mage Loren Silvercloak."),
        ("The Wandering Fire", "Guy Gavriel Kay", "9780451458889", "Fionavar faces eternal winter as Rakoth Maugrim unleashes dark power across the Five Kingdoms."),
        ("The Darkest Road", "Guy Gavriel Kay", "9780451458896", "The final battle in Fionavar as gods, mortals, and mages unite to destroy Rakoth Maugrim."),
        ("Tigana", "Guy Gavriel Kay", "9780451457769", "Rebels fight to reclaim the memory and name of their conquered province Tigana from sorcerer Brandin."),
        ("A Song for Arbonne", "Guy Gavriel Kay", "9780061057861", "Troubadours, courtly love, and religious crusades collide between troubadour south Arbonne and militaristic Gorhaut."),
        ("The Lions of Al-Rassan", "Guy Gavriel Kay", "9780061057335", "A physician, a military commander, and a mercenary captain navigate the reconquest of Moorish Spain analogue."),
        ("Sailing to Sarantium", "Guy Gavriel Kay", "9780061051944", "Mosaicist Crispin is summoned to the glorious capital of Sarantium to decorate a magnificent imperial sanctuary."),
        ("Lord of Emperors", "Guy Gavriel Kay", "9780061051951", "Crispin completes his sanctuary mosaic as intrigue, chariot races, and violence threaten Sarantium's throne."),
        ("The Last Light of the Sun", "Guy Gavriel Kay", "9780451459800", "Anglo-Saxon, Viking, and Celtic analogues clash in a tale of coastal raids, mages, and fairy woods."),
        ("Ysabel", "Guy Gavriel Kay", "9780060880316", "Fifteen-year-old Ned Marriner uncovers a two-thousand-year-old Celtic love triangle in Provence."),
        ("Under Heaven", "Guy Gavriel Kay", "9780451463890", "Shen Tai is gifted 250 Sardian horses for burying dead soldiers, triggering imperial Tang Dynasty court danger."),
        ("River of Stars", "Guy Gavriel Kay", "9780451465078", "Ren Daiyan and poet Lin Shan attempt to reclaim Northern empire lands during Song Dynasty fall."),
        ("Children of Earth and Sky", "Guy Gavriel Kay", "9780451472908", "A young pirate, a female archer, and a painter navigate Renaissance Venice and Ottoman Empire conflicts."),
        ("A Brightness Long Ago", "Guy Gavriel Kay", "9780441003389", "Guidambo Cibo remembers his youth among mercenary leaders and court rivalries in 15th-century Italy."),
        ("All the Seas of the World", "Guy Gavriel Kay", "9780593198087", "Corsair corsair Rafel and former slave Lenia pull off a political assassination that alters sea empire balances."),
        ("Assassin's Apprentice", "Robin Hobb", "9780553573398", "Royal bastard Fitz is trained as a royal assassin while discovering his forbidden animal-mind Skill magic."),
        ("Royal Assassin", "Robin Hobb", "9780553573411", "Fitz defends King Shrewd from Red-Ship Raiders and Prince Regal's court betrayals."),
        ("Assassin's Quest", "Robin Hobb", "9780553565690", "Fitz travels through mountain wilderness to wake the mythical stone Dragons and save the Six Duchies."),
        ("Ship of Magic", "Robin Hobb", "9780553575637", "The Liveship Vivacia awakens as quickwood comes to life while pirate Kennit seeks to unite the Pirate Isles."),
        ("Mad Ship", "Robin Hobb", "9780553575644", "Althea Vestrit and Brashen Trell charter the insane liveship Paragon to rescue captured Vivacia."),
        ("Ship of Destiny", "Robin Hobb", "9780553575651", "Bingtown traders and rain wild dragons battle Chalcedean fleets to win Liveship freedom."),
        ("Fool's Errand", "Robin Hobb", "9780553582444", "Fifteen years later, Fitz and the Fool reunite to rescue Prince Dutiful from Piebald Wit rebels."),
        ("Golden Fool", "Robin Hobb", "9780553582451", "Fitz serves as Skill tutor Lord Golden's bodyguard, coping with court intrigue and Wit prejudice."),
        ("Fool's Fate", "Robin Hobb", "9780553582468", "Fitz journeys to icy Aslevjal island to slay the dragon Icefyre and fulfill the Fool's prophecy."),
        ("Dragon Keeper", "Robin Hobb", "9780061561641", "Deformed dragons and teenage keepers travel up the toxic Rain Wild river seeking lost city Kelsingra."),
        ("Dragon Haven", "Robin Hobb", "9780061561658", "The dragon expedition continues searching for Kelsingra while dragon skills emerge."),
        ("City of Dragons", "Robin Hobb", "9780061561665", "The keepers discover Kelsingra's ancient elderling architecture and protective magic."),
        ("Blood of Dragons", "Robin Hobb", "9780061561672", "Dragons regain full flight and elderling memory, fighting Chalcedean invader armies."),
        ("Fool's Assassin", "Robin Hobb", "9780553392418", "Fitz lives as country gentleman Tom Badgerlock until masked assailants kidnap his daughter Bee."),
        ("Fool's Quest", "Robin Hobb", "9780553392432", "Fitz enters royal court as Prince FitzChivalry, using Skill portals to hunt Bee's kidnappers."),
        ("Assassin's Fate", "Robin Hobb", "9780553392456", "Fitz, the Fool, and Nighteyes travel to Clerres to destroy the Servants and rescue Bee."),
        ("The Dragonbone Chair", "Tad Williams", "9780886773847", "Kitchen boy Simon travels across Osten Ard seeking three magical swords to stop the Undying King."),
        ("Stone of Farewell", "Tad Williams", "9780886774806", "Simon and companions trek across winter lands to gather survivors at the ancient mountain refuge.")
    ],
    "Science Fiction": [
        ("Hyperion", "Dan Simmons", "9780553283686", "Seven pilgrims travel to the Time Tombs on Hyperion to petition the terrifying bladed Shrike creature."),
        ("The Fall of Hyperion", "Dan Simmons", "9780553288209", "AI TechnoCore war and Time Tombs opening threaten the Hegemony of Man across the web."),
        ("Endymion", "Dan Simmons", "9780553572940", "Raul Endymion is tasked with protecting messianic child Aenea from Pax Church Inquisitors."),
        ("The Rise of Endymion", "Dan Simmons", "9780553572988", "Aenea reveals the Shared Reality of the void that binds all consciousness against TechnoCore parasites."),
        ("Ilium", "Dan Simmons", "9780380817924", "Recreated 20th-century scholar Thomas Hockenberry observes the Trojan War enacted by post-human gods on Olympus."),
        ("Olympos", "Dan Simmons", "9780380817931", "Greeks, Trojans, Moravec robots, and post-humans unite against quantum entities and rogue Olympic gods."),
        ("Quarantine", "Greg Egan", "9780061057779", "In 2067, the Solar System is enclosed by an impenetrable alien sphere while detective Laura investigates human neural mods."),
        ("Permutation City", "Greg Egan", "9780061057816", "Paul Durham creates digital copies of human minds running inside virtual cellular automata universes."),
        ("Distress", "Greg Egan", "9780061057700", "Science journalist Andrew Worth covers a physics conference on Stateless artificial island presenting the Theory of Everything."),
        ("Diaspora", "Greg Egan", "9780061057984", "Software human consciousnesses living in digital polises explore higher dimensions when a neutron star collapses."),
        ("Teranesia", "Greg Egan", "9780061020063", "Prabir investigates strange plant and animal mutations on a remote Indonesian island after a military coup."),
        ("Schild's Ladder", "Greg Egan", "9780061050930", "A physics experiment creates a expanding void of novel quantum laws that consumes galaxy sectors."),
        ("Incandescence", "Greg Egan", "9780857662996", "Beings living inside a rocky asteroid orbiting a black hole deduce general relativity principles to survive."),
        ("Zendegi", "Greg Egan", "9781597802871", "A journalist in near-future Iran attempts to build a digital brain upload for his young son."),
        ("Revelation Space", "Alastair Reynolds", "9780441009428", "Archaeologist Dan Sylveste uncovers the extinct Amarantin alien civilization and the terrifying Inhibitor machines."),
        ("Chasm City", "Alastair Reynolds", "9780441010646", "Tanner Mirabel hunts a murderer through the nano-virus ruined gothic city of Yellowstone."),
        ("Redemption Ark", "Alastair Reynolds", "9780441011735", "Nevil Clavain steals ancient super-weapons to save human colonies from the awakening Inhibitors."),
        ("Absolution Gap", "Alastair Reynolds", "9780441012909", "Humanity makes its last stand on cathedral planet Hela against cosmic Inhibitor exterminators."),
        ("The Prefect", "Alastair Reynolds", "9780441017225", "Prefect Tom Dreyfus investigates an attack on a habitat in the Glitter Band surrounding Yellowstone."),
        ("Elysium Fire", "Alastair Reynolds", "9780316555678", "Tom Dreyfus investigates a sudden cybernetic brain melting virus affecting thousands of citizens."),
        ("House of Suns", "Alastair Reynolds", "9780441019182", "Clone-siblings Campion and Purslane return to Gentian Line reunion, discovering six million years of cosmic sabotage."),
        ("Pushing Ice", "Alastair Reynolds", "9780441015023", "Comet-mining ice-hauler Rockhopper follows Saturn's moon Janus as it suddenly breaks orbit as an alien starship."),
        ("Revenger", "Alastair Reynolds", "9780316555548", "Sisters Fura and Adrana Ness join space crew salvage trips among asteroid sun-shards, encountering space pirates."),
        ("Shadow Captain", "Alastair Reynolds", "9780316555593", "Fura Ness captains the Revenger, fleeing solar police while hunting ancient alien tech artifacts."),
        ("Bone Silence", "Alastair Reynolds", "9780316555623", "The Ness sisters uncover the true cycle of human collapse and alien revelations in the Congregation."),
        ("Century Rain", "Alastair Reynolds", "9780441014361", "Archaeologist Verity Auger travels through a wormhole to an alternative 1959 Paris Earth."),
        ("Terminal World", "Alastair Reynolds", "9780441019779", "Quillon flees Spearpoint city across zone levels where physical laws and technologies change."),
        ("Permafrost", "Alastair Reynolds", "9781250303561", "Fixing climate apocalypse by sending digital brain seeds into 2028 Arctic permafrost past."),
        ("Eversion", "Alastair Reynolds", "9780316462785", "Surgeon Silas Coade experiences repeating ship voyages through historical eras, discovering a cosmic simulation."),
        ("Fallen Dragon", "Peter F. Hamilton", "9780446611367", "Corporate mercenary Lawrence Newton attacks alien colony Amulsaa, discovering living dragon creatures."),
        ("Pandora's Star", "Peter F. Hamilton", "9780345461629", "Wormhole network exploration reveals Dyson Pair stars shielded by an aggressive xenophobic alien species Prime."),
        ("Judas Unchained", "Peter F. Hamilton", "9780345461667", "Humanity battles Starflyer alien infiltrators to save the Commonwealth from total assimilation."),
        ("The Dreaming Void", "Peter F. Hamilton", "9780345496539", "The Living Dream cult plans a pilgrimage into the Void at the center of the galaxy.")
    ],
    "Horror": [
        ("The Books of Blood (Vol 1-3)", "Clive Barker", "9780425165584", "Groundbreaking horror short stories written on the flesh of a dead liar at a haunted house crossroad."),
        ("The Damnation Game", "Clive Barker", "9780441135431", "Marty Strauss is hired as bodyguard for billionaire Joseph Whitehead, who made a WWII Faustian pact with Mr. Mamoulian."),
        ("The Hellbound Heart", "Clive Barker", "9780061452888", "Frank Cotton solves the Lemarchand puzzle box, opening portals to the sadomasochistic Cenobites led by Pinhead."),
        ("Weaveworld", "Clive Barker", "9780060935399", "Cal Mooney stumbles upon a magical carpet containing the SeErrorKind world of the Fugue, hunted by Shadow Shope."),
        ("Cabal", "Clive Barker", "9780061452895", "Boone believes he is a serial killer and flees to Midian, an underground sanctuary for monsters."),
        ("The Great and Secret Show", "Clive Barker", "9780060935405", "Jaffe and Fletcher discover the Nuncio liquid in a dead-letter postal office, waging war for Quiddity ocean."),
        ("Imajica", "Clive Barker", "9780060935412", "Gentle, Judith, and assassin Pie 'oh' Pah travel five Dominions to reconcile Earth with the cosmos."),
        ("Thief of Always", "Clive Barker", "9780060572976", "Ten-year-old Harvey Swick travels to Mr. Hood's Holiday House, where every day has four seasons and steals youth."),
        ("Everville", "Clive Barker", "9780060935429", "The second Art novel: Maeve O'Connell's town Everville hosts the opening of the Quiddity dream sea portal."),
        ("Mister B. Gone", "Clive Barker", "9780061562495", "Jakabok Botch, a demon trapped inside the pages of a medieval book, addresses the reader directly."),
        ("The Scarlet Gospels", "Clive Barker", "9780312867782", "Detective Harry D'Amour confronts Pinhead as the Hell Priest overthrows Lucifer in Hell."),
        ("Ghost Story", "Peter Straub", "9780425147580", "The Chowder Society in Milburn, New York, is haunted by a shared secret crime involving a shapeshifting woman."),
        ("Julia", "Peter Straub", "9780425147597", "Julia Lofting buys a London house after her daughter's choking death, haunted by a violent ghost child."),
        ("If You Could See Me Now", "Peter Straub", "9780425147603", "Miles Banyon returns to his valley home twenty years after his cousin Laura was murdered."),
        ("Shadowland", "Peter Straub", "9780425147610", "Tom and Del stay at Black House estate during summer break, learning dark stage magic from Uncle Coleman."),
        ("Floating Dragon", "Peter Straub", "9780425147627", "Hampstead, Connecticut, suffers a chemical spill and the revival of an ancient dragon-like murderous evil."),
        ("Koko", "Peter Straub", "9780425147634", "Four Vietnam veterans track a ritual killer using cards labeled KOKO across Asia."),
        ("Mystery", "Peter Straub", "9780425147641", "Young Tom Pasmore solves a local island murder with retired detective Lamont von Heilitz."),
        ("The Throat", "Peter Straub", "9780425147658", "Tim Underhill returns to Millbrook to investigate Blue Rose serial murders connected to WWII."),
        ("Lost Boy Lost Girl", "Peter Straub", "9780425199343", "Author Timothy Underhill investigates his nephew Mark's disappearance into a haunted house."),
        ("In the Night Room", "Peter Straub", "9780425206904", "Children's author Willy Patrick discovers her dead daughter and life are creations of Timothy Underhill's novel."),
        ("The Doll Who Ate His Mother", "Ramsey Campbell", "9780812516006", "Clare discovers her brother's killer Christopher Kelly eats human flesh in Liverpool."),
        ("The Face That Must Die", "Ramsey Campbell", "9780812516013", "Homophobic paranoid John Horridge embarks on vigilante murder sprees in Liverpool."),
        ("The Parasite", "Ramsey Campbell", "9780812516020", "Rose receives astral projection hauntings tied to a teenage occult ritual in Liverpool."),
        ("The Nameless", "Ramsey Campbell", "9780812516037", "Barbara receives phone calls from her daughter nine years after her ritual kidnapping murder."),
        ("Incarnate", "Ramsey Campbell", "9780812516044", "Five participants in a London sleep experiment see their nightmares manifest in physical reality."),
        ("The Hungry Moon", "Ramsey Campbell", "9780812516051", "Evangelist Diana Grace brings puritanical crusade to Peak District village, unleashing druidic darkness."),
        ("Ancient Images", "Ramsey Campbell", "9780812516068", "Film editor Graham searches for a lost 1930s Karloff and Lugosi horror film associated with real deaths."),
        ("Midnight Sun", "Ramsey Campbell", "9780812516075", "Ben Sterling visits his wife's ancestral Swedish forest home, becoming possessed by frozen cosmic entity."),
        ("Needing Ghosts", "Ramsey Campbell", "9780812516082", "Author Simon experiences surreal dreamlike memory loss while walking through a nightmare town."),
        ("The Count of Eleven", "Ramsey Campbell", "9780812516099", "Jack Orchard finds a chain letter promising luck, embarking on eleven bizarre murders."),
        ("The Long Lost", "Ramsey Campbell", "9780812516105", "Gwynneth invites an eccentric elderly relative to a family reunion, causing psychological madness."),
        ("The One Safe Place", "Ramsey Campbell", "9780812516112", "An American family in Manchester is stalked by a criminal urban family.")
    ],
    "Self-Help": [
        ("Atomic Habits", "James Clear", "9780735211292", "An easy and proven way to build good habits and break bad ones using 1% daily compound improvements."),
        ("Daring Greatly", "Brené Brown", "9781594631221", "How the courage to be vulnerable transforms the way we live, love, parent, and lead."),
        ("The Gifts of Imperfection", "Brené Brown", "9781592858491", "Let go of who you think you're supposed to be and embrace who you are."),
        ("Rising Strong", "Brené Brown", "9780812995824", "If we are brave enough often enough, we will fall; this is a physics of vulnerability process for getting back up."),
        ("Braving the Wilderness", "Brené Brown", "9780812995848", "The quest for true belonging and the courage to stand alone."),
        ("Dare to Lead", "Brené Brown", "9780399592522", "Brave work, tough conversations, and whole hearts in organizational leadership."),
        ("Atlas of the Heart", "Brené Brown", "9781984854032", "Mapping eighty-seven emotions and experiences that define human connection."),
        ("Mindset: The New Psychology of Success", "Carol S. Dweck", "9780345472328", "Fixed versus growth mindset and how belief in adaptability fosters achievement."),
        ("Quiet: The Power of Introverts", "Susan Cain", "9780307352156", "Celebrating introverts in a world that can't stop talking."),
        ("Bittersweet", "Susan Cain", "9780451499783", "How sorrow and longing make us whole and spur creative transformation."),
        ("The Power of Habit", "Charles Duhigg", "9780812981605", "Why we do what we do in life and business based on the Cue-Routine-Reward loop."),
        ("Smarter Faster Better", "Charles Duhigg", "9780812993011", "The transformative science of productivity in teams, motivation, and goal-setting."),
        ("Supercommunicators", "Charles Duhigg", "9780593243916", "How to unlock the secret language of connection in conversation."),
        ("Drive", "Daniel H. Pink", "9781594488849", "The surprising truth about what motivates us: autonomy, mastery, and purpose."),
        ("To Sell Is Human", "Daniel H. Pink", "9781594487156", "The surprising truth about moving others in modern professional and personal life."),
        ("When: The Scientific Secrets of Perfect Timing", "Daniel H. Pink", "9780735210622", "Using science-based timing to optimize performance, health, and decision making."),
        ("The Power of Regret", "Daniel H. Pink", "9780735210653", "How looking backward moves us forward through four core human regret types."),
        ("Deep Work", "Cal Newport", "9781455586691", "Rules for focused success in a distracted world using deep concentration routines."),
        ("So Good They Can't Ignore You", "Cal Newport", "9781455509126", "Why skills trump passion in the quest for work you love."),
        ("Digital Minimalism", "Cal Newport", "9780525536512", "Choosing a focused life in a noisy world through intentional technology philosophy."),
        ("A World Without Email", "Cal Newport", "9780525536550", "Reimagining work in an age of communication overload."),
        ("Slow Productivity", "Cal Newport", "9780593544853", "The lost art of accomplishment without burnout by doing fewer things better."),
        ("The Subtle Art of Not Giving a F*ck", "Mark Manson", "9780062457714", "A counterintuitive approach to living a good life by prioritizing meaningful values."),
        ("Everything Is F*cked", "Mark Manson", "9780062888433", "A book about hope, self-control, and navigating anxiety in modern culture."),
        ("Love Is Not Enough", "Mark Manson", "9780062888440", "Short essays on relationship boundaries, self-awareness, and personal responsibility."),
        ("The Obstacle Is the Way", "Ryan Holiday", "9781591846352", "The timeless art of turning trials into triumph using Stoic philosophy."),
        ("Ego Is the Enemy", "Ryan Holiday", "9781591847816", "The fight to master our greatest opponent: our own pride and illusion."),
        ("Stillness Is the Key", "Ryan Holiday", "9780525538585", "Drawing on Stoic and Buddhist wisdom to cultivate internal quiet amidst noise."),
        ("Courage Is Calling", "Ryan Holiday", "9780593191675", "Fortune favors the brave: standing up to fear in everyday life."),
        ("Discipline Is Destiny", "Ryan Holiday", "9780593191699", "The power of self-control, temperance, and habit mastery."),
        ("Right Thing Right Now", "Ryan Holiday", "9780593191712", "Justice and moral integrity as core pillars of a Stoic life."),
        ("Four Thousand Weeks", "Oliver Burkeman", "9780374159122", "Time management for mortals acknowledging finite life span and choosing what matters."),
        ("The Antidote", "Oliver Burkeman", "9780865479418", "Happiness for people who can't stand positive thinking: embracing uncertainty.")
    ],
    "Biography": [
        ("Steve Jobs", "Walter Isaacson", "9781451648539", "The exclusive biography of Apple co-founder Steve Jobs based on forty interviews."),
        ("Einstein: His Life and Universe", "Walter Isaacson", "9780743264730", "How Albert Einstein's imaginative mind revolted against authority to unlock the cosmos."),
        ("Benjamin Franklin: An American Life", "Walter Isaacson", "9780684807614", "The founding father's journey from printer apprentice to scientist, diplomat, and statesman."),
        ("Leonardo da Vinci", "Walter Isaacson", "9781501139154", "Connecting Leonardo's art, anatomy, optics, and theater to his insatiable curiosity."),
        ("Elon Musk", "Walter Isaacson", "9781398527492", "The intimate story of SpaceX, Tesla, and Neuralink founder Elon Musk."),
        ("The Code Breaker", "Walter Isaacson", "9781982115852", "Jennifer Doudna, gene editing, and the future of the human race through CRISPR."),
        ("Kissinger: A Biography", "Walter Isaacson", "9780743286657", "The comprehensive portrait of Henry Kissinger's cold-war realpolitik diplomacy."),
        ("Innovators", "Walter Isaacson", "9781476708690", "How a group of hackers, geniuses, and geeks created the digital revolution."),
        ("Alexander Hamilton", "Ron Chernow", "9780143034759", "The orphan immigrant who became George Washington's right-hand man and forged American finance."),
        ("Washington: A Life", "Ron Chernow", "9780143119968", "The Pulitzer Prize-winning portrait of George Washington's passion, military campaigns, and presidency."),
        ("Grant", "Ron Chernow", "9780143110637", "Ulysses S. Grant's journey from failed businessman to Union general and Civil Rights President."),
        ("Titan: John D. Rockefeller", "Ron Chernow", "9781400077380", "The life of America's first billionaire and creator of Standard Oil."),
        ("The House of Morgan", "Ron Chernow", "9780802144652", "The rise of modern international finance through the J.P. Morgan banking dynasty."),
        ("The Warburgs", "Ron Chernow", "9780679745235", "The 250-year epic story of a prominent German-Jewish banking family."),
        ("American Lion", "Jon Meacham", "9781400063253", "Andrew Jackson in the White House navigating nullification, Indian Removal, and bank wars."),
        ("Thomas Jefferson: The Art of Power", "Jon Meacham", "9781400067664", "How Jefferson used pragmatism and philosophy to lead the young American republic."),
        ("His Truth Is Marching On", "Jon Meacham", "9781984855022", "Civil rights icon John Lewis's faith and moral courage from Selma to Congress."),
        ("And There Was Light", "Jon Meacham", "9780553393965", "Abraham Lincoln and the American struggle over slavery and democracy."),
        ("Destiny and Power", "Jon Meacham", "9781400067657", "The American life of George Herbert Walker Bush from WWII pilot to 41st President."),
        ("The Power Broker", "Robert A. Caro", "9780394720241", "Robert Moses and the fall of New York: how one un-elected man built modern NYC highways."),
        ("The Path to Power", "Robert A. Caro", "9780679729457", "Volume one of The Years of Lyndon Johnson: Hill Country youth to 1941 Senate race."),
        ("Means of Ascent", "Robert A. Caro", "9780679733713", "Volume two: Lyndon Johnson's controversial 1948 Senate election victory."),
        ("Master of the Senate", "Robert A. Caro", "9780394528367", "Volume three: LBJ's legendary decade transforming the United States Senate."),
        ("The Passage of Power", "Robert A. Caro", "9780679405078", "Volume four: LBJ navigating the vice presidency, JFK assassination, and Civil Rights Act."),
        ("Team of Rivals", "Doris Kearns Goodwin", "9780684824901", "Abraham Lincoln's political genius in appointing his fierce presidential rivals to his cabinet."),
        ("No Ordinary Time", "Doris Kearns Goodwin", "9780684804484", "Franklin and Eleanor Roosevelt and the American homefront during World War II."),
        ("The Bully Pulpit", "Doris Kearns Goodwin", "9781416547860", "Theodore Roosevelt, William Howard Taft, and the Golden Age of muckraking journalism."),
        ("Leadership in Turbulent Times", "Doris Kearns Goodwin", "9781476795928", "Leadership lessons from Abraham Lincoln, Theodore Roosevelt, FDR, and Lyndon B. Johnson."),
        ("Churchill: A Life", "Martin Gilbert", "9780805023961", "The definitive single-volume biography of Winston Churchill by his official biographer."),
        ("Custer's Trials", "T.J. Stiles", "9780307592644", "George Armstrong Custer's life on the frontier and civil war battlefields."),
        ("The First Tycoon", "T.J. Stiles", "9780307271556", "Cornelius Vanderbilt and the epic creation of American steamship and railroad empire."),
        ("The Snowball", "Alice Schroeder", "9780553384611", "Warren Buffett and the business of life: the official authorized biography."),
        ("Shoe Dog", "Phil Knight", "9781501135910", "Nike founder Phil Knight recounts building his athletic shoe startup from a trunk.")
    ],
    "History": [
        ("The Age of Revolution: 1789-1848", "Eric Hobsbawm", "9780679772538", "How the French Revolution and British Industrial Revolution transformed the Western world."),
        ("The Age of Capital: 1848-1875", "Eric Hobsbawm", "9780679772545", "The global expansion of industrial capitalism, bourgeois society, and railroad networks."),
        ("The Age of Empire: 1875-1914", "Eric Hobsbawm", "9780679772552", "Colonial expansion, imperial rivalries, and culture leading up to World War I."),
        ("The Age of Extremes: 1914-1991", "Eric Hobsbawm", "9780679730057", "The short twentieth century from WWI outbreaks to the fall of the Soviet Union."),
        ("The Guns of August", "Barbara W. Tuchman", "9780345386236", "The disastrous first month of World War I and military miscalculations leading to trench stalemate."),
        ("A Distant Mirror", "Barbara W. Tuchman", "9780345349576", "The calamitous 14th century: Black Death, Hundred Years' War, and papal schism."),
        ("The Zimmerman Telegram", "Barbara W. Tuchman", "9780345324252", "The intercepted 1917 German telegram that pushed the United States into WWI."),
        ("The March of Folly", "Barbara W. Tuchman", "9780345308238", "From Troy to Vietnam: history of governments pursuing policies contrary to their own interests."),
        ("The Proud Tower", "Barbara W. Tuchman", "9780345405012", "A portrait of the world before the Great War: 1890-1914 European and American society."),
        ("Stilwell and the American Experience in China", "Barbara W. Tuchman", "9780345315486", "General 'Vinegar Joe' Stilwell and Sino-American wartime relations 1911-1945."),
        ("A People's Tragedy", "Orlando Figes", "9780140243642", "The Russian Revolution 1891-1924: social collapse, autocracy fall, and Bolshevik rise."),
        ("Natasha's Dance", "Orlando Figes", "9780312421953", "A cultural history of Russia covering literature, music, architecture, and folklore."),
        ("The Whisperers", "Orlando Figes", "9780312428037", "Private life in Stalin's Russia: how terror forced millions to live secret double lives."),
        ("Crimea: The Last Crusade", "Orlando Figes", "9780312429768", "The 19th-century Crimean War between Russia, Britain, France, and Ottoman Empire."),
        ("Revolutionary Russia", "Orlando Figes", "9780 Metropolitan Books", "A concise history of Russia's hundred-year revolutionary century from 1891 to 1991."),
        ("The Europeans", "Orlando Figes", "9780525562412", "How railways and copyright built a cosmopolitan European high culture in the 19th century."),
        ("Stalingrad", "Antony Beevor", "9780140284584", "The brutal 1942-1943 Eastern Front battle that turned the tide of World War II."),
        ("Berlin: The Downfall 1945", "Antony Beevor", "9780142003718", "The Red Army's final assault on Hitler's capital and civilian suffering."),
        ("D-Day: The Battle for Normandy", "Antony Beevor", "9780143118183", "The Allied invasion of Normandy from June 6 landings to Paris liberation."),
        ("The Second World War", "Antony Beevor", "9780316023740", "A comprehensive global single-volume history of WWII across all theaters."),
        ("Ardennes 1944", "Antony Beevor", "9780143129844", "Hitler's last major offensive campaign in the snowy Ardennes forest: Battle of the Bulge."),
        ("Russia: Revolution and Civil War", "Antony Beevor", "9780593493861", "The terrifying civil war 1917-1921 between Red and White armies across Russia."),
        ("The Sleepwalkers", "Christopher Clark", "9780061146657", "How Europe went to war in 1914 through diplomatic miscalculations and Balkan crisis."),
        ("Iron Kingdom", "Christopher Clark", "9780674023857", "The rise and downfall of Prussia from 1600 to its post-WWII abolition."),
        ("Time and Power", "Christopher Clark", "9780691181653", "Visions of history in German politics from the Great Elector to the Third Reich."),
        ("Postwar", "Tony Judt", "9780143037750", "A history of Europe since 1945 rebuilding from total devastation to European Union."),
        ("Ill Fares the Land", "Tony Judt", "9780143118763", "Judt's passionate defense of social democracy against free-market individualism."),
        ("The Transformation of the World", "Jürgen Osterhammel", "9780691169804", "A global history of the nineteenth century covering urbanization, empires, and networks."),
        ("The Inheritance of Rome", "Chris Wickham", "9780143117421", "Illuminating the Dark Ages: Western Europe from 400 to 1000 CE."),
        ("Framing the Early Middle Ages", "Chris Wickham", "9780199212965", "Europe and the Mediterranean 400-800 CE studied through economy and social structures."),
        ("Medieval Europe", "Chris Wickham", "9780300222210", "A sweeping new history of the Middle Ages from Rome's fall to the Renaissance."),
        ("The Scramble for Africa", "Thomas Pakenham", "9780380719990", "White man's conquest of the Dark Continent from 1876 to 1912."),
        ("The Boer War", "Thomas Pakenham", "9780380720019", "The bloody 1899-1902 South African conflict between Britain and Afrikaner republics.")
    ],
    "Philosophy": [
        ("Critique of Pure Reason", "Immanuel Kant", "9780140447470", "Kant bridges rationalism and empiricism, defining synthetic a priori knowledge and transcendental idealism."),
        ("Critique of Practical Reason", "Immanuel Kant", "9780521599665", "Kant presents his moral philosophy centered on duty and the categorical imperative."),
        ("Critique of Judgment", "Immanuel Kant", "9780199536962", "Kant examines aesthetics, the sublime, and teleological judgment in nature."),
        ("Groundwork of the Metaphysics of Morals", "Immanuel Kant", "9780521514576", "Act only according to that maxim whereby you can will that it should become a universal law."),
        ("Prolegomena to Any Future Metaphysics", "Immanuel Kant", "9780521531382", "Kant's accessible summary of the Critique of Pure Reason for students."),
        ("Perpetual Peace", "Immanuel Kant", "9780872201859", "Kant's philosophical essay proposing a federation of free republic states to prevent war."),
        ("Science of Logic", "Georg Wilhelm Friedrich Hegel", "9780521832557", "Hegel's masterwork on dialectical logic moving from Being to Essence and Concept."),
        ("Lectures on the Philosophy of History", "Georg Wilhelm Friedrich Hegel", "9780486437996", "World history as the progress of the consciousness of freedom."),
        ("Thus Spoke Zarathustra", "Friedrich Nietzsche", "9780140441185", "Zarathustra proclaims the death of God, the Übermensch, and the Eternal Recurrence."),
        ("Beyond Good and Evil", "Friedrich Nietzsche", "9780140449235", "A prelude to a philosophy of the future attacking traditional moral prejudices and slave morality."),
        ("On the Genealogy of Morals", "Friedrich Nietzsche", "9780679724629", "Three essays tracing master-slave morality origins, guilt, bad conscience, and ascetic ideals."),
        ("The Gay Science", "Friedrich Nietzsche", "9780679724636", "A aphoristic volume introducing the Will to Power and 'God is dead' declaration."),
        ("The Birth of Tragedy", "Friedrich Nietzsche", "9780140433395", "Contrasting Apollonian order and Dionysian chaotic energy in Greek drama."),
        ("Human, All Too Human", "Friedrich Nietzsche", "9780521567046", "Nietzsche's free-spirit book of psychological aphorisms breaking with Wagner and Schopenhauer."),
        ("Daybreak", "Friedrich Nietzsche", "9780521567886", "Thoughts on the prejudices of morality and the liberation of human spirit."),
        ("Twilight of the Idols", "Friedrich Nietzsche", "9780140445145", "How one philosophizes with a hammer: attacking Socrates, Kant, and modern idols."),
        ("The Antichrist", "Friedrich Nietzsche", "9780140445146", "A fierce curse on institutional Christianity and its resentment against noble life."),
        ("Ecce Homo", "Friedrich Nietzsche", "9780140445152", "Nietzsche's autobiographical self-assessment: 'Why I Am So Wise', 'Why I Write Such Good Books'."),
        ("Being and Time", "Martin Heidegger", "9780060638505", "An inquiry into the meaning of Being through the analysis of human existence (Dasein)."),
        ("The Question Concerning Technology", "Martin Heidegger", "9780061319693", "Analyzing modern technology as an 'enframing' (Gestell) that turns nature into standing-reserve."),
        ("What Is Called Thinking?", "Martin Heidegger", "9780060905286", "Lectures on Parmenides, Nietzsche, and the true essence of meditative thought."),
        ("Discourse on Thinking", "Martin Heidegger", "9780061314599", "Gelassenheit: releasement toward things and openness to mystery in a technological age."),
        ("Being and Nothingness", "Jean-Paul Sartre", "9780679723332", "Sartre's masterwork on existential ontology, bad faith, radical freedom, and the Other."),
        ("Existentialism Is a Humanism", "Jean-Paul Sartre", "9780300115468", "Sartre's popular 1945 lecture asserting existence precedes essence and humans are condemned to be free."),
        ("Nausea", "Jean-Paul Sartre", "9780811220309", "Antoine Roquentin experiences overwhelming existential disgust at the physical contingency of objects."),
        ("No Exit", "Jean-Paul Sartre", "9780679725169", "Hell is other people: Garcin, Inez, and Estelle trapped together in a Second Empire drawing room."),
        ("The Wall", "Jean-Paul Sartre", "9780811201896", "Five short existential fiction stories including Spanish Civil War prisoners facing firing squad."),
        ("Critique of Dialectical Reason", "Jean-Paul Sartre", "9781844670772", "Sartre attempts to reconcile existentialist individual freedom with Marxist historical materialism."),
        ("The Myth of Sisyphus", "Albert Camus", "9780679733737", "Confronting the Absurd: Sisyphus pushing his boulder uphill must be imagined happy."),
        ("The Rebel", "Albert Camus", "9780679733744", "An essay on man in revolt against tyranny without resorting to totalitarian terror."),
        ("The Stranger", "Albert Camus", "9780679720201", "Meursault shoots an Arab on an Algiers beach, facing trial for his emotional detachment."),
        ("The Plague", "Albert Camus", "9780679720218", "Dr. Rieux and residents of Oran fight a sudden outbreak of bubonic plague."),
        ("The Fall", "Albert Camus", "9780679720225", "Former lawyer Jean-Baptiste Clamence delivers a confession in an Amsterdam bar.")
    ],
    "Young Adult": [
        ("Looking for Alaska", "John Green", "9780142402511", "Miles 'Pudge' Halter attends Culver Creek boarding school, falling for mysterious Alaska Young."),
        ("An Abundance of Katherines", "John Green", "9780142410707", "Child prodigy Colin Singleton has been dumped by 19 girls named Katherine, seeking a mathematical theorem for love."),
        ("Paper Towns", "John Green", "9780142414934", "Quentin 'Q' Jacobsen follows clues left behind by his missing childhood crush Margo Roth Spiegelman."),
        ("The Fault in Our Stars", "John Green", "9780142424179", "Cancer patients Hazel Grace Lancaster and Augustus Waters share a romance and journey to Amsterdam."),
        ("Turtles All the Way Down", "John Green", "9780525555360", "Sixteen-year-old Aza Holmes navigates severe OCD while investigating a billionaire's disappearance."),
        ("The Anthropocene Reviewed", "John Green", "9780593300862", "Essays rating different facets of the human-centered planet on a five-star scale."),
        ("Eleanor & Park", "Rainbow Rowell", "9781250012579", "Two teenage misfits bond over comic books and punk music on a 1986 Omaha school bus."),
        ("Fangirl", "Rainbow Rowell", "9781250030955", "Cath writes Simon Snow fan fiction while coping with college freshman anxiety and twin sister separation."),
        ("Carry On", "Rainbow Rowell", "9781250135025", "Chosen One Simon Snow and his vampire roommate Baz fight magical monsters at Watford School."),
        ("Wayward Son", "Rainbow Rowell", "9781250146076", "Simon, Baz, and Penelope take an American West Coast road trip after saving the magical world."),
        ("Any Way the Wind Blows", "Rainbow Rowell", "9781250254320", "Simon Snow decides whether he wants to stay part of the World of Mages."),
        ("Landline", "Rainbow Rowell", "9781250049377", "TV writer Georgie discovers a rotary phone that connects her to her husband Neal in the past."),
        ("Attachments", "Rainbow Rowell", "9780425248639", "IT guy Lincoln monitors workplace emails, falling for copy editor Beth through her sent messages."),
        ("Pumpkinheads", "Rainbow Rowell & Faith Erin Hicks", "9781626721623", "Best friends Deja and Josiah work their final autumn shift together at a famous pumpkin patch."),
        ("One of Us Is Lying", "Karen M. McManus", "9781524714680", "Five students walk into detention, but gossip app creator Simon dies before it ends."),
        ("One of Us Is Next", "Karen M. McManus", "9781524714727", "A new Truth or Dare text game targets Bayview High students a year after Simon's death."),
        ("Two Can Keep a Secret", "Karen M. McManus", "9781524714758", "Ellery moves to Echo Ridge where her aunt vanished, dealing with homecoming queen murders."),
        ("The Cousins", "Karen M. McManus", "9780593175828", "Milly, Aubrey, and Jonah Story are invited to work at their disinheriting grandmother's island resort."),
        ("You'll Be the Death of Me", "Karen M. McManus", "9780593175866", "Ivy, Mateo, and Cal ditch school together, stumbling directly onto a murder crime scene."),
        ("Nothing More to Tell", "Karen M. McManus", "9780593175903", "Brynn starts an internship at a true crime show to solve her teacher Mr. Larkin's murder."),
        ("One of Us Is Back", "Karen M. McManus", "9780593485859", "The Bayview Crew unites when a billboard game threatens to expose new deadly secrets."),
        ("The Cruel Prince", "Karen M. McManus & Holly Black", "9780316310277", "Mortal Jude Duarte navigates treacherous High Faerie court politics to win power from Prince Cardan."),
        ("The Wicked King", "Holly Black", "9780316310352", "Jude controls High King Cardan behind the scenes while defending Elfhame from underwater Queen Orlagh."),
        ("The Queen of Nothing", "Holly Black", "9780316310420", "Exiled mortal Queen Jude returns to Elfhame to save her twin sister Taryn and Cardan."),
        ("How the King of Elfhame Learned to Hate Stories", "Holly Black", "9780316540889", "Illustrated backstory tales of Cardan's childhood before and after The Cruel Prince."),
        ("The Stolen Heir", "Holly Black", "9780316592703", "Runaway child Suren (Wren) teams up with Prince Oak on a dangerous quest to the Ice Citadel."),
        ("The Prisoner's Throne", "Holly Black", "9780316592796", "Prince Oak is imprisoned in the north, facing severe political choices between love and kingdom."),
        ("Tithe", "Holly Black", "9781442403390", "Sixteen-year-old Kaye discovers she is a pixie faerie changeling caught between Unseelie court wars."),
        ("Valiant", "Holly Black", "9781442403406", "Val flees to NYC subway tunnels, discovering troll squatter Ravus and dangerous faerie potion addiction."),
        ("Ironside", "Holly Black", "9781442403413", "Kaye must complete an impossible quest given by Queen Sula to free Roiben from his court oath."),
        ("The Coldest Girl in Coldtown", "Holly Black", "9780316125024", "Tana wakes up surrounded by corpses after a vampire party, traveling to quarantine Coldtown to save her ex."),
        ("Book of Night", "Holly Black", "9781255012117", "Charlie Hall is a shadow thief navigating dark magic practitioners whose shadows can act independently."),
        ("White Cat", "Holly Black", "9781416963936", "Cassel Sharpe comes from a family of curse workers whose touch can manipulate emotions and memory.")
    ],
    "Poetry": [
        ("Twenty Love Poems and a Song of Despair", "Pablo Neruda", "9780140186482", "Neruda's passionate 1924 debut celebrating sensuality, longing, and Chilean coastal landscapes."),
        ("100 Love Sonnets", "Pablo Neruda", "9780292705685", "Sonnets dedicated to his wife Matilde Urrutia divided into Morning, Afternoon, Evening, and Night."),
        ("The Heights of Macchu Picchu", "Pablo Neruda", "9780837166940", "Neruda's epic poem connecting his soul with the ancient Inca civilization stone ruins."),
        ("Canto General", "Pablo Neruda", "9780520070868", "A 15-section epic poem of the history, flora, fauna, and political struggles of the Americas."),
        ("Residence on Earth", "Pablo Neruda", "9780811208932", "Surrealist poetry written during Neruda's diplomatic posts in Burma, Ceylon, and Spain."),
        ("Odes to Common Things", "Pablo Neruda", "9780821220801", "Celebrating ordinary objects: tomatoes, socks, scissors, bicycles, and artichokes."),
        ("Book of Questions", "Pablo Neruda", "9781556590412", "316 unanswerable poetic questions exploring nature, dreams, and cosmic mystery."),
        ("Wild Geese", "Mary Oliver", "9780143104377", "Oliver's iconic nature poems reassuring readers: 'You do not have to be good.'"),
        ("American Primitive", "Mary Oliver", "9780316634502", "Pulitzer Prize-winning collection celebrating ponds, sunflowers, black bears, and wilderness love."),
        ("New and Selected Poems", "Mary Oliver", "9780807068779", "Thirty-year milestone collection including 'The Summer Day' ('What is it you plan to do with your one wild and precious life?')."),
        ("Why I Wake Early", "Mary Oliver", "9780807068793", "47 new poems honoring morning light, herons, crickets, and natural gratitude."),
        ("Thirst", "Mary Oliver", "9780807068960", "Grief and spiritual faith poems written following the death of her long-time partner Molly Cook."),
        ("A Thousand Mornings", "Mary Oliver", "9780143124054", "Observational lyrics from Provincetown walks along marshes and ocean shorelines."),
        ("Devotions", "Mary Oliver", "9780399563249", "The definitive curated collection of over 200 poems selected by Mary Oliver herself."),
        ("Upstream", "Mary Oliver", "9780143130086", "Prose essay collection reflecting on Emerson, Whitman, nature walks, and creative work."),
        ("Ariel", "Sylvia Plath", "9780060931728", "Groundbreaking posthumous collection featuring 'Lady Lazarus', 'Daddy', and 'Tulips'."),
        ("The Colossus and Other Poems", "Sylvia Plath", "9780375704468", "Plath's only poetry volume published during her lifetime in 1960."),
        ("Crossing the Water", "Sylvia Plath", "9780060931704", "Transitional poems written between The Colossus and Ariel."),
        ("Winter Trees", "Sylvia Plath", "9780060931711", "Final batch of Plath's poems including her verse play Three Women."),
        ("The Collected Poems", "Sylvia Plath", "9780060909000", "Ted Hughes's chronological edition of Plath's entire poetic body of work."),
        ("The Hawk in the Rain", "Ted Hughes", "9780571086207", "Hughes's dramatic 1957 debut volume celebrating raw animal nature and physical energy."),
        ("Lupercal", "Ted Hughes", "9780571086214", "Famous animal poems including 'Pike', 'An Otter', and 'Hawk Roosting'."),
        ("Crow", "Ted Hughes", "9780571098675", "A apocalyptic poetic myth cycle revolving around the surreal trickster figure Crow."),
        ("Birthday Letters", "Ted Hughes", "9780374525811", "Hughes's deeply personal reflections on his turbulent marriage to Sylvia Plath."),
        ("Tales from Ovid", "Ted Hughes", "9780374525583", "Vibrant verse translations of twenty-four stories from Ovid's Metamorphoses."),
        ("Selected Poems 1957-1994", "Ted Hughes", "9780374524777", "Comprehensive volume spanning Hughes's career as British Poet Laureate."),
        ("The Age of Anxiety", "W.H. Auden", "9780691138152", "Auden's Pulitzer Prize-winning baroque eclogue set in a New York bar during WWII."),
        ("Another Time", "W.H. Auden", "9780394701585", "1940 volume featuring 'Musée des Beaux Arts', 'September 1, 1939', and 'Funeral Blues'."),
        ("For the Time Being", "W.H. Auden", "9780691138169", "Two long philosophical poems: The Sea and the Mirror and a Christmas Oratorio."),
        ("The Shield of Achilles", "W.H. Auden", "9780394701592", "1955 National Book Award winner examining classical myths and modern totalitarian horror."),
        ("The Less Deceived", "Philip Larkin", "9780140585001", "Larkin's 1955 breakthrough collection featuring 'Church Going' and 'Toads'."),
        ("The Whitsun Weddings", "Philip Larkin", "9780140585018", "1964 volume featuring 'An Arundel Tomb', 'MCMXIV', and title train journey poem."),
        ("High Windows", "Philip Larkin", "9780140585025", "Larkin's final collection featuring 'This Be The Verse', 'The Old Fools', and 'Aubade'.")
    ],
    "Classic Literature": [
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "Orphan governess Jane Eyre falls in love with brooding Edward Rochester at Thornfield Hall."),
        ("Shirley", "Charlotte Brontë", "9780141441177", "Independent heiress Shirley Keeldar navigates Luddite industrial riots and romance in Yorkshire."),
        ("Villette", "Charlotte Brontë", "9780141441184", "Lucy Snowe travels to French-speaking Villette to teach at a girls' pensionnat, loving M. Paul Emanuel."),
        ("The Professor", "Charlotte Brontë", "9780141441160", "William Crimsworth seeks his fortune as a schoolmaster in Brussels, marrying pupil Frances Henri."),
        ("Wuthering Heights", "Emily Brontë", "9780141439556", "The passionate, destructive revenge love story between Heathcliff and Catherine Earnshaw on Yorkshire moors."),
        ("The Tenant of Wildfell Hall", "Anne Brontë", "9780141439655", "Helen Graham leaves her abusive alcoholic husband Arthur Huntingdon to protect her young son."),
        ("Agnes Grey", "Anne Brontë", "9780141439693", "Impoverished minister's daughter Agnes Grey works as a governess for snobbish gentry families."),
        ("Middlemarch", "George Eliot", "9780141439549", "Idealistic Dorothea Brooke and Dr. Tertius Lydgate navigate provincial marriages in a changing 1830s town."),
        ("The Mill on the Floss", "George Eliot", "9780141439624", "Passionate Maggie Tulliver and her brother Tom navigate family bankruptcy and tragic river flood."),
        ("Silas Marner", "George Eliot", "9780141439754", "Exiled weaver Silas Marner loses his gold coins but finds redemption raising abandoned golden-haired Eppie."),
        ("Daniel Deronda", "George Eliot", "9780141439839", "Daniel Deronda uncovers his Jewish heritage while supporting unhappy high-society wife Gwendolen Harleth."),
        ("Adam Bede", "George Eliot", "9780141439662", "Honest carpenter Adam Bede loves vain Hetty Sorrel, who faces tragedy after an affair with Arthur Donnithorne."),
        ("Romola", "George Eliot", "9780141439808", "Set in 15th-century Renaissance Florence during Savonarola's religious rule."),
        ("Scenes of Clerical Life", "George Eliot", "9780141439686", "Eliot's debut three stories of provincial English clergy and local community heartbreak."),
        ("Tess of the d'Urbervilles", "Thomas Hardy", "9780141439594", "Tess Durbeyfield suffers ruin from Alec d'Urberville and abandonment by Angel Clare."),
        ("Far from the Madding Crowd", "Thomas Hardy", "9780141439600", "Independent Bathsheba Everdene chooses between Gabriel Oak, William Boldwood, and Frank Troy."),
        ("The Mayor of Casterbridge", "Thomas Hardy", "9780141439785", "Michael Henchard sells his wife at a fair in a drunken rage, rising to mayor before his past ruins him."),
        ("Jude the Obscure", "Thomas Hardy", "9780141439648", "Stonemason Jude Fawley yearns for university education while loving cousin Sue Bridehead."),
        ("The Return of the Native", "Thomas Hardy", "9780141439631", "Eustacia Vye yearns to leave dark Egdon Heath, marrying idealistic Clym Yeobright."),
        ("Under the Greenwood Tree", "Thomas Hardy", "9780141439709", "Tranter Dewy's parish choir battle modernization while Dick Dewy woos new schoolmistress Fancy Day."),
        ("The Woodlanders", "Thomas Hardy", "9780141439853", "Grace Melbury marries sophisticated Dr. Fitzpiers despite loyal timber-merchant Giles Winterborne's love."),
        ("A Pair of Blue Eyes", "Thomas Hardy", "9780141441191", "Elfride Swancourt loves architect Stephen Smith and intellectual Henry Knight with tragic consequences."),
        ("Two on a Tower", "Thomas Hardy", "9780141441207", "Astronomy enthusiast Swithin St. Cleeve shares a secret romance with older Lady Viviette Constantine."),
        ("The Well-Beloved", "Thomas Hardy", "9780141441214", "Sculptor Jocelyn Pierston pursues his ideal concept of beauty across three generations of women."),
        ("North and South", "Elizabeth Gaskell", "9780141439679", "Southern Margaret Hale moves to industrial northern town Milton, clashing with mill owner John Thornton."),
        ("Cranford", "Elizabeth Gaskell", "9780141439723", "Humorous vignettes of single women navigating quiet Victorian village traditions."),
        ("Mary Barton", "Elizabeth Gaskell", "9780141439747", "Manchester working-class trade union struggles and murder during 1840s industrial distress."),
        ("Wives and Daughters", "Elizabeth Gaskell", "9780141439846", "Molly Gibson navigates her father's remarriage, stepsister Cynthia, and squire's son Roger Hamley."),
        ("Ruth", "Elizabeth Gaskell", "9780141441221", "An orphaned seamstress seduced and abandoned with a child is taken in by a compassionate minister."),
        ("Sylvia's Lovers", "Elizabeth Gaskell", "9780141441238", "Whaling port tragic love triangle torn apart by Napoleonic war impressment press-gangs."),
        ("The Woman in White", "Wilkie Collins", "9780141439617", "Drawing teacher Walter Hartright meets a mysterious woman in white on a moonlit London road."),
        ("The Moonstone", "Wilkie Collins", "9780141439730", "Sergeant Cuff investigates the theft of a sacred Indian diamond from a Yorkshire estate."),
        ("No Name", "Wilkie Collins", "9780141439921", "Magdalen Vanstone loses her inheritance due to illegitimacy laws, disguising herself to win it back.")
    ],
    "Non-Fiction": [
        ("The Devil in the White City", "Erik Larson", "9780375725609", "The twin stories of 1893 Chicago World's Fair architect Daniel Burnham and serial killer H.H. Holmes."),
        ("In the Garden of Beasts", "Erik Larson", "9780307408853", "American ambassador William E. Dodd and his daughter Martha witness Hitler's rise to power in 1930s Berlin."),
        ("Dead Wake", "Erik Larson", "9780307408877", "The sinking of the luxury ocean liner RMS Lusitania by a German U-boat in 1915."),
        ("The Splendid and the Vile", "Erik Larson", "9780385348713", "Winston Churchill, his family, and advisors during the 1940-1941 London Blitz bombing campaign."),
        ("Thunderstruck", "Erik Larson", "9781400033461", "Guglielmo Marconi's invention of wireless radio intersects with Dr. Hawley Crippen's murder arrest."),
        ("Isaac's Storm", "Erik Larson", "9780375708275", "Weatherman Isaac Cline and the deadliest hurricane in American history that destroyed Galveston in 1900."),
        ("The Demon of Unrest", "Erik Larson", "9780385348744", "The five chaotic months between Lincoln's election and the Civil War outbreak at Fort Sumter."),
        ("Into Thin Air", "Jon Krakauer", "9780385492089", "Krakauer's eyewitness account of the 1996 Mount Everest disaster that killed eight climbers."),
        ("Into the Wild", "Jon Krakauer", "9780385486804", "The journey and death of Christopher McCandless in the Alaskan wilderness."),
        ("Under the Banner of Heaven", "Jon Krakauer", "9781400032808", "A story of violent faith examining fundamentalist Mormon brothers Lafferty who committed ritual murder."),
        ("Where Men Win Glory", "Jon Krakauer", "9780307386045", "NFL star Pat Tillman's enlistment, service, and friendly-fire death in Afghanistan."),
        ("Missoula", "Jon Krakauer", "9780804170567", "Rape and the justice system in a college town: Montana university cases."),
        ("The Emperor of All Maladies", "Siddhartha Mukherjee", "9781439170915", "A biography of cancer from ancient Egyptian tumor records to modern targeted molecular therapy."),
        ("The Gene: An Intimate History", "Siddhartha Mukherjee", "9781439184005", "The history of genetics from Mendel and Darwin to gene editing and human identity."),
        ("The Song of the Cell", "Siddhartha Mukherjee", "9781476795508", "An exploration of cellular medicine, immunology, and the creation of the new human body."),
        ("The Orchid Thief", "Susan Orlean", "9780375751561", "Laroche's poaching of rare ghost orchids in Florida Fakahatchee Strand swamps."),
        ("The Library Book", "Susan Orlean", "9781476740195", "The mysterious 1986 Los Angeles Public Library fire and the cultural role of libraries."),
        ("Rin Tin Tin", "Susan Orlean", "9781439190142", "The life of the famous German Shepherd rescue dog who became an international film star."),
        ("On Animals", "Susan Orlean", "9781982181536", "Fifteen essays celebrating human connections with dogs, whales, chickens, and show mules."),
        ("The Immortal Life of Henrietta Lacks", "Rebecca Skloot", "9781400052189", "How HeLa cancer cells taken without consent in 1951 transformed modern medical science."),
        ("The Warmth of Other Suns", "Isabel Wilkerson", "9780679763888", "The epic story of America's Great Migration of six million Black citizens from the South."),
        ("Caste: The Origins of Our Discontents", "Isabel Wilkerson", "9780593230251", "Examining how America is shaped by an unspoken caste system alongside India and Nazi Germany."),
        ("Say Nothing", "Patrick Radden Keefe", "9780307279293", "A true story of murder and memory in Northern Ireland surrounding Jean McConville's disappearance."),
        ("Empire of Pain", "Patrick Radden Keefe", "9780385545686", "The secret history of the Sackler dynasty and OxyContin opioid epidemic."),
        ("Rogues", "Patrick Radden Keefe", "9780593466322", "Twelve true stories of grifters, killers, rebels, and crooks from New Yorker writer Keefe."),
        ("The Right Stuff", "Tom Wolfe", "9780312421618", "Military test pilots and Mercury Seven astronauts in the early American space program."),
        ("Radical Chic & Mau-Mauing the Flak Catchers", "Tom Wolfe", "9780312429133", "Wolfe's famous satire on high-society New York liberals hosting Black Panther fundraisers."),
        ("The Electric Kool-Aid Acid Test", "Tom Wolfe", "9780312427597", "Ken Kesey and the Merry Pranksters bus trip across 1960s psychedelic America."),
        ("In Cold Blood", "Truman Capote", "9780679745587", "The pioneering non-fiction novel detailing the 1959 murder of the Clutter family in Holcomb, Kansas."),
        ("Midnight in the Garden of Good and Evil", "John Berendt", "9780679751526", "Savannah eccentric society and the murder trials of antique dealer Jim Williams."),
        ("Helter Skelter", "Vincent Bugliosi & Curt Gentry", "9780393322231", "Prosecutor Bugliosi's true crime account of the Manson Family murders."),
        ("Killers of the Flower Moon", "David Grann", "9780307742483", "The Osage Indian murders in 1920s Oklahoma and the birth of J. Edgar Hoover's FBI."),
        ("The Wager", "David Grann", "9780593467152", "A tale of shipwreck, mutiny, and court martial aboard HMS Wager in Patagonia.")
    ]
}

def escape_sql(text):
    return text.replace("'", "''")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "seed_books_batch_9.sql")
    
    total_books = 0
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- PageMind Database Seed Script: Batch 9 of 10 (500 Books across 15 Genres)\n")
        f.write("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
        f.write("USE pagemind;\n\n")
        
        for genre, books in genres_data.items():
            f.write(f"-- =======================================================\n")
            f.write(f"-- Genre: {genre} ({len(books)} books)\n")
            f.write(f"-- =======================================================\n")
            for title, author, isbn, desc in books:
                t_esc = escape_sql(title)
                a_esc = escape_sql(author)
                d_esc = escape_sql(desc)
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
                
                # Build buy links JSON
                search_term = f"{title} {author}".replace(" ", "%20")
                buy_links = {
                    "amazon": f"https://www.amazon.in/s?k={search_term}",
                    "flipkart": f"https://www.flipkart.com/search?q={search_term}"
                }
                buy_json = escape_sql(json.dumps(buy_links))
                
                pub_year = get_published_year(title, author, genre, desc, isbn)

                
                rating = get_rating(title, author)

                
                sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{t_esc}', '{a_esc}', '{genre}', '{d_esc}', '{cover_url}', '{buy_json}', {pub_year}, {rating});\n"
                f.write(sql)
                total_books += 1
            f.write("\n")
            
    print(f"Successfully generated {output_path} with {total_books} book insert statements across {len(genres_data)} genres!")

if __name__ == "__main__":
    main()
