from book_metadata_utils import get_rating, get_published_year
import json
import urllib.parse
import os

# Batch 6: 500 Real, Published Books across 15 Genres (33-34 books per genre)
# Deep-catalog titles completely distinct from Batches 1, 2, 3, 4, and 5.

GENRE_DATA_BATCH_6 = {
    "Fiction": [
        ("A Gentleman in Moscow", "Amor Towles", "9780735221673", "Count Alexander Rostov is sentenced to spend his life inside the luxurious Hotel Metropol in 1922 Moscow."),
        ("Rules of Civility", "Amor Towles", "9780143121169", "Katey Kontent navigates high-society Manhattan in 1938 after a chance meeting at a jazz club."),
        ("The Lincoln Highway", "Amor Towles", "9780735222151", "Eighteen-year-old Emmett Watson is driven home to Nebraska after serving time, embarking on a ten-day cross-country journey."),
        ("Bel Canto", "Ann Patchett", "9780060838720", "An opera singer and international guests are taken hostage at a vice-presidential home in South America."),
        ("State of Wonder", "Ann Patchett", "9780062049810", "Dr. Marina Singh travels into the Amazon basin to track down her former mentor and a secret drug trial."),
        ("Commonwealth", "Ann Patchett", "9780062491794", "A chance romantic encounter at a christening party entangles two families over five decades."),
        ("The Dutch House", "Ann Patchett", "9780062963673", "Maeve and Danny Conroy reflect on their childhood estate in Philadelphia and their stepmother's exile."),
        ("Tom Lake", "Ann Patchett", "9780063327528", "Lara tells her three daughters about her youth as an actress and her romance with famous actor Peter Duke."),
        ("Patron Saint of Liars", "Ann Patchett", "9780061990267", "Pregnant Rose leaves her husband and flees to a Catholic home for unwed mothers in Kentucky."),
        ("Taft", "Ann Patchett", "9780061990274", "John Nickel manages a Memphis bar and becomes involved in the turbulent lives of two teenage siblings."),
        ("The Magician's Assistant", "Ann Patchett", "9780061990250", "Sabine, widow of magician Parsifal, uncovers her late husband's secret past family in Nebraska."),
        ("Run", "Ann Patchett", "9780061340642", "A snowstorm in Boston forces a politician's family and an unexpected mother and daughter together."),
        ("A Long Petal of the Sea", "Isabel Allende", "9781984820150", "Victor Dalmau and Roser Bruguera flee the Spanish Civil War aboard a rescue ship to Chile."),
        ("Violeta", "Isabel Allende", "9780593498583", "A woman lives through one hundred years of world events, from the 1920 influenza to the 2020 pandemic."),
        ("The Wind Knows My Name", "Isabel Allende", "9780593598108", "Connecting a Jewish boy escaping Nazi Austria in 1938 with a Salvadoran girl seeking asylum in 2019 US."),
        ("The Japanese Lover", "Isabel Allende", "9781501116988", "Alma Belasco conceals a lifelong secret love affair with Japanese gardener Ichimei Fukuda."),
        ("Ripper", "Isabel Allende", "9780062291417", "Teenager Amanda plays an online murder mystery game that intersects with real serial killings in San Francisco."),
        ("Inés of My Soul", "Isabel Allende", "9780061149559", "Inés Suárez travels to the New World in 1537 and helps conquer Chile alongside Pedro de Valdivia."),
        ("Zorro", "Isabel Allende", "9780060778989", "The origin story of Diego de la Vega becoming the masked hero Zorro in California and Spain."),
        ("The Infinite Plan", "Isabel Allende", "9780060924980", "Gregory Reeves grows up in a itinerant preacher's family and seeks his destiny in Hispanic Los Angeles."),
        ("Of Love and Shadows", "Isabel Allende", "9781501117039", "Journalist Irene Beltrán uncovers political executions during Pinochet's military dictatorship in Chile."),
        ("The Remains of the Day", "Kazuo Ishiguro", "9780679731726", "Elderly butler Stevens reflects on his decades of loyal service at Darlington Hall and lost personal love."),
        ("Never Let Me Go", "Kazuo Ishiguro", "9781400078776", "Kathy, Tommy, and Ruth grow up at Hailsham boarding school, discovering their tragic purpose in society."),
        ("Klara and the Sun", "Kazuo Ishiguro", "9780593318171", "An Artificial Friend named Klara observes human nature while caring for a sick teenage girl."),
        ("The Buried Giant", "Kazuo Ishiguro", "9780307271082", "An elderly Saxon couple set out across a misty post-Arthurian Britain where collective memory is lost."),
        ("An Artist of the Floating World", "Kazuo Ishiguro", "9780679722663", "Retired painter Masuji Ono revisits his propaganda art career in post-WWII recovering Japan."),
        ("A Pale View of Hills", "Kazuo Ishiguro", "9780679722670", "Etsuko, a Japanese widow living in England, remembers her life in Nagasaki following her daughter's suicide."),
        ("The Unconsoled", "Kazuo Ishiguro", "9780679735878", "Concert pianist Ryder arrives in a dreamlike Central European city to perform an unspecified performance."),
        ("When We Were Orphans", "Kazuo Ishiguro", "9780375724497", "1930s London detective Christopher Banks travels to war-torn Shanghai to solve his parents' disappearance."),
        ("Nocturnes", "Kazuo Ishiguro", "9780307455796", "Five short stories exploring music, nightfall, and long-standing personal relationships."),
        ("Cannery Row", "John Steinbeck", "9780140177381", "The colorful inhabitants of a Monterey street during the Great Depression gather to throw a party for Doc."),
        ("Sweet Thursday", "John Steinbeck", "9780140187526", "Doc returns to Cannery Row after WWII and his eccentric friends try to help him find love."),
        ("Tortilla Flat", "John Steinbeck", "9780140187403", "Danny and his paisano companions live a carefree, chivalric life in the hills above Monterey.")
    ],

    "Mystery": [
        ("A Judgement in Stone", "Ruth Rendell", "9780307455017", "Eunice Parch killed the Coverdale family because she could not read or write."),
        ("From Doon with Death", "Ruth Rendell", "9780099496464", "Inspector Wexford investigates the strangulation of a modest housewife with a hidden collection of poetry."),
        ("To Fear a Painted Devil", "Ruth Rendell", "9780099515562", "A neighborhood garden party in a quiet village turns deadly when Patrick Selby dies under suspicious circumstances."),
        ("Vanishing Point", "Ruth Rendell", "9780099581970", "A young woman vanishes from her home, leading investigators into a web of domestic secrets."),
        ("A Demon in My View", "Ruth Rendell", "9780307455031", "Arthur Johnson keeps a mannequin in his cellar to suppress his murderous compulsions until a new tenant moves in."),
        ("A Sleeping Life", "Ruth Rendell", "9780099496532", "Inspector Wexford investigates an unidentified woman stabbed to death near a rural English village."),
        ("The Lake of Darkness", "Ruth Rendell", "9780307455055", "Martin Land satisfies his conscience by giving away lottery winnings, attracting a hitman's obsession."),
        ("Master of the Moor", "Ruth Rendell", "9780307455062", "Stephen Whalby finds the body of a young woman on the desolate moor, making him the prime suspect."),
        ("The Tree of Hands", "Ruth Rendell", "9780307455079", "A grieving mother's mentally ill parent kidnaps a child, entangling two very different families."),
        ("Live Flesh", "Ruth Rendell", "9780307455086", "Victor Jenner is released from prison after shooting a police officer and stalks his victim's fiancee."),
        ("Talking to Strange Men", "Ruth Rendell", "9780307455093", "Schoolboys playing a mock spy game accidentally intercept coded messages from real criminals."),
        ("Going Wrong", "Ruth Rendell", "9780307455109", "Guy Curran's childhood obsession with Leonora drives him into dangerous obsessive insanity."),
        ("Whose Body?", "Dorothy L. Sayers", "9780062196293", "Lord Peter Wimsey investigates a nude corpse wearing nothing but a pince-nez in a Battersea bathtub."),
        ("Clouds of Witness", "Dorothy L. Sayers", "9780062196309", "Lord Peter Wimsey defends his brother, the Duke of Denver, charged with murder at a shooting lodge."),
        ("Unnatural Death", "Dorothy L. Sayers", "9780062196316", "Lord Peter Wimsey and Miss Climpson investigate an elderly woman's mysterious death before changing her will."),
        ("The Unpleasantness at the Bellona Club", "Dorothy L. Sayers", "9780062196323", "General Fentiman dies in his armchair at a London gentleman's club on Armistice Day."),
        ("Strong Poison", "Dorothy L. Sayers", "9780062196330", "Lord Peter Wimsey falls in love with mystery writer Harriet Vane while investigating her murder trial."),
        ("The Five Red Herrings", "Dorothy L. Sayers", "9780062196347", "An unpopular artist is murdered in a Scottish colony, leaving six suspects with valid alibis."),
        ("Have His Carcase", "Dorothy L. Sayers", "9780062196354", "Harriet Vane finds a man's throat cut on a secluded beach, teaming up with Lord Peter Wimsey."),
        ("Murder Must Advertise", "Dorothy L. Sayers", "9780062196361", "Lord Peter Wimsey goes undercover at Pym's Publicity advertising agency after a copywriter's death."),
        ("The Nine Tailors", "Dorothy L. Sayers", "9780062196378", "Church bell ringing, flooding in the Fens, and an unidentified body in a grave engage Lord Peter Wimsey."),
        ("Gaudy Night", "Dorothy L. Sayers", "9780062196385", "Harriet Vane investigates poison pen letters and vandalism at Oxford's Harriet's alma mater college."),
        ("Busman's Honeymoon", "Dorothy L. Sayers", "9780062196392", "Lord Peter Wimsey and Harriet Vane find the former owner murdered in their new country house cellar."),
        ("Cover Her Face", "P.D. James", "9780307474025", "Adam Dalgliesh investigates the murder of a housemaid at a country manor in Essex."),
        ("A Mind to Murder", "P.D. James", "9780307474032", "Dalgliesh is called to a psychiatric clinic in London after an administrative officer is stabbed."),
        ("Unnatural Causes", "P.D. James", "9780307474049", "A mystery writer is found dead in a dinghy with both hands severed on a Suffolk beach."),
        ("Shroud for a Nightingale", "P.D. James", "9780307474056", "Two student nurses die under suspicious circumstances during training at Nightingale House."),
        ("The Black Tower", "P.D. James", "9780307474063", "Dalgliesh visits a home for the disabled in Dorset, arriving just after suspicious deaths."),
        ("Death of an Expert Witness", "P.D. James", "9780307474070", "A senior forensic biologist is murdered inside his laboratory in East Anglia."),
        ("Innocent Blood", "P.D. James", "9780307474087", "Adopted Philippa Palfrey traces her biological parents, unlocking dark criminal history."),
        ("The Skull Beneath the Skin", "P.D. James", "9780307474094", "Private investigator Cordelia Gray is hired to protect an actress on an island castle."),
        ("A Taste for Death", "P.D. James", "9780307474100", "A former minister and a vagrant are found with their throats cut inside a London church vestry."),
        ("Devices and Desires", "P.D. James", "9780307474117", "A serial killer terrorizes Norfolk near a nuclear power station during Dalgliesh's vacation.")
    ],

    "Thriller": [
        ("Tell No One", "Harlan Coben", "9780385335690", "Dr. David Beck receives an anonymous email containing a password only he and his murdered wife knew."),
        ("Gone for Good", "Harlan Coben", "9780385336680", "Will Klein's brother disappeared eleven years ago, and now his girlfriend vanishes without a trace."),
        ("No Second Chance", "Harlan Coben", "9780385336697", "Dr. Marc Seidman wakes up from a coma to discover his wife is dead and his baby daughter kidnapped."),
        ("Just One Look", "Harlan Coben", "9780385337779", "Grace Lawson develops a batch of family photos and finds an old photograph showing a strange young woman."),
        ("The Woods", "Harlan Coben", "9780385340427", "Paul Copeland investigates a corpse that might be tied to his sister's disappearance twenty years ago."),
        ("Hold Tight", "Harlan Coben", "9780385340434", "Parents install spyware on their son's computer after his friend commits suicide, uncovering dark suburban secrets."),
        ("Caught", "Harlan Coben", "9780385343824", "A reporter exposes sexual predators online, leading to a high school stepmother's disappearance."),
        ("Stay Close", "Harlan Coben", "9780385343831", "Three adults living comfortable lives hide dark pasts that resurface when a man vanishes."),
        ("Six Years", "Harlan Coben", "9780525953487", "Jake Fisher watches the love of his life marry another man, but six years later finds her husband murdered."),
        ("Missing You", "Harlan Coben", "9780525953494", "Detective Kat Donovan finds her ex-fiance's profile on a dating site, leading to a sinister kidnapping ring."),
        ("Fool Me Once", "Harlan Coben", "9780525955092", "Maya sees her supposedly murdered husband playing with their daughter on a nanny cam video."),
        ("Don't Let Go", "Harlan Coben", "9780525955115", "Detective Napoleon Dumas investigates a double murder connected to his twin brother's death years ago."),
        ("Run Away", "Harlan Coben", "9781538748466", "Simon searches for his addicted runaway daughter Paige, falling into a dangerous underworld."),
        ("The Boy from the Woods", "Harlan Coben", "9781538748480", "Wilde, a feral child raised in the woods, uses his tracking skills to find a missing teenage girl."),
        ("Win", "Harlan Coben", "9781538748541", "Billionaire adventurer Win investigates a cold case art theft involving his family."),
        ("I Will Find You", "Harlan Coben", "9781538748589", "David Burroughs serves a life sentence for murdering his son until evidence shows the boy is still alive."),
        ("The Andromeda Strain", "Michael Crichton", "9781101974490", "A team of scientists race against time in an underground laboratory to neutralize an extraterrestrial microbe."),
        ("Congo", "Michael Crichton", "9781101974506", "An expedition into the African jungle searches for industrial diamonds while hunted by killer gorillas."),
        ("Sphere", "Michael Crichton", "9781101974513", "Scientists enter a massive spacecraft submerged on the Pacific ocean floor, encountering a mind-reading sphere."),
        ("Jurassic Park", "Michael Crichton", "9781101974520", "Genetically engineered dinosaurs on a remote Costa Rican island escape containment during a power failure."),
        ("Rising Sun", "Michael Crichton", "9781101974537", "A murder inside a Japanese corporate skyscraper in Los Angeles exposes high-tech business competition."),
        ("Disclosure", "Michael Crichton", "9781101974544", "A tech executive faces false sexual harassment allegations from his new female boss at a virtual reality firm."),
        ("The Lost World", "Michael Crichton", "9781101974551", "Ian Malcolm returns to Site B on Isla Sorna to study surviving dinosaur ecosystems."),
        ("Airframe", "Michael Crichton", "9781101974568", "An aviation investigator uncovers political and mechanical cover-ups after an inflight airliner catastrophe."),
        ("Timeline", "Michael Crichton", "9781101974575", "Historians travel through quantum technology to 14th-century France to rescue their project leader."),
        ("Prey", "Michael Crichton", "9781101974582", "Autonomous swarms of predatory nanobots escape a Nevada laboratory, threatening human life."),
        ("State of Fear", "Michael Crichton", "9781101974599", "Eco-terrorists attempt to trigger artificial natural disasters to manipulate environmental funding."),
        ("Next", "Michael Crichton", "9781101974605", "Genetic patenting and animal human chimeras create legal and biological mayhem."),
        ("Pirate Latitudes", "Michael Crichton", "9780061929373", "Captain Charles Hunter leads a privateer crew to raid a Spanish treasure galleon in 1665 Jamaica."),
        ("Micro", "Michael Crichton & Richard Preston", "9780060873172", "Seven graduate students are shrunken to micro-size by a bio-tech firm and fight for survival in a Hawaiian rain forest."),
        ("Dragon Teeth", "Michael Crichton", "9780062473356", "In 1876, a Yale student gets caught between rival paleontologists Othniel Marsh and Edward Drinker Cope."),
        ("Killing Floor", "Lee Child", "9780515153651", "Ex-military policeman Jack Reacher is arrested for murder minutes after stepping off a bus in Margrave, Georgia."),
        ("Die Trying", "Lee Child", "9780515142242", "Reacher is kidnapped alongside an FBI agent by a militant militia group in Montana.")
    ],

    "Romance": [
        ("Vision in White", "Nora Roberts", "9780425230008", "Wedding photographer Mackensie Elliot falls for stable English teacher Carter Maguire."),
        ("Bed of Roses", "Nora Roberts", "9780425238691", "Wedding florist Emma Grant rediscovers love with longtime friend and architect Jack Cooke."),
        ("Savor the Moment", "Nora Roberts", "9780425233689", "Pastry chef Laurel McBane navigates a romance with her best friend's older brother Delaney Caine."),
        ("Happy Ever After", "Nora Roberts", "9780425241707", "Wedding executive Parker Brown connects with mechanic Malcom Kavanaugh."),
        ("Jewels of the Sun", "Nora Roberts", "9780515126778", "American Jude Murray moves to Ireland and falls for pub owner Aidan Gallagher."),
        ("Tears of the Moon", "Nora Roberts", "9780515127836", "Songwriter Shawn Gallagher falls for independent business woman Lady Brenna O'Toole."),
        ("Heart of the Sea", "Nora Roberts", "9780515129465", "Darcy Gallagher captivates wealthy businessman Trevor Magee in Ardmore."),
        ("Dance Upon the Air", "Nora Roberts", "9780515131221", "Nell Channing flees an abusive husband and settles on Three Sisters Island, meeting Sheriff Zack Todd."),
        ("Heaven and Earth", "Nora Roberts", "9780515132020", "Ripley Todd navigates her growing magical witch abilities and researcher MacAllister Booke."),
        ("Face the Fire", "Nora Roberts", "9780515133645", "Mia Devlin reconciles with Sam Logan to save Three Sisters Island from an ancient curse."),
        ("Blue Dahlia", "Nora Roberts", "9780515138558", "Widow Stella Rothchild moves to Memphis and falls for landscape designer Logan Kitridge."),
        ("Black Rose", "Nora Roberts", "9780515139265", "Rosalind Harper confronts the Harper House ghost while falling for genealogist Mitchell Carnegie."),
        ("Red Lily", "Nora Roberts", "9780515139401", "Hayley Phillips raises her baby daughter at Harper House and connects with Stephen Harper."),
        ("The Next Always", "Nora Roberts", "9780425246023", "Architect Beckett Montgomery renovates a Boonsboro hotel and pursues childhood crush Clare Brewster."),
        ("The Last Boyfriend", "Nora Roberts", "9780425246030", "Owen Montgomery manages hotel details and connects with childhood friend Avery MacTavish."),
        ("The Hope Chest", "Nora Roberts", "9780425246047", "Ryder Montgomery's hard exterior softens around fiery hotel manager Hope Hopewell."),
        ("Bay of Sighs", "Nora Roberts", "9780425280119", "Mermaid Annika and archaeologist Sawyer King search for the Water Star in Corfu."),
        ("Island of Glass", "Nora Roberts", "9780425280126", "Doyle Mac наблюдения and Riley Gentry search for the Ice Star in Ireland."),
        ("Year One", "Nora Roberts", "9781250122957", "A deadly virus destroys modern civilization, leaving survivors with emerging magical gifts."),
        ("Of Blood and Bone", "Nora Roberts", "9781250122995", "Fallon Swift trains her magical powers to lead the new world against dark forces."),
        ("The Rise of Magicks", "Nora Roberts", "9781250123039", "Fallon leads the final battle to defeat the Purity warriors and restore balance."),
        ("Hideaway", "Nora Roberts", "9781250207104", "Caitlyn Sullivan survives a childhood kidnapping and rebuilds her life at her family estate in Big Sur."),
        ("Legacy", "Nora Roberts", "9781250207142", "Adrian Rizzo builds a fitness empire while dealing with an anonymous stalker."),
        ("Nightwork", "Nora Roberts", "9781250207180", "Harry Booth works as a high-end thief to pay family medical bills, falling for Miranda Emerson."),
        ("Identity", "Nora Roberts", "9781250278180", "Morgan Albright rebuilds her life in Vermont after a serial killer murders her roommate."),
        ("Inheritance", "Nora Roberts", "9781250278227", "Sonny Sullivan inherits a Victorian house in Maine haunted by family spirits."),
        ("Beach Read", "Emily Henry", "9781984806734", "Romance writer January and literary novelist Augustus swap genres for a summer competition."),
        ("You and Me on Vacation", "Emily Henry", "9780593334836", "Best friends Poppy and Alex take one last summer trip to fix their broken friendship."),
        ("Book Lovers", "Emily Henry", "9780593334850", "Cutthroat literary agent Nora keeps running into brooding rival editor Charlie in a small North Carolina town."),
        ("Happy Place", "Emily Henry", "9780593441275", "Ex-couple Harriet and Wyn fake being together during their annual friend group Maine cottage trip."),
        ("Funny Story", "Emily Henry", "9780593441299", "Daphne and Miles become unlikely roommates after their respective exes leave them for each other."),
        ("The Hating Game", "Sally Thorne", "9780062439598", "Executive assistants Lucy and Joshua wage passive-aggressive office warfare while feeling mutual attraction."),
        ("99 Percent Mine", "Sally Thorne", "9780062877390", "Darcy Barrett renovates her grandmother's cottage with her brother's best friend Tom Valeska.")
    ],

    "Fantasy": [
        ("The Name of the Wind", "Patrick Rothfuss", "9780756404741", "Kvothe recounts his legendary youth, arcana academy education, and search for the Chandrian."),
        ("The Wise Man's Fear", "Patrick Rothfuss", "9780756407919", "Kvothe travels to Vintas, visits the Fae realm of Felurian, and studies with Adem mercenaries."),
        ("The Slow Regard of Silent Things", "Patrick Rothfuss", "9780756411329", "A tender novella detailing seven days in the subterranean Underthing life of mysterious Auri."),
        ("The Narrow Road Between Desires", "Patrick Rothfuss", "9780756419042", "Bast makes deals and navigates human folklore in the town of Newarre."),
        ("The Lies of Locke Lamora", "Scott Lynch", "9780553588941", "Con artist Locke Lamora leads the Gentlemen Bastards in high-stakes heists across Venice-like Camorr."),
        ("Red Seas Under Red Skies", "Scott Lynch", "9780553588958", "Locke and Jean target a casino in Tal Verrar and are forced into high-seas piracy."),
        ("The Republic of Thieves", "Scott Lynch", "9780553804690", "Locke and Jean compete against Locke's lost love Sabetha in a rigged political election."),
        ("Neverwhere", "Neil Gaiman", "9780060557812", "Richard Mayhew helps injured Door and falls into London Below, a magical subterranean world."),
        ("Stardust", "Neil Gaiman", "9780061142024", "Tristran Thorn crosses the wall of Wall into Faerie to retrieve a fallen star named Yvaine."),
        ("American Gods", "Neil Gaiman", "9780062564344", "Ex-con Shadow Moon travels America with Wednesday as old mythological gods battle modern tech deities."),
        ("Coraline", "Neil Gaiman", "9780061167591", "Coraline discovers a secret door leading to a sinister parallel home ruled by her Other Mother."),
        ("Anansi Boys", "Neil Gaiman", "9780060515195", "Fat Charlie Nancy discovers his deceased father was the trickster spider god Anansi."),
        ("The Graveyard Book", "Neil Gaiman", "9780060530945", "Nobody Owens is raised by ghosts, a werewolf, and a vampire inside a Victorian graveyard."),
        ("The Ocean at the End of the Lane", "Neil Gaiman", "9780062255655", "A man returns to his childhood home, remembering ancient magical neighbors on Hempstock farm."),
        ("Norse Mythology", "Neil Gaiman", "9780393356182", "Gaiman retells classic Norse myths from Odin and Thor to Loki and Ragnarok."),
        ("Good Omens", "Terry Pratchett & Neil Gaiman", "9780060853983", "Angel Aziraphale and demon Crowley team up to stop the apocalypse after losing the Antichrist."),
        ("The Color of Magic", "Terry Pratchett", "9780062225672", "Failed wizard Rincewind guides tourist Twoflower across the flat Discworld resting on four elephants."),
        ("The Light Fantastic", "Terry Pratchett", "9780062225689", "Rincewind and Twoflower try to save Discworld from a colliding red star."),
        ("Equal Rites", "Terry Pratchett", "9780062225696", "Granny Weatherwax mentors Eskarina, the first girl destined to become a wizard."),
        ("Mort", "Terry Pratchett", "9780062225702", "Death takes on young Mort as an apprentice, causing chaotic timeline disruptions."),
        ("Sourcery", "Terry Pratchett", "9780062225719", "A young sourcerer threatens to unleash magical armageddon at Unseen University."),
        ("Wyrd Sisters", "Terry Pratchett", "9780062225726", "Three witches intervene in Lancre royal politics in a parody of Shakespeare's Macbeth."),
        ("Pyramids", "Terry Pratchett", "9780062225733", "TeXelles assassin Teppic inherits the pharaoh throne of Djelibeybi."),
        ("Guards! Guards!", "Terry Pratchett", "9780062225757", "Captain Sam Vimes and the Ankh-Morpork City Watch fight a summoned dragon."),
        ("Eric", "Terry Pratchett", "9780062225764", "Rincewind is summoned by 13-year-old demonologist Eric in a Faustian parody."),
        ("Moving Pictures", "Terry Pratchett", "9780062225771", "The introduction of alchemical moving pictures causes chaos in Holy Wood."),
        ("Reaper Man", "Terry Pratchett", "9780062225788", "Death is fired by the Auditors and works as a farm laborer while life force overflows."),
        ("Witches Abroad", "Terry Pratchett", "9780062225795", "Granny Weatherwax, Nanny Ogg, and Magrat Garlick travel to Genua to stop a fairy godmother."),
        ("Small Gods", "Terry Pratchett", "9780062225801", "The great god Om is reduced to a tortoise until novice monk Brutha helps restore real faith."),
        ("Lords and Ladies", "Terry Pratchett", "9780062225818", "The Lancre witches fight off cruel, beautiful elves invading during Midsummer."),
        ("Men at Arms", "Terry Pratchett", "9780062225825", "Corporal Carrot leads a diverse City Watch investigating a deadly gonne weapon."),
        ("Soul Music", "Terry Pratchett", "9780062225832", "Imp Y Celyn introduces Music With Rocks In to Discworld, seducing Death's granddaughter Susan."),
        ("Interesting Times", "Terry Pratchett", "9780062225849", "Rincewind travels to the Agatean Empire to aid a revolution led by Cohen the Barbarian.")
    ],

    "Science Fiction": [
        ("The Martian", "Andy Weir", "9780553418026", "Astronaut Mark Watney is stranded on Mars after a storm and uses botany and engineering to survive."),
        ("Artemis", "Andy Weir", "9780553448146", "Smuggler Jazz Bashara gets caught in a conspiracy for control of the moon's only city."),
        ("Project Hail Mary", "Andy Weir", "9780593135228", "Ryland Grace awakens with amnesia aboard a starship, tasked with saving Earth from solar extinction."),
        ("Dark Matter", "Andy Weir & Blake Crouch", "9781101904244", "Physicist Jason Dessen is kidnapped into an alternate reality where he pursued his career instead of family."),
        ("Recursion", "Blake Crouch", "9781524759780", "Detective Barry Simcoe investigates False Memory Syndrome and a device capable of rewriting past time."),
        ("Upgrade", "Blake Crouch", "9781984819611", "Logan Ramsay's genome is altered, raising his intellect to save humanity from self-destruction."),
        ("Pines", "Blake Crouch", "9781477808726", "Secret Service agent Ethan Burke investigates missing agents in Wayward Pines, Idaho."),
        ("Wayward", "Blake Crouch", "9781477808702", "Ethan discovers the truth behind Wayward Pines' electrified fences and mutant threat."),
        ("The Last Town", "Blake Crouch", "9781477808719", "The survival of Wayward Pines hangs in the balance as the town's secrets leak out."),
        ("Run", "Blake Crouch", "9781477809624", "A solar event turns half the human population into murderous killers, forcing a family to flee."),
        ("Abandon", "Blake Crouch", "9781477809631", "A mining town vanished in 1893, and a modern expedition uncovers the violent truth."),
        ("All Systems Red", "Martha Wells", "9780765397522", "A security android calling itself Murderbot hacks its governor module while protecting scientists."),
        ("Artificial Condition", "Martha Wells", "9780765397539", "Murderbot travels to a research station to uncover the truth about its past massacre."),
        ("Rogue Protocol", "Martha Wells", "9780765397546", "Murderbot infiltrates a terraforming facility to assist an innocent transport shuttle AI."),
        ("Exit Strategy", "Martha Wells", "9780765397553", "Murderbot rescues its former human client Dr. Mensah from corporate rivals."),
        ("Network Effect", "Martha Wells", "9781250229861", "Murderbot's human companions are captured, forcing it to team up with an old research vessel AI."),
        ("Fugitive Telemetry", "Martha Wells", "9781250765376", "Murderbot investigates a dead body on Preservation Station without looking like the suspect."),
        ("System Collapse", "Martha Wells", "9781250826978", "Murderbot handles corporate intervention on a colonist planet while managing performance anxiety."),
        ("The Cloud Roads", "Martha Wells", "9781597802161", "Moon, a lonely shapeshifting Raksura, finds his long-lost family colony under threat from Fell monsters."),
        ("The Serpent Sea", "Martha Wells", "9781597803328", "Moon helps the Indigo Cloud court migrate across dangerous seas to a new home tree."),
        ("The Siren Depths", "Martha Wells", "9781597804561", "Moon returns to his birthplace to defend his court from ancestral royal rivals."),
        ("Ancillary Justice", "Ann Leckie", "9780316246620", "Breq, a former troop carrier AI inhabiting a human body, seeks revenge against the Radch emperor."),
        ("Ancillary Sword", "Ann Leckie", "9780316246651", "Breq commands a starstation, defending workers and alien species against imperial civil war."),
        ("Ancillary Mercy", "Ann Leckie", "9780316246682", "Breq defends Athoek station from the Radch ruler's opposing clone army."),
        ("Provenance", "Ann Leckie", "9780316552011", "Ingray attempts to steal historical vestiges to gain family status, triggering diplomatic conflict."),
        ("Translation State", "Ann Leckie", "9780316289696", "Three individuals clash over alien Presger translators and diplomatic human treaties."),
        ("Old Man's War", "John Scalzi", "9780765315243", "John Perry turns 75 and joins the Colonial Defense Force, getting a genetically enhanced young body for space war."),
        ("The Ghost Brigades", "John Scalzi", "9780765354068", "Jane Sagan fights in the special forces born from cloned DNA to stop an alien coalition."),
        ("The Last Colony", "John Scalzi", "9780765356185", "John and Jane lead a new colony planet Roanoke that becomes a pawn in intergalactic diplomacy."),
        ("Zoe's Tale", "John Scalzi", "9780765316981", "Zoe Boutin Perry narrates the events of Roanoke colony from her teenage perspective."),
        ("Human Division", "John Scalzi", "9780765333521", "Earth learns of the Colonial Union's secrets while diplomatic teams fix space relations."),
        ("End of All Things", "John Scalzi", "9780765376077", "The Colonial Union faces dissolution as hidden conspirators manipulate space warfare."),
        ("Redshirts", "John Scalzi", "9780765334795", "Ensign Andrew Dahl realizes lower-ranking crew members die on every away mission due to bad narrative tropes.")
    ],

    "Horror": [
        ("Carrie", "Stephen King", "9780307743664", "Telekinetic high school outcast Carrie White unleashes vengeance on her small town at prom."),
        ("'Salem's Lot", "Stephen King", "9780307743671", "Writer Ben Mears returns to Jerusalem's Lot, discovering vampires led by Kurt Barlow taking over."),
        ("The Shining", "Stephen King", "9780307743657", "Jack Torrance takes a winter caretaker job at the snowbound Overlook Hotel, slipping into murderous madness."),
        ("The Stand", "Stephen King", "9780307743688", "A weaponized flu wipes out 99% of humanity, setting up an apocalyptic clash between Mother Abagail and Randall Flagg."),
        ("The Dead Zone", "Stephen King", "9781501144509", "Johnny Smith wakes from a five-year coma with clairvoyant abilities, foreseeing a politician's nuclear threat."),
        ("Cujo", "Stephen King", "9781501144516", "A friendly St. Bernard contracts rabies, trapping a mother and young son inside a broken car."),
        ("Pet Sematary", "Stephen King", "9781501156700", "Louis Creed buries his son in an ancient Micmac burial ground that returns the dead wrong."),
        ("It", "Stephen King", "9781501142970", "Seven children in Derry fight a shapeshifting alien entity named Pennywise, returning 27 years later."),
        ("Misery", "Stephen King", "9781501143106", "Novelists Paul Sheldon is rescued from a car crash by his number one fan Annie Wilkes, who holds him captive."),
        ("The Dark Half", "Stephen King", "9781501144196", "Thad Beaumont kills off his crime pen name George Stark, who physically manifests to murder."),
        ("Needful Things", "Stephen King", "9781501143786", "Leland Gaunt opens an antique shop in Castle Rock, trading desires for malicious pranks."),
        ("Gerald's Game", "Stephen King", "9781501143809", "Jessie is left handcuffed to a bed in a remote cabin after her husband dies of a heart attack."),
        ("Dolores Claiborne", "Stephen King", "9781501143823", "Dolores gives a police confession about her employer's death and her abusive husband's past demise."),
        ("Desperation", "Stephen King", "9781501144264", "Travelers on Nevada Route 50 are terrorized by corrupt Sheriff Collie Entragian possessed by Tak."),
        ("The Green Mile", "Stephen King", "9781501160448", "Death row guard Paul Edgecombe discovers inmate John Coffey possesses miraculous healing powers."),
        ("Bag of Bones", "Stephen King", "9781501144226", "Grieving author Mike Noonan retreats to a Maine lake house haunted by spirits and custody disputes."),
        ("The Girl Who Loved Tom Gordon", "Stephen King", "9781501144547", "Nine-year-old Trisha gets lost on the Appalachian Trail, listening to Red Sox baseball games on radio."),
        ("Dreamcatcher", "Stephen King", "9781501144202", "Four friends with telepathic gifts confront parasitic alien invaders in the Maine woods."),
        ("From a Buick 8", "Stephen King", "9781501144172", "Pennsylvania state troopers keep a mysterious vintage car hidden in Shed B that opens portals."),
        ("Cell", "Stephen King", "9781501143755", "A global cell phone signal turns users into zombie-like telepathic flock monsters."),
        ("Duma Key", "Stephen King", "9781501144189", "Ed Edgar moves to Florida to paint after an accident, discovering his art controls real life."),
        ("Under the Dome", "Stephen King", "9781439149034", "Chester's Mill is suddenly sealed off from the world by an invisible force field."),
        ("11/22/63", "Stephen King", "9781451627299", "Jake Epping travels back to 1958 through a time portal to stop the assassination of JFK."),
        ("Joyland", "Stephen King", "9781781162644", "Devin Jones takes a summer job at a North Carolina amusement park haunted by a murdered girl."),
        ("Doctor Sleep", "Stephen King", "9781451698855", "An adult Dan Torrance uses his shining to defend young Abra from the True Knot cult."),
        ("Revival", "Stephen King", "9781476770383", "A minister obsessed with secret electricity attempts to view the afterlife with terrifying results."),
        ("The Outsider", "Stephen King", "9781501180989", "Terry Maitland is arrested for a gruesome murder despite ironclad alibis in another town."),
        ("The Institute", "Stephen King", "9781982110567", "Telekinetic and telepathic children are kidnapped and forced into covert government experiments."),
        ("Fairy Tale", "Stephen King", "9781668002179", "Charlie Reade inherits a shed containing a portal to a dark, decaying fairytale kingdom."),
        ("Holly", "Stephen King", "9781668016138", "Holly Gibney investigates missing persons tied to elderly retired professors hiding cannibal secrets."),
        ("Mr. X", "Peter Straub", "9780451197993", "Ned Dunstan experiences visions of his evil doppelganger Mr. X committing gruesome murders."),
        ("Lost Boy Lost Girl", "Peter Straub", "9780060841553", "Tim Underhill investigates his nephew's disappearance into an abandoned haunted house."),
        ("In the Night Room", "Peter Straub", "9780345481757", "Author Timothy Underhill meets a woman whose deceased daughter's spirit alters written reality.")
    ],

    "Self-Help": [
        ("How to Win Friends and Influence People", "Dale Carnegie", "9780671027032", "Time-tested principles on handling people, making people like you, and winning people to your way of thinking."),
        ("How to Stop Worrying and Start Living", "Dale Carnegie", "9780671733353", "Practical formulas for eliminating anxiety, breaking worry habits, and living with peace of mind."),
        ("The Quick and Easy Way to Effective Speaking", "Dale Carnegie", "9780671724009", "Developing self-confidence and influencing people through public speaking skills."),
        ("The 7 Habits of Highly Effective People", "Stephen R. Covey", "9781451639612", "A principle-centered framework for personal and professional effectiveness."),
        ("First Things First", "Stephen R. Covey", "9780684802039", "Time management focused on putting important life priorities ahead of urgent tasks."),
        ("Principle-Centered Leadership", "Stephen R. Covey", "9780684858417", "Building trust, empowering employees, and managing organizational change with core values."),
        ("The 8th Habit", "Stephen R. Covey", "9780743287937", "Moving from effectiveness to greatness by finding your voice and inspiring others."),
        ("The Speed of Trust", "Stephen M.R. Covey", "9781416528852", "How trust drives speed and lowers cost in business and personal relationships."),
        ("The 3rd Alternative", "Stephen R. Covey", "9781451626261", "Solving life's difficult problems through creative synergy rather than compromise."),
        ("The Power of Now", "Eckhart Tolle", "9781577314806", "A guide to spiritual enlightenment by anchoring consciousness in the present moment."),
        ("A New Earth", "Eckhart Tolle", "9780452289963", "Awakening to your life's purpose by transcending ego-based thinking."),
        ("Stillness Speaks", "Eckhart Tolle", "9781577314004", "Short meditative reflections on inner silence and presence."),
        ("Practicing the Power of Now", "Eckhart Tolle", "9781577311959", "Essential teachings and exercises from The Power of Now."),
        ("The Seven Spiritual Laws of Success", "Deepak Chopra", "9781878424310", "Seven natural laws for achieving fulfillment, harmony, and material abundance."),
        ("Ageless Body, Timeless Mind", "Deepak Chopra", "9780517882122", "Mind-body medicine strategies for reversing physical aging through consciousness."),
        ("Quantum Healing", "Deepak Chopra", "9780385313209", "Exploring the connection between mind, body, and cellular healing."),
        ("The Book of Secrets", "Deepak Chopra", "9780553382167", "Unlocking hidden dimensions of consciousness and personal transformation."),
        ("Super Brain", "Deepak Chopra & Rudolph E. Tanzi", "9780307956828", "Unleashing the brain's potential through neuroplasticity and mindfulness."),
        ("Metahuman", "Deepak Chopra", "9780593138700", "Unlocking higher consciousness beyond everyday perception and mental conditioning."),
        ("The Monk Who Sold His Ferrari", "Robin Sharma", "9780062515674", "A fable about fulfilling your dreams and reaching your destiny through mindfulness."),
        ("The 5 AM Club", "Robin Sharma", "9780062839268", "Own your morning and elevate your life through a structured early routine."),
        ("The Leader Who Had No Title", "Robin Sharma", "9781439109137", "Driving innovation and excellence without needing formal rank."),
        ("MegaLiving", "Robin Sharma", "9788172246143", "30 days to a perfect life incorporating mental focus and physical vitality."),
        ("Discover Your Destiny", "Robin Sharma", "9780060088980", "The 7 stages of self-awakening according to the monk who sold his Ferrari."),
        ("The Everyday Hero Manifesto", "Robin Sharma", "9780063135895", "Daily habits and mindset tools for elite achievement and personal peace."),
        ("Rich Dad Poor Dad", "Robert T. Kiyosaki", "9781612680194", "What the rich teach their kids about money that the poor and middle class do not."),
        ("Cashflow Quadrant", "Robert T. Kiyosaki", "9781612680057", "Guide to financial freedom shifting from employee to investor."),
        ("Guide to Investing", "Robert T. Kiyosaki", "9781612680217", "What the rich invest in that the poor and middle class do not."),
        ("Retire Young Retire Rich", "Robert T. Kiyosaki", "9781612680415", "How to get rich quickly and stay rich forever using financial leverage."),
        ("Increase Your Financial IQ", "Robert T. Kiyosaki", "9781612680651", "Five financial intelligences for getting smarter with your money."),
        ("Think and Grow Rich", "Napoleon Hill", "9781585424337", "The landmark 13-step philosophy of personal achievement based on Andrew Carnegie."),
        ("Outwitting the Devil", "Napoleon Hill", "9781454900672", "Secrets to freedom and success overcoming fear and drifting in life."),
        ("The Law of Success", "Napoleon Hill", "9781585444641", "The original 16 lessons on personal achievement and leadership.")
    ],

    "Biography": [
        ("John Adams", "David McCullough", "9780743223133", "Pulitzer Prize-winning biography of America's second president and founding revolutionary."),
        ("Truman", "David McCullough", "9780671869205", "Pulitzer Prize-winning life of Harry S. Truman from Missouri farm boy to atomic bomb decision."),
        ("Mornings on Horseback", "David McCullough", "9780671447540", "The young Theodore Roosevelt growing up in New York and transforming his health in the Badlands."),
        ("The Path Between the Seas", "David McCullough", "9780671244095", "The epic story of the building of the Panama Canal 1870-1914."),
        ("The Wright Brothers", "David McCullough", "9781476728759", "Wilbur and Orville Wright's courage and mechanical genius achieving human flight at Kitty Hawk."),
        ("1776", "David McCullough", "9780743226738", "The military history of George Washington and American troops during the pivotal year 1776."),
        ("The Great Bridge", "David McCullough", "9780671437114", "The construction of the Brooklyn Bridge engineered by John and Washington Roebling."),
        ("The Johnstown Flood", "David McCullough", "9780671207144", "The 1889 Pennsylvania dam collapse tragedy that killed over 2,000 people."),
        ("Brave Companions", "David McCullough", "9780671792763", "Essays on historical figures including Alexander von Humboldt, Harriet Beecher Stowe, and Louis Agassiz."),
        ("Cleopatra: A Life", "Stacy Schiff", "9780316001946", "Pulitzer Prize-winning biographer restores Egypt's last queen as a brilliant political strategist."),
        ("The Witches: Salem, 1692", "Stacy Schiff", "9780316200615", "Unraveling the panic, religious hysteria, and trials in colonial Salem, Massachusetts."),
        ("Véra (Mrs. Vladimir Nabokov)", "Stacy Schiff", "9780375705205", "Pulitzer Prize portrait of Vera Nabokov, editor, muse, and partner to Vladimir Nabokov."),
        ("Saint-Exupéry", "Stacy Schiff", "9780805079135", "The life of Antoine de Saint-Exupéry, pioneering aviator and author of The Little Prince."),
        ("A Great Improvisation", "Stacy Schiff", "9780805066340", "Benjamin Franklin's diplomatic mission to France securing French funding for the Revolution."),
        ("Unbroken", "Laura Hillenbrand", "9780812974492", "Louis Zamperini's WWII story of survival on a raft for 47 days and Japanese POW camps."),
        ("Seabiscuit", "Laura Hillenbrand", "9780449005613", "The underdog racehorse Seabiscuit and his ragtag team who inspired Great Depression America."),
        ("Killers of the Flower Moon", "David Grann", "9780307742483", "The Osage Indian murders for oil wealth in 1920s Oklahoma and the birth of J. Edgar Hoover's FBI."),
        ("The Lost City of Z", "David Grann", "9781400078455", "British explorer Percy Fawcett's fatal 1925 expedition into the Amazon searching for an ancient civilization."),
        ("The Wager", "David Grann", "9780593467152", "Shipwreck, mutiny, and court martial following HMS Wager's disaster off Patagonia in 1741."),
        ("The Devil and Sherlock Holmes", "David Grann", "9780307742490", "True tales of obsession, arson, murder, and mystery from the New Yorker writer."),
        ("Kissinger: A Biography", "Walter Isaacson", "9780743286978", "Comprehensive life of Henry Kissinger examining realpolitik, Vietnam war diplomacy, and China opening."),
        ("Napoleon: A Life", "Andrew Roberts", "9780143127857", "Definitive single-volume biography of Napoleon Bonaparte using his 33,000 published letters."),
        ("Churchill: Walking with Destiny", "Andrew Roberts", "9781101981009", "Acclaimed biography of Winston Churchill drawing on King George VI's private wartime diaries."),
        ("George III", "Andrew Roberts", "9781101981146", "Re-evaluating Britain's most misunderstood monarch through personal papers."),
        ("The Storm of War", "Andrew Roberts", "9780061228605", "A strategic overview of how World War II was fought and won across all theaters."),
        ("The Last Lion: Visions of Glory", "William Manchester", "9780385313452", "The first volume of Winston Churchill's biography from Victorian birth to 1932."),
        ("The Last Lion: Alone", "William Manchester", "9780385313469", "The second volume tracking Churchill's warning against Hitler during the 1930s."),
        ("The Last Lion: Defender of the Realm", "William Manchester & Paul Reid", "9780345548634", "The final volume documenting Churchill leading Britain to WWII victory."),
        ("Personal Memoirs of U.S. Grant", "Ulysses S. Grant", "9780140437010", "Grant's masterpiece autobiography detailing his Mexican War service and Civil War commands."),
        ("The Rise of Theodore Roosevelt", "Edmund Morris", "9780375756788", "Pulitzer Prize biography tracking TR's youth up to his 1901 presidency."),
        ("Theodore Rex", "Edmund Morris", "9780812966008", "The presidential administration of TR, trust-busting, and Panama Canal construction."),
        ("Colonel Roosevelt", "Edmund Morris", "9780375504877", "TR's final years post-presidency including African safari and Amazon exploration."),
        ("Frida: A Biography of Frida Kahlo", "Hayden Herrera", "9780060085896", "The painful life, art, and tempestuous marriage of Mexican painter Frida Kahlo.")
    ],

    "History": [
        ("The Guns of August", "Barbara W. Tuchman", "9780345476098", "Pulitzer Prize-winning account of the opening month of World War I in August 1914."),
        ("The Proud Tower", "Barbara W. Tuchman", "9780345405012", "A portrait of Western society in the twenty-five years leading up to World War I 1890-1914."),
        ("A Distant Mirror", "Barbara W. Tuchman", "9780345349576", "The calamitous 14th century depicted through the life of French nobleman Enguerrand de Coucy VII."),
        ("The March of Folly", "Barbara W. Tuchman", "9780345308238", "Governments pursuing policies contrary to their own interests from Troy to Vietnam."),
        ("Stilwell and the American Experience in China", "Barbara W. Tuchman", "9780871138545", "General Joseph Stilwell's command in WWII China and US foreign policy failures."),
        ("The Zimmerman Telegram", "Barbara W. Tuchman", "9780345324252", "How British intelligence intercepted Germany's secret cable proposing a Mexican alliance in WWI."),
        ("Bible and Sword", "Barbara W. Tuchman", "9780345314277", "England's historical involvement with Palestine from Roman times to the Balfour Declaration."),
        ("The Anarchy", "William Dalrymple", "9781635573954", "How the East India Company conquered India and replaced the Mughal Empire with corporate rule."),
        ("White Mughals", "William Dalrymple", "9780142004128", "Interracial romance and cultural exchange between British officers and Indian nobility in 18th-century Hyderabad."),
        ("The Last Mughal", "William Dalrymple", "9781400078332", "The fall of Delhi and the 1857 Indian Uprising seen through Bahadur Shah Zafar II."),
        ("Return of a King", "William Dalrymple", "9780307948533", "The First Anglo-Afghan War 1839-1842 and the catastrophic retreat from Kabul."),
        ("Nine Lives", "William Dalrymple", "9780307271709", "Nine modern spiritual journeys across sacred traditions in modernizing India."),
        ("City of Djinns", "William Dalrymple", "9780140152500", "A year spent exploring the layered history and centuries of Delhi."),
        ("In Xanadu", "William Dalrymple", "9780140293999", "A travel journey following Marco Polo's route from Jerusalem to Shangdu, China."),
        ("From the Holy Mountain", "William Dalrymple", "9780140281095", "Tracking the decline of Eastern Christianity across the Middle East following monk John Moschos."),
        ("Stalingrad", "Antony Beevor", "9780140284584", "The brutal 1942-1943 WWII battle that turned the tide against Nazi Germany on the Eastern Front."),
        ("Berlin: The Downfall 1945", "Antony Beevor", "9780142003718", "The Soviet Red Army's assault on Berlin and the final days of the Third Reich."),
        ("D-Day: The Battle for Normandy", "Antony Beevor", "9780143118183", "The Allied invasion of Normandy on June 6, 1944 and the liberation of France."),
        ("The Second World War", "Antony Beevor", "9780316023740", "Comprehensive single-volume history of WWII spanning global land, air, and naval campaigns."),
        ("Ardennes 1944", "Antony Beevor", "9780143109860", "Hitler's last major Western offensive during the winter Battle of the Bulge."),
        ("Russia: Revolution and Civil War 1917-1921", "Antony Beevor", "9780593493861", "The collapse of Tsarism, Bolshevik coup, and brutal Russian Civil War."),
        ("Crete 1941", "Antony Beevor", "9780140158823", "German paratrooper invasion of Crete and British resistance warfare."),
        ("The Spanish Civil War", "Antony Beevor", "9780143037651", "Military and political struggle between Republicans and Franco's Nationalists 1936-1939."),
        ("Catastrophe 1914", "Max Hastings", "9780307700858", "Europe going to war in 1914 and the early battles of Mons, Marne, and Tannenberg."),
        ("Vietnam: An Epic History", "Max Hastings", "9780358118237", "Tragically complex history of the Vietnam War from 1945 French rule to 1975 Saigon fall."),
        ("Abyss: The Cuban Missile Crisis", "Max Hastings", "9780063000940", "Thirteen days in October 1962 when the US and USSR teetered on nuclear war."),
        ("Inferno: The World at War 1939-1945", "Max Hastings", "9780307475534", "Human stories of ordinary soldiers and civilians across WWII battlefields."),
        ("Armageddon: The Battle for Germany", "Max Hastings", "9780375714221", "The desperate final nine months of WWII in Europe 1944-1945."),
        ("Nemesis: The Battle for Japan", "Max Hastings", "9780307275080", "The Pacific War's bloody final phase from Leyte Gulf to Hiroshima."),
        ("Overlord: D-Day and the Battle for Normandy", "Max Hastings", "9780307274984", "Military operational analysis of the D-Day invasion and Normandy breakout."),
        ("Bomber Command", "Max Hastings", "9780330513617", "RAF strategic night bombing campaign over Germany during WWII."),
        ("The Korean War", "Max Hastings", "9780330513631", "The 1950-1953 bloody conflict on the Korean peninsula between UN forces and China/North Korea."),
        ("Das Reich", "Max Hastings", "9780330513624", "The SS Panzer division's march across France post-D-Day and Oradour massacre.")
    ],

    "Philosophy": [
        ("The Logic of Scientific Discovery", "Karl Popper", "9780415278447", "Scientific theories can never be verified, only falsified through empirical testing."),
        ("The Open Society and Its Enemies", "Karl Popper", "9780691158136", "A defense of liberal democracy against totalitarian philosophies in Plato, Hegel, and Marx."),
        ("The Poverty of Historicism", "Karl Popper", "9780415278461", "Refuting the idea that history unfolds according to inevitable predictive historical laws."),
        ("Conjectures and Refutations", "Karl Popper", "9780415285940", "Essays on how knowledge grows through bold guesses and rigorous critical testing."),
        ("Objective Knowledge", "Karl Popper", "9780198750246", "An evolutionary approach to epistemology and World 3 abstract mental creations."),
        ("The Structure of Scientific Revolutions", "Thomas S. Kuhn", "9780226458083", "Landmark work introducing paradigm shifts, normal science, and scientific revolutions."),
        ("The Essential Tension", "Thomas S. Kuhn", "9780226458069", "Selected studies in scientific tradition and change."),
        ("Black-Body Theory and the Quantum Discontinuity", "Thomas S. Kuhn", "9780226458007", "Historical analysis of Max Planck and the origins of quantum physics."),
        ("Philosophy and the Mirror of Nature", "Richard Rorty", "9780691141367", "Critiquing the Cartesian-Lockean-Kantian tradition of mind reflecting external reality."),
        ("Consequences of Pragmatism", "Richard Rorty", "9780816610648", "Essays advocating neo-pragmatism following Dewey, Heidegger, and Wittgenstein."),
        ("Contingency, Irony, and Solidarity", "Richard Rorty", "9780521367813", "Ironism, language games, and liberal hope without metaphysical foundations."),
        ("Achieving Our Country", "Richard Rorty", "9780674003125", "Leftist American politics, national pride, and pragmatic reform over cultural despair."),
        ("From a Logical Point of View", "W.V.O. Quine", "9780674323513", "Nine logico-philosophical essays including Two Dogmas of Empiricism."),
        ("Word and Object", "W.V.O. Quine", "9780262670012", "Indeterminacy of translation, stimulus meaning, and physicalist ontology."),
        ("Ontological Relativity", "W.V.O. Quine", "9780231083577", "Relativity of reference, naturalized epistemology, and philosophical boundaries."),
        ("The Web of Belief", "W.V.O. Quine & J.S. Ullian", "9780075549079", "Introduction to belief justification, evidence, hypothesis, and scientific coherence."),
        ("Naming and Necessity", "Saul A. Kripke", "9780631128014", "Rigid designators, necessary a posteriori truths, and causal theory of reference."),
        ("Wittgenstein on Rules and Private Language", "Saul A. Kripke", "9780674954014", "An influential interpretation of Wittgenstein's rule-following paradox and skeptical solution."),
        ("A Theory of Justice", "John Rawls", "9780674000780", "Formulating justice as fairness using the Original Position behind a Veil of Ignorance."),
        ("Political Liberalism", "John Rawls", "9780231130899", "How a stable and just society can persist amidst reasonable pluralism of doctrines."),
        ("The Law of Peoples", "John Rawls", "9780674000797", "Extending liberal concepts of justice to international law and global human rights."),
        ("Justice as Fairness: A Restatement", "John Rawls", "9780674005112", "A concise summary reformulating Rawls's core principles of political justice."),
        ("Anarchy, State, and Utopia", "Robert Nozick", "9780465051007", "Libertarian response to Rawls defending the minimal state limited to protection against force."),
        ("Philosophical Explanations", "Robert Nozick", "9780674664791", "Tracking truth knowledge theory, identity, free will, value, and meaning."),
        ("The Examined Life", "Robert Nozick", "9780671725013", "Philosophical meditations on love, death, faith, money, and personal fulfillment."),
        ("Invariances", "Robert Nozick", "9780674012929", "The structure of the objective world, truth, necessity, and ethics."),
        ("The Problems of Philosophy", "Bertrand Russell", "9780195115529", "Classic introductory text on knowledge by acquaintance, appearance versus reality, and idealism."),
        ("A History of Western Philosophy", "Bertrand Russell", "9780671201586", "Comprehensive overview of Western thought from Pre-Socratics to 20th century."),
        ("Why I Am Not a Christian", "Bertrand Russell", "9780671203238", "Essays on religion, rationalism, ethics, and free thought."),
        ("In Praise of Idleness", "Bertrand Russell", "9780415325066", "Essays advocating reduced work hours, social sanity, and intellectual leisure."),
        ("The Conquest of Happiness", "Bertrand Russell", "9780415325059", "Causes of unhappiness and rational habits to achieve joyful living."),
        ("Human Knowledge: Its Scope and Limits", "Bertrand Russell", "9780415478472", "Examining non-demonstrative inference and scientific methodology."),
        ("Marriage and Morals", "Bertrand Russell", "9780415482899", "Critique of Victorian sexual morality, marriage institutions, and family law.")
    ],

    "Young Adult": [
        ("The Lightning Thief", "Rick Riordan", "9780786838653", "Percy Jackson discovers he is a demigod son of Poseidon and is accused of stealing Zeus's master lightning bolt."),
        ("The Sea of Monsters", "Rick Riordan", "9780786856862", "Percy and Annabeth sail into the Bermuda Triangle to retrieve the Golden Fleece and save Camp Half-Blood."),
        ("The Titan's Curse", "Rick Riordan", "9781423101451", "Percy rescues Artemis and Annabeth while facing Atlas bearing the weight of the sky."),
        ("The Battle of the Labyrinth", "Rick Riordan", "9781423101468", "Demigods navigate Daedalus's subterranean Labyrinth to prevent Kronos's army from invading camp."),
        ("The Last Olympian", "Rick Riordan", "9781423101475", "Percy leads demigods in defending Mount Olympus atop the Empire State Building against Kronos."),
        ("The Lost Hero", "Rick Riordan", "9781423113393", "Amnesiac Jason Grace, Piper, and Leo arrive at Camp Half-Blood and embark on a quest to rescue Hera."),
        ("The Son of Neptune", "Rick Riordan", "9781423140597", "Percy wakes up at Camp Jupiter with no memory except Annabeth's name and travels to Alaska."),
        ("The Mark of Athena", "Rick Riordan", "9781423140603", "Seven Greek and Roman demigods sail aboard the Argo II to Rome to fulfill the Prophecy of Seven."),
        ("The House of Hades", "Rick Riordan", "9781423146728", "Percy and Annabeth fight through Tartarus while their friends sail to the Doors of Death."),
        ("The Blood of Olympus", "Rick Riordan", "9781423146735", "The final battle in Athens to stop the earth goddess Gaea from waking."),
        ("The Hidden Oracle", "Rick Riordan", "9781484725023", "God Apollo is cast down to Earth as a mortal teenager Lester Papadopoulos in New York."),
        ("The Dark Prophecy", "Rick Riordan", "9781484725030", "Lester travels across America's Midwest to restore the Oracle of Trophonius."),
        ("The Burning Maze", "Rick Riordan", "9781484725047", "Lester and Meg navigate a fiery maze in Southern California, facing emperor Caligula."),
        ("The Tyrant's Tomb", "Rick Riordan", "9781484725054", "Lester defends Camp Jupiter against the combined army of Commodus and Caligula."),
        ("The Tower of Nero", "Rick Riordan", "9781484725061", "Apollo faces Nero and Python in New York to regain his godhood."),
        ("The Red Pyramid", "Rick Riordan", "9781423113386", "Carter and Sadie Kane discover their family descends from Egyptian pharaoh magicians."),
        ("The Throne of Fire", "Rick Riordan", "9781423140566", "The Kanes travel the globe to find the Book of Ra and awaken the sun god."),
        ("The Serpent's Shadow", "Rick Riordan", "9781423140573", "The Kanes battle Apophis the chaos serpent to prevent eternal darkness."),
        ("The Sword of Summer", "Rick Riordan", "9781423160915", "Magnus Chase dies in Boston and goes to Valhalla, learning he is the son of Frey."),
        ("The Hammer of Thor", "Rick Riordan", "9781423160922", "Magnus searches for Thor's lost hammer Mjolnir before giant enemies invade."),
        ("The Ship of the Dead", "Rick Riordan", "9781423160939", "Magnus sails to edge of Norse worlds to defeat Loki in a flyting contest."),
        ("City of Bones", "Cassandra Clare", "9781442403543", "Clary Fray discovers Shadowhunters who protect the human world from demons in New York."),
        ("City of Ashes", "Cassandra Clare", "9781442403550", "Clary and Jace confront Valentine while he seeks the Mortal Sword."),
        ("City of Glass", "Cassandra Clare", "9781442403567", "Clary travels to Alicante, home city of the Shadowhunters, for the ultimate battle."),
        ("City of Fallen Angels", "Cassandra Clare", "9781442403574", "Someone is killing Shadowhunters in New York while Jace experiences terrifying nightmares."),
        ("City of Lost Souls", "Cassandra Clare", "9781442403581", "Jace is bound to evil Sebastian, driving Clary to join them to save Jace's soul."),
        ("City of Heavenly Fire", "Cassandra Clare", "9781442416895", "The final stand against Sebastian's Endarkened army in the demon realm of Edom."),
        ("Clockwork Angel", "Cassandra Clare", "9781442403338", "Tessa Gray arrives in Victorian London and is rescued by Shadowhunters Will and Jem."),
        ("Clockwork Prince", "Cassandra Clare", "9781442403352", "Tessa, Will, and Jem track the mysterious Magus Mortmain who builds clockwork automatons."),
        ("Clockwork Princess", "Cassandra Clare", "9781442403376", "Mortmain kidnaps Tessa, forcing Will and Jem to risk everything in Wales."),
        ("Lady Midnight", "Cassandra Clare", "9781442468351", "Emma Carstairs investigates dark murders in Los Angeles tied to her parents' death."),
        ("Lord of Shadows", "Cassandra Clare", "9781442468382", "Emma and Julian Blackthorn navigate forbidden parabatai love and Faerie court war."),
        ("Queen of Air and Darkness", "Cassandra Clare", "9781442468412", "The tragic climax in Los Angeles as the Shadowhunter Council collapses into extremism.")
    ],

    "Poetry": [
        ("The Colossus", "Sylvia Plath", "9780375704468", "Plath's debut poetry collection featuring early visions of landscapes, sea, and family ghosts."),
        ("Ariel", "Sylvia Plath", "9780060931728", "Groundbreaking posthumous collection featuring Lady Lazarus, Daddy, and Tulips."),
        ("Crossing the Water", "Sylvia Plath", "9780060902452", "Posthumous poems written between The Colossus and Ariel showing transitional mastery."),
        ("Winter Trees", "Sylvia Plath", "9780060902469", "Final poems written during the last months of Plath's life in 1962-1963."),
        ("The Collected Poems", "Sylvia Plath", "9780060909000", "Pulitzer Prize-winning volume gathering Plath's complete chronological poetic works."),
        ("To Bedlam and Part Way Back", "Anne Sexton", "9780395081822", "Sexton's debut confessional collection exploring mental illness, asylum stays, and recovery."),
        ("All My Pretty Ones", "Anne Sexton", "9780395081792", "Poems addressing grief, loss of parents, faith, and womanhood."),
        ("Live or Die", "Anne Sexton", "9780395081808", "Pulitzer Prize-winning collection exploring survival, despair, and choice between life and death."),
        ("Love Poems", "Anne Sexton", "9780395081815", "Sensual, passionate, and raw poems detailing romantic love and physical desire."),
        ("Transformations", "Anne Sexton", "9780395127216", "Dark, feminist, modern reimaginings of sixteen classic Grimm fairy tales."),
        ("The Book of Folly", "Anne Sexton", "9780395140130", "Fables, Jesus papers, and intense confessional lyrics."),
        ("The Death Notebooks", "Anne Sexton", "9780395182819", "Meditations on mortality, psalms, and spiritual longing."),
        ("The Awful Rowing Toward God", "Anne Sexton", "9780395207321", "Sexton's final collection searching for divine grace and spiritual peace."),
        ("North & South", "Elizabeth Bishop", "9780374526979", "Bishop's debut collection featuring The Fish, The Map, and The Roosters."),
        ("A Cold Spring", "Elizabeth Bishop", "9780374526986", "Pulitzer Prize-winning collection depicting natural observation in Maryland and Nova Scotia."),
        ("Questions of Travel", "Elizabeth Bishop", "9780374526993", "Poetic reflections on Bishop's years living in Brazil and childhood memories of Canada."),
        ("Geography III", "Elizabeth Bishop", "9780374527006", "Masterful collection featuring One Art, In the Waiting Room, and Crusoe in England."),
        ("The Complete Poems", "Elizabeth Bishop", "9780374518172", "The definitive gathered works of Elizabeth Bishop spanning her lifetime."),
        ("A Boy's Will", "Robert Frost", "9780486268668", "Frost's debut collection celebrating rural New England landscapes, seasons, and solitude."),
        ("North of Boston", "Robert Frost", "9780486268675", "Landmark collection featuring Mending Wall, After Apple-Picking, and Death of the Hired Man."),
        ("Mountain Interval", "Robert Frost", "9780486275505", "Featuring The Road Not Taken, Birches, and Out, Out-."),
        ("New Hampshire", "Robert Frost", "9780486406862", "Pulitzer Prize-winning collection featuring Stopping by Woods on a Snowy Evening and Fire and Ice."),
        ("West-Running Brook", "Robert Frost", "9780805069860", "Meditative lyrics on nature, philosophical resilience, and love."),
        ("A Further Range", "Robert Frost", "9780805069877", "Pulitzer Prize-winning collection featuring Two Tramps in Mud Time and A Lone Striker."),
        ("A Witness Tree", "Robert Frost", "9780805069884", "Pulitzer Prize-winning collection written following family personal tragedies."),
        ("Steeple Bush", "Robert Frost", "9780805069891", "Post-war reflections on technology, nature, and human spirit."),
        ("In the Clearing", "Robert Frost", "9780805069907", "Frost's final published collection featuring The Gift Outright read at JFK's inauguration."),
        ("Harmonium", "Wallace Stevens", "9780375708305", "Stevens's landmark debut featuring The Emperor of Ice-Cream, Sunday Morning, and Thirteen Ways of Looking at a Blackbird."),
        ("Ideas of Order", "Wallace Stevens", "9780375708312", "Meditations on artistic order against chaos featuring The Idea of Order at Key West."),
        ("The Man with the Blue Guitar", "Wallace Stevens", "9780375708329", "Exploring the tension between reality and poetic imagination."),
        ("Parts of a World", "Wallace Stevens", "9780375708336", "Poetic responses to WWII, perception, and abstract thought."),
        ("Transport to Summer", "Wallace Stevens", "9780375708343", "Featuring Notes Toward a Supreme Fiction and Esthétique du Mal."),
        ("The Auroras of Autumn", "Wallace Stevens", "9780375708350", "National Book Award-winning meditations on time, change, and light.")
    ],

    "Classic Literature": [
        ("The Pickwick Papers", "Charles Dickens", "9780140436112", "The comical misadventures of Samuel Pickwick and members of the Pickwick Club traveling across England."),
        ("Oliver Twist", "Charles Dickens", "9780141439747", "Orphan Oliver escapes the parish workhouse into London's underworld of pickpockets led by Fagin."),
        ("Nicholas Nickleby", "Charles Dickens", "9780140435122", "Young Nicholas defends his mother and sister against his villainous uncle Ralph Nickleby."),
        ("The Old Curiosity Shop", "Charles Dickens", "9780140437423", "Little Nell and her grandfather flee London to escape the cruel money-lender Daniel Quilp."),
        ("Barnaby Rudge", "Charles Dickens", "9780140437287", "Historical novel depicting anti-Catholic Gordon Riots of 1780 in London."),
        ("Martin Chuzzlewit", "Charles Dickens", "9780140437386", "A satire on selfishness, hypocrisy, and Victorian society spanning England and boom-town America."),
        ("Dombey and Son", "Charles Dickens", "9780140435467", "Cold shipping merchant Paul Dombey values his business son over loving daughter Florence."),
        ("David Copperfield", "Charles Dickens", "9780140439441", "Dickens's favorite autobiographical novel tracing David's growth from abused child to successful author."),
        ("Bleak House", "Charles Dickens", "9780141439723", "Esther Summerson's story intertwined with the endless Court of Chancery legal lawsuit Jarndyce v Jarndyce."),
        ("Hard Times", "Charles Dickens", "9780141439679", "Thomas Gradgrind raises his children on cold facts, ruining lives in industrial Coketown."),
        ("Little Dorrit", "Charles Dickens", "9780141439662", "Amy Dorrit is born and raised in Marshalsea debtor's prison, caring for her proud father."),
        ("A Tale of Two Cities", "Charles Dickens", "9780141439600", "Charles Darnay and Sydney Carton during the French Revolution in London and Paris."),
        ("Great Expectations", "Charles Dickens", "9780141439563", "Orphan Pip receives secret wealth from an unknown benefactor, pursuing cold Estella."),
        ("Our Mutual Friend", "Charles Dickens", "9780140437973", "John Harmon pretends to be poor after inheriting dust heaps money along the Thames river."),
        ("Far from the Madding Crowd", "Thomas Hardy", "9780141439655", "Independent Bathsheba Everdene is pursued by shepherd Gabriel Oak, farmer Boldwood, and Sergeant Troy."),
        ("The Return of the Native", "Thomas Hardy", "9780141439648", "Passionate Eustacia Vye yearns to leave Egdon Heath, marrying Clym Yeobright with tragic results."),
        ("The Mayor of Casterbridge", "Thomas Hardy", "9780141439785", "Michael Henchard sells his wife in a drunken fit, rising to mayor before secret past ruins him."),
        ("Tess of the d'Urbervilles", "Thomas Hardy", "9780141439594", "Pure country girl Tess Durbeyfield suffers hypocrisy and tragedy from Alec d'Urberville and Angel Clare."),
        ("Jude the Obscure", "Thomas Hardy", "9780141439458", "Working-class Jude Fawley dreams of university learning, facing societal condemnation with Sue Bridehead."),
        ("Under the Greenwood Tree", "Thomas Hardy", "9780140435535", "Charming Mellstock church choir novel featuring shoe-maker Dick Dewy loving schoolmistress Fancy Day."),
        ("The Woodlanders", "Thomas Hardy", "9780140435382", "Grace Melbury marries doctor Fitzpiers despite loyal woodsman Giles Winterborne's love."),
        ("Sense and Sensibility", "Jane Austen", "9780141439686", "Prudent Elinor and romantic Marianne Dashwood navigate love, money, and heartbreak in Devonshire."),
        ("Pride and Prejudice", "Jane Austen", "9780141439518", "Spirited Elizabeth Bennet clashes with proud Mr. Darcy in Regency England."),
        ("Mansfield Park", "Jane Austen", "9780141439808", "Shy Fanny Price is raised by wealthy relatives at Mansfield Park, holding fast to moral principles."),
        ("Emma", "Jane Austen", "9780141439587", "Clever Emma Woodhouse plays matchmaker in Highbury, blind to her own feelings for Mr. Knightley."),
        ("Northanger Abbey", "Jane Austen", "9780141439792", "Gothic novel enthusiast Catherine Morland visits Bath and stays at General Tilney's abbey."),
        ("Persuasion", "Jane Austen", "9780141439693", "Anne Elliot reconnects with Captain Frederick Wentworth eight years after breaking their engagement."),
        ("Lady Susan", "Jane Austen", "9780140437430", "An epistolary novella following beautiful, manipulative widow Lady Susan Vernon pursuing husbands."),
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "Orphan governess Jane Eyre falls in love with brooding Mr. Rochester at Thornfield Hall."),
        ("Shirley", "Charlotte Brontë", "9780141441436", "Industrial Luddite riots in Yorkshire forming backdrop for heiress Shirley Keeldar and Caroline Helstone."),
        ("Villette", "Charlotte Brontë", "9780141439730", "Lucy Snowe travels to French-speaking Labassecour to teach at a girls' pensionnat, falling for Paul Emanuel."),
        ("Wuthering Heights", "Emily Brontë", "9780141439556", "The wild, obsessive love between Heathcliff and Catherine Earnshaw on the Yorkshire moors."),
        ("The Tenant of Wildfell Hall", "Anne Brontë", "9780141439778", "Helen Graham flees an abusive alcoholic husband to protect her son, living independently as a painter.")
    ],

    "Non-Fiction": [
        ("A Short History of Nearly Everything", "Bill Bryson", "9780767908184", "A funny, accessible journey through cosmology, geology, chemistry, and paleontology."),
        ("Notes from a Small Island", "Bill Bryson", "9780380727506", "Bryson's hilarious farewell travelogue journey across Great Britain by train and bus."),
        ("The Lost Continent", "Bill Bryson", "9780060920081", "Driving 13,900 miles across small-town America searching for nostalgic innocence."),
        ("A Walk in the Woods", "Bill Bryson", "9780307279460", "Hiking the 2,100-mile Appalachian Trail with his out-of-shape friend Stephen Katz."),
        ("In a Sunburned Country", "Bill Bryson", "9780767903868", "Exploring the dangerous wildlife, vast outback, and friendly people of Australia."),
        ("The Life and Times of the Thunderbolt Kid", "Bill Bryson", "9780767919371", "Bryson's heartwarming memoir growing up in 1950s Des Moines, Iowa."),
        ("At Home: A Short History of Private Life", "Bill Bryson", "9780767919395", "Taking a tour of his Norfolk rectory house to explain how domestic history evolved."),
        ("One Summer: America 1927", "Bill Bryson", "9780767919418", "Charles Lindbergh, Babe Ruth, Al Capone, and the eventful summer of 1927."),
        ("The Body: A Guide for Occupants", "Bill Bryson", "9780385539241", "A head-to-toe guide on how the human body works, heals, and functions."),
        ("The Omnivore's Dilemma", "Michael Pollan", "9780143038580", "Tracing four human meals from industrial corn fields and organic farms to hunter-gathering."),
        ("In Defense of Food", "Michael Pollan", "9780143114963", "An eater's manifesto: Eat food. Not too much. Mostly plants."),
        ("Food Rules", "Michael Pollan", "9780143116387", "Sixty-four simple, memorable rules for eating wisely in modern society."),
        ("Cooked: A Natural History of Transformation", "Michael Pollan", "9780143125334", "Transforming food through the four classical elements: Fire, Water, Air, and Earth."),
        ("How to Change Your Mind", "Michael Pollan", "9780735224155", "What the new science of psychedelics teaches us about consciousness, dying, and depression."),
        ("This Is Your Mind on Plants", "Michael Pollan", "9780593296905", "Exploring opium, caffeine, and mescaline and human plant relationships."),
        ("The Botany of Desire", "Michael Pollan", "9780375760396", "How apples, tulips, marijuana, and potatoes co-evolved to satisfy human desires."),
        ("A Place of My Own", "Michael Pollan", "9780143114741", "Building a small writing house in the woods to understand architecture and craft."),
        ("The Man Who Mistook His Wife for a Hat", "Oliver Sacks", "9780679745402", "Case histories of neurological patients experiencing bizarre perceptual and memory deficits."),
        ("Awakenings", "Oliver Sacks", "9780375704055", "L-Dopa drug trials reviving catatonic encephalitis lethargica victims in 1969."),
        ("An Anthropologist on Mars", "Oliver Sacks", "9780679756972", "Seven paradoxical neurological cases including an autistic artist and a colorblind painter."),
        ("Migraine", "Oliver Sacks", "9780375704062", "Comprehensive medical study of migraine symptoms, vision aura, and psychological triggers."),
        ("Seeing Voices", "Oliver Sacks", "9780375704079", "A journey into the world of Deaf culture and Sign Language linguistics."),
        ("Island of the Colorblind", "Oliver Sacks", "9780375700736", "Travels to Pacific atolls where congenital total colorblindness is widespread."),
        ("Uncle Tungsten", "Oliver Sacks", "9780375704048", "Memories of a chemical childhood in wartime London obsessed with periodic table elements."),
        ("Oaxaca Journal", "Oliver Sacks", "9780375708541", "Botanical travel notes exploring giant ferns and Mexican history in Oaxaca."),
        ("Musicophilia", "Oliver Sacks", "9781400033539", "Tales of music and the brain, musical hallucinations, and amusia."),
        ("Hallucinations", "Oliver Sacks", "9780307945723", "Exploring sensory hallucinations from Charles Bonnet syndrome to drug visions."),
        ("On the Move: A Life", "Oliver Sacks", "9780385352543", "Autobiography detailing Sacks's passion for motorcycles, weightlifting, and clinical neurology."),
        ("Gratitude", "Oliver Sacks", "9780451494702", "Four moving essays written during Sacks's final months facing terminal cancer."),
        ("The River of Consciousness", "Oliver Sacks", "9780385352567", "Essays on Darwin, Freud, speed, time perception, and memory."),
        ("The Big Short", "Michael Lewis", "9780393338829", "Inside the eccentric investors who predicted the 2008 housing market collapse."),
        ("Moneyball", "Michael Lewis", "9780393324815", "How Billy Beane used statistical Sabermetrics to revolutionize Oakland Athletics baseball."),
        ("The Blind Side", "Michael Lewis", "9780393330472", "Evolution of the NFL offensive left tackle position and Michael Oher's inspiring story.")
    ]
}

def escape_sql_str(val):
    return val.replace("'", "''")

def main():
    target_path = r"c:\pdd1\database\seed_books_batch_6.sql"
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    statements = []
    statements.append("-- PageMind Database Seed Script: Batch 6 of 10 (500 Books across 15 Genres)\n")
    statements.append("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
    statements.append("USE pagemind;\n\n")

    count = 0
    for genre, books in GENRE_DATA_BATCH_6.items():
        statements.append(f"-- =======================================================\n")
        statements.append(f"-- Genre: {genre} ({len(books)} books)\n")
        statements.append(f"-- =======================================================\n")
        
        for title, author, isbn, desc in books:
            count += 1
            e_title = escape_sql_str(title)
            e_author = escape_sql_str(author)
            e_genre = escape_sql_str(genre)
            e_desc = escape_sql_str(desc)
            
            if isbn:
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
            else:
                cover_url = f"https://via.placeholder.com/300x450/1e1b4b/a5b4fc?text={urllib.parse.quote(title)}"
            e_cover_url = escape_sql_str(cover_url)
            
            amazon_url = f"https://www.amazon.in/s?k={urllib.parse.quote(f'{title} {author}')}"
            flipkart_url = f"https://www.flipkart.com/search?q={urllib.parse.quote(f'{title} {author}')}"
            
            buy_links_dict = {
                "amazon": amazon_url,
                "flipkart": flipkart_url
            }
            buy_links_json = json.dumps(buy_links_dict)
            e_buy_links_json = escape_sql_str(buy_links_json)
            
            pub_year = get_published_year(title, author, genre, desc, isbn)

            
            rating = get_rating(title, author)

            
            sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{e_title}', '{e_author}', '{e_genre}', '{e_desc}', '{e_cover_url}', '{e_buy_links_json}', {pub_year}, {rating});\n"
            statements.append(sql)
            
        statements.append("\n")

    with open(target_path, "w", encoding="utf-8") as f:
        f.writelines(statements)

    print(f"Successfully generated {target_path} with {count} book insert statements across {len(GENRE_DATA_BATCH_6)} genres!")

if __name__ == "__main__":
    main()
