from book_metadata_utils import get_rating, get_published_year
import json
import urllib.parse
import os

# Batch 5: 495+ Real, Published Books across 15 Genres (33 books per genre)
# Deep-catalog titles completely distinct from Batches 1, 2, 3, and 4.

GENRE_DATA_BATCH_5 = {
    "Fiction": [
        ("Demon Copperhead", "Barbara Kingsolver", "9780063251922", "A Appalachian boy born in a trailer home navigates foster care, addiction, and love."),
        ("The Poisonwood Bible", "Barbara Kingsolver", "9780060786502", "A fierce evangelical minister moves his wife and four daughters to the Belgian Congo in 1959."),
        ("Flight Behavior", "Barbara Kingsolver", "9780062124272", "A young mother discovers a bizarre natural phenomenon of monarch butterflies in Tennessee."),
        ("The Lacuna", "Barbara Kingsolver", "9780060852580", "Harrison Shepherd's life spans 1930s Mexico working for Diego Rivera and Frida Kahlo to post-war US."),
        ("The Bean Trees", "Barbara Kingsolver", "9780061097317", "Taylor Greer leaves Kentucky in a beat-up car and inherits an abandoned Native American child."),
        ("Animal Dreams", "Barbara Kingsolver", "9780060921149", "Codi Noline returns to her Arizona hometown to face her family history and environmental crisis."),
        ("Pigs in Heaven", "Barbara Kingsolver", "9780060922535", "Taylor and Turtle face a legal and cultural custody battle over Turtle's Cherokee heritage."),
        ("My Brilliant Friend", "Elena Ferrante", "9781609450786", "The fierce lifelong friendship of Elena and Lila growing up in post-war Naples."),
        ("The Story of a New Name", "Elena Ferrante", "9781609451349", "Lila enters a troubled marriage while Elena pursues her academic ambitions."),
        ("Those Who Leave and Those Who Stay", "Elena Ferrante", "9781609452339", "Elena and Lila navigate motherland politics, feminism, and career choices in 1970s Italy."),
        ("The Story of the Lost Child", "Elena Ferrante", "9781609452865", "The mature lives and tragic final phase of Elena and Lila's friendship in Naples."),
        ("Love in the Time of Cholera", "Gabriel García Márquez", "9780307389732", "Florentino Ariza waits over fifty years to renew his vow of love to Fermina Daza."),
        ("Of Love and Other Demons", "Gabriel García Márquez", "9780140256369", "A young girl bitten by a rabid dog is sent to a convent where a priest falls passionately in love."),
        ("Chronicle of a Death Foretold", "Gabriel García Márquez", "9781400034710", "A small town re-examines the events leading up to the honor killing of Santiago Nasar."),
        ("The General in His Labyrinth", "Gabriel García Márquez", "9781400034703", "A fictionalized account of Simón Bolívar's final journey down the Magdalena River."),
        ("South of the Border, West of the Sun", "Haruki Murakami", "9780679767398", "A successful Tokyo jazz bar owner is visited by his childhood love carrying mysterious baggage."),
        ("After Dark", "Haruki Murakami", "9780307278739", "A surreal midnight journey through Tokyo diner booths, hotel rooms, and love motels."),
        ("Sputnik Sweetheart", "Haruki Murakami", "9780375726057", "K-sumi falls in love with an older woman named Miu, leading to a strange disappearance on a Greek island."),
        ("Colorless Tsukuru Tazaki", "Haruki Murakami", "9780385353380", "A train station designer visits his high school friends to discover why they abandoned him."),
        ("The House of the Spirits", "Isabel Allende", "9780553383805", "The Trueba family's multi-generational saga intertwined with Chilean political upheaval."),
        ("Eva Luna", "Isabel Allende", "9781501117015", "An orphan girl in South America uses storytelling to survive dictatorship and romance."),
        ("Daughter of Fortune", "Isabel Allende", "9780061097645", "Eliza Sommers leaves Chile during the 1849 California Gold Rush to search for her lover."),
        ("Portrait in Sepia", "Isabel Allende", "9780066214092", "Aurora del Valle uncovers family secrets in 19th-century San Francisco and Chile."),
        ("Wolf Hall", "Hilary Mantel", "9780312428549", "Thomas Cromwell's rise from blacksmith's son to chief minister in Henry VIII's court."),
        ("Bring Up the Bodies", "Hilary Mantel", "9780312428501", "Cromwell orchestrates the downfall of Anne Boleyn to clear the way for Jane Seymour."),
        ("The Mirror & the Light", "Hilary Mantel", "9780805096606", "The final triumph and tragic downfall of Thomas Cromwell under Henry VIII."),
        ("Half of a Yellow Sun", "Chimamanda Ngozi Adichie", "9781400095209", "Three lives entangled during the Biafran war for independence in 1960s Nigeria."),
        ("Purple Hibiscus", "Chimamanda Ngozi Adichie", "9781616202415", "Kambili grows up under a tyrannical, wealthy father in post-colonial Nigeria."),
        ("Americanah", "Chimamanda Ngozi Adichie", "9780307455925", "Ifemelu leaves Nigeria for America, grappling with race, identity, and blog writing."),
        ("The Thing Around Your Neck", "Chimamanda Ngozi Adichie", "9780307455994", "Short stories depicting cultural conflict between Nigeria and the Western world."),
        ("White Teeth", "Zadie Smith", "9780375703867", "Two wartime friends in London build lives across multi-generational multicultural families."),
        ("On Beauty", "Zadie Smith", "9780143037743", "Cultural and academic feuds ignite between two liberal and conservative families in Massachusetts."),
        ("Interpreter of Maladies", "Jhumpa Lahiri", "9780395927205", "Pulitzer-winning short stories about Indians and Indian Americans navigating roots and migration.")
    ],

    "Mystery": [
        ("In the Woods", "Tana French", "9780143113492", "Detective Rob Ryan investigates a child murder in the woods where he lost his friends as a boy."),
        ("The Likeness", "Tana French", "9780143115625", "Detective Cassie Maddox goes undercover as a murdered woman who looks identical to her."),
        ("Faithful Place", "Tana French", "9780143119494", "Frank Mackey returns to his old neighborhood after his teenage love's suitcase is found in an abandoned house."),
        ("Broken Harbor", "Tana French", "9780143123309", "Scorcher Kennedy investigates a murder suicide in a half-built recession ghost estate."),
        ("The Secret Place", "Tana French", "9780143127581", "Stephen Moran re-opens a murder at an elite girl's boarding school after a mystery note appears."),
        ("The Trespasser", "Tana French", "9780143110309", "Antoinette Conway faces office harassment while tackling a seemingly straightforward domestic murder."),
        ("The Wych Elm", "Tana French", "9780735212893", "Toby discovers a human skull hidden inside an ancient wych elm tree in his family garden."),
        ("The Searcher", "Tana French", "9780735212954", "Ex-Chicago cop Cal Hooper moves to rural Ireland seeking peace, only to help find a missing boy."),
        ("The Hunter", "Tana French", "9780593493434", "Cal Hooper and Lena defend young Trey when her estranged father returns chasing gold."),
        ("Raven Black", "Ann Cleeves", "9780312944322", "Inspector Jimmy Perez investigates a young girl's murder in snowy Shetland."),
        ("White Nights", "Ann Cleeves", "9780312384333", "During midsummer light in Shetland, an outsider's eerie performance leads to murder."),
        ("Red Bones", "Ann Cleeves", "9780312384340", "An archaeological dig in Shetland uncovers old bones, triggering a modern shooting."),
        ("Blue Lightning", "Ann Cleeves", "9780312658861", "Jimmy Perez investigates a murder inside a bird observatory during an autumn storm."),
        ("Dead Water", "Ann Cleeves", "9781250044525", "A journalist is murdered after returning to Shetland with a sensitive news lead."),
        ("Thin Air", "Ann Cleeves", "9781250073280", "A group of old friends gather on Unst where a woman vanishes following a ghost story."),
        ("Cold Earth", "Ann Cleeves", "9781250143891", "A landslide exposes a body dressed in a red silk dress in Shetland."),
        ("Wild Fire", "Ann Cleeves", "9781250143921", "The final Shetland case involving rumor, betrayal, and murder in a new family's home."),
        ("Still Life", "Louise Penny", "9780312541538", "Chief Inspector Armand Gamache investigates the hunting death of Jane Neal in Three Pines."),
        ("A Fatal Grace", "Louise Penny", "9780312352561", "Gamache uncovers secrets when a hated woman is electrocuted during a frozen lake curling match."),
        ("The Cruelest Month", "Louise Penny", "9780312352585", "A Easter seance at the Hadley House in Three Pines frightens a resident to death."),
        ("A Rule Against Murder", "Louise Penny", "9780312380854", "Gamache's anniversary stay at the Manoir Bellechasse is disrupted by a crushed body under a statue."),
        ("The Brutal Telling", "Louise Penny", "9780312541163", "A stranger is murdered inside Olivier's bistro in Three Pines, surrounded by rare antiques."),
        ("Bury Your Dead", "Louise Penny", "9780312626907", "Gamache uncovers historical murder secrets while recovering from trauma in Quebec City."),
        ("A Trick of the Light", "Louise Penny", "9780312626914", "An art critic is murdered in Clara Morrow's garden after a triumph exhibition party."),
        ("The Beautiful Mystery", "Louise Penny", "9781250031112", "Gamache travels to a remote monastery in Quebec where a choir master monk was slain."),
        ("Strangers on a Train", "Patricia Highsmith", "9780393312805", "Two strangers trade murders on a train, but one takes the pact fatally seriously."),
        ("The Talented Mr. Ripley", "Patricia Highsmith", "9780393310191", "Tom Ripley travels to Italy to fetch Dickie Greenleaf and steals his identity through murder."),
        ("Ripley Under Ground", "Patricia Highsmith", "9780393318623", "Ripley manages an art forgery scam in France while avoiding police suspicion."),
        ("Ripley's Game", "Patricia Highsmith", "9780393319293", "Ripley manipulates an innocent picture framer into committing two mob assassinations."),
        ("Wobble to Death", "Peter Lovesey", "9780330026215", "Sergeant Cribb investigates murder during an 1870s Victorian six-day walking race."),
        ("Gallows Court", "Martin Edwards", "9780008289126", "In 1930s London, Rachel Savernake solves brutal mysteries involving wealthy elites."),
        ("A Man Lay Dead", "Ngaio Marsh", "9780007254422", "Inspector Roderick Alleyn solves a dagger murder during a country house Murder Game."),
        ("The Crime at Black Dudley", "Margery Allingham", "9780141193007", "Albert Campion assists guests when a ritual dagger game turns deadly at a secluded manor.")
    ],

    "Thriller": [
        ("The Kill Artist", "Daniel Silva", "9780451209343", "Gabriel Allon, art restorer and Israeli intelligence officer, is lured back to catch a Palestinian assassin."),
        ("The English Assassin", "Daniel Silva", "9780451208186", "Allon uncovers looted Nazi art treasures and Swiss banking secrets after a murder in Zurich."),
        ("The Confessor", "Daniel Silva", "9780451211751", "Allon investigates the murder of an author uncovering Vatican secrets during World War II."),
        ("A Death in Vienna", "Daniel Silva", "9780451213182", "A bomb explosion in Vienna leads Allon to a Nazi concentration camp commander."),
        ("Prince of Fire", "Daniel Silva", "9780451215735", "A embassy bombing in Rome sends Allon searching for an elusive terror mastermind."),
        ("The Messenger", "Daniel Silva", "9780451219241", "Gabriel Allon thwarts a terror plot targeting St. Peter's Basilica in Rome."),
        ("The Secret Servant", "Daniel Silva", "9780451224163", "Allon races through Amsterdam and London to rescue a kidnapped ambassador's daughter."),
        ("Moscow Rules", "Daniel Silva", "9780451227386", "Allon travels to Russia to stop an arms dealer from selling lethal weapons to terrorists."),
        ("The Defector", "Daniel Silva", "9780451229670", "A Russian defector is kidnapped in London, driving Allon into a high-stakes standoff."),
        ("The Rembrandt Affair", "Daniel Silva", "9780451233899", "The theft of a stolen Rembrandt painting reveals nuclear proliferation secrets."),
        ("The Bourne Identity", "Robert Ludlum", "9780553593549", "Amneric amnesiac Jason Bourne fished out of the sea struggles to regain his memory while dodging hitmen."),
        ("The Bourne Supremacy", "Robert Ludlum", "9780553263220", "Bourne is forced back into action in Asia when an impostor assassinates a Chinese leader."),
        ("The Bourne Ultimatum", "Robert Ludlum", "9780553287738", "Bourne faces his arch-enemy Carlos the Jackal in a final explosive confrontation."),
        ("The Holcroft Covenant", "Robert Ludlum", "9780553272994", "Noel Holcroft inherits a massive fund meant for Nazi victims, only to uncover a Fourth Reich conspiracy."),
        ("The Chancellor Manuscript", "Robert Ludlum", "9780553260946", "An author investigates the secret blackmail files of J. Edgar Hoover."),
        ("The Day of the Jackal", "Frederick Forsyth", "9780062898746", "An anonymous professional assassin is hired by French dissidents to kill President Charles de Gaulle."),
        ("The Odessa File", "Frederick Forsyth", "9780062898753", "A German journalist uncovers the secret ODESSA network protecting former SS officers."),
        ("The Dogs of War", "Frederick Forsyth", "9780062898760", "British mercenaries plot a coup in a mineral-rich West African republic."),
        ("The Fourth Protocol", "Frederick Forsyth", "9780062898777", "KGB hardliners scheme to detonate a covert nuclear bomb near a US airbase in Britain."),
        ("The Fist of God", "Frederick Forsyth", "9780062898784", "A British agent infiltrates Baghdad during the Gulf War to find Saddam's super-weapon."),
        ("The Hunt for Red October", "Tom Clancy", "9780451201385", "Soviet submarine captain Marko Ramius attempts to defect with a stealth nuclear submarine."),
        ("Patriot Games", "Tom Clancy", "9780451207500", "Jack Ryan thwarts a terrorist attack on British royalty in London and faces retribution in Maryland."),
        ("Clear and Present Danger", "Tom Clancy", "9780451201613", "Jack Ryan investigates a covert US black-ops war against Colombian drug cartels."),
        ("The Sum of All Fears", "Tom Clancy", "9780451203891", "Terrorists recover a lost Israeli nuclear warhead and plan to detonate it at the Super Bowl."),
        ("Without Remorse", "Tom Clancy", "9780451201118", "John Clark's origin story as a Navy SEAL conducting a private revenge mission against drug lords."),
        ("Eye of the Needle", "Ken Follett", "9780451203877", "A ruthless German spy in WWII Britain uncovers Allied invasion deception plans."),
        ("The Key to Rebecca", "Ken Follett", "9780451207609", "A German spy uses code keys hidden inside Daphne du Maurier's Rebecca in WWII Cairo."),
        ("The Man from St. Petersburg", "Ken Follett", "9780451208759", "A Russian anarchist attempts to assassinate a diplomat negotiating a WWI treaty in London."),
        ("Night Over Water", "Ken Follett", "9780451208766", "Passengers on a Pan Am flying boat crossing the Atlantic in September 1939 harbor dangerous secrets."),
        ("Code to Zero", "Ken Follett", "9780451204010", "A space scientist wakes up in a train station toilet with total amnesia on launch day in 1958."),
        ("Absolute Power", "David Baldacci", "9780446603584", "A burglar witnesses the President of the United States killed by Secret Service agents."),
        ("The Winner", "David Baldacci", "9780446606325", "A poor mother accepts a rigged lottery win from a criminal mastermind, only to be hunted."),
        ("Saving Faith", "David Baldacci", "9780446608893", "A whistleblower at a lobby firm exposes illegal CIA bribe operations.")
    ],

    "Romance": [
        ("The Duke and I", "Julia Quinn", "9780062353597", "Daphne Bridgerton and Simon Basset fake a courtship to fool society mamas in Regency London."),
        ("The Viscount Who Loved Me", "Julia Quinn", "9780062353634", "Anthony Bridgerton decides to marry, but falls for his intended's protective elder sister Kate."),
        ("An Offer From a Gentleman", "Julia Quinn", "9780062353641", "Benedict Bridgerton falls for Sophie Beckett at a masquerade ball in a Cinderella retelling."),
        ("Romancing Mister Bridgerton", "Julia Quinn", "9780062353658", "Penelope Featherington's long secret crush on Colin Bridgerton shifts into real romance."),
        ("To Sir Phillip, With Love", "Julia Quinn", "9780062353665", "Eloise Bridgerton corresponds with widow Sir Phillip Crane and runs away to meet him."),
        ("When He Was Wicked", "Julia Quinn", "9780062353672", "Michael Stirling has loved Francesca Bridgerton from afar, but family duty keeps them apart."),
        ("It's in His Kiss", "Julia Quinn", "9780062353689", "Hyacinth Bridgerton and Gareth St. Clair decipher an Italian diary containing family secrets."),
        ("On the Way to the Wedding", "Julia Quinn", "9780062353696", "Gregory Bridgerton must stop the wedding of the woman he loves before it is too late."),
        ("Secrets of a Summer Night", "Lisa Kleypas", "9780060562519", "Annabelle Peyton searches for a wealthy husband and meets ruthless industrialist Simon Hunt."),
        ("It Happened One Autumn", "Lisa Kleypas", "9780060562526", "American heiress Lillian Bowman clashes with traditional English aristocrat Marcus Lord Westcliff."),
        ("Devil in Winter", "Lisa Kleypas", "9780060562533", "Shy Evangeline Jenner proposes a marriage of convenience to notorious rake Sebastian St. Vincent."),
        ("Scandal in Spring", "Lisa Kleypas", "9780060562540", "Daisy Bowman's father orders her to choose a husband or marry his ambitious protege Matthew Swift."),
        ("Mine Till Midnight", "Lisa Kleypas", "9780312949808", "Amelia Hathaway takes care of her eccentric family and meets enigmatic hotel owner Cam Rohan."),
        ("Seduce Me at Sunrise", "Lisa Kleypas", "9780312949815", "Kev Merripen hides his forbidden passion for fragile Winnifred Hathaway."),
        ("Tempt Me at Twilight", "Lisa Kleypas", "9780312949822", "Poppy Hathaway falls for hotelier Harry Rutledge after he manipulates her engagement."),
        ("Married By Morning", "Lisa Kleypas", "9780312949839", "Governess Catherine Marks clashes with Leo Hathaway until sparks ignite between them."),
        ("Love in the Afternoon", "Lisa Kleypas", "9780312605391", "Beatrix Hathaway writes letters to Captain Christopher Phelan on the Crimean front under her friend's name."),
        ("The Wedding Date", "Jasmine Guillory", "9780399587665", "Alexa agrees to be Drew's fake girlfriend for a wedding after getting stuck in an elevator."),
        ("The Proposal", "Jasmine Guillory", "9780399587689", "Nikole is rescued from a public scoreboard proposal by doctor Carlos Benton."),
        ("The Wedding Party", "Jasmine Guillory", "9780399587702", "Maddie and Theo hate each other but enter a secret hookup arrangement during their friend's wedding."),
        ("Party of Two", "Jasmine Guillory", "9780593100820", "Lawyer Olivia Monroe begins a high-profile secret romance with California senator Max Powell."),
        ("While We Were Dating", "Jasmine Guillory", "9780593100851", "Ben and movie star Anna turn a fake promotional romance into genuine love."),
        ("Drunk on Love", "Jasmine Guillory", "9780593100882", "Napa Valley winery owner Margot has a one-night stand with her newly hired tasting room employee."),
        ("The Kiss Quotient", "Helen Hoang", "9780451490803", "Stella, an econometrician with Asperger's, hires escort Michael to practice romantic intimacy."),
        ("The Bride Test", "Helen Hoang", "9780451490827", "Khai's mother brings Esme from Vietnam to America as a potential bride for her autistic son."),
        ("The Heart Principle", "Helen Hoang", "9780451490841", "Violinist Anna undergoes burnout and connects with motorcycle-riding Quan."),
        ("The Unhoneymooners", "Christina Lauren", "9781501170799", "Olive and Ethan are forced to go on their twin sister's free Hawaiian honeymoon together."),
        ("Roomies", "Christina Lauren", "9781501165832", "Holland marries street musician Calvin to get him a green card and a Broadway role."),
        ("Love and Other Words", "Christina Lauren", "9781501128012", "Childhood sweethearts Macy and Elliot reconnect years after a devastating misunderstanding."),
        ("Twice in a Blue Moon", "Christina Lauren", "9781501197413", "Tate reunites with her first love Sam on a movie set years after he exposed her celebrity family secrets."),
        ("The Soulmate Equation", "Christina Lauren", "9781982123963", "Single mom Jess tests a genetic matching service and gets a 98% match with the arrogant founder."),
        ("Something Wilder", "Christina Lauren", "9781982173401", "Lily leads treasure hunt tours in Utah and runs into her ex-boyfriend Leo."),
        ("The True Love Experiment", "Christina Lauren", "9781982173432", "Romance novelist Fizzy stars in a reality dating show produced by documentary maker Connor.")
    ],

    "Fantasy": [
        ("Assassin's Apprentice", "Robin Hobb", "9780553573398", "Royal bastard Fitz is raised at Buckkeep Castle and trained in secret royal assassin skills."),
        ("Royal Assassin", "Robin Hobb", "9780553573411", "Fitz survives poisoning and defends the Six Duchies against Red-Ship Raiders."),
        ("Assassin's Quest", "Robin Hobb", "9780553565690", "Fitz embarks on a dangerous journey to find Prince Verity and awaken the ancient stone Dragons."),
        ("Ship of Magic", "Robin Hobb", "9780553575637", "The Vestrit family fights to claim their sentient liveship Vivacia amidst pirate wars."),
        ("Mad Ship", "Robin Hobb", "9780553575644", "Althea and Brashen rescue Vivacia while the insane liveship Paragon is restored."),
        ("Ship of Destiny", "Robin Hobb", "9780553575651", "Pirate King Kennit captures Vivacia as secrets of liveship origins are uncovered."),
        ("Fool's Errand", "Robin Hobb", "9780553582444", "Fitz lives incognito in a cottage until Chade and the Fool call him back to rescue Prince Dutiful."),
        ("Golden Fool", "Robin Hobb", "9780553582451", "Fitz acts as servant to the Fool at Buckkeep while managing Skill magic training."),
        ("Fool's Fate", "Robin Hobb", "9780553582468", "Fitz travels to Aslevjal island to slay an ice dragon and fulfill prophecy."),
        ("The Priory of the Orange Tree", "Samantha Shannon", "9781635570298", "Ead Duryan defends Queen Sabran while dragon rider Tané trains in an East-West fantasy realm."),
        ("A Day of Fallen Night", "Samantha Shannon", "9781635578928", "Four women navigate catastrophic volcanic dread and dragon fire five centuries before Priory."),
        ("The Bone Season", "Samantha Shannon", "9781620402634", "Paige Mahoney, a dreamwalker clairvoyant in dystopian London, is abducted to Scion's penal colony."),
        ("The Mime Order", "Samantha Shannon", "9781620402672", "Paige enters a bloody tournament among criminal clairvoyant syndicates in London."),
        ("The Song Rising", "Samantha Shannon", "9781620402702", "Paige becomes Underqueen and fights Scion's automated Scanner technology."),
        ("The Mask Falling", "Samantha Shannon", "9781635570342", "Paige escapes to Paris where she joins the French clairvoyant resistance network."),
        ("Tigana", "Guy Gavriel Kay", "9780451457769", "Rebels fight to liberate their conquered province whose very name was erased from memory by magic."),
        ("The Lions of Al-Rassan", "Guy Gavriel Kay", "9780060733490", "A physician, a military leader, and a mercenary navigate religious wars in medieval Moorish Spain."),
        ("Sailing to Sarantium", "Guy Gavriel Kay", "9780061051265", "Mosaicist Crispin travels to the grand empire city of Sarantium to decorate a sanctuary dome."),
        ("Lord of Emperors", "Guy Gavriel Kay", "9780061051272", "Chariot races and political conspiracies reach climax in Sarantium."),
        ("Under Heaven", "Guy Gavriel Kay", "9780451463807", "Shen Tai is gifted 250 Sardian horses, triggering imperial intrigue in Tang dynasty China."),
        ("River of Stars", "Guy Gavriel Kay", "9780451465221", "Poet Ren Daiyan and scholar Lin Shan navigate invasion during the Song dynasty decline."),
        ("A Brightness Long Ago", "Guy Gavriel Kay", "9780440000785", "Mercenaries, killers, and bookbinders clash in Renaissance Italian city-states."),
        ("Uprooted", "Naomi Novik", "9780804179805", "Agnieszka is selected by the wizard Dragon to live in his tower and protect the valley from Wood corruption."),
        ("Spinning Silver", "Naomi Novik", "9780425290316", "Miryem turns silver into gold and catches the eye of the icy winter Staryk king."),
        ("A Deadly Education", "Naomi Novik", "9780593128480", "El Higgins navigates Scholomance, a magical boarding school full of deadly monsters and no teachers."),
        ("The Last Graduate", "Naomi Novik", "9780593128862", "El and her classmates plan an impossible escape for the entire senior class during graduation."),
        ("The Golden Enclaves", "Naomi Novik", "9780593128893", "El discovers dark secrets behind the creation of magical enclaves worldwide."),
        ("His Majesty's Dragon", "Naomi Novik", "9780345481283", "Captain Will Laurence bonds with dragon Temeraire in an alternate Napoleonic War era."),
        ("Throne of Jade", "Naomi Novik", "9780345481290", "Laurence and Temeraire travel to Imperial China to defend Laurence's dragon companion."),
        ("Black Powder War", "Naomi Novik", "9780345481306", "Temeraire travels across Istanbul and Prussia to bring dragon eggs home to Britain."),
        ("The Bear and the Nightingale", "Katherine Arden", "9781101885956", "Vasya uses old folk magic in medieval Russia to protect her village from a frost demon."),
        ("The Girl in the Tower", "Katherine Arden", "9781101885987", "Vasya disguises herself as a boy and rides to Moscow to fight bandits."),
        ("The Winter of the Witch", "Katherine Arden", "9781101886014", "Vasya rallies Russian spirits and humans to battle invading Tatars.")
    ],

    "Science Fiction": [
        ("The Left Hand of Darkness", "Ursula K. Le Guin", "9780441478125", "Genly Ai acts as envoy to ambisexual human inhabitants of planet Gethen."),
        ("The Dispossessed", "Ursula K. Le Guin", "9780061054884", "Physicist Shevek travels between an anarchist moon colony and a capitalist mother planet."),
        ("The Lathe of Heaven", "Ursula K. Le Guin", "9781416556961", "George Orr's dreams alter reality, and a psychiatrist attempts to manipulate them for world peace."),
        ("The Word for World Is Forest", "Ursula K. Le Guin", "9780812577174", "Indigenous inhabitants of planet Athshe revolt against destructive human logging colonizers."),
        ("The Telling", "Ursula K. Le Guin", "9780156012867", "Sutty travels to planet Aka to record outlawed ancient storytelling traditions."),
        ("The Shadow of the Torturer", "Gene Wolfe", "9780312890170", "Exiled apprentice torturer Severian wanders dying future Earth carrying the executioner sword Terminus Est."),
        ("The Claw of the Conciliator", "Gene Wolfe", "9780312890187", "Severian acquires a miraculous healing gem while traveling north to Thrax."),
        ("The Sword of the Lictor", "Gene Wolfe", "9780312890194", "Severian rules as executioner in Thrax but flees into the mountains after sparing a victim."),
        ("The Citadel of the Autarch", "Gene Wolfe", "9780312890200", "Severian fights in the Northern war and fulfills his destiny to become Autarch of Urth."),
        ("Permutation City", "Greg Egan", "9781597805391", "Virtual reality copies of human minds construct self-sustaining universes in digital space."),
        ("Diaspora", "Greg Egan", "9781597805421", "Post-biological software beings explore higher-dimensional physics after a cosmic disaster."),
        ("Quarantine", "Greg Egan", "9781597805384", "A private detective investigates a missing mental patient after the solar system is enclosed in a bubble."),
        ("Schild's Ladder", "Greg Egan", "9780061050930", "Physicists investigate a expanding novel vacuum state consuming stars in deep space."),
        ("Revelation Space", "Alastair Reynolds", "9780441009428", "Dan Sylveste explores an extinct alien civilization while an ultra-ship crew seeks his secrets."),
        ("Chasm City", "Alastair Reynolds", "9780441010646", "Tanner Mirabel hunts an assassin in a decaying high-tech city infected by a nano-plague."),
        ("Redemption Ark", "Alastair Reynolds", "9780441011735", "Human factions battle for ancient alien super-weapons to fight the Inhibitor machines."),
        ("Absolution Gap", "Alastair Reynolds", "9780441012725", "Religious cultists worship a gas giant planet that vanishes and reappears."),
        ("House of Suns", "Alastair Reynolds", "9780441018246", "Six million years in the future, clone shatterling siblings investigate the massacre of their line."),
        ("Pushing Ice", "Alastair Reynolds", "9780441015023", "A comet-mining crew is diverted to chase Saturn's moon Janus as it leaves orbit."),
        ("Hyperion", "Dan Simmons", "9780553283686", "Seven pilgrims travel to the Time Tombs of Hyperion to meet the terrifying metallic Shrike."),
        ("The Fall of Hyperion", "Dan Simmons", "9780553288209", "The Hegemony battles Ouster invaders while the pilgrims uncover AI TechnoCore betrayals."),
        ("Endymion", "Dan Simmons", "9780553572940", "Raul Endymion is chosen to rescue Aenea, a child destined to challenge the Pax Church empire."),
        ("The Rise of Endymion", "Dan Simmons", "9780553572988", "Raul and Aenea travel across worlds to spread empathy and defeat the Pax armada."),
        ("The Three-Body Problem", "Cixin Liu", "9780765377067", "A secret military project sends signals into space, inviting an alien civilization on a doomed planet."),
        ("The Dark Forest", "Cixin Liu", "9780765377081", "Humanity appoints four Wallfacers to develop secret defence plans against Trisolaran sophon surveillance."),
        ("Death's End", "Cixin Liu", "9780765377104", "Cheng Xin awakens centuries later to manage cosmic deterrence in a multi-dimensional universe."),
        ("Ball Lightning", "Cixin Liu", "9780765394071", "A researcher obsessed with ball lightning develops weaponized high-energy physics."),
        ("The Wandering Earth", "Cixin Liu", "9781786692047", "Short stories depicting humanity building thrusters to move Earth away from an expanding sun."),
        ("Dawn", "Octavia E. Butler", "9780446603775", "Lilith Iyapo awakens aboard an alien ship after nuclear war and must help interbreed humanity with the Oankali."),
        ("Adulthood Rites", "Octavia E. Butler", "9780446603782", "Lilith's construct son Akin navigates human resistance colonies and alien genetics."),
        ("Imago", "Octavia E. Butler", "9780446603799", "Jodahs becomes the first construct ooloi, guiding human and alien evolution."),
        ("Parable of the Sower", "Octavia E. Butler", "9780446675505", "Lauren Olamina suffers from hyperempathy while founding Earthseed in climate-ravaged California."),
        ("Parable of the Talents", "Octavia E. Butler", "9780446675512", "Lauren defends Earthseed communities against fanatical religious militants.")
    ],

    "Horror": [
        ("The Haunting of Hill House", "Shirley Jackson", "9780143039983", "Four paranormal investigators stay at Hill House, where Eleanor Vance experiences intense supernatural pressure."),
        ("We Have Always Lived in the Castle", "Shirley Jackson", "9780143039976", "Merricat Blackwood lives isolated in a mansion with her sister Constance after family arsenic poisonings."),
        ("The Sundial", "Shirley Jackson", "9780143107071", "An eccentric wealthy family prepares inside their estate for an impending apocalyptic end of the world."),
        ("The Bird's Nest", "Shirley Jackson", "9780143125297", "A shy young woman undergoes psychoanalysis revealing four distinct splintered personalities."),
        ("Hangsaman", "Shirley Jackson", "9780143122098", "Natalie Waite goes to college and slips into psychological isolation and delusion."),
        ("Songs of a Dead Dreamer", "Thomas Ligotti", "9780143107767", "Unsettling puppet dreams, corporate dread, and philosophical cosmic horror stories."),
        ("Grimscribe: His Lives and Works", "Thomas Ligotti", "9780143107774", "Tales of strange rituals, decrepit towns, and hopeless fatalism."),
        ("Teatro Grottesco", "Thomas Ligotti", "9780578028682", "Surreal stories detailing art obsessives, mysterious troupes, and existential void."),
        ("The Conspiracy Against the Human Race", "Thomas Ligotti", "9780143133148", "A philosophical non-fiction work examining pessimism, anti-natalism, and human consciousness as a tragic error."),
        ("Books of Blood: Volumes One to Three", "Clive Barker", "9780425165584", "Groundbreaking modern horror stories featuring bodily transformation, monsters, and dark imagination."),
        ("The Damnation Game", "Clive Barker", "9780451168283", "Marty Strauss acts as bodyguard for a billionaire who made a Faustian pact with a immortal gambler."),
        ("Weaveworld", "Clive Barker", "9780061001109", "A magical realm woven into a carpet is pursued by dark sorcerers and human guardians."),
        ("Imajica", "Clive Barker", "9780060937263", "A massive epic connecting Earth to four parallel magical Dominions through reconciliation rituals."),
        ("Cabal", "Clive Barker", "9780061000928", "Boone searches for Midian, a subterranean city of monsters and outcasts."),
        ("The Thief of Always", "Clive Barker", "9780060572977", "Harvey Swick visits the Holiday House where every day brings four seasons, but at a terrible price."),
        ("Ghost Story", "Peter Straub", "9780061000145", "Four elderly men in Milburn gather to share ghost stories, pursued by an ancient shapeshifting terror."),
        ("Julia", "Peter Straub", "9780445041042", "A grieving mother moves into a London house haunted by a sadistic child ghost."),
        ("If You Could See Me Now", "Peter Straub", "9780445043810", "Miles returns to his hometown twenty years after his cousin's murder, reopening old horrors."),
        ("Shadowland", "Peter Straub", "9780061000152", "Two boys spending summer at a secluded estate learn real stage magic that turns dark."),
        ("Koko", "Peter Straub", "9780061000169", "Four Vietnam veterans track down a serial killer using a secret military nickname in Asia."),
        ("Mystery", "Peter Straub", "9780061000176", "Young Tom Pasmore solves a island murder mystery alongside an aging detective."),
        ("The Throat", "Peter Straub", "9780061000183", "Tim Underhill returns to Blue Rose to solve serial murders linked to Vietnam."),
        ("The Drowning Girl", "Caitlín R. Kiernan", "9780451464477", "India Morgan Phelps, a schizophrenic narrator, unravels her encounters with a mysterious siren woman."),
        ("Threshold", "Caitlín R. Kiernan", "9780451458889", "A paleontology student uncovers primordial subterranean entities under Birmingham."),
        ("Low Red Moon", "Caitlín R. Kiernan", "9780451459794", "Chance and Deacon investigate brutal murders tied to a psychic vampire spirit."),
        ("Houses Under the Sea", "Caitlín R. Kiernan", "9781596069060", "Mythos short stories exploring deep ocean terror, rituals, and dark visions."),
        ("The House on the Borderland", "William Hope Hodgson", "9780486467368", "Two hikers discover a manuscript in an Irish ruin describing a house subject to swine-monsters and time acceleration."),
        ("The Night Land", "William Hope Hodgson", "9780486467375", "Millions of years in the future, the Last Redoubt human fortress survives under eternal darkness."),
        ("The King in Yellow", "Robert W. Chambers", "9780486437507", "Macabre stories surrounding a forbidden play that drives its readers insane."),
        ("The Willows", "Algernon Blackwood", "9781420956559", "Two canoeists on the Danube river encounter otherworldly forces near flooded willow islands."),
        ("The Wendigo", "Algernon Blackwood", "9781420956566", "A hunting party in the Canadian wilderness is terrorized by a legendary flesh-eating wind spirit."),
        ("At the Mountains of Madness", "H.P. Lovecraft", "9780486440538", "An Antarctic expedition uncovers pre-human ruins built by Elder Things."),
        ("The Shadow over Innsmouth", "H.P. Lovecraft", "9780486823843", "A student visits a decaying Massachusetts seaport town ruled by fish-hybrid cultists.")
    ],

    "Self-Help": [
        ("The Gifts of Imperfection", "Brené Brown", "9781592858491", "Let go of who you think you're supposed to be and embrace who you are."),
        ("Daring Greatly", "Brené Brown", "9781594631504", "How the courage to be vulnerable transforms the way we live, love, parent, and lead."),
        ("Rising Strong", "Brené Brown", "9780812995824", "The reckoning, rumble, and revolution of resetting after failure and heartbreak."),
        ("Braving the Wilderness", "Brené Brown", "9780812995848", "The quest for true belonging and the courage to stand alone."),
        ("Dare to Lead", "Brené Brown", "9780399592522", "Brave work, tough conversations, and showing up with wholehearted leadership."),
        ("Atlas of the Heart", "Brené Brown", "9781984854032", "Mapping eighty-seven emotions and experiences that define what it means to be human."),
        ("Mindset: The New Psychology of Success", "Carol S. Dweck", "9780345472328", "How believing in growth versus fixed mindset shapes achievement in school, work, and sports."),
        ("Quiet: The Power of Introverts", "Susan Cain", "9780307352156", "Celebrating introverted strengths in a world that can't stop talking."),
        ("Bittersweet", "Susan Cain", "9780451499782", "How sorrow and longing make us whole and fuel creativity."),
        ("The Happiness Project", "Gretchen Rubin", "9780061583261", "Test-driving age-old wisdom and modern science on how to be happier."),
        ("Happier at Home", "Gretchen Rubin", "9780307886781", "Focusing on home life, clutter, parenthood, and family relationships."),
        ("Better Than Before", "Gretchen Rubin", "9780385348614", "What habit change science reveals about making and breaking daily habits."),
        ("The Four Tendencies", "Gretchen Rubin", "9780451499706", "Understanding how you respond to expectations: Upholder, Questioner, Obliger, or Rebel."),
        ("Outer Order, Inner Calm", "Gretchen Rubin", "9781984822802", "Decluttering strategies to clear space and mind."),
        ("Life in Five Senses", "Gretchen Rubin", "9780593442745", "How tuning into sight, sound, smell, taste, and touch restores joy."),
        ("Deep Work", "Cal Newport", "9781455586691", "Rules for focused success in a distracted world."),
        ("Digital Minimalism", "Cal Newport", "9780525536512", "Choosing a focused life in a noisy digital age."),
        ("So Good They Can't Ignore You", "Cal Newport", "9781455509126", "Why career passion is a myth and skill acquisition crafts great work."),
        ("A World Without Email", "Cal Newport", "9780525536550", "Reimagining work in an age of communication overload."),
        ("Slow Productivity", "Cal Newport", "9780593544853", "The lost art of accomplishment without burnout."),
        ("The Power of Habit", "Charles Duhigg", "9780812981605", "Why we do what we do in life and business through habit loops."),
        ("Smarter Faster Better", "Charles Duhigg", "9780812993394", "The science of productivity, motivation, and goal setting."),
        ("Supercommunicators", "Charles Duhigg", "9780593243916", "How to unlock the secret language of connection and conversation."),
        ("Maybe You Should Talk to Someone", "Lori Gottlieb", "9781328662057", "A therapist, her therapist, and our lives revealed with humor and wisdom."),
        ("Set Boundaries, Find Peace", "Nedra Glover Tawwab", "9780593192092", "A guide to reclaiming yourself through healthy personal boundaries."),
        ("Drama Free", "Nedra Glover Tawwab", "9780593539279", "A guide to managing unwholesome family relationships and setting healthy boundaries."),
        ("Essentialism", "Greg McKeown", "9780804137386", "The disciplined pursuit of less in work and personal life."),
        ("Effortless", "Greg McKeown", "9780593135648", "Make it easier to do what matters most."),
        ("The Subtle Art of Not Giving a F*ck", "Mark Manson", "9780062457714", "A counterintuitive approach to living a good life by prioritizing values."),
        ("Everything Is F*cked", "Mark Manson", "9780062888433", "A book about hope, anxiety, and modern psychological challenges."),
        ("Atomic Habits", "James Clear", "9780735211292", "An easy and proven way to build good habits and break bad ones."),
        ("Grit: The Power of Passion and Perseverance", "Angela Duckworth", "9781501111105", "Why passion and resilience matter more than talent for long-term success."),
        ("Mindsets for Success", "Carol S. Dweck", "9780345472335", "Practical application of growth mindset across daily decision making.")
    ],

    "Biography": [
        ("The Power Broker", "Robert A. Caro", "9780394720241", "Robert Moses and the rise and fall of New York's urban landscape."),
        ("The Path to Power", "Robert A. Caro", "9780679729457", "The first volume of LBJ's biography covering his Texas Hill Country upbringing."),
        ("Means of Ascent", "Robert A. Caro", "9780679733713", "The second volume covering Lyndon Johnson's 1948 Senate campaign victory."),
        ("Master of the Senate", "Robert A. Caro", "9780394528367", "The third volume documenting LBJ's tactical genius as Senate Majority Leader."),
        ("The Passage of Power", "Robert A. Caro", "9780679405078", "The fourth volume tracing LBJ's vice presidency and ascension following JFK's death."),
        ("Alexander Hamilton", "Ron Chernow", "9780143034759", "The founding father who built America's financial system and government institutions."),
        ("Washington: A Life", "Ron Chernow", "9780143119968", "Pulitzer Prize-winning biography of George Washington as general and president."),
        ("Grant", "Ron Chernow", "9780143110637", "The Civil War general and 18th President's military genius and presidential record."),
        ("Titan: The Life of John D. Rockefeller Sr.", "Ron Chernow", "9781400077304", "The oil tycoon who built Standard Oil and pioneered modern philanthropy."),
        ("The House of Morgan", "Ron Chernow", "9780802144652", "An epic history of the Morgan banking dynasty across American history."),
        ("FDR", "Jean Edward Smith", "9780812970494", "The definitive biography of Franklin Delano Roosevelt from childhood to presidency."),
        ("Eisenhower in War and Peace", "Jean Edward Smith", "9780679644293", "The Allied Supreme Commander and 34th President's strategic leadership."),
        ("George W. Bush", "Jean Edward Smith", "9781476743967", "A critical assessment of the 43rd President's war decisions and domestic policy."),
        ("Team of Rivals", "Doris Kearns Goodwin", "9780684824901", "Abraham Lincoln's political genius in appointing rival opponents to his cabinet."),
        ("Leadership in Turbulent Times", "Doris Kearns Goodwin", "9781476795928", "Leadership lessons from Abraham Lincoln, Theodore Roosevelt, FDR, and LBJ."),
        ("No Ordinary Time", "Doris Kearns Goodwin", "9780684804484", "Franklin and Eleanor Roosevelt's home front leadership during World War II."),
        ("The Bully Pulpit", "Doris Kearns Goodwin", "9781416547860", "Theodore Roosevelt, William Howard Taft, and the Golden Age of journalism."),
        ("Steve Jobs", "Walter Isaacson", "9781451648539", "The exclusive biography of Apple co-founder Steve Jobs based on forty interviews."),
        ("Leonardo da Vinci", "Walter Isaacson", "9781501139154", "Connecting art, science, and curiosity through Leonardo's genius notebooks."),
        ("Einstein: His Life and Universe", "Walter Isaacson", "9780743264747", "How Albert Einstein's imaginative mind reshaped physics and global history."),
        ("Benjamin Franklin: An American Life", "Walter Isaacson", "9780743258074", "The printer, scientist, inventor, and diplomat who defined American identity."),
        ("Elon Musk", "Walter Isaacson", "9781982181284", "Inside the turbulent life and ventures of SpaceX, Tesla, and Neuralink founder."),
        ("Churchill: A Life", "Martin Gilbert", "9780060927431", "The official single-volume biography of Britain's wartime Prime Minister."),
        ("Custer's Trials", "T.J. Stiles", "9780307592644", "Pulitzer-winning biography of George Armstrong Custer in Civil War and West."),
        ("The First Tycoon", "T.J. Stiles", "9780307271556", "The life of Cornelius Vanderbilt, railroad baron and creator of modern capitalism."),
        ("The Rise of Theodore Roosevelt", "Edmund Morris", "9780375756788", "The Pulitzer-winning chronicle of TR's life up to the presidency."),
        ("Theodore Rex", "Edmund Morris", "9780812966008", "The presidential years of Theodore Roosevelt from 1901 to 1909."),
        ("Colonel Roosevelt", "Edmund Morris", "9780375504877", "The final years of TR's life including African safari and River of Doubt."),
        ("Dutch: A Memoir of Ronald Reagan", "Edmund Morris", "9780374145705", "The authorized biographical portrait of the 40th President."),
        ("Empress Dowager Cixi", "Jung Chang", "9780307456700", "The concubine who launched modern China and ruled behind the throne for decades."),
        ("Wild Swans", "Jung Chang", "9780743246989", "Three daughters of China navigating imperial rule, warlords, and Maoist revolution."),
        ("Mao: The Unknown Story", "Jung Chang & Jon Halliday", "9780679746324", "A groundbreaking revisionist biography of Mao Zedong."),
        ("Madame Curie", "Eve Curie", "9780306810381", "The moving biography of double Nobel laureate Marie Curie written by her daughter.")
    ],

    "History": [
        ("The Age of Revolution: 1789-148", "Eric Hobsbawm", "9780679772538", "The dual transformation of society by French Revolution and British Industrial Revolution."),
        ("The Age of Capital: 1848-1875", "Eric Hobsbawm", "9780679772545", "The worldwide rise of industrial capitalism and bourgeois culture."),
        ("The Age of Empire: 1875-1914", "Eric Hobsbawm", "9780679772552", "Global imperialism, colonial expansion, and rivalries leading up to WWI."),
        ("The Age of Extremes: 1914-1991", "Eric Hobsbawm", "9780679730057", "The short twentieth century from WWI to the collapse of the Soviet Union."),
        ("Hitler: 1889-1936 Hubris", "Ian Kershaw", "9780393320350", "Tracing Hitler's early life, political rise, and totalitarian dictatorship."),
        ("Hitler: 1936-1945 Nemesis", "Ian Kershaw", "9780393322521", "The military aggression, Holocaust, and total collapse of the Nazi state."),
        ("To Hell and Back: Europe 1914-1949", "Ian Kershaw", "9780143111245", "Europe's devastating self-destruction during two world wars and recovery."),
        ("Roller-Coaster: Europe 1950-2017", "Ian Kershaw", "9780525559900", "Post-war European unity, Cold War tension, and modern challenges."),
        ("The Sleepwalkers", "Christopher Clark", "9780061146664", "How European leaders stumbled blindly into World War I in July 1914."),
        ("Iron Kingdom: The Rise and Downfall of Prussia", "Christopher Clark", "9780674031968", "The history of Prussia from 1600s militarism to post-WWII dissolution."),
        ("A People's Tragedy", "Orlando Figes", "9780140243642", "The Russian Revolution 1891-1924 analyzed across all social classes."),
        ("The Whisperers", "Orlando Figes", "9780312428037", "Private life in Stalin's Russia based on oral histories and personal diaries."),
        ("Natasha's Dance", "Orlando Figes", "9780312421953", "A cultural history of Russia spanning literature, music, folk traditions, and architecture."),
        ("The Europeans", "Orlando Figes", "9780451494894", "The 19th-century railway boom and birth of cosmopolitan European culture."),
        ("The Rise and Fall of the Third Reich", "William L. Shirer", "9781451651683", "The classic single-volume journalistic history of Nazi Germany."),
        ("Berlin Diary", "William L. Shirer", "9780801870569", "Eyewitness account of foreign correspondent reporting from Berlin 1934-1941."),
        ("The Coming of the Third Reich", "Richard J. Evans", "9780143034698", "How Weimar Democracy disintegrated into Nazi dictatorship."),
        ("The Third Reich in Power", "Richard J. Evans", "9780143037903", "Police state terror, propaganda, and rearmament in 1930s Germany."),
        ("The Third Reich at War", "Richard J. Evans", "9780143116714", "WWII military campaigns, terror across occupied Europe, and Holocaust."),
        ("Postwar: A History of Europe Since 1945", "Tony Judt", "9780143037750", "The definitive history of Europe's post-WWII division and transformation."),
        ("The Splendid and the Vile", "Erik Larson", "9780385348713", "Winston Churchill and London surviving the Blitz during 1940-1941."),
        ("The Devil in the White City", "Erik Larson", "9780375725609", "The 1893 Chicago World's Fair architect Daniel Burnham and serial killer H.H. Holmes."),
        ("In the Garden of Beasts", "Erik Larson", "9780307408853", "US Ambassador William Dodd and his family in 1930s Berlin as Hitler takes power."),
        ("Dead Wake", "Erik Larson", "9780307408877", "The sinking of the Lusitania in 1915 and US entry into World War I."),
        ("Thunderstruck", "Erik Larson", "9781400063321", "Marconi's wireless telegraph invention tied to murderer Hawley Crippen's escape."),
        ("Isaac's Storm", "Erik Larson", "9780375708275", "The devastating 1900 Galveston hurricane and early meteorology."),
        ("Demon of Unrest", "Erik Larson", "9780385348744", "The five months between Lincoln's election and the attack on Fort Sumter."),
        ("Command and Control", "Eric Schlosser", "9780143125785", "Nuclear weapons safety, Titan II missile silo accidents, and illusion of safety."),
        ("Fast Food Nation", "Eric Schlosser", "9780547238234", "The dark side of the all-American meal and industrial food supply chain."),
        ("Caste: The Origins of Our Discontents", "Isabel Wilkerson", "9780593230251", "Comparing unspoken social hierarchies in America, India, and Nazi Germany."),
        ("The Warmth of Other Suns", "Isabel Wilkerson", "9780679760733", "The epic story of America's Great Migration of Black citizens moving North and West."),
        ("Say Nothing", "Patrick Radden Keefe", "9780385521314", "A true story of murder and memory in Northern Ireland during The Troubles."),
        ("Empire of Pain", "Patrick Radden Keefe", "9780385545686", "The secret history of the Sackler dynasty and OxyContin opioid crisis.")
    ],

    "Philosophy": [
        ("The Fragility of Goodness", "Martha C. Nussbaum", "9780521791267", "Luck and ethics in Greek tragedy and philosophy from Sophocles to Aristotle."),
        ("Cultivating Humanity", "Martha C. Nussbaum", "9780674179493", "A classical defense of reform in liberal education and citizenship."),
        ("Upheavals of Thought", "Martha C. Nussbaum", "9780521531825", "The intelligence of emotions and their role in moral judgment."),
        ("Frontiers of Justice", "Martha C. Nussbaum", "9780674024106", "Disability, nationality, and species membership expanding social contract theory."),
        ("Creating Capabilities", "Martha C. Nussbaum", "9780674072350", "The human development approach to global justice and quality of life."),
        ("After Virtue", "Alasdair MacIntyre", "9780268035044", "A critique of Enlightenment moral theory proposing a return to Aristotelian virtue ethics."),
        ("Whose Justice? Which Rationality?", "Alasdair MacIntyre", "9780268019426", "Comparing Aristotelian, Augustinian, Humean, and modern liberal traditions."),
        ("Three Rival Versions of Moral Enquiry", "Alasdair MacIntyre", "9780268018771", "Encyclopaedia, Genealogy, and Tradition in moral philosophy."),
        ("Sources of the Self", "Charles Taylor", "9780674824263", "The making of modern identity across inwardness, ordinary life, and nature."),
        ("A Secular Age", "Charles Taylor", "9780674026766", "Tracing how Western society shifted from belief to secular options over five centuries."),
        ("Modern Social Imaginaries", "Charles Taylor", "9780822332930", "Public sphere, market economy, and self-governing people defining modern life."),
        ("Reasons and Persons", "Derek Parfit", "9780198249085", "Personal identity over time, rationality, and ethics for future generations."),
        ("On What Matters: Volume One", "Derek Parfit", "9780199572809", "Synthesizing Kantianism, Utilitarianism, and Contractualism into one moral peak."),
        ("On What Matters: Volume Two", "Derek Parfit", "9780199572816", "Responding to critics on normativity, objectivity, and moral truth."),
        ("Ethics and the Limits of Philosophy", "Bernard Williams", "9780674010161", "Arguing against systematic moral theories like Kantianism and Utilitarianism."),
        ("Shame and Necessity", "Bernard Williams", "9780520256248", "Ancient Greek moral ideas versus modern Kantian notions of responsibility."),
        ("Truth and Truthfulness", "Bernard Williams", "9780691117911", "Defending the virtues of accuracy and sincerity in historical and scientific debate."),
        ("Practical Ethics", "Peter Singer", "9780521707688", "Applied ethics on animal liberation, abortion, euthanasia, and global poverty."),
        ("Animal Liberation", "Peter Singer", "9780061730054", "The landmark manifesto advocating speciesism rejection and animal welfare."),
        ("The Life You Can Save", "Peter Singer", "9780345518606", "Acting now to end world poverty through effective altruism donation."),
        ("The Expanding Circle", "Peter Singer", "9780691150697", "Ethics and sociobiology explaining the evolutionary expansion of moral concern."),
        ("The Sovereignty of Good", "Iris Murdoch", "9780415253994", "Platonic moral philosophy emphasizing attention, love, and un-selfing."),
        ("Existentialists and Mystics", "Iris Murdoch", "9780140264920", "Essays on literature, philosophy, Sartre, and Simone de Beauvoir."),
        ("The Ethics of Ambiguity", "Simone de Beauvoir", "9780806501604", "Existentialist ethics emphasizing human freedom and action without dogmatism."),
        ("The Second Sex", "Simone de Beauvoir", "9780307277787", "Foundational feminist philosophy examining the social construction of womanhood."),
        ("The Human Condition", "Hannah Arendt", "9780226025988", "Labor, work, and action in classical and modern political existence."),
        ("Eichmann in Jerusalem", "Hannah Arendt", "9780143039884", "A report on the banality of evil during Adolf Eichmann's war crimes trial."),
        ("The Origins of Totalitarianism", "Hannah Arendt", "9780156701532", "Antisemitism, imperialism, and totalitarian regimes in Nazi Germany and Stalinist Russia."),
        ("On Revolution", "Hannah Arendt", "9780141186764", "Comparing the American and French revolutions on freedom and political council."),
        ("The Life of the Mind", "Hannah Arendt", "9780156526005", "Thinking, Willing, and Judging as core human mental faculties."),
        ("Simulacra and Simulation", "Jean Baudrillard", "9780472065219", "Postmodern philosophy arguing signs and symbols substitute for physical reality."),
        ("The Order of Things", "Michel Foucault", "9780679753353", "An archaeology of human sciences and shifting historical episteme paradigms."),
        ("Discipline and Punish", "Michel Foucault", "9780679752554", "The birth of the prison system, panopticism, and power knowledge networks.")
    ],

    "Young Adult": [
        ("Six of Crows", "Leigh Bardugo", "9781627791601", "Kaz Brekker leads a crew of six deadly outcasts on an impossible heist in Ketterdam."),
        ("Crooked Kingdom", "Leigh Bardugo", "9781627791618", "Kaz and his crew fight for redemption and survival against powerful rival syndicates."),
        ("Shadow and Bone", "Leigh Bardugo", "9780374384654", "Alina Starkov discovers sun-summoning magic that could destroy the Shadow Fold."),
        ("Siege and Storm", "Leigh Bardugo", "9780374384678", "Alina and Mal flee Ravka while the Darkling hunts sea whip amplifiers."),
        ("Ruin and Rising", "Leigh Bardugo", "9780374384708", "Alina hunts the firebird amplifier to make her final stand against the Darkling."),
        ("King of Scars", "Leigh Bardugo", "9781250142283", "Nikolai Lantsov defends Ravka while fighting a dark demon sleeping within him."),
        ("Rule of Wolves", "Leigh Bardugo", "9781250142306", "Nikolai, Zoya, and Nina risk everything to save Ravka from total destruction."),
        ("Red Queen", "Victoria Aveyard", "9780062310637", "Mare Barrow discovers she has electric powers despite having common Red blood."),
        ("Glass Sword", "Victoria Aveyard", "9780062310668", "Mare rallies a rebellion of newbloods against King Maven's Silver army."),
        ("King's Cage", "Victoria Aveyard", "9780062310699", "Mare is imprisoned at court while Iris and Cal plot massive war alliances."),
        ("War Storm", "Victoria Aveyard", "9780062310729", "The epic final war for freedom and equality in Norta."),
        ("Realm Breaker", "Victoria Aveyard", "9780062872623", "Corayne gathers a band of misfits to save the world from realm-tearing gates."),
        ("Blade Breaker", "Victoria Aveyard", "9780062872654", "Corayne's companions face ancient demonic forces as spindles rupture."),
        ("An Ember in the Ashes", "Sabaa Tahir", "9780451474346", "Laia goes undercover as a slave at the Martial academy where Laia meets soldier Elias."),
        ("A Torch Against the Night", "Sabaa Tahir", "9780451474360", "Laia and Elias fight through Empire territory to rescue Laia's brother from Kauf prison."),
        ("A Reaper at the Gates", "Sabaa Tahir", "9780451474384", "Helena fights to preserve the Empire while Nightbringer unleashes djinn armies."),
        ("A Sky Beyond the Storm", "Sabaa Tahir", "9780593108871", "The dramatic conclusion as Laia, Elias, and Helena confront the Nightbringer."),
        ("All My Rage", "Sabaa Tahir", "9780593202395", "Salahudin and Noor navigate family trauma, immigration, and love in California desert town."),
        ("One of Us Is Lying", "Karen M. McManus", "9781524714680", "Five students walk into detention, but only four walk out alive after high school gossip creator dies."),
        ("One of Us Is Next", "Karen M. McManus", "9781524714727", "A deadly Truth or Dare game targets Bayview High students a year after Simon's death."),
        ("One of Us Is Back", "Karen M. McManus", "9780593485842", "The Bayview Crew unites again when a mysterious billboard triggers a new threat."),
        ("Two Can Keep a Secret", "Karen M. McManus", "9781524714697", "Ellery moves to Echo Ridge where homecoming queens have a history of vanishing."),
        ("The Cousins", "Karen M. McManus", "9780593175828", "Three cousins receive invitations to work at their secretive grandmother's island resort."),
        ("You'll Be the Death of Me", "Karen M. McManus", "9780593175866", "Three old friends ditching school walk right into a crime scene."),
        ("The Poet X", "Elizabeth Acevedo", "9780062662805", "Xiomara Batista finds her voice through slam poetry in Harlem."),
        ("With the Fire on High", "Elizabeth Acevedo", "9780062662836", "High school senior Emoni balances motherhood, culinary talent, and a trip to Spain."),
        ("Clap When You Land", "Elizabeth Acevedo", "9780062882769", "Two half-sisters learn of each other's existence after their father dies in a plane crash."),
        ("Family Lore", "Elizabeth Acevedo", "9780063207264", "A multi-generational novel following Dominican sisters possessing unique magical gifts."),
        ("Carry On", "Rainbow Rowell", "9781250135025", "Simon Snow attends Watford School of Magick while dealing with his vampire roommate Baz."),
        ("Wayward Son", "Rainbow Rowell", "9781250146076", "Simon, Baz, and Penelope take an American West road trip facing vintage vampires."),
        ("Any Way the Wind Blows", "Rainbow Rowell", "9781250257000", "Simon returns to London to resolve his magic identity and relationship with Baz."),
        ("Fangirl", "Rainbow Rowell", "9781250030955", "Cath starts college writing fanfiction while navigating her twin sister's independence."),
        ("Eleanor & Park", "Rainbow Rowell", "9781250012579", "Two teenage misfits bond over comic books and mixtapes on a 1986 bus.")
    ],

    "Poetry": [
        ("Death of a Naturalist", "Seamus Heaney", "9780871133076", "Heaney's debut collection depicting rural Irish farm labor, nature, and childhood."),
        ("Door into the Dark", "Seamus Heaney", "9780571089208", "Craftsmanship, blacksmiths, and Irish bog landscapes in resonant verse."),
        ("Wintering Out", "Seamus Heaney", "9780571101580", "Linguistic origins and sectarian tension in 1970s Northern Ireland."),
        ("North", "Seamus Heaney", "9780571105649", "Poetic reflections on ancient Iron Age bog bodies and modern Troubles conflict."),
        ("Field Work", "Seamus Heaney", "9780374154851", "Elegies for friends and rural tranquility in County Wicklow."),
        ("Station Island", "Seamus Heaney", "9780374269784", "A spiritual pilgrimage poem sequence encountering ghosts of Irish literary history."),
        ("Seeing Things", "Seamus Heaney", "9780374257699", "Reflections on vision, fatherhood, memory, and spiritual light."),
        ("The Spirit Level", "Seamus Heaney", "9780374267773", "Peace building, hope, and everyday miracles in post-ceasefire Ireland."),
        ("Electric Light", "Seamus Heaney", "9780374146702", "Travels through Greece and Europe reflecting on classical pastoral poetry."),
        ("District and Circle", "Seamus Heaney", "9780374140922", "Subway journeys, rural memories, and modern political anxieties."),
        ("Human Chain", "Seamus Heaney", "9780374173500", "Heaney's final tender collection exploring aging, stroke recovery, and inheritance."),
        ("Diving into the Wreck", "Seamus Heaney & Adrienne Rich", "9780393311631", "Feminist landmark poetry exploring womanhood, history, and social justice."),
        ("The Dream of a Common Language", "Adrienne Rich", "9780393044942", "Twenty-one love poems celebrating lesbian love, female creativity, and power."),
        ("A Wild Patience Has Taken Me This Far", "Adrienne Rich", "9780393300376", "Historical recovery of pioneer women and feminist activism."),
        ("An Atlas of the Difficult World", "Adrienne Rich", "9780393308310", "A long poem examining American landscape, inequality, and moral responsibility."),
        ("The Hawk in the Rain", "Ted Hughes", "9780571086207", "Raw, muscular poems celebrating animal vitality and elemental nature."),
        ("Lupercal", "Ted Hughes", "9780571086214", "Intense animal portraits including Pike, An Otter, and Hawk Roosting."),
        ("Wodwo", "Ted Hughes", "9780571086221", "Mythic stories and verse exploring wild wood spirits and consciousness."),
        ("Crow: From the Life and Songs of the Crow", "Ted Hughes", "9780571095902", "Dark cosmic trickster myths depicting Crow surviving creation and apocalypse."),
        ("Birthday Letters", "Ted Hughes", "9780374525811", "Moving, intimate poetic letters reflecting on Hughes' marriage to Sylvia Plath."),
        ("The Less Deceived", "Philip Larkin", "9780571086108", "Larkin's breakout collection featuring Church Going and Toads."),
        ("The Whitsun Weddings", "Philip Larkin", "9780571086115", "Witty, elegiac portraits of 1950s post-war British provincial life."),
        ("High Windows", "Philip Larkin", "9780571105526", "Larkin's final collection featuring This Be The Verse and Sad Steps."),
        ("Omeros", "Derek Walcott", "9780374523503", "An epic poem set in St. Lucia updating Homeric myths to Caribbean fishermen."),
        ("Another Life", "Derek Walcott", "9780837198704", "Autobiographical epic verse depicting artistic growth in St. Lucia."),
        ("White Egrets", "Derek Walcott", "9780374281083", "Elegies on mortality, Caribbean landscape, and aging artist's grace."),
        ("House of Light", "Mary Oliver", "9780060916886", "Pulitzer Prize-winning poems celebrating sun, wild roses, and quiet woods."),
        ("White Pine", "Mary Oliver", "9780140250008", "Poems on shorebirds, quiet pine groves, and solitary observation."),
        ("West Wind", "Mary Oliver", "9780140285000", "Prose poems and verse celebrating seasonal change and love."),
        ("What Do We Know", "Mary Oliver", "9780306812897", "Forty new poems exploring nature's daily mysteries."),
        ("Selected Poems", "W.S. Merwin", "9781556592614", "Zen-like minimalist poetry on ecology, silence, and memory."),
        ("The Rain in the Trees", "W.S. Merwin", "9780394758589", "Environmental elegies celebrating Hawaiian rain forests and native trees."),
        ("Migration: Selected Poems", "W.S. Merwin", "9781556592188", "National Book Award-winning comprehensive collection spanning fifty years.")
    ],

    "Classic Literature": [
        ("Anna Karenina", "Leo Tolstoy", "9780143035008", "The tragic affair between Anna Karenina and Count Vronsky contrasted with Levin's rural search for faith."),
        ("War and Peace", "Leo Tolstoy", "9780140447934", "Five aristocratic families navigate Napoleon's 1812 invasion of Russia."),
        ("The Death of Ivan Ilyich", "Leo Tolstoy", "9780140448016", "A high court judge faces terminal illness, realizing the vanity of his superficial life."),
        ("Resurrection", "Leo Tolstoy", "9780140449242", "Nobleman Nekhlyudov seeks moral redemption after causing a young woman's ruin."),
        ("The Cossacks", "Leo Tolstoy", "9780140449594", "Disillusioned aristocrat Olenin joins the army in the Caucasus and falls for Cossack life."),
        ("Hadji Murat", "Leo Tolstoy", "9780307951007", "A Chechen rebel commander forms an uneasy alliance with Russians against his own leader."),
        ("Crime and Punishment", "Fyodor Dostoevsky", "9780143107637", "Raskolnikov murders a pawnbroker to prove his extraordinary man theory, suffering psychological torment."),
        ("The Brothers Karamazov", "Fyodor Dostoevsky", "9780375761218", "Patricide, faith, free will, and morality clash among four brothers in a provincial town."),
        ("The Idiot", "Fyodor Dostoevsky", "9780375702419", "Prince Myshkin's innocent goodness is misunderstood as idiocy by corrupt St. Petersburg society."),
        ("Demons", "Fyodor Dostoevsky", "9780679734567", "A terrifying political satire on nihilist revolutionaries in 1860s Russia."),
        ("Notes from Underground", "Fyodor Dostoevsky", "9780140445275", "An embittered retired civil servant writes a rambling philosophical critique of rational self-interest."),
        ("The House of the Dead", "Fyodor Dostoevsky", "9780140444568", "A semi-autobiographical account of life and human dignity inside a Siberian prison camp."),
        ("The Cherry Orchard", "Anton Chekhov", "9780486266824", "An aristocratic Russian family loses their beloved estate and cherry orchard at auction."),
        ("Uncle Vanya", "Anton Chekhov", "9780486284958", "Vanya and Sonia labor on a rural estate while confronting wasted lives and unrequited love."),
        ("Three Sisters", "Anton Chekhov", "9780486275574", "Olga, Masha, and Irina yearn to return to Moscow while trapped in a dull garrison town."),
        ("The Seagull", "Anton Chekhov", "9780486298573", "Artistic rivalries, romantic obsession, and tragic ambition unfold at a country estate."),
        ("Ward No. 6", "Anton Chekhov", "9780140449044", "A hospital doctor converses with an intelligent mental patient until he is locked up himself."),
        ("The Lady with the Dog", "Anton Chekhov", "9780140449624", "Gurov and Anna fall into a deep, secret love affair starting during a Yalta holiday."),
        ("Madame Bovary", "Gustave Flaubert", "9780140449129", "Emma Bovary seeks escape from provincial marriage through romantic fantasies, affairs, and debt."),
        ("Sentimental Education", "Gustave Flaubert", "9780140442045", "Frédéric Moreau's romantic and political illusions during the 1848 French Revolution."),
        ("Salammbô", "Gustave Flaubert", "9780140443769", "A sensuous historical novel depicting the Mercenary Revolt against ancient Carthage."),
        ("Three Tales", "Gustave Flaubert", "9780140449273", "Three novellas showcasing Flaubert's mastery: A Simple Heart, Saint Julian, and Herodias."),
        ("Père Goriot", "Honoré de Balzac", "9780140449723", "An old father sacrifices everything for his ungrateful daughters in a Parisian boarding house."),
        ("Lost Illusions", "Honoré de Balzac", "9780140449419", "Provincial poet Lucien de Rubempré seeks fame in Paris journalism and corruption."),
        ("Cousin Bette", "Honoré de Balzac", "9780140444704", "Poor relation Bette plots revenge against her wealthy family using a courtesan."),
        ("Cousin Pons", "Honoré de Balzac", "9780140445138", "An eccentric art collector is preyed upon by greedy relatives on his deathbed."),
        ("Eugénie Grandet", "Honoré de Balzac", "9780140449556", "A miserly father sacrifices his daughter's romantic happiness for money."),
        ("Germinal", "Émile Zola", "9780140447422", "Etienne Lantier leads a desperate coal miners' strike in northern France."),
        ("L'Assommoir", "Émile Zola", "9780140446470", "Laundress Gervaise Macquart struggles against alcoholism and poverty in working-class Paris."),
        ("Nana", "Émile Zola", "9780140449693", "An actress becomes a high-class courtesan, ruining Parisian aristocrats and society."),
        ("La Bête Humaine", "Émile Zola", "9780140447835", "Murder, jealousy, and hereditary madness set against the French railway network."),
        ("The Ladies' Paradise", "Émile Zola", "9780140446838", "Denise Baudu comes to Paris and works in the city's first mega department store."),
        ("Therese Raquin", "Émile Zola", "9780140449280", "Therese and her lover Laurent murder her sickly husband, haunted by guilt.")
    ],

    "Non-Fiction": [
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "Environmental and geographical factors shaping human history and continental fortunes."),
        ("Collapse: How Societies Choose to Fail or Succeed", "Jared Diamond", "9780143117001", "Why past civilizations (Easter Island, Norse Greenland) collapsed due to eco-damage."),
        ("The Third Chimpanzee", "Jared Diamond", "9780060845506", "The evolution and future of the human animal sharing 98% DNA with chimps."),
        ("Upheaval: Turning Points for Nations in Crisis", "Jared Diamond", "9780316409131", "How nations recover from national crisis using personal coping mechanisms."),
        ("The World Until Yesterday", "Jared Diamond", "9780143124405", "What traditional tribal societies teach us about conflict resolution, elder care, and health."),
        ("The Blank Slate", "Steven Pinker", "9780142003343", "The modern denial of human nature and its psychological implications."),
        ("The Better Angels of Our Nature", "Steven Pinker", "9780143122012", "Why violence has declined historically across human history."),
        ("Enlightenment Now", "Steven Pinker", "9780143111382", "The case for reason, science, humanism, and progress."),
        ("How the Mind Works", "Steven Pinker", "9780393318487", "Reverse-engineering the human mind through cognitive science and evolutionary psychology."),
        ("The Language Instinct", "Steven Pinker", "9780060958336", "How language is a biological instinct hardwired into the human brain."),
        ("Rationality: What It Is, Why It Seems Scarce", "Steven Pinker", "9780593296707", "Logic, probability, critical thinking, and overcoming cognitive biases."),
        ("Sapiens: A Brief History of Humankind", "Yuval Noah Harari", "9780062316097", "How Cognitive, Agricultural, and Scientific Revolutions shaped Homo sapiens."),
        ("Homo Deus: A Brief History of Tomorrow", "Yuval Noah Harari", "9780062464316", "Exploring the future of humanity, AI, dataism, and biotechnology."),
        ("21 Lessons for the 21st Century", "Yuval Noah Harari", "9780525512172", "Tackling urgent global challenges like tech disruption, fake news, and nationalism."),
        ("Nexus: A Brief History of Information Networks", "Yuval Noah Harari", "9780593732380", "How information networks built human empire from stone tablets to AI."),
        ("The Tipping Point", "Malcolm Gladwell", "9780316346627", "How little things can make a big difference in viral trends and social ideas."),
        ("Blink: The Power of Thinking Without Thinking", "Malcolm Gladwell", "9780316010665", "Rapid cognition, thin-slicing, and intuitive decision making."),
        ("Outliers: The Story of Success", "Malcolm Gladwell", "9780316017930", "Why some people succeed based on culture, timing, 10,000 hours, and opportunity."),
        ("What the Dog Saw", "Malcolm Gladwell", "9780316075848", "A collection of Gladwell's best New Yorker essays on talent, dog trainers, and ketchup."),
        ("David and Goliath", "Malcolm Gladwell", "9780316213042", "Underdogs, misfits, and the art of battling giants."),
        ("Talking to Strangers", "Malcolm Gladwell", "9780316478526", "What we should know about the people we don't know."),
        ("The Bomber Mafia", "Malcolm Gladwell", "9780316296618", "Precision bombing dreams, WWII aviation pioneers, and firebombing Tokyo."),
        ("Fooled by Randomness", "Nassim Nicholas Taleb", "9780812975215", "The hidden role of chance in life and financial markets."),
        ("The Black Swan", "Nassim Nicholas Taleb", "9781400063512", "The impact of the highly improbable events in history and finance."),
        ("Antifragile: Things That Gain from Disorder", "Nassim Nicholas Taleb", "9781400067824", "Systems that benefit from stress, chaos, volatility, and uncertainty."),
        ("The Bed of Procrustes", "Nassim Nicholas Taleb", "9780812982404", "Philosophical and practical aphorisms on modern life and illusions."),
        ("Skin in the Game", "Nassim Nicholas Taleb", "9780425284629", "Hidden asymmetries in daily life and holding decision makers responsible."),
        ("Freakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060731335", "A rogue economist explores the hidden side of everything."),
        ("SuperFreakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060889579", "Global warming, altruistic prostitutes, and suicide bombers analyzed."),
        ("Think Like a Freak", "Steven D. Levitt & Stephen J. Dubner", "9780062218339", "How to think more productively, creatively, and rationally."),
        ("When to Rob a Bank", "Steven D. Levitt & Stephen J. Dubner", "9780062385321", "Selected blog posts on unconventional economics and life."),
        ("Factfulness", "Hans Rosling", "9781250107817", "Ten reasons we're wrong about the world and why things are better than you think."),
        ("Quiet: Introverts Power", "Susan Cain", "9780307352163", "Extensive work on personality types and quiet productivity.")
    ]
}

def escape_sql_str(val):
    return val.replace("'", "''")

def main():
    target_path = r"c:\pdd1\database\seed_books_batch_5.sql"
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    statements = []
    statements.append("-- PageMind Database Seed Script: Batch 5 of 10 (500 Books across 15 Genres)\n")
    statements.append("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
    statements.append("USE pagemind;\n\n")

    count = 0
    for genre, books in GENRE_DATA_BATCH_5.items():
        statements.append(f"-- =======================================================\n")
        statements.append(f"-- Genre: {genre} ({len(books)} books)\n")
        statements.append(f"-- =======================================================\n")
        
        for title, author, isbn, desc in books:
            count += 1
            e_title = escape_sql_str(title)
            e_author = escape_sql_str(author)
            e_genre = escape_sql_str(genre)
            e_desc = escape_sql_str(desc)
            
            if isbn:
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
            else:
                cover_url = f"https://via.placeholder.com/300x450/1e1b4b/a5b4fc?text={urllib.parse.quote(title)}"
            e_cover_url = escape_sql_str(cover_url)
            
            amazon_url = f"https://www.amazon.in/s?k={urllib.parse.quote(f'{title} {author}')}"
            flipkart_url = f"https://www.flipkart.com/search?q={urllib.parse.quote(f'{title} {author}')}"
            
            buy_links_dict = {
                "amazon": amazon_url,
                "flipkart": flipkart_url
            }
            buy_links_json = json.dumps(buy_links_dict)
            e_buy_links_json = escape_sql_str(buy_links_json)
            
            pub_year = get_published_year(title, author, genre, desc, isbn)

            
            rating = get_rating(title, author)

            
            sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{e_title}', '{e_author}', '{e_genre}', '{e_desc}', '{e_cover_url}', '{e_buy_links_json}', {pub_year}, {rating});\n"
            statements.append(sql)
            
        statements.append("\n")

    with open(target_path, "w", encoding="utf-8") as f:
        f.writelines(statements)

    print(f"Successfully generated {target_path} with {count} book insert statements across {len(GENRE_DATA_BATCH_5)} genres!")

if __name__ == "__main__":
    main()
