# generate_batch_10.py
# Generates seed_books_batch_10.sql containing 500 unique book insert statements across 15 genres

from book_metadata_utils import get_rating, get_published_year
import json
import os

genres_data = {
    "Fiction": [
        ("The Power and the Glory", "Graham Greene", "9780142437308", "A whiskey priest in 1930s anti-clerical Mexico is hunted by a ruthless police lieutenant."),
        ("The End of the Affair", "Graham Greene", "9780142437988", "Maurice Bendrix reflects on his intense wartime London affair with Sarah Miles and its spiritual turn."),
        ("The Quiet American", "Graham Greene", "9780143039549", "British journalist Thomas Fowler and idealist American CIA agent Alden Pyle clash in 1950s Vietnam."),
        ("Our Man in Havana", "Graham Greene", "9780140184938", "Vacuum cleaner salesman James Wormold invents fake MI6 spy reports in pre-Castro Cuba."),
        ("The Heart of the Matter", "Graham Greene", "9780142437995", "Police Officer Henry Scobie in WWII West Africa breaks his moral vows through pity and Catholic guilt."),
        ("Brighton Rock", "Graham Greene", "9780142437971", "Seventeen-year-old psychopathic mobster Pinkie Brown commits murder and marries naive witness Rose in Brighton."),
        ("The Comedians", "Graham Greene", "9780140184945", "Foreign visitors and hotelier Brown navigate terror under Papa Doc Duvalier's Tonton Macoutes in Haiti."),
        ("Travels with My Aunt", "Graham Greene", "9780140184990", "Retired bank manager Henry Pulling is swept into international smuggling by his seventy-five-year-old Aunt Augusta."),
        ("The Honorary Consul", "Graham Greene", "9780140184969", "Rogue Paraguayan revolutionaries kidnap elderly British consul Charley Fortnum by mistake in Argentina."),
        ("Monsignor Quixote", "Graham Greene", "9780140185003", "A Spanish parish priest and a communist former mayor travel across post-Franco Spain in a rickety Fiat."),
        ("Lord of the Flies", "William Golding", "9780399501487", "Schoolboys stranded on a deserted island degenerate into savage tribal ritual violence."),
        ("The Inheritors", "William Golding", "9780156443791", "A gentle Neanderthal tribe faces extinction at the hands of sophisticated Homo sapiens invaders."),
        ("Pincher Martin", "William Golding", "9780156718103", "A torpedoed WWII naval officer fights for survival on a barren North Atlantic rock peak."),
        ("Free Fall", "William Golding", "9780156334686", "Artist Sammy Mountjoy reflects on his free-will moral choices while held in a Nazi POW interrogation cell."),
        ("The Spire", "William Golding", "9780156847605", "Dean Jocelin becomes obsessed with constructing a magnificent 400-foot spire atop his cathedral without foundations."),
        ("Rites of Passage", "William Golding", "9780140119794", "Aristocratic Edmund Talbot keeps a journal during an 18th-century passenger voyage to Australia."),
        ("Close Quarters", "William Golding", "9780374521363", "Edmund Talbot's sailing ship collides with another vessel in Southern oceans while fighting naval decay."),
        ("Fire Down Below", "William Golding", "9780374521370", "The wooden warship reaches Australia as fires and structural collapse threaten passengers."),
        ("A Clockwork Orange", "Anthony Burgess", "9780393312836", "Violent youth Alex undergoes state-sponsored psychological aversion therapy in a dystopian Britain."),
        ("The Wanting Seed", "Anthony Burgess", "9780393318098", "Overpopulated future world enforces homosexuality, anti-family state laws, and eventual synthetic wars."),
        ("Earthly Powers", "Anthony Burgess", "9780099440819", "Octogenarian gay Catholic writer Kenneth Toomey reflects on 20th-century culture, evil, and his pope brother-in-law."),
        ("Enderby Outside", "Anthony Burgess", "9780393322194", "Eccentric poet Enderby flees to Morocco after being framed for an assassination at a London poetry reading."),
        ("Nothing Like the Sun", "Anthony Burgess", "9780393309379", "A fictionalized story of William Shakespeare's romantic life, dark lady, and creative genius."),
        ("MF", "Anthony Burgess", "9780393322187", "Young Miles Faber travels to Caribbean island Castita to study poet Sib Legeru, stumbling into incestuous traps."),
        ("The Sea, The Sea", "Iris Murdoch", "9780141186160", "Retired theater director Charles Arrowby moves to a seaside cottage, becoming obsessed with his childhood love."),
        ("Under the Net", "Iris Murdoch", "9780141186122", "Bohemian writer Jake Donaghue wanders London, chasing old philosopher friend Hugo Belfounder and lost loves."),
        ("The Bell", "Iris Murdoch", "9780141186139", "Dora Greenfield visits a lay religious community near an Anglican abbey where a medieval bell is dredged from a lake."),
        ("A Severed Head", "Iris Murdoch", "9780141186146", "Wine merchant Martin Lynch-Gibbon faces a farce of shifting extra-marital affairs and psychoanalytic power games."),
        ("The Black Prince", "Iris Murdoch", "9780141186153", "Elderly writer Bradley Pearson gets entangled with his rival Arnold Baffin's family, leading to murder accusations."),
        ("The Green Knight", "Iris Murdoch", "9780140232479", "Clement and Lucas attempt a bizarre ritual revenge following a mysterious assault in a dark London alley."),
        ("Jackson's Dilemma", "Iris Murdoch", "9780140259834", "An enigmatic manservant Jackson quietly repairs broken aristocratic romances and family misunderstandings."),
        ("The Good Apprentice", "Iris Murdoch", "9780140084702", "Edward Baltram copes with drug-induced guilt over a friend's death by visiting his eccentric artist father."),
        ("The Philosopher's Pupil", "Iris Murdoch", "9780140071373", "Former student George McCaffrey confronts grand philosopher John Robert Doyle upon his return to a spa town.")
    ],
    "Mystery": [
        ("Dead Cert", "Dick Francis", "9780393318715", "Jockey Alan York investigates a horse race fall that killed his friend Bill Davidson."),
        ("Nerve", "Dick Francis", "9780425208649", "Steeplechase jockey Rob Finn investigates why top riders are suddenly losing their nerve and reputation."),
        ("For Kicks", "Dick Francis", "9780425208656", "Australian horse breeder Daniel Roke goes undercover in English racing stables to uncover performance-enhancing drug plots."),
        ("Odds Against", "Dick Francis", "9780425208663", "Ex-jockey Sid Halley, disabled by a crushed hand, works as a private detective investigating racing syndicate land grabs."),
        ("Flying Finish", "Dick Francis", "9780425208670", "Amateur jockey Henry Grey takes a job transporting racehorses by cargo plane, discovering illegal air smuggling."),
        ("Blood Sport", "Dick Francis", "9780425208687", "British intelligence officer Gene Hawkins hunts stolen breeding stallions across North America."),
        ("Forfeit", "Dick Francis", "9780425208694", "Racing journalist James Tyrone uncovers a fraud ring taking bets on horses secretly pulled from races."),
        ("Enquiry", "Dick Francis", "9780425208700", "Jockey Kelly Hughes and trainer Dexter Caine fight a framed racing commission ban for throwing a race."),
        ("Rat Race", "Dick Francis", "9780425208717", "Air taxi pilot Matt Shore flies racegoers to meetings, surviving a bomb explosion in his plane."),
        ("Slayride", "Dick Francis", "9780425208724", "Investigator David Cleveland travels to Norway to find missing steeplechase race funds and a drowned treasurer."),
        ("Smokescreen", "Dick Francis", "9780425208731", "Actor Edward Lincoln travels to South Africa to investigate why a friend's racehorses are inexplicably failing to win."),
        ("Knockdown", "Dick Francis", "9780425208748", "Bloodstock agent Jonah Dereham uncovers violent fixed auctions and extortion in racehorse buying."),
        ("High Stakes", "Dick Francis", "9780425208755", "Wealthy inventor Steven Scott discovers his racehorse trainer is systematically defrauding him of prize horses."),
        ("In the Frame", "Dick Francis", "9780425208762", "Wine artist Charles Todd investigates a cousin's murdered wife and a fraud ring selling fake horse paintings."),
        ("Risk", "Dick Francis", "9780425208779", "Accountant jockey Roland Britten is kidnapped on the night of his Gold Cup victory."),
        ("Reflex", "Dick Francis", "9780425208786", "Jockey photographer Philip Nore decodes cipher photo negatives left behind by a deceased blackmailer."),
        ("Whip Hand", "Dick Francis", "9780425208793", "Sid Halley investigates a vaccine scam affecting racehorses and suspicious betting syndicates."),
        ("Banker", "Dick Francis", "9780425208809", "Merchant banker Tim Ekaterin finances a multi-million-pound breeding stallion whose offspring are born deformed."),
        ("Proof", "Dick Francis", "9780425208816", "Wine merchant Tony Beach investigates counterfeit scotch whisky and lethal hit-and-run horse truck crashes."),
        ("Break In", "Dick Francis", "9780425208823", "Steeplechase jockey Kit Fielding defends his estranged brother-in-law trainer from a smear campaign."),
        ("Bolt", "Dick Francis", "9780425208830", "Kit Fielding fights a French industrialist who threatens his employer's horses with a captive bolt gun."),
        ("Hot Money", "Dick Francis", "9780425208847", "Amateur jockey Malcolm Pembroke's multi-millionaire gold-trader father faces murder attempts by ex-wives."),
        ("The Edge", "Dick Francis", "9780425208854", "Undercover investigator Tor Kelsey boards a luxury Canadian transcontinental murder-mystery train carrying real killers."),
        ("Straight", "Dick Francis", "9780425208861", "Jockey Derek Franklin inherits his brother's gemstone business and racehorse, facing jewel thieves."),
        ("Longshot", "Dick Francis", "9780425208878", "Survival guide author John Kendall writes a biography of a horse trainer, witnessing arson and murder."),
        ("Comeback", "Dick Francis", "9780425208885", "Diplomat Peter Darwin returns to his childhood English village, protecting a veterinary surgeon friend from sabotage."),
        ("Driving Force", "Dick Francis", "9780425208892", "Ex-jockey Freddie Croft manages a horse transport fleet whose driver picks up a hitchhiker found dead."),
        ("Decider", "Dick Francis", "9780425208908", "Architect Lee Morris inherits shares in a ruined racecourse torn apart by family board disputes and bombings."),
        ("Wild Horses", "Dick Francis", "9780425208915", "Film director Thomas Lyon shoots a movie about an unsolved 26-year-old death in Newmarket."),
        ("Come to Grief", "Dick Francis", "9780425208922", "Sid Halley discovers his trusted close friend is mutilating young horses for psychological thrills."),
        ("To the Hilt", "Dick Francis", "9780425208939", "Artist Alexander Kinloch lives in Scottish mountains, defending his family's brewery and historical gold sword."),
        ("10 lb Penalty", "Dick Francis", "9780425208946", "Ben Juliard assists his parliamentary candidate father while riding steeplechases, surviving political hit attempts."),
        ("Second Wind", "Dick Francis", "9780425208953", "TV meteorologist Perry Stuart flies into a category 5 hurricane, uncovering a remote Caribbean island secret.")
    ],
    "Thriller": [
        ("The Kill Artist", "Daniel Silva", "9780451209336", "Restorer and Mossad assassin Gabriel Allon is pulled out of retirement to hunt Palestinian terrorist Tariq."),
        ("The English Assassin", "Daniel Silva", "9780451209343", "Gabriel Allon arrives in Zurich to restore a painting, discovering a Swiss banker murdered and Nazi looted art theft."),
        ("The Confessor", "Daniel Silva", "9780451213074", "Allon investigates the murder of a scholar in Munich, uncovering Catholic Church secret WWII archives."),
        ("A Death in Vienna", "Daniel Silva", "9780451213197", "Allon investigates a bomb blast at an Austrian Holocaust center, confronting SS camp commander Radek."),
        ("Prince of Fire", "Daniel Silva", "9780451215733", "Allon is targeted by a terror bomb in Rome, leading a Mossad team against terrorist mastermind Zev Saad."),
        ("The Messenger", "Daniel Silva", "9780451219953", "Allon uncovers an Al-Qaeda plot against the Vatican, sending art restorer Sarah Bancroft undercover."),
        ("The Secret Servant", "Daniel Silva", "9780451224057", "Allon investigates an ambassador's daughter kidnapped in London by Islamic extremists."),
        ("Moscow Rules", "Daniel Silva", "9780451227386", "Allon travels to Russia to stop arms dealer Ivan Kharkov from selling shoulder-fired missiles."),
        ("The Defector", "Daniel Silva", "9780451230751", "Allon rescues Russian defector Grigori in London while fighting billionaire arms oligarch Kharkov."),
        ("The Rembrandt Affair", "Daniel Silva", "9780451233967", "Allon investigates a stolen Rembrandt portrait in England and a Swiss pharmaceutical company smuggling yellowcake."),
        ("Fallen Angel", "Daniel Silva", "9780451238948", "Allon assists Vatican police with a woman found dead beneath St. Peter's Basilica dome."),
        ("The English Girl", "Daniel Silva", "9780062073167", "Allon rescues kidnapped British political rising star Madeline Hart in Corsica."),
        ("The Heist", "Daniel Silva", "9780062073198", "Allon hunts a stolen Caravaggio masterpiece used by Syrian dictator Assad to hide stolen state funds."),
        ("The English Spy", "Daniel Silva", "9780062320131", "Allon hunts IRA bomb maker Eamon Vance who assassinated a British royal family member."),
        ("The Black Widow", "Daniel Silva", "9780062405982", "Allon sends doctor Natalie Mizrahi undercover into ISIS to hunt terrorist mastermind Saladin."),
        ("House of Spies", "Daniel Silva", "9780062406019", "Allon tracks Saladin to Southern France following terror attacks in London and Washington."),
        ("The Other Woman", "Daniel Silva", "9780062834829", "Allon uncovers a high-level Russian mole inside British MI6 operating since the Cold War."),
        ("The New Girl", "Daniel Silva", "9780062834850", "Allon rescues the kidnapped daughter of Saudi Arabia's crown prince."),
        ("The Order", "Daniel Silva", "9780062834881", "Allon investigates Pope Paul VII's sudden death in the Vatican, uncovering a lost gospel."),
        ("The Cellist", "Daniel Silva", "9780062834911", "Allon uses a concert cellist to dismantle a Russian money-laundering network in Zurich."),
        ("Portrait of an Unknown Woman", "Daniel Silva", "9780062834942", "Allon retires to Venice, uncovering a forgery ring manipulating the international art market."),
        ("The Collector", "Daniel Silva", "9780063211100", "Allon teams up with an art thief to recover a stolen Vermeer and stop a Russian nuclear plot."),
        ("A Death in Cornwall", "Daniel Silva", "9780063211131", "Allon investigates an art historian's murder in Cornwall connected to a stolen Picasso."),
        ("The Spy Who Came in from the Cold", "John le Carré", "9780143124931", "British agent Alec Leamas accepts one last dangerous mission in Cold War East Berlin."),
        ("Tinker Tailor Soldier Spy", "John le Carré", "9780143119784", "George Smiley comes out of retirement to hunt a Soviet mole at the top of Circus MI6."),
        ("The Honourable Schoolboy", "John le Carré", "9780143119739", "Smiley sends journalist Jerry Westerby to Hong Kong to rebuild circus intelligence networks."),
        ("Smiley's People", "John le Carré", "9780143119760", "George Smiley conducts a final chess match against Soviet KGB spymaster Karla."),
        ("The Little Drummer Girl", "John le Carré", "9780143119746", "English actress Charlie is recruited by Israeli intelligence to infiltrate a Palestinian terror cell."),
        ("A Perfect Spy", "John le Carré", "9780143119753", "Magnus Pym vanishes after his father's funeral, revealing his double life as a lifelong spy."),
        ("The Russia House", "John le Carré", "9780143119777", "British publisher Barley Blair receives Soviet nuclear defense flaw manuscripts from Katya."),
        ("The Tailor of Panama", "John le Carré", "9780143119791", "Ex-con British tailor Harry Pendel fabricates fake Panamanian revolution intel for MI6."),
        ("The Constant Gardener", "John le Carré", "9780143119722", "Diplomat Justin Quayle investigates his activist wife Tessa's murder in Kenya, uncovering Big Pharma trials."),
        ("Absolute Friends", "John le Carré", "9780143119715", "Ted Mundy and Sasha meet as 1968 Berlin student radicals, reuniting years later in a fatal anti-war plot.")
    ],
    "Romance": [
        ("The Velvet Promise", "Jude Deveraux", "9780671738723", "Gavin Montgomery marries Judith Revedon for family duty, but her fierce spirit wins his heart."),
        ("Highland Velvet", "Jude Deveraux", "9780671738730", "Scottish laird Stephen Montgomery captures clan enemy Judith Revedon, discovering passionate love."),
        ("Velvet Song", "Jude Deveraux", "9780671738747", "Alyx Blackett disguises herself as a male lute player, entering Rylan Montgomery's outlaw band."),
        ("Velvet Angel", "Jude Deveraux", "9780671738754", "Elizabeth Chatworth is kidnapped by Miles Montgomery to avenge clan feuds, leading to romance."),
        ("Sweetbriar", "Jude Deveraux", "9780671707378", "Linnet escapes an arranged marriage in 1784, finding protection with mountain scout Devin Macalister."),
        ("Counterfeit Lady", "Jude Deveraux", "9780671707385", "Nicole inherits a Virginia plantation, clashing with rugged neighbor Clayton Ring."),
        ("Lost Lady", "Jude Deveraux", "9780671707392", "Regan van Alen flees an unwanted suitor in 1792, finding refuge with horse breeder Travis Stanford."),
        ("River Lady", "Jude Deveraux", "9780671707408", "Cory Sanders marries wealthy Rafe Halloran, fighting class prejudice along the Virginia river."),
        ("Twin of Ice", "Jude Deveraux", "9780671739713", "Proper Houston Chandler falls for rough miner Kane Taggert in 1892 Colorado."),
        ("Twin of Fire", "Jude Deveraux", "9780671739720", "Outspoken doctor Blair Chandler falls for rival doctor Houston in Chandler, Colorado."),
        ("The Maiden", "Jude Deveraux", "9780671743840", "Princess Jura of Lanconia marries masked warrior Prince Rowan in medieval Europe."),
        ("The Temptress", "Jude Deveraux", "9780671743857", "Christiana flees across 18th-century Europe with handsome highwayman Haydon."),
        ("The Raider", "Jude Deveraux", "9780671743864", "Jessica Taggert falls for masked colonial vigilante Raider, unaware he is mild Alexander."),
        ("The Princess", "Jude Deveraux", "9780671743871", "World War II officer J.T. Montgomery rescues European Princess Aria, falling in love on a remote island."),
        ("The Awakening", "Jude Deveraux", "9780671743888", "Amanda Caulden falls for union organizer Hank Montgomery in 1913 garment mill strikes."),
        ("The Enchanted Land", "Jude Deveraux", "9780671707361", "Heidi inherits a New Mexico ranch, fighting land grabbers beside handsome Morgan Revedon."),
        ("The Duchess", "Jude Deveraux", "9780671743895", "American heiress Trevlyn marries Scottish Duke Claire, transforming his ruined castle."),
        ("Mountain Laurel", "Jude Deveraux", "9780671743901", "Captain Ring Montgomery protects opera singer Laurel Kincaid during 1859 pioneer travels."),
        ("A Knight in Shining Armor", "Jude Deveraux", "9780671705091", "Abandoned tourist Dougless Montgomery accidently summons 1564 knight Nicholas Stafford to modern England."),
        ("Wishing Well", "Jude Deveraux", "9780671743918", "Jace Montgomery buys a historic house, discovering a time-travel Wishing Well and local romance."),
        ("Remembrance", "Jude Deveraux", "9780671743925", "Romance writer Hayden Lane discovers past-life memories of Edwardian English beauty Lady de Warenne."),
        ("Eternity", "Jude Deveraux", "9780671743932", "Carrie Montgomery posts a mail-order bride ad in 1865, traveling to Colorado to marry Josh Greene."),
        ("Sweet Liar", "Jude Deveraux", "9780671743949", "Samantha Elliot and Michael Taggert investigate a 1920s murder in a NYC brownstone."),
        ("The Heiress", "Jude Deveraux", "9780671743956", "Rich heiress Axia marries knight Jamie Montgomery, traveling across 16th-century England."),
        ("Legend", "Jude Deveraux", "9780671743963", "Kalli enters a virtual reality simulation game, falling for high-tech warrior Cole."),
        ("An Angel for Emily", "Jude Deveraux", "9780671743970", "Guardian angel Michael is sent to Earth to save Emily Jane Todd from fatal accidents."),
        ("High Tide", "Jude Deveraux", "9780671014193", "Fiona travels to Florida keys, getting swept into murder mysteries with Roy Taggert."),
        ("Carolina Isle", "Jude Deveraux", "9780671014209", "Sara and cousin Kim swap identities on a North Carolina island vacation."),
        ("First Impressions", "Jude Deveraux", "9780743237147", "Eden Palmer moves to a small North Carolina town, deciding between two handsome suitors."),
        ("Always", "Jude Deveraux", "9780743237178", "Darci Montgomery uses her psychic abilities to find her missing husband Adam."),
        ("Wild Orchids", "Jude Deveraux", "9780743237208", "Ford Montgomery falls for quiet novelist Dr. Jilly Taggert in a haunted house."),
        ("Met Before", "Jude Deveraux", "9781416509745", "Alix Madsen inherits a Nantucket cottage, uncovering family ghost secrets with Jared Montgomery."),
        ("Summerhouse", "Jude Deveraux", "9780743437189", "Three women meet at a Maine summerhouse, receiving a chance from a magic man to relive a past year.")
    ],
    "Fantasy": [
        ("The Shadow of the Torturer", "Gene Wolfe", "9780312890179", "Apprentice torturer Severian is exiled from the Guild for showing mercy, embarking on a journey across Urth."),
        ("The Claw of the Conciliator", "Gene Wolfe", "9780312890186", "Severian possesses a miraculous glowing gem while traveling to his post as executioner in Thrax."),
        ("The Sword of the Lictor", "Gene Wolfe", "9780312890193", "Severian rules as Lictor of Thrax, but flees into the mountains after refusing to execute a woman."),
        ("The Citadel of the Autarch", "Gene Wolfe", "9780312890209", "Severian fights in the northern war against Ascians, fulfilling his destiny to become Autarch of Urth."),
        ("The Urth of the New Sun", "Gene Wolfe", "9780312890056", "Autarch Severian travels across time and space aboard a cosmic ship to bring a New Sun to dying Urth."),
        ("Nightside Long Sun", "Gene Wolfe", "9780312854940", "Patera Silk, a poor priest in the generation starship Whorl, receives a divine vision from the god Pas."),
        ("Lake of the Long Sun", "Gene Wolfe", "9780312855671", "Patera Silk navigates gang wars and corrupt rulers to save his neighborhood manteion sanctuary."),
        ("Caldé of the Long Sun", "Gene Wolfe", "9780312855688", "Patera Silk becomes the political Caldé of Viron during a revolution aboard the Whorl starship."),
        ("Exodus From the Long Sun", "Gene Wolfe", "9780312855695", "Silk leads the citizens of Viron onto lander ships to settle the new planet Blue."),
        ("On Blue's Waters", "Gene Wolfe", "9780312872359", "Horn travels across the ocean planet Blue seeking Patera Silk to lead their struggling colony."),
        ("In Green's Jungles", "Gene Wolfe", "9780312872366", "Horn fights alien inhumi parasites in the jungle planet Green while recalling his journey."),
        ("Return to the Whorl", "Gene Wolfe", "9780312872373", "Horn completes his spiritual quest between Blue, Green, and the ancient starship Whorl."),
        ("The Knight", "Gene Wolfe", "9780765309907", "Teenager Sir Able is transported to the seven-tiered Nordic myth world of Mythgarthr as a knight."),
        ("The Wizard", "Gene Wolfe", "9780765309914", "Sir Able wields the magical sword Ethereal, fighting frost giants and dragons to save Mythgarthr."),
        ("Soldier of the Mist", "Gene Wolfe", "9780312863418", "Latro suffers amnesia during Persian Wars, writing daily scroll notes while seeing gods and spirits."),
        ("Soldier of Arete", "Gene Wolfe", "9780312863425", "Latro travels to Sparta and Delphi, seeking a cure for his memory loss from the Greek gods."),
        ("Soldier of Sidon", "Gene Wolfe", "9780765316646", "Latro travels up the Nile River into ancient Egypt, encountering pharaonic magic and spirits."),
        ("Peace", "Gene Wolfe", "9780312858016", "Alden Dennis Weer narrates his quiet life and haunting memories in a small Midwestern town."),
        ("The Fifth Head of Cerberus", "Gene Wolfe", "9780312865207", "Three novella puzzle stories exploring human clones and extinct shapeshifting aliens on Sainte Croix."),
        ("There Are Doors", "Gene Wolfe", "9780312865214", "Mr. Green travels through alternate dimension doors to find a woman who is a goddess."),
        ("Free Live Free", "Gene Wolfe", "9780312865221", "Four eccentrics search a condemned rooming house for mysterious inventor Free's lost box."),
        ("The Sorcerer's House", "Gene Wolfe", "9780765324580", "Ex-con Bax inherits a strange mansion in Black Mountains, writing letters about ghosts and fae."),
        ("Home Fires", "Gene Wolfe", "9780765327376", "Skip's wife Chelle returns from space war via lightspeed travel, un-aged while he has grown old."),
        ("The Land Across", "Gene Wolfe", "9780765335616", "Travel writer Grafton is trapped in a mysterious Balkan nation ruled by secret police and occult forces."),
        ("A Borrowed Man", "Gene Wolfe", "9780765381835", "Re-animated clone author Ern A. Smith is borrowed from a library to solve a murder mystery."),
        ("Interlibrary Loan", "Gene Wolfe", "9781250238719", "Clone author Ern Smith is loaned to a remote island community where multi-generational secrets fester."),
        ("Pirate Freedom", "Gene Wolfe", "9780765318350", "A modern novice priest is time-transported to become a 18th-century pirate captain in the Caribbean."),
        ("An Evil Guest", "Gene Wolfe", "9780765321305", "Actress Cassie Casey deals with Lovecraftian cosmic entities and billionaire private space moguls."),
        ("Operation Ares", "Gene Wolfe", "9780425019023", "Wolfe's debut novel: John Carter fights a technophobic anti-science US regime after Mars colony return."),
        ("The Devil in a Forest", "Gene Wolfe", "9780812530187", "Young Mark lives in a medieval village, torn between forest outlaw Wat and an honest shrine keeper."),
        ("Castleview", "Gene Wolfe", "9780812500059", "Arthurian ghost castles manifest in modern Illinois, drawing local residents into mythic battles."),
        ("Pandora by Holly Hollander", "Gene Wolfe", "9780312850197", "Holly Hollander solves a locked-box murder mystery in a small Illinois suburb."),
        ("The Best of Gene Wolfe", "Gene Wolfe", "9780765321367", "Definitive short story collection including 'The Death of Doctor Island' and 'The Island of Doctor Death'.")
    ],
    "Science Fiction": [
        ("The Dying Earth", "Jack Vance", "9780312874568", "Tales of sorcery, science, and strange civilizations under a dim red dying sun."),
        ("The Eyes of the Overworld", "Jack Vance", "9780312874575", "The rogue Cugel the Clever is sent across Urwile by Iucounu the Laughing Magician to retrieve a lens."),
        ("Cugel's Saga", "Jack Vance", "9780312874582", "Cugel journeys back across the Dying Earth, using trickery and wits against monsters and wizards."),
        ("Rhialto the Marvellous", "Jack Vance", "9780312874599", "Arch-mage Rhialto defends his reputation against rival sorcerers using IOUN stones."),
        ("The Dragon Masters", "Jack Vance", "9780312874605", "Humans and alien Basic creatures fight on Aerlith, using genetically modified versions of each other as war beasts."),
        ("The Last Castle", "Jack Vance", "9780312874612", "Aristocratic humans living in automated castles on Earth face a revolt by their alien Mek slaves."),
        ("Big Planet", "Jack Vance", "9780312874629", "A crash-landed survey team must trek 40,000 miles across a giant metal-poor planet."),
        ("The Languages of Pao", "Jack Vance", "9780312874636", "Lord Beran uses engineered new languages to transform passive Pao citizens into warriors and scientists."),
        ("To Live Forever", "Jack Vance", "9780312874643", "Gavin Waylock fights the immortality registry system in Clarges city to regain high rank."),
        ("Slaves of the Klau", "Jack Vance", "9780312874650", "Earthman Roy Barch is enslaved on planet Magar by alien Klau, plotting a prison break."),
        ("Vandals of the Void", "Jack Vance", "9780312874667", "Teenager Dick Murdock travels to Moon Observatory, uncovering space pirate sabotage."),
        ("The Houses of Iszm", "Jack Vance", "9780312874674", "Iszm grows living botanical houses, guarding its monopoly against botanist Jack Garvie."),
        ("Son of the Tree", "Jack Vance", "9780312874681", "Joe Smith visits planet Kyril, fighting a druidic cult worshipping a giant blood-drinking tree."),
        ("The Blue World", "Jack Vance", "9780312874698", "Descendants of crash-landed prison ship humans live on giant floating lily-pads, fighting giant sea worms."),
        ("Emphyrio", "Jack Vance", "9780312874704", "Woodcarver Ghyl Tarvoke rebels against alien Lords of Halma who suppress human art and automation."),
        ("The Anome", "Jack Vance", "9780312874711", "In Shantivun, citizens wear explosive explosive neck rings controlled by the anonymous dictator Anome."),
        ("The Brave Free Men", "Jack Vance", "9780312874728", "Darnley hunts the faceless Anome while alien Roguskhoi invade the provinces."),
        ("The Asutra", "Jack Vance", "9780312874735", "Darnley travels off-world to locate the origin of parasitic alien Asutra controlling human minds."),
        ("Showboat World", "Jack Vance", "9780312874742", "Rival showboat captains Apollon and Zime race down the giant Vism river presenting theatrical plays."),
        ("Maske: Thaery", "Jack Vance", "9780312874759", "Outcast Jubal Dunsany uncovers corruption and high-tech intrigue among Maske ruling castes."),
        ("Wyst: Alastor 666", "Jack Vance", "9780312874766", "Artist Jathan visits egalitarian utopia planet Wyst, uncovering a dark coup plot."),
        ("Trullion: Alastor 2262", "Jack Vance", "9780312874773", "Gethin returns from space navy service to water-world Trullion, playing hussade and hunting pirates."),
        ("Marune: Alastor 933", "Jack Vance", "9780312874780", "An amnesiac man travels to four-sun planet Marune to reclaim his identity as a regional chieftain."),
        ("City of the Chasch", "Jack Vance", "9780312874797", "Scout Adam Reith crash-lands on planet Tschai, fighting alien Chasch and human sub-species."),
        ("Servants of the Wankh", "Jack Vance", "9780312874803", "Adam Reith captures a Wankh spaceship, navigating black-skinned Wankh alien intrigue."),
        ("The Dirdir", "Jack Vance", "9780312874810", "Adam Reith hunts hunting-grounds for glass gems to pay for spaceship repairs on Tschai."),
        ("The Pnume", "Jack Vance", "9780312874827", "Adam Reith is captured by subterranean alien Pnume who record Tschai history."),
        ("Araminta Station", "Jack Vance", "9780312874834", "Gavin Waylock's descendant Glawen Clattuc investigates murders in Cadwal planet preserve."),
        ("Ecce and Old Earth", "Jack Vance", "9780312874841", "Glawen Clattuc searches Old Earth historical archives to save Cadwal from development."),
        ("Throy", "Jack Vance", "9780312874858", "Final confrontation on Cadwal between conservationists and corrupt development charter baronies."),
        ("Night Lamp", "Jack Vance", "9780312874865", "Jarrow uncovers his forgotten childhood identity in the Froy system."),
        ("Lurulu", "Jack Vance", "9780312874872", "Myron Tany travels across Gaian Reach worlds aboard cargo tramp freighter Areamur."),
        ("Ports of Call", "Jack Vance", "9780312874889", "Myron Tany joins eccentric aunt Madoc on a luxury tour of exotic outer worlds.")
    ],
    "Horror": [
        ("Songs of a Dead Dreamer", "Thomas Ligotti", "9780982429693", "Philosophical weird horror short stories examining puppet themes and existential dread."),
        ("Grimscribe: His Lives and Works", "Thomas Ligotti", "9780982429709", "Tales of decaying industrial towns, strange cults, and sinister voice transmissions."),
        ("Noctuary", "Thomas Ligotti", "9780982429716", "Short horror fiction divided into Studies in Shadow and Discourse on Blackness."),
        ("The Nightmare Factory", "Thomas Ligotti", "9780451456182", "Comprehensive collection of Ligotti's nightmare prose and corporate surrealist terror."),
        ("My Work Is Not Yet Done", "Thomas Ligotti", "9780061582912", "Corporate middle manager Frank Dominio gets revenge on company executives with supernatural shadows."),
        ("Teatro Grottesco", "Thomas Ligotti", "9780982429723", "Stories of artistic madness, mysterious theater troupes, and surreal corporate disease."),
        ("The Conspiracy Against the Human Race", "Thomas Ligotti", "9780143133148", "Ligotti's non-fiction philosophical treatise arguing consciousness is a tragic evolutionary misstep."),
        ("Necroscope", "Brian Lumley", "9780812521374", "Harry Keogh can communicate with the dead, using their knowledge to fight Soviet psychic spies and vampires."),
        ("Wamphyri!", "Brian Lumley", "9780812521381", "Harry Keogh travels to alien vampire world Starside to fight the Wamphyri blood-lords."),
        ("The Source", "Brian Lumley", "9780812521398", "Soviet industrial diggers accidentally breach an ancient vampire tomb in the Urals."),
        ("Deadspeak", "Brian Lumley", "9780812521404", "Vampire lord Radu Lykan awakens on Starside while Harry Keogh's dead allies fight back."),
        ("Deadspawn", "Brian Lumley", "9780812521411", "Harry Keogh faces a nightmare parasite entity threatening Earth and Starside."),
        ("Blood Brothers", "Brian Lumley", "9780812530194", "Harry Keogh's twin sons Nathan and Nestor grow up on Starside with opposing human and vampire destinies."),
        ("The Last Aircraft", "Brian Lumley", "9780812530200", "Nathan Keogh defends human tribes against Wamphyri airships."),
        ("Bloodwars", "Brian Lumley", "9780812530217", "Final battle on Starside between Nathan Keogh's alliance and resurrected Wamphyri lords."),
        ("Fruiting Bodies and Other Fungi", "Brian Lumley", "9780812530224", "Collection of British fungus horror stories and sea coast weird fiction."),
        ("The House of Doors", "Brian Lumley", "9780812530231", "A group of disparate humans are trapped inside an alien maze house with doors to death worlds."),
        ("Maze of Worlds", "Brian Lumley", "9780812530248", "Surviving humans navigate outer-space dimensions to stop the alien machine entity."),
        ("The House of Cthulhu", "Brian Lumley", "9780765310744", "Sword and sorcery Cthulhu Mythos tales set in ancient continent Theem'hdra."),
        ("Tarra Khash: Hater of Men", "Brian Lumley", "9780765310751", "Barbarian warrior Tarra Khash fights eldritch monsters and sorcerers in Theem'hdra."),
        ("Sorqueror of Irem", "Brian Lumley", "9780765310768", "Tales of desert sorcery and eldritch horrors in the City of Pillars."),
        ("Titus Crow", "Brian Lumley", "9780812530255", "Titus Crow investigates Cthulhu Mythos cults with psychic companion Henri Laurent de Marigny."),
        ("The Burrowers Beneath", "Brian Lumley", "9780812530262", "Titus Crow battles giant subterranean squid creatures (Chthonians) causing earthquakes."),
        ("The Transition of Titus Crow", "Brian Lumley", "9780812530279", "Titus Crow travels through time and space in a clock-shaped vessel to escape Cthulhu."),
        ("The Clock of Dreams", "Brian Lumley", "9780812530286", "de Marigny enters the Dreamlands to rescue Titus Crow from cosmic sleep."),
        ("Spawn of the Winds", "Brian Lumley", "9780812530293", "Hank Stillwater encounters air elemental god Ithaqua in the frozen Canadian arctic."),
        ("In the Moons of Borea", "Brian Lumley", "9780812530309", "Titus Crow travels to icy moon Borea to fight Ithaqua's ice worshippers."),
        ("Elysia: Coming of Cthulhu", "Brian Lumley", "9780812530316", "Elder Gods and Titus Crow battle Great Old Ones in a final cosmic confrontation."),
        ("Psychomech", "Brian Lumley", "9780812530323", "Richard Garrison builds a bio-feedback machine granting him psychic energy powers."),
        ("Psychosphere", "Brian Lumley", "9780812530330", "Garrison uses his psychic machine to fight corporate enemies and dimension entities."),
        ("Psychamok", "Brian Lumley", "9780812530347", "Garrison's psychically powered child fights insane machine powers."),
        ("Demogorgon", "Brian Lumley", "9780812530354", "A ancient shape-shifting demon hunts victims in modern London."),
        ("Beneath the Moors", "Brian Lumley", "9780812530361", "Archaeologists discover a buried Cthulhu Mythos city beneath Yorkshire moors.")
    ],
    "Self-Help": [
        ("The 7 Habits of Highly Effective People", "Stephen R. Covey", "9780743269513", "Principle-centered paradigm shifts for personal and professional effectiveness."),
        ("First Things First", "Stephen R. Covey", "9780684802039", "Time management framework prioritizing urgency versus importance."),
        ("Principle-Centered Leadership", "Stephen R. Covey", "9780671792800", "Building organizational trust and effectiveness through core moral principles."),
        ("The 8th Habit", "Stephen R. Covey", "9780743287937", "From effectiveness to greatness: finding your voice and inspiring others to find theirs."),
        ("The Speed of Trust", "Stephen M.R. Covey", "9781416528852", "How trust acts as a measurable performance multiplier in business and relationships."),
        ("The Leader in Me", "Stephen R. Covey", "9781439103265", "How schools and parents around the world are inspiring greatness in children."),
        ("3rd Alternative", "Stephen R. Covey", "9781451626261", "Solving life's most difficult problems through synergy and creative win-win solutions."),
        ("Think and Grow Rich", "Napoleon Hill", "9781585424337", "The classic 1937 guide to wealth creation based on interviews with 500 successful figures."),
        ("The Law of Success", "Napoleon Hill", "9781585440801", "The original 16-lesson master course on personal achievement and self-discipline."),
        ("Outwitting the Devil", "Napoleon Hill", "9781454900672", "Hill's suppressed 1938 manuscript on breaking free from fear, procrastination, and conformity."),
        ("Master-Key to Riches", "Napoleon Hill", "9780448119182", "Unlocking the mental principles behind Andrew Carnegie's business success."),
        ("How to Sell Your Way Through Life", "Napoleon Hill", "9780470446867", "Applying persuasion, self-confidence, and salesmanship to personal career goals."),
        ("Success Through a Positive Mental Attitude", "Napoleon Hill & W. Clement Stone", "9780671743222", "How PMA unlocks energy, health, and commercial success."),
        ("Psycho-Cybernetics", "Maxwell Maltz", "9780399176135", "Using self-image psychology and visualization to reprogram your subconscious mind."),
        ("The Power of Positive Thinking", "Norman Vincent Peale", "9780743234801", "Faith-based practical techniques to eliminate defeatist attitudes and build peace of mind."),
        ("A Guide to Confident Living", "Norman Vincent Peale", "9780449911920", "Overcoming fear, anxiety, and self-doubt through spiritual optimism."),
        ("Enthusiasm Makes the Difference", "Norman Vincent Peale", "9780449911937", "How enthusiasm transforms routine work and overcomes life obstacles."),
        ("You Can If You Think You Can", "Norman Vincent Peale", "9780449911944", "Developing tenacity, faith, and problem-solving focus in stressful times."),
        ("The Tough-Minded Optimist", "Norman Vincent Peale", "9780449911951", "Combining practical realism with resilient optimism in personal hardship."),
        ("See You at the Top", "Zig Ziglar", "9780882891262", "The classic guide to self-image, attitude, goals, relationships, and faith."),
        ("Secrets of Closing the Sale", "Zig Ziglar", "9780800759759", "Persuasion principles, communication techniques, and ethical closing strategies."),
        ("Over the Top", "Zig Ziglar", "9780849914713", "Moving from mid-level success to ultimate performance excellence."),
        ("Born to Win", "Zig Ziglar", "9781612680347", "Ziglar's final comprehensive guide to planning, preparing, and expecting to win."),
        ("Eat That Frog!", "Brian Tracy", "9781626569416", "21 great ways to stop procrastinating and get more done in less time."),
        ("No Excuses!", "Brian Tracy", "9781599951683", "The power of self-discipline in personal success, career, and financial goals."),
        ("Goals!", "Brian Tracy", "9781605094113", "How to get everything you want faster than you ever thought possible."),
        ("Psychology of Selling", "Brian Tracy", "9780785288060", "Increase your sales, income, and business performance using proven psychological tactics."),
        ("Maximum Achievement", "Brian Tracy", "9780671865184", "Strategies and skills that will unlock your hidden powers to succeed."),
        ("The Power of Self-Confidence", "Brian Tracy", "9780470439692", "Become unstoppable, irresistible, and unafraid in every area of your life."),
        ("Master Your Time Master Your Life", "Brian Tracy", "9780399183812", "The breakthrough system to get more done in less time."),
        ("Advanced Selling Strategies", "Brian Tracy", "9780684824741", "Proven insights to sell more, faster, and easier in difficult markets."),
        ("Flight Plan", "Brian Tracy", "9781576754979", "How to achieve real success in any area of your life using aviation navigation principles."),
        ("Earn What You're Really Worth", "Brian Tracy", "9781599951669", "Strategies to double and triple your income in any economy.")
    ],
    "Biography": [
        ("Eminent Victorians", "Lytton Strachey", "9780140183504", "Iconoclastic biographies of Cardinal Manning, Florence Nightingale, Thomas Arnold, and General Gordon."),
        ("Queen Victoria", "Lytton Strachey", "9780141393520", "The human portrait of Queen Victoria from youthful coronation to grand matriarch."),
        ("Elizabeth and Essex", "Lytton Strachey", "9780141393537", "The tragic romantic power struggle between Queen Elizabeth I and the Earl of Essex."),
        ("Marie Antoinette", "Stefan Zweig", "9781590174586", "The portrait of an average woman thrown into French revolutionary tragedy."),
        ("Erasmus of Rotterdam", "Stefan Zweig", "9781590179925", "The life of the great humanist scholar caught between religious reformation zealots."),
        ("Mary Queen of Scotland", "Stefan Zweig", "9781590173169", "The dramatic biography of Mary Stuart's downfall, lovers, and execution by Elizabeth I."),
        ("Magellan", "Stefan Zweig", "9781590176375", "The pioneer of the Pacific: Ferdinand Magellan's historic first circumnavigation voyage."),
        ("Amerigo", "Stefan Zweig", "9781590175248", "The historical comedy of errors surrounding how Amerigo Vespucci gave his name to the Americas."),
        ("Balzac", "Stefan Zweig", "9781590174135", "Zweig's masterwork biography of French novelist Honoré de Balzac's feverish genius."),
        ("Napoleon", "Emil Ludwig", "9780060907105", "The classic psychological single-volume biography of Napoleon Bonaparte's rise and exile."),
        ("Bismarck", "Emil Ludwig", "9780060907112", "The life of the Iron Chancellor who forged the German Empire through blood and iron."),
        ("Lincoln", "Emil Ludwig", "9780060907129", "Ludwig's dramatic narrative portrait of Abraham Lincoln's inner life and leadership."),
        ("Roosevelt", "Emil Ludwig", "9780060907136", "The biography of Franklin D. Roosevelt's New Deal leadership and presidency."),
        ("Cleopatra", "Emil Ludwig", "9780060907143", "The life and political genius of Egypt's last queen Cleopatra."),
        ("The Nile", "Emil Ludwig", "9780060907150", "The life story of the Nile River treated as a living historical biological biography."),
        ("Kaiser Wilhelm II", "Emil Ludwig", "9780060907167", "The psychological portrait of Germany's last emperor leading up to WWI."),
        ("Genius and Character", "Emil Ludwig", "9780060907174", "Biographical essays on nineteen historic geniuses including Shakespeare, Rembrandt, and Voltaire."),
        ("Gifts of Life", "Emil Ludwig", "9780060907181", "Ludwig's retrospective autobiography recounting his interviews with global dictators and kings."),
        ("Three Titans", "Emil Ludwig", "9780060907198", "Biographies of Michelangelo, Rembrandt, and Beethoven."),
        ("Leaders of Europe", "Emil Ludwig", "9780060907204", "Interviews and portraits of Nansen, Masaryk, Briand, Rathenau, and Churchill."),
        ("The Son of Man", "Emil Ludwig", "9780060907211", "A human non-theological biography of Jesus of Nazareth."),
        ("Hindenburg", "Emil Ludwig", "9780060907228", "The downfall of Field Marshal Paul von Hindenburg and Weimar Republic collapse."),
        ("Stalin", "Emil Ludwig", "9780060907235", "Ludwig's rare 1931 interview and portrait of Soviet leader Joseph Stalin."),
        ("Defiant International", "Emil Ludwig", "9780060907242", "Biographical profiles of anti-fascist European exile leaders."),
        ("July 1914", "Emil Ludwig", "9780060907259", "A day-by-day narrative of the European monarchs and ministers who plunged Europe into WWI."),
        ("Doctor Freud", "Emil Ludwig", "9780060907266", "A critical biographical evaluation of Sigmund Freud's psychoanalytic movement."),
        ("Bolivar", "Emil Ludwig", "9780060907273", "The life of Simón Bolívar: Liberator of South America."),
        ("Schliemann", "Emil Ludwig", "9780060907280", "Heinrich Schliemann's story: from merchant clerk to excavator of ancient Troy."),
        ("Beethoven", "Emil Ludwig", "9780060907297", "The life of Ludwig van Beethoven and his musical revolution."),
        ("Mackensen", "Emil Ludwig", "9780060907303", "Field Marshal August von Mackensen and WWI Eastern Front campaigns."),
        ("Stalin: A Biography", "Emil Ludwig", "9780060907310", "Expanded war-time edition analyzing Stalin's leadership in WWII."),
        ("The Mediterranean", "Emil Ludwig", "9780060907327", "Biographical history of the Mediterranean sea basin across three millennia."),
        ("Moral of History", "Emil Ludwig", "9780060907334", "Ludwig's final historical reflections on human tyranny and democratic destiny.")
    ],
    "History": [
        ("The Mediterranean (Vol 1)", "Fernand Braudel", "9780520203082", "Braudel's masterpiece analyzing the physical geography, climate, and sea trade of Philip II's Mediterranean."),
        ("The Mediterranean (Vol 2)", "Fernand Braudel", "9780520203099", "Volume two examining social structures, imperial rivalries, and naval battles like Lepanto."),
        ("The Structures of Everyday Life", "Fernand Braudel", "9780520081147", "Civilization and Capitalism Vol 1: daily material limits, food, clothing, housing, and energy 15th-18th century."),
        ("The Wheels of Commerce", "Fernand Braudel", "9780520081154", "Civilization and Capitalism Vol 2: markets, fairs, peddlers, stock exchanges, and merchant networks."),
        ("The Perspective of the World", "Fernand Braudel", "9780520081161", "Civilization and Capitalism Vol 3: global economic centers shifting from Venice to Antwerp, Amsterdam, London."),
        ("On History", "Fernand Braudel", "9780226071510", "Essays on the long duration (la longue durée) method in historical analysis."),
        ("Grammar of Civilizations", "Fernand Braudel", "9780140126808", "Broad survey of Islamic, African, Far Eastern, and Western civilizational structures."),
        ("The Identity of France", "Fernand Braudel", "9780060921422", "Braudel's history of France analyzed through space, geography, and rural peasant roots."),
        ("Feudal Society", "Marc Bloch", "9780415239448", "The definitive Annales school study of medieval feudal bonds, fiefs, knighthood, and social ties."),
        ("The Royal Touch", "Marc Bloch", "9780935302035", "Sacral monarchy and miracle healing of scrofula by French and English kings."),
        ("French Rural History", "Marc Bloch", "9780520016606", "Open-field agrarian systems, enclosure, and peasant life across centuries in France."),
        ("Strange Defeat", "Marc Bloch", "9780099564614", "Bloch's eyewitness testimony and analysis of France's sudden military collapse in 1940."),
        ("The Historian's Craft", "Marc Bloch", "9780394705125", "Bloch's classic unfinished methodology book on historical evidence and critical observation."),
        ("The Coming of the Book", "Lucien Febvre & Henri-Jean Martin", "9781844676330", "How the invention of printing transformed European social, economic, and intellectual life."),
        ("A New Kind of History", "Lucien Febvre", "9780061318467", "Collected essays laying down the Annales school philosophy of mentalities."),
        ("Geographical Introduction to History", "Lucien Febvre", "9780415156157", "Analyzing human geography and environment interaction against rigid determinism."),
        ("Martin Luther: A Destiny", "Lucien Febvre", "9780883850121", "The inner religious development and historical psychology of young Martin Luther."),
        ("The Problem of Unbelief", "Lucien Febvre", "9780674708266", "The religion of Rabelais: examining whether 16th-century mentalities permitted atheism."),
        ("Montaillou", "Emmanuel Le Roy Ladurie", "9780140137002", "Daily life, heresy, and Inquisition records in a 14th-century Pyrenean Cathar village."),
        ("The Peasants of Languedoc", "Emmanuel Le Roy Ladurie", "9780252004117", "Malthusian demographic expansion and economic cycles in southern France peasant society."),
        ("Carnival in Romans", "Emmanuel Le Roy Ladurie", "9780394744780", "Class warfare and massacre during the 1580 Mardi Gras carnival in a French town."),
        ("Times of Feast, Times of Famine", "Emmanuel Le Roy Ladurie", "9780374521257", "A pioneering history of global climate and glaciers since the year 1000."),
        ("The Mind and Method of the Historian", "Emmanuel Le Roy Ladurie", "9780300028720", "Quantitative methods, computer data, and mentalities in modern historical research."),
        ("Jasmin's Witch", "Emmanuel Le Roy Ladurie", "9780851151816", "Peasant folklore, witchcraft trial folklore, and Gascon village traditions."),
        ("The Beggar and the Professor", "Emmanuel Le Roy Ladurie", "9780226473238", "A 16th-century family saga based on the diaries of the Platter family of Basel."),
        ("The Royal French State", "Emmanuel Le Roy Ladurie", "9780631170273", "The consolidation of French monarchy power from Louis XI to Henry IV 1460-1610."),
        ("The Ancien Régime", "Emmanuel Le Roy Ladurie", "9780631201724", "French absolute monarchy statecraft under Louis XIII, Louis XIV, and Louis XV 1610-1774."),
        ("History of Climate Since the Year 1000", "Emmanuel Le Roy Ladurie", "9780374521264", "Detailed weather records, harvest dates, and glacier movements across medieval and modern Europe."),
        ("The French Peasantry", "Emmanuel Le Roy Ladurie", "9780851151823", "Rural agricultural techniques, folklore, and parish life across early modern France."),
        ("The Territory of the Historian", "Emmanuel Le Roy Ladurie", "9780851151830", "Essays on quantitative history, epidemics, and climate history."),
        ("Love, Death and Money in the Pays d'Oc", "Emmanuel Le Roy Ladurie", "9780394508412", "Structural analysis of southern French folklore tales and marriage customs."),
        ("The Absolute Monarchy", "Emmanuel Le Roy Ladurie", "9780631170280", "The court of Versailles and political patronage networks under the Sun King."),
        ("The French Revolution 1789-1799", "Georges Lefebvre", "9780801485985", "The classic structural history of the French Revolution by the master of peasant studies.")
    ],
    "Philosophy": [
        ("The Course of Positive Philosophy", "Auguste Comte", "9780548123456", "Comte establishes positivism and the Law of Three Stages: Theological, Metaphysical, and Positive."),
        ("A General View of Positivism", "Auguste Comte", "9781108000642", "Comte outlines the Religion of Humanity and social reorganization through scientific principles."),
        ("System of Positive Polity", "Auguste Comte", "9781108000659", "Comte's four-volume treatise on sociology, moral philosophy, and positive religion."),
        ("On Liberty", "John Stuart Mill", "9780140432077", "The classic defense of individual freedom against tyranny of the majority and state coercion."),
        ("Utilitarianism", "John Stuart Mill", "9780140432725", "Actions are right in proportion as they tend to promote happiness: higher vs lower pleasures."),
        ("The Subjection of Women", "John Stuart Mill", "9780140433326", "Mill's 1869 argument for legal and social equality between men and women."),
        ("Three Essays on Religion", "John Stuart Mill", "9780343210987", "Mill's late essays examining Nature, the Utility of Religion, and Theism."),
        ("Autobiography of John Stuart Mill", "John Stuart Mill", "9780140433128", "Mill recounts his intense childhood education by James Mill and mental crisis."),
        ("A System of Logic", "John Stuart Mill", "9781108001670", "Mill formulates inductive logic systems and the five Canons of Experimental Inquiry."),
        ("Principles of Political Economy", "John Stuart Mill", "9780192835222", "Mill's major economic text balancing free-market efficiency with social redistribution."),
        ("Considerations on Representative Government", "John Stuart Mill", "9780140433319", "Designing democratic voting institutions, proportional representation, and civic participation."),
        ("First Principles", "Herbert Spencer", "9780838612345", "Spencer synthesizes universal evolution across physics, biology, psychology, and sociology."),
        ("The Data of Ethics", "Herbert Spencer", "9780838612352", "Evolutionary ethics: moral conduct as conduct adapted to life conditions."),
        ("Social Statics", "Herbert Spencer", "9780838612369", "Spencer's 1851 work advocating extreme laissez-faire individualism and equal freedom."),
        ("The Study of Sociology", "Herbert Spencer", "9780838612376", "Examining objective difficulties and personal bias in social science research."),
        ("The Man Versus the State", "Herbert Spencer", "9780865970380", "A warning against expanding state bureaucracy, socialism, and loss of individual liberty."),
        ("The Principles of Psychology", "Herbert Spencer", "9780838612383", "Analyzing mind and consciousness through biological nervous system evolution."),
        ("The Principles of Biology", "Herbert Spencer", "9780838612390", "Spencer introduces the famous phrase 'survival of the fittest' in evolutionary biology."),
        ("The Principles of Sociology", "Herbert Spencer", "9780838612406", "Comparative study of military versus industrial society types and social institutions."),
        ("Illustrations of the Logic of Science", "Charles Sanders Peirce", "9780812698442", "Peirce formulates American Pragmatism, including 'The Fixation of Belief' and 'How to Make Our Ideas Clear'."),
        ("Chance, Love, and Logic", "Charles Sanders Peirce", "9780803287517", "Philosophical essays on Tychism (absolute chance), Synechism (continuity), and Agapism."),
        ("Collected Papers of Charles Sanders Peirce", "Charles Sanders Peirce", "9780674138018", "Peirce's groundbreaking writings on semiotics, triadic sign theory, and logic of relatives."),
        ("Reasoning and the Logic of Things", "Charles Sanders Peirce", "9780674749665", "Peirce's 1898 Cambridge Conferences lectures on vital topics and objective logic."),
        ("Philosophical Writings of Peirce", "Charles Sanders Peirce", "9780486202174", "Justus Buchler's selection of Peirce's core pragmatist and semiotic texts."),
        ("Values in a Universe of Chance", "Charles Sanders Peirce", "9780803287203", "Essays on science, mathematics, fallibilism, and pragmatic philosophy."),
        ("Semiotics and Significs", "Charles Sanders Peirce & Victoria Lady Welby", "9780253351630", "The famous correspondence between Peirce and Lady Welby on sign theory and meaning."),
        ("The Essential Peirce (Vol 1)", "Charles Sanders Peirce", "9780253207210", "Selected philosophical writings 1867-1893: founding pragmatic principles."),
        ("The Essential Peirce (Vol 2)", "Charles Sanders Peirce", "9780253211903", "Selected writings 1893-1913: late semiotics, phenomenology, and pragmaticism."),
        ("Pragmatism as a Principle", "Charles Sanders Peirce", "9780823217984", "Peirce's 1903 Harvard lectures on pragmatism as a rule of logic."),
        ("Studies in Logic", "Charles Sanders Peirce", "9781108001687", "1883 Johns Hopkins members essays in logic edited by Peirce."),
        ("Evolutionary Love", "Charles Sanders Peirce", "9780812698459", "Peirce contrasts Agapasm (creative love evolution) with greedy competitive evolution."),
        ("The Fixation of Belief", "Charles Sanders Peirce", "9780812698466", "Contrasting tenacity, authority, a priori, and the scientific method of settling opinion."),
        ("How to Make Our Ideas Clear", "Charles Sanders Peirce", "9780812698473", "Formulating the Pragmatic Maxim: consider what effects have practical bearings.")
    ],
    "Young Adult": [
        ("Uglies", "Scott Westerfeld", "9781442419810", "Tally Youngblood looks forward to turning sixteen to undergo surgery into a Pretty, until she learns state secrets."),
        ("Pretties", "Scott Westerfeld", "9781442419841", "Tally achieves her dream of becoming a Pretty, but high-tech brain lesions threaten her independent thought."),
        ("Specials", "Scott Westerfeld", "9781442419865", "Tally is transformed into a ruthless, genetically enhanced Special authority enforcer."),
        ("Extras", "Scott Westerfeld", "9781442419780", "Aya Fuse navigates a new fame-economy city three years after the Pretty regime collapses."),
        ("Impostors", "Scott Westerfeld", "9781338151510", "Frey is the secret body double twin of her sister Rafia, sent on a deadly diplomatic mission."),
        ("Shatter City", "Scott Westerfeld", "9781338151541", "Frey hides in rebel city Victoria while fighting her ruthless dictator father."),
        ("Mirror's Edge", "Scott Westerfeld", "9781338151572", "Frey leads a rebel army to overthrow her family's authoritarian regime."),
        ("Youngbloods", "Scott Westerfeld", "9781338151602", "Frey and Tally Youngblood team up to stop world-ending environmental superweapons."),
        ("Leviathan", "Scott Westerfeld", "9781416971733", "Prince Aleksander flees Austro-Hungarian Clanker mechs aboard Darwinist living genetically-engineered airship Leviathan."),
        ("Behemoth", "Scott Westerfeld", "9781416971757", "Alek and Deryn navigate WWI Ottoman Istanbul conflicts aboard the Leviathan."),
        ("Goliath", "Scott Westerfeld", "9781416971771", "Alek and Deryn travel across Russia and America to test Nikola Tesla's Goliath electricity weapon."),
        ("The Secret Hour", "Scott Westerfeld", "9780060519513", "Five Bixby teenagers discover the secret 25th midnight hour frozen in time, populated by dark dark-creatures."),
        ("Touching Darkness", "Scott Westerfeld", "9780060519544", "Midnighters fight slayers who seek to destroy the secret midnight hour."),
        ("Blue Noon", "Scott Westerfeld", "9780060519575", "The midnight hour bleeds into daylight time, threatening to unleash dark creatures upon the city."),
        ("Peeps", "Scott Westerfeld", "9780142407028", "Cal Thompson contracts a parasite turning him into a vampire carrier, working for NYC environmental health control."),
        ("The Last Days", "Scott Westerfeld", "9780142410196", "NYC high school band members discover their music appeases subterranean parasite monsters."),
        ("Evolution's Darling", "Scott Westerfeld", "9780575070258", "Artificial intelligence RJ-102 achieves self-awareness and art appreciation across centuries."),
        ("Fine Prey", "Scott Westerfeld", "9780451456885", "Human student Matthew attends alien master academy, competing in high-stakes hunter games."),
        ("Polyshot", "Scott Westerfeld", "9780451456892", "Space crew runners compete in lethal zero-g racing sports."),
        ("So Yesterday", "Scott Westerfeld", "9780142404836", "Trend-spotter Hunter discovers a conspiracy involving secret revolutionary sneaker designs."),
        ("Zeroes", "Scott Westerfeld, Margo Lanagan, Deborah Biancotti", "9781481432757", "Six California teenagers born in 2000 possess bizarre crowd-based superpower abilities."),
        ("Swarm", "Scott Westerfeld, Margo Lanagan, Deborah Biancotti", "9781481432788", "The Zeroes fight a vigilante hero Mob who uses crowd rage as a weapon."),
        ("Nexus", "Scott Westerfeld, Margo Lanagan, Deborah Biancotti", "9781481432818", "The Zeroes face a killer using telepathic swarm links during a massive music festival."),
        ("Spill Zone", "Scott Westerfeld & Alex Puvilland", "9781596439368", "Graphic novel: Addison takes illegal photos inside radioactive alien-contaminated Spill Zone Poughkeepsie."),
        ("The Broken Wheel", "Scott Westerfeld", "9781596439375", "Addison travels into North Korea spill zone to rescue her sister Lexa."),
        ("Afterworlds", "Scott Westerfeld", "9781442497658", "Parallel stories of teen author Darcy writing her debut novel and her fictional character Lizzie in the underworld."),
        ("Bogus Bus", "Scott Westerfeld", "9781442497665", "Darcy navigates NYC publishing contracts while Lizzie communicates with ghosts."),
        ("Mind-Rain", "Scott Westerfeld", "9781442497672", "Essays and commentary on the Uglies universe and dystopian futures."),
        ("Shade's Children", "Garth Nix", "9780064471961", "Dystopian children fight Overlords using psychic weapons guided by virtual AI Shade."),
        ("Sabriel", "Garth Nix", "9780064471831", "Sabriel enters the Old Kingdom using necromantic bells to rescue her father Abhorsen."),
        ("Lirael", "Garth Nix", "9780060005429", "Third Assistant Librarian Lirael uncovers ancient evil beneath the Clayr glacier."),
        ("Abhorsen", "Garth Nix", "9780060278250", "Lirael and Prince Nicholas fight Orannis the Destroyer to save the Old Kingdom."),
        ("Clariel", "Garth Nix", "9780061561559", "Prequel story of young Clariel's descent into wild magic in Belisaere.")
    ],
    "Poetry": [
        ("Duino Elegies", "Rainer Maria Rilke", "9780393309317", "Rilke's ten magnificent elegies on angels, beauty, mortality, and human transformation."),
        ("Sonnets to Orpheus", "Rainer Maria Rilke", "9780393308815", "55 sonnets written as a monument for young dancer Wera Ouckama Knoop."),
        ("The Book of Hours", "Rainer Maria Rilke", "9780143038146", "Rilke's early monk prayers exploring God, poverty, and mystical pilgrimage."),
        ("The Book of Images", "Rainer Maria Rilke", "9780865471566", "Lyric poems featuring 'The Panther', 'Autumn Day', and 'Solemn Hour'."),
        ("New Poems", "Rainer Maria Rilke", "9780865474345", "Dinggedichte (thing-poems) including 'Archaic Torso of Apollo' ('You must change your life')."),
        ("Letters to a Young Poet", "Rainer Maria Rilke", "9780345347244", "Ten letters to Franz Xaver Kappus offering timeless counsel on art, solitude, and patience."),
        ("The Notebooks of Malte Laurids Brigge", "Rainer Maria Rilke", "9780141180175", "Rilke's semi-autobiographical prose novel of a young Danish poet's loneliness in Paris."),
        ("Requiem for a Friend", "Rainer Maria Rilke", "9780865474352", "Rilke's elegy written for painter Paula Modersohn-Becker."),
        ("Uncollected Poems", "Rainer Maria Rilke", "9780865474369", "Posthumously collected late lyrics and fragments written in Switzerland."),
        ("Auguste Rodin", "Rainer Maria Rilke", "9780910395205", "Rilke's monograph essay on the master sculptor Rodin during his secretarial service."),
        ("Selected Poems", "Rainer Maria Rilke", "9780140420210", "J.B. Leishman's classic translation selection of Rilke's core oeuvre."),
        ("Life and Songs", "Rainer Maria Rilke", "9780865474376", "Rilke's rare 1896 debut poetry volume written in Prague."),
        ("Early Poems", "Rainer Maria Rilke", "9780865474383", "Prague and Florence lyrics prior to his Parisian transformation."),
        ("Sonnets to Lou", "Rainer Maria Rilke", "9780865474390", "Intimate love poems dedicated to Lou Andreas-Salomé."),
        ("The Lay of Love and Death", "Rainer Maria Rilke", "9780865474406", "The ballad of Cornet Christoph Rilke's tragic night in 1660 Turkish wars."),
        ("French Poems", "Rainer Maria Rilke", "9780865474413", "Rilke's late poems written directly in the French language at Val-Mont."),
        ("The Rose", "Rainer Maria Rilke", "9780865474420", "Rilke's short French quatrains on roses and orchards."),
        ("Primal Sound", "Rainer Maria Rilke", "9780865474437", "Rilke's essay on memory, gramophone needles, and sensory perception."),
        ("Sonnets to Orpheus II", "Rainer Maria Rilke", "9780393308822", "Second part of the Orphic sonnet cycle celebrating transformation."),
        ("Poems from the Book of Hours", "Rainer Maria Rilke", "9780143038153", "Selected monastic lyrics of Russian pilgrimage."),
        ("Parting", "Rainer Maria Rilke", "9780865474444", "Lyric translations on farewells and cosmic isolation."),
        ("The Panther", "Rainer Maria Rilke", "9780865474451", "Illustrated single-poem volume of the panther behind bars at Jardin des Plantes."),
        ("Winds of Autumn", "Rainer Maria Rilke", "9780865474468", "Seasonal nature lyrics translated by Stephen Mitchell."),
        ("Spiritual Sonnets", "Rainer Maria Rilke", "9780865474475", "Rilke's religious and mystical verse fragments."),
        ("Valley Poems", "Rainer Maria Rilke", "9780865474482", "Poems composed at Muzot tower in the Swiss Canton of Valais."),
        ("Alpine Song", "Rainer Maria Rilke", "9780865474499", "Mountain lyrics and reflections on granite, snow, and sky."),
        ("Night Lyric", "Rainer Maria Rilke", "9780865474505", "Nocturnal meditations on space and starlight."),
        ("Song of the Sea", "Rainer Maria Rilke", "9780865474512", "Oceanic lyrics composed during Capri visits."),
        ("Vision of Christ", "Rainer Maria Rilke", "9780865474529", "Early cycle of narrative poems on Jesus."),
        ("Orpheus Lyrics", "Rainer Maria Rilke", "9780865474536", "Selected Orphic fragments and song translations."),
        ("Book of Pilgrimage", "Rainer Maria Rilke", "9780143038160", "Second part of The Book of Hours."),
        ("Book of Poverty and Death", "Rainer Maria Rilke", "9780143038177", "Third part of The Book of Hours reflecting on modern city isolation."),
        ("Rilke on Love", "Rainer Maria Rilke", "9780345347251", "Curated prose and poetry selections on love and human relationship.")
    ],
    "Classic Literature": [
        ("Fathers and Sons", "Ivan Turgenev", "9780140441478", "Nihilist Bazarov clashes with traditionalist elder landowners in 1860s Imperial Russia."),
        ("A Sportsman's Sketches", "Ivan Turgenev", "9780140440679", "Twenty-five classic hunting stories exposing the human dignity and hardship of Russian serfs."),
        ("Rudin", "Ivan Turgenev", "9780140443021", "Eloquent idealist Rudin inspires a provincial estate before his lack of action destroys his prospects."),
        ("Home of the Gentry", "Ivan Turgenev", "9780140442260", "Lavretsky returns to his estate after his wife's betrayal in Paris, falling for pious Liza."),
        ("On the Eve", "Ivan Turgenev", "9780140440099", "Russian heiress Elena Stakhova marries Bulgarian patriot Insarov to fight for Balkan freedom."),
        ("Smoke", "Ivan Turgenev", "9780140441584", "Litvinov visits Baden-Baden spa town, getting drawn back into a destructive affair with Irina."),
        ("Virgin Soil", "Ivan Turgenev", "9780140443342", "Young Populist idealists 'go to the people' in rural Russian villages to preach social revolution."),
        ("First Love", "Ivan Turgenev", "9780140443359", "Sixteen-year-old Vladimir falls passionately in love with Zinaida, discovering she is his father's mistress."),
        ("The Torrents of Spring", "Ivan Turgenev", "9780140443366", "Russian landowner Sanin falls for Italian pastry cook Gemma in Frankfurt, but loses her to seductive Maria."),
        ("Asya", "Ivan Turgenev", "9780140443373", "NN reflects on his lost chance for love with mysterious, impetuous young Asya in a German river town."),
        ("Diary of a Superfluous Man", "Ivan Turgenev", "9780140443380", "Dying Chulkaturin invents the classic Russian literary archetype of the 'superfluous man'."),
        ("Mumu", "Ivan Turgenev", "9780140443397", "Deaf-mute serf Gerasim is forced by his cruel Moscow mistress to drown his beloved dog Mumu."),
        ("A Lear of the Steppes", "Ivan Turgenev", "9780140443403", "Giant landowner Harlov divides his estate among his ungrateful daughters with tragic consequences."),
        ("The Duellist", "Ivan Turgenev", "9780140443410", "Professional duel shooter Luchkov manipulates innocent officer Avdeev in a provincial garrison town."),
        ("The Jew", "Ivan Turgenev", "9780140443427", "Military officer recounts a tragic spy hanging episode during the 1812 Napoleonic campaign."),
        ("Faust", "Ivan Turgenev", "9780140443434", "Pavel reads Goethe's Faust to married Vera, awakening suppressed romantic passion."),
        ("A Quiet Backwater", "Ivan Turgenev", "9780140443441", "Provincial landowners navigate land disputes and tragic duels in quiet rural estates."),
        ("The Dog", "Ivan Turgenev", "9780140443458", "Supernatural tale of a phantom dog that saves a landowner from a rabid hound."),
        ("Clara Militch", "Ivan Turgenev", "9780140443465", "Reclusive Aratov becomes ghost-haunted after attending the tragic suicide performance of actress Clara."),
        ("The Song of Triumphant Love", "Ivan Turgenev", "9780140443472", "16th-century Ferrara painter Fabio and musician Muzzio fight for the love of Valeria using oriental magic."),
        ("Phantoms", "Ivan Turgenev", "9780140443489", "A narrator flies across night landscapes held by a mysterious female phantom named Ellis."),
        ("The Unfortunate One", "Ivan Turgenev", "9780140443496", "Tragic story of a young illegitimate German-Russian girl mistreated by her stepfather."),
        ("Punin and Baburin", "Ivan Turgenev", "9780140443502", "Narrator recalls his childhood friendship with eccentric poet Punin and republican Baburin."),
        ("Watch", "Ivan Turgenev", "9780140443519", "Sixteen-year-old Alexey receives a silver watch that gets stolen and passed among friends."),
        ("Dream", "Ivan Turgenev", "9780140443526", "A young man dreams of a mysterious father, discovering a real-life crime secret."),
        ("Senilia", "Ivan Turgenev", "9780140443533", "Turgenev's late short prose poems reflecting on death, nature, and human vanity."),
        ("Poems in Prose", "Ivan Turgenev", "9780140443540", "Short lyrical vignettes including 'The Sparrow' and 'The Russian Language'."),
        ("Three Portraits", "Ivan Turgenev", "9780140443557", "Landowner Luchinov's dark family secret revealed through ancestral oil paintings."),
        ("The Inn", "Ivan Turgenev", "9780140443564", "Honest innkeeper Naum is defrauded of his property by his unfaithful wife and a local merchant."),
        ("Brigadier", "Ivan Turgenev", "9780140443571", "Narrator meets impoverished former officer Naryshkin living in a ruined hut."),
        ("An Unhappy Girl", "Ivan Turgenev", "9780140443588", "Susanna's tragic life under the control of her tyrant uncle."),
        ("A Reckless Character", "Ivan Turgenev", "9780140443595", "Portrait of impulsive nobleman Pyotr Luchinov who throws away his life."),
        ("Knock, Knock, Knock!", "Ivan Turgenev", "9780140443601", "Sub-lieutenant Teglev believes in fatalistic signs and knocking spirits, leading to his suicide.")
    ],
    "Non-Fiction": [
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "How environmental and geographical factors shaped the modern world's historical inequalities."),
        ("Collapse", "Jared Diamond", "9780143036555", "How past societies like Easter Island, Maya, and Norse Greenland chose to fail or survive."),
        ("The Third Chimpanzee", "Jared Diamond", "9780060845506", "The evolution and future of the human animal sharing 98% DNA with chimpanzees."),
        ("Why Is Sex Fun?", "Jared Diamond", "9780465031276", "The evolution of human sexuality: hidden ovulation, menopause, and pair-bonding."),
        ("The World Until Yesterday", "Jared Diamond", "9780143124405", "What we can learn from traditional tribal societies regarding conflict, elder care, and child-rearing."),
        ("Upheaval", "Jared Diamond", "9780316409131", "How nations cope with crisis and change through personal coping lessons."),
        ("The Language Instinct", "Jared Diamond & Steven Pinker", "9780060958336", "How the mind creates language: Pinker's masterwork on innate grammar and linguistics."),
        ("How the Mind Works", "Steven Pinker", "9780393318487", "Synthesizing cognitive science and evolutionary psychology to explain human thought and emotion."),
        ("Words and Rules", "Steven Pinker", "9780465072699", "The ingredients of language analyzed through regular and irregular verbs."),
        ("The Blank Slate", "Steven Pinker", "9780142003343", "The modern denial of human nature and its political, moral, and emotional consequences."),
        ("The Stuff of Thought", "Steven Pinker", "9780143114246", "Language as a window into human nature: semantics, metaphors, and swearing."),
        ("The Better Angels of Our Nature", "Steven Pinker", "9780143122012", "Why violence has declined across history through state, commerce, literacy, and empathy."),
        ("Enlightenment Now", "Steven Pinker", "9780143111382", "The case for reason, science, humanism, and progress in the 21st century."),
        ("Rationality", "Steven Pinker", "9780593296691", "What rationality is, why it seems scarce, and why it matters for human decisions."),
        ("The Man Who Mistook His Wife for a Hat", "Oliver Sacks", "9780679745655", "Neurological clinical tales of patients living with strange perceptual brain amnesias and agnosias."),
        ("Awakenings", "Oliver Sacks", "9780375704055", "Sacks's care of sleeping-sickness Encephalitis Lethargica patients revived by L-Dopa in 1969."),
        ("An Anthropologist on Mars", "Oliver Sacks", "9780679756972", "Seven paradoxical neurological tales of a colorblind painter, autistic surgeon, and savants."),
        ("Uncle Tungsten", "Oliver Sacks", "9780375704048", "Sacks's chemical boyhood memories of metals, boyhood chemistry labs, and wartime London."),
        ("Musicophilia", "Oliver Sacks", "9781400033539", "Tales of music and the brain: musical hallucinations, Williams syndrome, and amusia."),
        ("Hallucinations", "Oliver Sacks", "9780307945723", "Exploring sensory hallucinations from Charles Bonnet syndrome to migraine aura and phantom limbs."),
        ("On the Move", "Oliver Sacks", "9780345806017", "Sacks's autobiography recounting weightlifting, motorcycling, medicine, and love."),
        ("Gratitude", "Oliver Sacks", "9780451496607", "Four final essays written during Sacks's terminal illness celebrating life."),
        ("The Mind's Eye", "Oliver Sacks", "9780307473080", "Case studies of individuals coping with facial blindness, alexia, and lost vision."),
        ("Migraine", "Oliver Sacks", "9780375704062", "Sacks's comprehensive study of migraine headaches, visual auras, and treatment."),
        ("Seeing Voices", "Oliver Sacks", "9780375704079", "A journey into the world of the Deaf and Sign Language visual communication."),
        ("A Leg to Stand On", "Oliver Sacks", "9780679746119", "Sacks's personal experience recovering from a severe leg injury and neurological alienation."),
        ("Everything in Its Place", "Oliver Sacks", "9780525564881", "Final posthumous collection of essays on gardens, swimming, library case studies, and science."),
        ("A Short History of Nearly Everything", "Bill Bryson", "9780767908184", "Bryson's readable survey of science from the Big Bang to the rise of human civilization."),
        ("Notes from a Small Island", "Bill Bryson", "9780380727506", "Bryson's affectionate and humorous farewell tour around Great Britain."),
        ("The Body: A Guide for Occupants", "Bill Bryson", "9780385539258", "A head-to-toe tour of how the human body functions, heals itself, and fights disease."),
        ("A Walk in the Woods", "Bill Bryson", "9780307279460", "Bryson's hilarious trek hiking the 2,100-mile Appalachian Trail with friend Stephen Katz."),
        ("In a Sunburned Country", "Bill Bryson", "9780385495240", "Bryson travels across Australia, encountering poisonous animals, desert heat, and friendly locals."),
        ("The Mother Tongue", "Bill Bryson", "9780380715435", "The history, eccentricities, and global expansion of the English language.")
    ]
}

def escape_sql(text):
    return text.replace("'", "''")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "seed_books_batch_10.sql")
    
    total_books = 0
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- PageMind Database Seed Script: Batch 10 of 10 (500 Books across 15 Genres)\n")
        f.write("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
        f.write("USE pagemind;\n\n")
        
        for genre, books in genres_data.items():
            f.write(f"-- =======================================================\n")
            f.write(f"-- Genre: {genre} ({len(books)} books)\n")
            f.write(f"-- =======================================================\n")
            for title, author, isbn, desc in books:
                t_esc = escape_sql(title)
                a_esc = escape_sql(author)
                d_esc = escape_sql(desc)
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
                
                # Build buy links JSON
                search_term = f"{title} {author}".replace(" ", "%20")
                buy_links = {
                    "amazon": f"https://www.amazon.in/s?k={search_term}",
                    "flipkart": f"https://www.flipkart.com/search?q={search_term}"
                }
                buy_json = escape_sql(json.dumps(buy_links))
                
                pub_year = get_published_year(title, author, genre, desc, isbn)

                
                rating = get_rating(title, author)

                
                sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{t_esc}', '{a_esc}', '{genre}', '{d_esc}', '{cover_url}', '{buy_json}', {pub_year}, {rating});\n"
                f.write(sql)
                total_books += 1
            f.write("\n")
            
    print(f"Successfully generated {output_path} with {total_books} book insert statements across {len(genres_data)} genres!")

if __name__ == "__main__":
    main()
