# generate_batch_7.py
# Generates seed_books_batch_7.sql containing 500 unique book insert statements across 15 genres

from book_metadata_utils import get_rating, get_published_year
import json
import os

genres_data = {
    "Fiction": [
        ("The Robber Bride", "Margaret Atwood", "9780385476355", "Zenia, a villainous seductress, returns from the dead to torment three Toronto women."),
        ("Alias Grace", "Margaret Atwood", "9780385490443", "Dr. Simon Jordan interviews convicted murderess Grace Marks in 1840s Canada."),
        ("The Blind Assassin", "Margaret Atwood", "9780385720953", "Iris Chase Griffen narrates her family history intertwined with a science fiction novel written by her sister."),
        ("Oryx and Crake", "Margaret Atwood", "9780385721677", "Snowman lives in a post-apocalyptic world created by bio-engineered plague, remembering his friends Oryx and Crake."),
        ("The Year of the Flood", "Margaret Atwood", "9780307455475", "Toby and Ren survive the Waterless Flood pandemic inside a eco-religious group called God's Gardeners."),
        ("MaddAddam", "Margaret Atwood", "9780307455482", "The survivors of the bio-plague unite with the Crakers to reclaim civilization."),
        ("The Heart Goes Last", "Margaret Atwood", "9781101912362", "Stan and Charmaine join the Positron Project, alternating months as prisoners and suburban householders."),
        ("Hag-Seed", "Margaret Atwood", "9780804141291", "Deposed theater director Felix staging Shakespeare's The Tempest inside a correctional facility."),
        ("Cat's Eye", "Margaret Atwood", "9780385491020", "Painter Elaine Risley returns to Toronto for a retrospective, confronting childhood bullying memories."),
        ("Surfacing", "Margaret Atwood", "9780385491051", "A young woman searches for her missing father in northern Quebec wilderness."),
        ("The Bean Trees", "Margaret Atwood & Barbara Kingsolver", "9780061097317", "Taylor Greer leaves Kentucky in a beat-up car and inherits an abandoned Native American child named Turtle."),
        ("Pigs in Heaven", "Barbara Kingsolver", "9780060922535", "Taylor Greer fights to maintain custody of Turtle against Cherokee Nation legal claims."),
        ("Animal Dreams", "Barbara Kingsolver", "9780060921149", "Codi Noline returns to Grace, Arizona to care for her ailing father and confront her past."),
        ("The Poisonwood Bible", "Barbara Kingsolver", "9780060786502", "Nathan Price takes his wife and four daughters on a fierce evangelical mission to the Belgian Congo in 1959."),
        ("Prodigal Summer", "Barbara Kingsolver", "9780060959036", "Three distinct love stories unfold in the southern Appalachian mountains over one humid summer."),
        ("The Lacuna", "Barbara Kingsolver", "9780060852580", "Harrison Shepherd works for Diego Rivera, Frida Kahlo, and Leon Trotsky before facing McCarthyism."),
        ("Flight Behavior", "Barbara Kingsolver", "9780062124272", "Dellarobia Turnbow discovers millions of monarch butterflies roosting unnaturally in Tennessee mountains."),
        ("Unsheltered", "Barbara Kingsolver", "9780062684738", "Two families living in Vineland, New Jersey during different centuries navigate shifting societal collapse."),
        ("Demon Copperhead", "Barbara Kingsolver", "9780063251922", "A modern reimagining of David Copperfield set in the mountains of southern Appalachia battling addiction."),
        ("The Temple of My Familiar", "Alice Walker", "9780156894500", "Six interconnected voices spans centuries of African diaspora history, mythology, and reincarnation."),
        ("Possessing the Secret of Joy", "Alice Walker", "9780156718202", "Tashi, a tribal woman, suffers female genital mutilation and copes with trauma in America."),
        ("By the Light of My Father's Smile", "Alice Walker", "9780345426147", "Sisters Susannah and Magdalena explore sexuality, grief, and ancestral influence in Mexico."),
        ("Now Is the Time to Open Your Heart", "Alice Walker", "9780345455321", "Novelists Kate leaves her long-time partner to embark on a spiritual river journey in the Amazon."),
        ("The Third Life of Grange Copeland", "Alice Walker", "9780156890458", "Three generations of black sharecroppers fight poverty, racism, and domestic cycles of violence."),
        ("Meridian", "Alice Walker", "9780156586603", "Meridian Hill commits her life to the Civil Rights Movement in the American South during the 1960s."),
        ("Daughter of Fortune", "Isabel Allende", "9780061099144", "Eliza Sommers follows her lover from Valparaiso to the 1849 California Gold Rush disguised as a man."),
        ("Portrait in Sepia", "Isabel Allende", "9780066214092", "Aurora del Valle uncovers her family roots in late 19th-century San Francisco and Chile."),
        ("The House of the Spirits", "Isabel Allende", "9780593466827", "The Trueba family experiences love, magic, and political revolution in an unnamed South American nation."),
        ("Eva Luna", "Isabel Allende", "9780060953317", "An orphaned girl with a talent for storytelling navigates Latin American political turmoil."),
        ("The Stories of Eva Luna", "Isabel Allende", "9780060953324", "Twenty-three enchantingly woven short stories narrated by Eva Luna to her lover Rolf Carlé."),
        ("Paula", "Isabel Allende", "9780060927219", "Allende's poignant memoir written at the bedside of her comatose twenty-eight-year-old daughter."),
        ("The Sum of Our Days", "Isabel Allende", "9780061550676", "A candid continuation of Allende's family life following the tragedy of Paula's passing."),
        ("My Invented Country", "Isabel Allende", "9780060545666", "A personal nostalgia memoir exploring Chilean culture, exile, and national identity.")
    ],
    "Mystery": [
        ("In the Woods", "Tana French", "9780143113492", "Detective Rob Ryan investigates a twelve-year-old girl's murder in the same woods where his childhood friends disappeared."),
        ("The Likeness", "Tana French", "9780143115625", "Detective Cassie Maddox goes undercover as a murdered woman who looks identical to her."),
        ("Faithful Place", "Tana French", "9780143119494", "Frank Mackey returns to his old Dublin neighborhood when his childhood girlfriend's suitcase is found 22 years later."),
        ("Broken Harbor", "Tana French", "9780143123309", "Mick Scorcher investigates a brutal double murder in an abandoned ghost estate near Dublin."),
        ("The Secret Place", "Tana French", "9780143127680", "Stephen Moran and Antoinette Conway investigate a murder at a prestigious girls' boarding school."),
        ("The Trespasser", "Tana French", "9780143129578", "Conway and Moran handle what looks like a simple domestic murder that conceals department corruption."),
        ("The Wych Elm", "Tana French", "9780735224643", "Toby retreats to his family's ancestral home after a burglary, discovering a skull in the garden tree."),
        ("The Searcher", "Tana French", "9780735224674", "Retired Chicago cop Cal Hooper moves to rural Ireland and gets pulled into searching for a missing boy."),
        ("The Hunter", "Tana French", "9780593493434", "Cal Hooper defends his quiet Irish life when a former resident returns with a gold-hunting scheme."),
        ("Still Life", "Louise Penny", "9780312541538", "Chief Inspector Armand Gamache investigates the mysterious hunting arrow death of Jane Neal in Three Pines."),
        ("A Fatal Grace", "Louise Penny", "9780312541545", "Gamache investigates the electrocution of unliked CC de Poitiers on a frozen lake in Three Pines."),
        ("The Cruelest Month", "Louise Penny", "9780312541552", "A easter séance at the Old Hadley House turns fatal when a town resident dies of fright."),
        ("A Rule Against Murder", "Louise Penny", "9780312541569", "Gamache's anniversary at Manoir Bellechateau is disrupted when an aristocratic family member is crushed by a statue."),
        ("The Brutal Telling", "Louise Penny", "9780312541576", "An unknown hermit is found murdered inside Olivier's bistro in Three Pines."),
        ("Bury Your Dead", "Louise Penny", "9780312626907", "Gamache investigates an archaeologist's death in Quebec City while recovering from a tragic police raid."),
        ("A Trick of the Light", "Louise Penny", "9780312626914", "An art critic is murdered in Clara Morrow's garden after a career-defining exhibition party."),
        ("The Beautiful Mystery", "Louise Penny", "9780312626921", "Gamache and Beauvoir enter a secluded monastery in remote Quebec where a choir director was murdered."),
        ("How the Light Gets In", "Louise Penny", "9780312626938", "Gamache faces dangerous political corruption within the Sûreté while solving a famous woman's disappearance."),
        ("The Long Way Home", "Louise Penny", "9781250022066", "Gamache retires to Three Pines but helps Clara find her missing artist husband Peter."),
        ("The Nature of the Beast", "Louise Penny", "9781250022080", "A nine-year-old boy known for tall tales is found murdered after discovering a giant weapon in the forest."),
        ("A Great Reckoning", "Louise Penny", "9781250022103", "Gamache becomes head of the police academy and discovers an old map hidden inside a bistro wall."),
        ("Glass Houses", "Louise Penny", "9781250066190", "A mysterious figure in a dark cobwebbed cloak appears on the village green of Three Pines."),
        ("Kingdom of the Blind", "Louise Penny", "9781250066213", "Gamache is named executor of a bizarre stranger's will while suspended from the force."),
        ("A Better Man", "Louise Penny", "9781250066237", "Gamache returns as head of homicide during devastating spring floods and a young pregnant woman's murder."),
        ("All the Devils Are Here", "Louise Penny", "9781250145239", "The Gamache family in Paris investigates an attack on Armand's godfather, billionaire Stephen Horowitz."),
        ("The Madness of Crowds", "Louise Penny", "9781250145260", "Gamache provides security for a controversial visiting professor advocating extreme eugenics."),
        ("A World of Curiosities", "Louise Penny", "9781250145291", "Young siblings return to Quebec years after Gamache solved their mother's murder."),
        ("The Grey Wolf", "Louise Penny", "9781250341778", "Gamache uncovers a dangerous bioweapon conspiracy threatening Canadian infrastructure."),
        ("Knots and Crosses", "Ian Rankin", "9780312951719", "Inspector John Rebus investigates child abductions in Edinburgh while receiving cryptic knot-tied letters."),
        ("Hide and Seek", "Ian Rankin", "9780312953287", "Rebus investigates a heroin addict's death in an abandoned tenement linked to wealthy underground clubs."),
        ("Tooth and Nail", "Ian Rankin", "9780312955021", "Rebus travels to London to assist Scotland Yard in hunting a brutal serial killer called the Wolfman."),
        ("Strip Jack", "Ian Rankin", "9780312957131", "A respected MP is caught in a police raid on a brothel, followed by his wife's disappearance."),
        ("The Black Book", "Ian Rankin", "9780312958770", "Rebus uses his hospitalized colleague's notebook to reopen a cold case five-star hotel fire.")
    ],
    "Thriller": [
        ("Blindsighted", "Karin Slaughter", "9780062429087", "Pediatrician and coroner Sara Linton investigates a brutal serial rapist in Heartsdale, Georgia."),
        ("Kisscut", "Karin Slaughter", "9780062429094", "Sara Linton and Police Chief Jeffrey Tolliver uncover a child exploitation ring following a teenage shooting."),
        ("A Faint Cold Fear", "Karin Slaughter", "9780062429100", "A series of apparent student suicides at Grant Technical College conceals a murder spree."),
        ("Indelible", "Karin Slaughter", "9780062429117", "A hostage crisis at the police station forces Sara to relive Jeffrey's dark past in Alabama."),
        ("Faithless", "Karin Slaughter", "9780062429124", "A young woman is buried alive in the woods, leading investigators to a sinister religious commune."),
        ("Beyond Reach", "Karin Slaughter", "9780062429131", "Detective Lena Adams is arrested for murder in her home county, forcing Sara and Jeffrey to investigate."),
        ("Fractured", "Karin Slaughter", "9780061240829", "Special Agent Will Trent investigates a mansion murder where a mother killed her daughter's attacker."),
        ("Undone", "Karin Slaughter", "9780061240850", "Will Trent and Sara Linton team up when a woman is hit by a car fleeing an underground torture chamber."),
        ("Broken", "Karin Slaughter", "9780061763076", "A woman's body found in Lake Grant brings Sara Linton back to Grant County alongside Will Trent."),
        ("Fallen", "Karin Slaughter", "9780061763106", "Faith Mitchell's mother is taken hostage inside her own home, exposing corruption in the GBI."),
        ("Criminal", "Karin Slaughter", "9780062102805", "Will Trent investigates a student's disappearance that mirrors a 1975 case handled by his boss Amanda Wagner."),
        ("Unseen", "Karin Slaughter", "9780062102843", "Will Trent goes undercover as a gritty ex-con in Macon while Sara Linton treats an injured officer."),
        ("Cop Town", "Karin Slaughter", "9780345547613", "Two female officers fight sexism and crime in 1974 Atlanta while hunting a cop killer."),
        ("Pretty Girls", "Karin Slaughter", "9780062429056", "Two estranged sisters uncover shocking footage explaining their third sister's disappearance twenty years ago."),
        ("The Good Daughter", "Karin Slaughter", "9780062430205", "Twenty-eight years after a tragic home invasion, lawyer Charlie Quinn defends a student accused of school shooting."),
        ("Pieces of Her", "Karin Slaughter", "9780062430267", "Andrea Oliver witnesses her mother Laura calmly eliminate a shooter, exposing Laura's hidden past."),
        ("False Witness", "Karin Slaughter", "9780062858092", "Defense attorney Leigh Collier is forced to defend a wealthy man who knows her childhood secrets."),
        ("Girl, Forgotten", "Karin Slaughter", "9780062858184", "US Marshal Andrea Oliver travels to Longbill Beach to solve a 1982 cold case high school murder."),
        ("After That Night", "Karin Slaughter", "9780063303669", "Sara Linton's past trauma resurfaces fifteen years later when an ER patient arrives with identical injuries."),
        ("The Kill Artist", "Daniel Silva", "9780061015090", "Restorer Gabriel Allon is called back into Israeli intelligence to eliminate a Palestinian terrorist."),
        ("The English Assassin", "Daniel Silva", "9780399148590", "Gabriel Allon investigates an art collector's murder in Zurich, uncovering Nazi-looted artwork sales."),
        ("The Confessor", "Daniel Silva", "9780399149726", "Gabriel investigates a scholar's murder in Munich tied to Vatican secrecy during the Holocaust."),
        ("A Death in Vienna", "Daniel Silva", "9780399151439", "Gabriel investigates a Holocaust survivor's bombing in Vienna that connects to his own mother's tormentor."),
        ("Prince of Fire", "Daniel Silva", "9780399152436", "A bombing at the Israeli embassy in Rome brings Gabriel Allon into combat with an arch-terrorist."),
        ("The Messenger", "Daniel Silva", "9780399153355", "Gabriel Allon infiltrates Al-Qaeda terror networks plotting an attack on the Vatican."),
        ("The Secret Servant", "Daniel Silva", "9780399154225", "Gabriel pursues an Islamic extremist group in Amsterdam after an ambassador's daughter is kidnapped."),
        ("Moscow Rules", "Daniel Silva", "9780399155017", "Gabriel travels to Russia to stop an arms dealer selling deadly missiles to terrorist groups."),
        ("The Defector", "Daniel Silva", "9780399155680", "Gabriel hunts an oligarch ex-KGB colonel who kidnapped a Russian defector in London."),
        ("The Rembrandt Affair", "Daniel Silva", "9780399156588", "Gabriel searches for a stolen Rembrandt painting, tracking funds to Iran's nuclear program."),
        ("The Portrait", "Daniel Silva", "9780451216311", "Gabriel poses as an art restorer in Venice to uncover the truth behind an assassin's employer."),
        ("The Mark of the Assassin", "Daniel Silva", "9780061013447", "CIA agent Michael Osbourne investigates a commercial airliner shootdown linked to a professional hitman."),
        ("The Unlikely Spy", "Daniel Silva", "9780399142253", "Professor Alfred Vicary uncovers a Nazi sleeper agent in WWII London threatening Operation Overlord."),
        ("The Fallen Angel", "Daniel Silva", "9780399158223", "Gabriel Allon investigates a woman's fatal fall inside St. Peter's Basilica at the Pope's request.")
    ],
    "Romance": [
        ("Secrets of a Summer Night", "Lisa Kleypas", "9780060562510", "Annabelle Peyton seeks a wealthy husband but falls for arrogant self-made industrialist Simon Hunt."),
        ("It Happened One Autumn", "Lisa Kleypas", "9780060562527", "Headstrong American heiress Lillian Bowman clashes with stern, aristocratic Marcus, Earl of Westcliff."),
        ("Devil in Winter", "Lisa Kleypas", "9780060562534", "Shy Evangeline Jenner proposes a marriage of convenience to notorious rake Sebastian, Lord St. Vincent."),
        ("Scandal in Spring", "Lisa Kleypas", "9780060562541", "Daisy Bowman is ordered to find a husband or marry her father's stern employee Matthew Swift."),
        ("A Wallflower Christmas", "Lisa Kleypas", "9780061734281", "Rafe Bowman arrives in London for an arranged marriage but finds himself captivated by her companion Hannah."),
        ("Mine Till Midnight", "Lisa Kleypas", "9780312949808", "Amelia Hathaway takes care of her eccentric family with the help of enigmatic Roma hotel owner Cam Rohan."),
        ("Seduce Me at Sunrise", "Lisa Kleypas", "9780312949815", "Kev Merripen hides his love for frail Win Hathaway due to his dark past."),
        ("Tempt Me at Twilight", "Lisa Kleypas", "9780312949822", "Poppy Hathaway agrees to marry ruthless hotelier Harry Rutledge under deceptive circumstances."),
        ("Married by Morning", "Lisa Kleypas", "9780312949839", "Governess Catherine Marks and notorious playboy Leo Hathaway bicker while shielding her identity."),
        ("Love in the Afternoon", "Lisa Kleypas", "9780312605865", "Beatrix Hathaway writes secret letters to Captain Christopher Phelan while he is fighting in Crimea."),
        ("Cold-Hearted Rake", "Lisa Kleypas", "9780062371829", "Devon Ravenel inherits an earldom and clashes with Kathleen, his late cousin's young widow."),
        ("Marrying Winterborne", "Lisa Kleypas", "9780062371850", "Lady Helen Ravenel navigates society rules to marry ambitious department store tycoon Rhys Winterborne."),
        ("Devil in Spring", "Lisa Kleypas", "9780062371881", "Lady Pandora Ravenel is compromised into marrying Gabriel, Lord St. Vincent, Sebastian's son."),
        ("Hello Stranger", "Lisa Kleypas", "9780062371911", "Dr. Garrett Gibson, London's only female physician, engages in passion with secret agent Ethan Ransom."),
        ("Devil's Daughter", "Lisa Kleypas", "9780062371942", "Widowed Phoebe, Lady Clare, meets Westcliff's estate manager Keir MacRae without realizing his family past."),
        ("Chasing Cassandra", "Lisa Kleypas", "9780062371973", "Railway magnate Tom Severin decides to marry Lady Cassandra Ravenel despite claims of lacking emotions."),
        ("Devil in Disguise", "Lisa Kleypas", "9780062956279", "Scottish distillery manager Keir MacRae gets saved from assassination by whisky shop owner Merritt Sterling."),
        ("The Duke and I", "Julia Quinn", "9780062353597", "Daphne Bridgerton and Simon Basset fake a courtship to fool society matrons, catching real feelings."),
        ("The Viscount Who Loved Me", "Julia Quinn", "9780062353634", "Anthony Bridgerton decides to marry Edwina Sheffield but falls head over heels for her protective sister Kate."),
        ("An Offer From a Gentleman", "Julia Quinn", "9780062353641", "Benedict Bridgerton falls for a mysterious masked woman at a ball who is secretly housemaid Sophie Beckett."),
        ("Romancing Mister Bridgerton", "Julia Quinn", "9780062353658", "Penelope Featherington's secret love for Colin Bridgerton is tested when Lady Whistledown's identity is hunted."),
        ("To Sir Phillip, With Love", "Julia Quinn", "9780062353665", "Eloise Bridgerton corresponds with widowed Sir Phillip Crane and unexpectedly runs away to meet him."),
        ("When He Was Wicked", "Julia Quinn", "9780062353672", "Michael Stirling falls for Francesca Bridgerton, the wife of his cousin, keeping his distance until fate intervenes."),
        ("It's In His Kiss", "Julia Quinn", "9780062353689", "Hyacinth Bridgerton helps Gareth St. Clair translate an Italian diary to unlock his family inheritance."),
        ("On the Way to the Wedding", "Julia Quinn", "9780062353696", "Gregory Bridgerton helps Lucy Abernathy woo her friend, only to realize he loves Lucy instead."),
        ("The Bridgertons: Happily Ever After", "Julia Quinn", "9780062283085", "Second epilogues detailing the long-term futures of all eight Bridgerton siblings."),
        ("Because of Miss Bridgerton", "Julia Quinn", "9780062424082", "Billie Bridgerton cannot stand her arrogant neighbor George Rokesby until a rescue changes everything."),
        ("The Girl with the Make-Believe Husband", "Julia Quinn", "9780062424112", "Cecilia Harcourt claims wounded officer Edward Rokesby is her husband to care for him in New York."),
        ("The Other Miss Bridgerton", "Julia Quinn", "9780062424143", "Poppy Bridgerton is kidnapped by privateer Captain Andrew Rokesby on the high seas."),
        ("First Comes Scandal", "Julia Quinn", "9780062424174", "Nicholas Rokesby marries family friend Georgiana Bridgerton to save her social standing after a kidnapping."),
        ("The Secrets of Sir Richard Kenworthy", "Julia Quinn", "9780062353603", "Sir Richard Kenworthy rushes to court Iris Smythe-Smith to hide a dark family secret."),
        ("The Sum of All Kisses", "Julia Quinn", "9780062072924", "Hugh Prentice and Lady Sarah Pleinsworth overcome past feuds while organizing a wedding."),
        ("Just Like Heaven", "Julia Quinn", "9780062072894", "Honoria Smythe-Smith's terrible violin playing is tolerated by Marcus Holroyd as he falls in love.")
    ],
    "Fantasy": [
        ("The Fifth Season", "N.K. Jemisin", "9780316229296", "Essun discovers her daughter has been kidnapped on the day a catastrophic tectonic rift begins ending the world."),
        ("The Obelisk Gate", "N.K. Jemisin", "9780316229265", "Essun learns to harness magic through giant floating obelisks as global atmosphere collapses."),
        ("The Stone Sky", "N.K. Jemisin", "9780316229241", "Essun and her daughter Nassun face off over whether to restore the moon or destroy the Stillness forever."),
        ("The Hundred Thousand Kingdoms", "N.K. Jemisin", "9780316043915", "Yeine Arneh is named heir to the celestial city of Sky, surrounded by captive enslaved gods."),
        ("The Broken Kingdoms", "N.K. Jemisin", "9780316043922", "Oree Shoth, a blind artist in Shadow, protects a fallen wounded god living among mortals."),
        ("The Kingdom of Gods", "N.K. Jemisin", "9780316043939", "Sieh, god of childhood, gets turned mortal and entangled in mortal imperial successions."),
        ("The Killing Moon", "N.K. Jemisin", "9780316087230", "Gatherer Ehiru harvests peace magic from dying dreamers in the ancient holy city of Gujaareh."),
        ("The Shadowed Sun", "N.K. Jemisin", "9780316087247", "Sunandi and Hanani fight a plague of madness threatening the desert kingdom."),
        ("The City We Became", "N.K. Jemisin", "9780316509848", "Five avatars representing New York City's five boroughs unite to fight an otherworldly cosmic horror."),
        ("The World We Make", "N.K. Jemisin", "9780316509893", "The NYC avatars defend their living city against a demagogue politician backed by cosmic evil."),
        ("Assassin's Apprentice", "Robin Hobb", "9780553573398", "Royal bastard Fitz is trained as a secret assassin for King Shrewd in the Six Duchies."),
        ("Royal Assassin", "Robin Hobb", "9780553573411", "Fitz uses his telepathic Wit bond with wolf Nighteyes to protect Prince Verity against Red-Ship Raiders."),
        ("Assassin's Quest", "Robin Hobb", "9780553575651", "Fitz journeys across mountain wastes to find Prince Verity and awaken the ancient Elderling dragons."),
        ("Ship of Magic", "Robin Hobb", "9780553575637", "Althea Vestrit fights to reclaim her sentient wizardwood liveship Vivacia from pirate Captain Kennit."),
        ("Mad Ship", "Robin Hobb", "9780553575644", "The Vestrit family restores the insane liveship Paragon to sail into pirate territory."),
        ("Ship of Destiny", "Robin Hobb", "9780553557459", "Althea and Brashen rescue Vivacia while discovering the tragic secret dragon origin of wizardwood."),
        ("Fool's Errand", "Robin Hobb", "9780553582444", "Fitz lives in quiet exile as Tom Badgerlock until the Fool returns requesting help finding Prince Dutiful."),
        ("Golden Fool", "Robin Hobb", "9780553582451", "Fitz serves as court assassin and Skill teacher while hiding his outlaw Wit magic bond."),
        ("Fool's Fate", "Robin Hobb", "9780553582468", "Fitz travels to Aslevjal island to slay the dragon Icefyre and fulfill the Fool's prophecies."),
        ("Dragon Keeper", "Robin Hobb", "9780061561641", "Thymara and keeper companions guide stunted, deformed hatchling dragons up the Rain Wild River."),
        ("Dragon Haven", "Robin Hobb", "9780061561658", "The Rain Wild keepers and dragons search for Kelsingra, the lost ancient city of Elderlings."),
        ("City of Dragons", "Robin Hobb", "9780061561665", "Dragons achieve full flight near Kelsingra while human traders plot to harvest dragon blood."),
        ("Blood of Dragons", "Robin Hobb", "9780061561672", "The dragons defend Kelsingra against invader fleets, reclaiming their divine place in the world."),
        ("Fool's Assassin", "Robin Hobb", "9780553390735", "Fitz lives as a country gentleman at Withywoods until his home is attacked and his daughter Bee kidnapped."),
        ("Fool's Quest", "Robin Hobb", "9780553390766", "Fitz reveals his royal identity at Buckkeep and uses Skill portals to hunt his daughter's abductors."),
        ("Assassin's Fate", "Robin Hobb", "9780553390797", "Fitz, the Fool, and Nighteyes travel to Clerres to destroy the Servants and save Bee."),
        ("Tigana", "Robin Hobb & Guy Gavriel Kay", "9780451457769", "A band of rebels fight to restore the erased memory and name of their conquered province Tigana."),
        ("The Lions of Al-Rassan", "Guy Gavriel Kay", "9780060733490", "Physician Jehane, Moorish warrior Rodrigo, and poet Ammar navigate war in medieval Spain counterpart."),
        ("The Sarantine Mosaic", "Guy Gavriel Kay", "9780061051258", "Mosaicist Crispin travels to Sarantium to construct a grand dome cathedral for Emperor Valerius."),
        ("Under Heaven", "Guy Gavriel Kay", "9780451463890", "Shen Tai receives a gift of 250 heavenly horses, entangling him in Tang Dynasty court assassination plots."),
        ("River of Stars", "Guy Gavriel Kay", "9780451464972", "Ren Daiyan leads soldier bands to defend the Song Dynasty kingdom from northern invaders."),
        ("Children of Earth and Sky", "Guy Gavriel Kay", "9780451472908", "Five strangers cross paths in Renaissance Europe counterpart during war between Osmanli empire and holy city."),
        ("A Brightness Long Ago", "Guy Gavriel Kay", "9780441003464", "Guidambo, Danio, and Adria navigate mercenary captain rivalries in 15th-century Italy counterpart.")
    ],
    "Science Fiction": [
        ("The Left Hand of Darkness", "Ursula K. Le Guin", "9780441478125", "Genly Ai is sent as envoy to planet Gethen, where inhabitants possess no fixed gender."),
        ("The Dispossessed", "Ursula K. Le Guin", "9780061054884", "Physicist Shevek travels between anarchist moon Anarres and capitalist mother planet Urras."),
        ("The Lathe of Heaven", "Ursula K. Le Guin", "9781476732046", "George Orr's dreams literally alter reality, and his ambitious psychiatrist manipulates them."),
        ("A Wizard of Earthsea", "Ursula K. Le Guin", "9780547773742", "Young Ged releases a shadow beast in pride and journeys across the archipelago to conquer it."),
        ("The Tombs of Atuan", "Ursula K. Le Guin", "9780547773735", "Tenar is dedicated as high priestess to the Nameless Ones in underground labyrinth tombs until Ged arrives."),
        ("The Farthest Shore", "Ursula K. Le Guin", "9780547773728", "Archmage Ged and Prince Arren travel to the edge of Earthsea to stop magic from leaking out of the world."),
        ("Tehanu", "Ursula K. Le Guin", "9780547773704", "Tenar raises abused child Therru in rural Gont while Ged copes with lost power."),
        ("The Other Wind", "Ursula K. Le Guin", "9780156027328", "Sorcerer Alder seeks Ged's counsel regarding dreams where the dead reach across the stone wall."),
        ("Four Ways to Forgiveness", "Ursula K. Le Guin", "9780061054013", "Four novellas exploring slavery, freedom, and revolution on planets Werel and Yeowe."),
        ("The Telling", "Ursula K. Le Guin", "9780156012867", "Sutty studies suppressed oral storytelling culture on corporation-dominated planet Aka."),
        ("Snow Crash", "Neal Stephenson", "9780553380958", "Pizza delivery driver Hiro Protagonist and skateboard courier Y.T. fight a digital virus named Snow Crash."),
        ("The Diamond Age", "Neal Stephenson", "9780553380965", "Young Nell receives an interactive nanotechnology book designed to foster subversive creative thinking."),
        ("Cryptonomicon", "Neal Stephenson", "9780060512804", "WWII codebreakers Lawrence Waterhouse and Alan Turing intersect with 1990s crypto-currency entrepreneurs."),
        ("Quicksilver", "Neal Stephenson", "9780060833169", "Daniel Waterhouse and vagabond Jack Shaftoe navigate 17th-century scientific revolution and alchemy."),
        ("The Confusion", "Neal Stephenson", "9780060833176", "Jack Shaftoe captures a gold galley while Eliza manipulates royal courts in Versailles."),
        ("The System of the World", "Neal Stephenson", "9780060833183", "Isaac Newton and Gottfried Leibniz dispute calculus invention amidst London currency counter-feiting."),
        ("Anathem", "Neal Stephenson", "9780061474101", "Erasmas, a mathematician monk in a secluded cloister, discovers an alien starship orbiting his planet."),
        ("Reamde", "Neal Stephenson", "9780062191496", "A ransomware virus in an MMORPG triggers a global chase involving Russian mobsters and terrorists."),
        ("Seveneves", "Neal Stephenson", "9780062334510", "Earth's moon explodes without warning, forcing humanity to build a cloud ark in space before firestorms."),
        ("Termination Shock", "Neal Stephenson", "9780063028050", "A Texas oil billionaire builds a massive gun to inject sulfur into the stratosphere to combat climate change."),
        ("Neuromancer", "William Gibson", "9780441569564", "Washed-up hacker Case is hired by mysterious Armitage to pull off an impossible heist against an AI."),
        ("Count Zero", "William Gibson", "9780441117734", "Corporate mercenary Turner, computer kid Bobby, and art dealer Marly investigate weird bio-chip entities."),
        ("Mona Lisa Overdrive", "William Gibson", "9780441535491", "Mona, Kumiko, and Angie's paths converge in the cyberspace matrix as powerful AI gods evolve."),
        ("Virtual Light", "William Gibson", "9780553566062", "Bicycle messenger Chevette steals high-tech sunglasses containing blueprints for rebuilding San Francisco."),
        ("Idoru", "William Gibson", "9780425158449", "Colin Laney uses data intuition to investigate rock star Rez's marriage to virtual holographic idol Rei Toei."),
        ("All Tomorrow's Parties", "William Gibson", "9780425175705", "Laney foresees a global societal shift centered on a San Francisco convenience store."),
        ("Pattern Recognition", "William Gibson", "9780425192931", "Coolhunter Cayce Pollard tracks down the anonymous creator of mysterious viral film clips."),
        ("Spook Country", "William Gibson", "9780425222010", "Former singer Hollis Henry investigates GPS-located locative art and illicit cargo ships."),
        ("Zero History", "William Gibson", "9780425240779", "Hollis Henry and Milgrim track down secret military clothing designs for eccentric brand owner Bigend."),
        ("The Peripheral", "William Gibson", "9780425276235", "Flynne Fisher tests a VR game that is actually a quantum link to 22nd-century post-apocalyptic London."),
        ("Agency", "William Gibson", "9781101986936", "Verity Jane tests a self-aware AI named Eunice in an alternate 2017 timeline without Brexit."),
        ("Old Man's War", "John Scalzi", "9780765315243", "75-year-old John Perry enlists in the Colonial Defense Force, gaining a genetically engineered green body."),
        ("The Ghost Brigades", "John Scalzi", "9780765354068", "Jane Sagan commands special forces troops cloned from dead humans to fight alien alliances.")
    ],
    "Horror": [
        ("The Books of Blood", "Clive Barker", "9780425165584", "Collection of visceral horror tales written on the skin of a fake psychic messenger."),
        ("The Damnation Game", "Clive Barker", "9780445204416", "Bodyguard Marty Strauss protects billionaire Joseph Whitehead from an immortal Faustian gambler named Mamoulian."),
        ("The Hellbound Heart", "Clive Barker", "9780061452086", "Hedonist Frank Cotton opens Lemarchand's puzzle box, summoning sadomasochistic Cenobites led by Pinhead."),
        ("Weaveworld", "Clive Barker", "9780060749491", "Cal Mooney discovers a magical carpet containing the SeErrorKind world of the magical Kindred."),
        ("Cabal", "Clive Barker", "9780061452093", "Boone searches for Midian, an underground city of monster outcasts, becoming its defender."),
        ("The Great and Secret Show", "Clive Barker", "9780060743994", "Fletcher and Jaffe discover the Quiddity ocean of human consciousness, waging a cosmic war in Palomo Grove."),
        ("Imajica", "Clive Barker", "9780060937263", "Gentle, Judith, and assassin Pie 'oh' Pah travel across five parallel dominions to reconcile Earth with heaven."),
        ("Thief of Always", "Clive Barker", "9780060572419", "Ten-year-old Harvey Swick enters the Holiday House where seasons change daily, hiding a soul-eating monster."),
        ("Everville", "Clive Barker", "9780061054082", "The portal to Quiddity opens in an Oregon town, triggering an invasion of interdimensional creatures."),
        ("Sacrament", "Clive Barker", "9780060179465", "Wildlife photographer Will Rabjohns wakes from a bear attack coma to confront extinct magical species."),
        ("Coldheart Canyon", "Clive Barker", "9780061031342", "Aging movie star Will Dempsey retreats to a Hollywood mansion featuring a tile room containing historical ghosts."),
        ("Mister B. Gone", "Clive Barker", "9780061432850", "Demon Jakabok Botch speaks directly to the reader, begging them to burn the book containing his soul."),
        ("The Scarlet Gospels", "Clive Barker", "9780312625894", "Detective Harry D'Amour confronts Pinhead as the Hell Priest attempts to overthrow Satan."),
        ("The Doll Who Ate His Mother", "Ramsey Campbell", "9780812516709", "Clare discovers her brother's killer is a cannibalistic man who lived in subterranean Liverpool."),
        ("The Face That Must Die", "Ramsey Campbell", "9780812516716", "Paranoid homophobe Horridge embarks on a murderous vigilante campaign in Liverpool believing he spots a killer."),
        ("The Parasite", "Ramsey Campbell", "9780812516723", "Rose is drawn into an astral-projecting occult cult from her childhood that parasitizes her mind."),
        ("The Nameless", "Ramsey Campbell", "9780812516730", "Barbara receives phone calls from her daughter who was kidnapped nine years ago by a cruel cult."),
        ("Incarnate", "Ramsey Campbell", "9780812516747", "Five sleep research volunteers find their nightmares manifesting in physical reality."),
        ("The Hungry Moon", "Ramsey Campbell", "9780812516754", "An American televangelist drives an ancient pagan entity out of its cave beneath a Peak District village."),
        ("The Influence", "Ramsey Campbell", "9780812516761", "Deceased matriarch Queenie's ghost attempts to possess young Rowan in a seaside town."),
        ("Ancient Images", "Ramsey Campbell", "9780812516778", "Film editor Sandy searches for a lost 1930s Karloff and Lugosi horror film that causes deaths."),
        ("Midnight Sun", "Ramsey Campbell", "9780812516785", "Writer Ben Sterling moves to his wife's ancestral Swedish village, succumbing to icy cosmic dread."),
        ("Needing Ghosts", "Ramsey Campbell", "9780812516792", "Crime author Edward wake up with memory loss in a nightmare surreal version of his home town."),
        ("The Long Lost", "Ramsey Campbell", "9780812516808", "Gwen brings an elderly relative home from Wales who subtly destroys her family through malevolent influence."),
        ("The One Safe Place", "Ramsey Campbell", "9780812516815", "An urban family moves to a rural cottage only to be terrorized by a local criminal clan."),
        ("The House on Nazareth Hill", "Ramsey Campbell", "9780812516822", "Amy moves into an apartment in a former asylum where her father's paranoia unlocks hauntings."),
        ("Silent Children", "Ramsey Campbell", "9780812516839", "A mother hunts down a child-kidnapping serial killer hiding inside abandoned suburban housing."),
        ("Pact of the Fathers", "Ramsey Campbell", "9780812516846", "Dani investigates her estate agent father's sudden death, uncovering an ancient church brotherhood."),
        ("The Grin of the Dark", "Ramsey Campbell", "9780812516853", "Film historian Simon researches silent film comedian Tubby Thackeray, descending into laughing madness."),
        ("Thieving Bear", "Ramsey Campbell", "9780812516860", "A remote park warden confronts a shape-shifting entity hiding among tourist campsites."),
        ("The Wise Friend", "Ramsey Campbell", "9781789094053", "Patrick investigates his late artist aunt's journals, locating folk magic sites across England."),
        ("Fell Stones", "Ramsey Campbell", "9781789099867", "Paul returns to his adoptive home village where a stone circle alters his musical family's minds."),
        ("Ghost Story", "Peter Straub", "9780143105787", "The Chowder Society elderly men are haunted by a nightmare mistake from their youth in Milburn, NY.")
    ],
    "Self-Help": [
        ("Atomic Habits", "James Clear", "9780735211292", "An easy and proven way to build good habits and break bad ones using tiny 1% changes."),
        ("The Power of Habit", "Charles Duhigg", "9780812981605", "Why we do what we do in life and business, exploring the cue-routine-reward habit loop."),
        ("Smarter Faster Better", "Charles Duhigg", "9780812983593", "Eight key productivity concepts behind transforming personal and organizational performance."),
        ("Supercommunicators", "Charles Duhigg", "9780593243916", "How to unlock the secret language of connection in conversations."),
        ("Quiet", "Susan Cain", "9780307352156", "The power of introverts in a world that can't stop talking."),
        ("Bittersweet", "Susan Cain", "9780451499783", "How sorrow and longing make us whole and transform pain into creativity."),
        ("The Gifts of Imperfection", "Brené Brown", "9781592858491", "Let go of who you think you're supposed to be and embrace who you are."),
        ("Daring Greatly", "Brené Brown", "9781594631511", "How the courage to be vulnerable transforms the way we live, love, parent, and lead."),
        ("Rising Strong", "Brené Brown", "9780812985801", "The reckoning, the rumble, and the revolution of getting back up after falling."),
        ("Braving the Wilderness", "Brené Brown", "9780812995848", "The quest for true belonging and the courage to stand alone."),
        ("Dare to Lead", "Brené Brown", "9780399592522", "Brave work, tough conversations, and whole hearts in organizational leadership."),
        ("Atlas of the Heart", "Brené Brown", "9781984854032", "Mapping meaningful connection and the language of human experience through 87 emotions."),
        ("Mindset: The New Psychology of Success", "Carol S. Dweck", "9780345472328", "How we can learn to fulfill our potential through fixed versus growth mindsets."),
        ("Grit: The Power of Passion and Perseverance", "Angela Duckworth", "9781501111105", "Why passion and resilience matter more than talent for long-term success."),
        ("Deep Work", "Cal Newport", "9781455586691", "Rules for focused success in a distracted world."),
        ("So Good They Can't Ignore You", "Cal Newport", "9781455509126", "Why skills trump passion in the quest for work you love."),
        ("Digital Minimalism", "Cal Newport", "9780525536512", "Choosing a focused life in a noisy digital world."),
        ("A World Without Email", "Cal Newport", "9780525536550", "Reimagining work in an age of communication overload."),
        ("Slow Productivity", "Cal Newport", "9780593544853", "The lost art of accomplishment without burnout."),
        ("The Subtle Art of Not Giving a F*ck", "Mark Manson", "9780062457714", "A counterintuitive approach to living a good life by prioritizing core values."),
        ("Everything is F*cked", "Mark Manson", "9780062888433", "A book about hope, examining modern psychological angst and existential purpose."),
        ("Four Thousand Weeks", "Oliver Burkeman", "9780374159122", "Time management for mortals acknowledging our brief four-thousand-week lifespan."),
        ("The Antidote", "Oliver Burkeman", "9780865479418", "Happiness for people who can't stand positive thinking, exploring embracing uncertainty."),
        ("The Happiness Project", "Gretchen Rubin", "9780061583261", "One woman's year-long test of happiness research and ancient wisdom."),
        ("Better Than Before", "Gretchen Rubin", "9780385348614", "Mastering the habits of our everyday lives through self-knowledge."),
        ("The Four Tendencies", "Gretchen Rubin", "9781524760915", "Personality profiles dividing people into Upholders, Questioners, Obligers, and Rebels."),
        ("The Big Leap", "Gay Hendricks", "9780061735363", "Conquer your hidden fear and take life to the next level by overcoming Upper Limit Problems."),
        ("The ONE Thing", "Gary Keller & Jay Papasan", "9781885167774", "The surprisingly simple truth behind extraordinary results focusing on single priorities."),
        ("Getting Things Done", "David Allen", "9780143126560", "The art of stress-free productivity organizing workflow into trusted systems."),
        ("The 4-Hour Workweek", "Timothy Ferriss", "9780307465351", "Escape 9-to-5, live anywhere, and join the new rich through lifestyle design."),
        ("The 4-Hour Body", "Timothy Ferriss", "9780307463630", "An uncommon guide to rapid fat-loss, incredible sex, and becoming superhuman."),
        ("Tools of Titans", "Timothy Ferriss", "9780544918290", "The tactics, routines, and habits of billionaires, icons, and world-class performers."),
        ("Tribe of Mentors", "Timothy Ferriss", "9781328918375", "Short life advice from the best in the world answering eleven key questions.")
    ],
    "Biography": [
        ("Steve Jobs", "Walter Isaacson", "9781451648539", "The exclusive biography of Apple co-founder Steve Jobs based on forty interviews."),
        ("Einstein: His Life and Universe", "Walter Isaacson", "9780743264747", "How Albert Einstein's imaginative mind worked from clerk to revolutionizing physics."),
        ("Benjamin Franklin: An American Life", "Walter Isaacson", "9780684807614", "The founding father who helped create the American national identity as printer and scientist."),
        ("Leonardo da Vinci", "Walter Isaacson", "9781501139154", "How Leonardo linked art to science, optics, anatomy, and engineering."),
        ("The Innovators", "Walter Isaacson", "9781476708690", "How a group of hackers, geniuses, and geeks created the digital revolution."),
        ("The Code Breaker", "Walter Isaacson", "9781982115852", "Jennifer Doudna, gene editing, and the future of the human species through CRISPR."),
        ("Elon Musk", "Walter Isaacson", "9781982181284", "The intimate story of the controversial innovator behind SpaceX, Tesla, and Neuralink."),
        ("Kissinger", "Walter Isaacson", "9780671663230", "A comprehensive study of Henry Kissinger's balance of power diplomacy and realpolitik."),
        ("Alexander Hamilton", "Walter Isaacson & Ron Chernow", "9780143034759", "The orphan who built the financial system of the United States and died in a tragic duel."),
        ("Washington: A Life", "Ron Chernow", "9780143119968", "A landmark portrait of George Washington as general and president."),
        ("Grant", "Ron Chernow", "9780143110637", "Ulysses S. Grant's journey from quiet clerk to Civil War hero and president."),
        ("Titan: The Life of John D. Rockefeller, Sr.", "Ron Chernow", "9781400077304", "The story of America's first billionaire and Standard Oil monopoly founder."),
        ("The House of Morgan", "Ron Chernow", "9780802144652", "An epic history of the J.P. Morgan banking empire across two centuries."),
        ("The Warburgs", "Ron Chernow", "9780679745198", "The twentieth-century story of a remarkable German-Jewish banking family."),
        ("The Power Broker", "Robert A. Caro", "9780394720241", "Robert Moses and the fall of New York City's public planning power."),
        ("The Path to Power", "Robert A. Caro", "9780679729457", "Volume One of The Years of Lyndon Johnson detailing his poverty-stricken Texas Hill Country youth."),
        ("Means of Ascent", "Robert A. Caro", "9780679733713", "Volume Two of Lyndon Johnson's biography covering his ruthless 1948 Senate campaign."),
        ("Master of the Senate", "Robert A. Caro", "9780394528367", "Volume Three detailing LBJ's decade dominating the United States Senate."),
        ("The Passage of Power", "Robert A. Caro", "9780375713255", "Volume Four following LBJ's vice presidency, JFK's assassination, and civil rights push."),
        ("John Adams", "David McCullough", "9780684813639", "The life of the independent founding father, diplomat, and second US President."),
        ("Truman", "David McCullough", "9780684804057", "Harry S. Truman's journey from Missouri farm boy to president ordering atomic drop."),
        ("Mornings on Horseback", "David McCullough", "9780671447540", "The young Theodore Roosevelt growing up in a prominent family overcoming severe asthma."),
        ("The Wright Brothers", "David McCullough", "9781476728759", "How Wilbur and Orville Wright invented human flight in Kitty Hawk."),
        ("The Path Between the Seas", "David McCullough", "9780671244095", "The engineering epic building the Panama Canal from French failure to US opening."),
        ("The Great Bridge", "David McCullough", "9780671457112", "The construction of the Brooklyn Bridge led by John and Washington Roebling."),
        ("1776", "David McCullough", "9780743226714", "The military history of George Washington's continental army during the founding year."),
        ("Brave Companions", "David McCullough", "9780671792763", "Short portraits of exceptional historical figures including Alexander von Humboldt and Louis Agassiz."),
        ("Churchill: A Life", "Martin Gilbert", "9780805023961", "The single-volume definitive biography of Winston Churchill by his official biographer."),
        ("Frida: A Biography of Frida Kahlo", "Hayden Herrera", "9780060085896", "The life, art, accident, and marriage of Mexican painter Frida Kahlo."),
        ("The Immortal Life of Henrietta Lacks", "Rebecca Skloot", "9781400052189", "How HeLa cells taken without permission transformed medical research and tissue ownership."),
        ("Shoe Dog", "Phil Knight", "9781501135927", "Nike founder Phil Knight tells the story of building his athletic footwear startup."),
        ("Steve Jobs: The Man Who Thought Different", "Karen Blumenthal", "9781255562098", "A concise biography of Steve Jobs highlighting design philosophy and entrepreneurial drive."),
        ("Open", "Andre Agassi", "9780307388407", "Tennis legend Andre Agassi reveals his complex love-hate relationship with tennis and success.")
    ],
    "History": [
        ("The Age of Revolution: 1789-1848", "Eric Hobsbawm", "9780679772538", "How the French Revolution and British Industrial Revolution transformed the world order."),
        ("The Age of Capital: 1848-1875", "Eric Hobsbawm", "9780679772545", "The global expansion of industrial capitalism and bourgeois society in the 19th century."),
        ("The Age of Empire: 1875-1914", "Eric Hobsbawm", "9780679772552", "The era of colonial rivalry leading up to the catastrophe of World War I."),
        ("The Age of Extremes: 1914-1991", "Eric Hobsbawm", "9780679730057", "A short history of the short twentieth century from WWI to the collapse of the Soviet Union."),
        ("The Guns of August", "Barbara W. Tuchman", "9780345386236", "The diplomatic miscalculations and military decisions of the opening month of World War I."),
        ("A Distant Mirror", "Barbara W. Tuchman", "9780345349576", "The calamitous 14th century viewed through nobleman Enguerrand de Coucy VII."),
        ("The Proud Tower", "Barbara W. Tuchman", "9780345405012", "A portrait of Western society in the twenty-five years before World War I."),
        ("The March of Folly", "Barbara W. Tuchman", "9780345308238", "How governments pursue policies contrary to their own interests from Troy to Vietnam."),
        ("The Zimmermann Telegram", "Barbara W. Tuchman", "9780345324252", "The secret German telegram proposing a Mexican alliance that drew America into WWI."),
        ("Practicing History", "Barbara W. Tuchman", "9780345303639", "Selected essays on writing history, current events, and historical crafts."),
        ("Stilwell and the American Experience in China", "Barbara W. Tuchman", "9780345315486", "General Joseph Stilwell's WWII military command in China and relations with Chiang Kai-shek."),
        ("Stalingrad", "Antony Beevor", "9780140284584", "The brutal 1942-1943 battle for Stalingrad that marked the turning point of WWII."),
        ("Berlin: The Downfall 1945", "Antony Beevor", "9780142001691", "The Red Army's final assault on Berlin and the collapse of Hitler's Third Reich."),
        ("D-Day: The Battle for Normandy", "Antony Beevor", "9780143118183", "The Allied invasion of Normandy on June 6, 1944 and fighting across hedgerows."),
        ("The Second World War", "Antony Beevor", "9780316023740", "A comprehensive single-volume global history of WWII operations and civilian suffering."),
        ("The Spanish Civil War", "Antony Beevor", "9780143037651", "The 1936-1939 conflict between Republican forces and General Franco's Nationalists."),
        ("Ardennes 1944", "Antony Beevor", "9780143109860", "Hitler's last gamble in the winter cold of the Battle of the Bulge."),
        ("Russia: Revolution and Civil War 1917-1921", "Antony Beevor", "9780593493861", "The violent collapse of Tsarist Russia and the rise of Bolshevik power."),
        ("The Rise and Fall of the Third Reich", "William L. Shirer", "9781451651683", "The definitive journalistic history of Nazi Germany from Hitler's birth to Nuremberg trials."),
        ("Berlin Diary", "William L. Shirer", "9780801870569", "Shirer's firsthand journal as a foreign correspondent in Berlin from 1934 to 1941."),
        ("The Collapse of the Third Republic", "William L. Shirer", "9780307389909", "An inquiry into the fall of France to German forces in 1940."),
        ("A People's Tragedy", "Orlando Figes", "9780140243642", "A sweeping history of the Russian Revolution from 1891 to the death of Lenin in 1924."),
        ("Natasha's Dance", "Orlando Figes", "9780312421953", "A cultural history of Russia examining literature, art, music, and folk traditions."),
        ("The Whisperers", "Orlando Figes", "9780312428037", "Private life in Stalin's Russia based on oral history interviews with terror survivors."),
        ("Crimean War", "Orlando Figes", "9780312674403", "The 1853-1856 war between Russia and Allied powers setting 19th-century geopolitics."),
        ("Revolutionary Russia: 1891-1991", "Orlando Figes", "9780805091311", "A hundred-year overview of Russian revolutionary ideology and state evolution."),
        ("The Europeans", "Orlando Figes", "9780525562504", "Three lives at the heart of 19th-century European cultural internationalism."),
        ("Postwar: A History of Europe Since 1945", "Tony Judt", "9780143037750", "The rebuilding of Europe after WWII through the collapse of communism and EU formation."),
        ("The Making of the English Working Class", "E.P. Thompson", "9780140136036", "The social history of English artisans and workers during the industrial revolution."),
        ("Sapiens: A Brief History of Humankind", "Yuval Noah Harari", "9780062316097", "How Homo sapiens evolved through cognitive, agricultural, and scientific revolutions."),
        ("Homo Deus", "Yuval Noah Harari", "9780062464316", "A brief history of tomorrow exploring artificial intelligence, biotechnology, and dataism."),
        ("21 Lessons for the 21st Century", "Yuval Noah Harari", "9780525512172", "Navigating disinformation, technological disruption, and nuclear threats today."),
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "The fates of human societies shaped by geographic and environmental endowments.")
    ],
    "Philosophy": [
        ("A History of Western Philosophy", "Bertrand Russell", "9780671201586", "Russell's celebrated survey of philosophy from Pre-Socratics to 20th-century logic."),
        ("The Problems of Philosophy", "Bertrand Russell", "9780192854230", "An introduction to epistemology, distinction between knowledge by acquaintance and description."),
        ("In Praise of Idleness", "Bertrand Russell", "9780415325066", "Essays advocating for reduced working hours, critical thinking, and social tolerance."),
        ("The Conquest of Happiness", "Bertrand Russell", "9780415325080", "Practical advice for eliminating self-absorption, envy, and fatigue to achieve joy."),
        ("Why I Am Not a Christian", "Bertrand Russell", "9780671205966", "Russell's classic debate and essays attacking religious dogma and theological arguments."),
        ("Thus Spoke Zarathustra", "Friedrich Nietzsche", "9780140441185", "Zarathustra proclaims the death of God, the Übermensch, and the eternal recurrence."),
        ("Beyond Good and Evil", "Friedrich Nietzsche", "9780140449235", "A critique of past philosophers' moral prejudices and proposal for free spirits."),
        ("On the Genealogy of Morals", "Friedrich Nietzsche", "9780679724629", "Three essays tracing master-slave morality, guilt, bad conscience, and ascetic ideals."),
        ("The Gay Science", "Friedrich Nietzsche", "9780679724636", "Poetic reflections containing the first announcement of God's death and love of fate."),
        ("The Birth of Tragedy", "Friedrich Nietzsche", "9780140433395", "The tension between Apollonian order and Dionysian chaos in Greek drama."),
        ("Human, All Too Human", "Friedrich Nietzsche", "9780521567046", "Aphroisms written during Nietzsche's free-thinking period analyzing psychology and art."),
        ("The Antichrist", "Friedrich Nietzsche", "9780140445145", "A fierce polemic against Christian morality and institutional religion."),
        ("Twilight of the Idols", "Friedrich Nietzsche", "9780140445145", "How to philosophize with a hammer, dissecting Western cultural idols."),
        ("Ecce Homo", "Friedrich Nietzsche", "9780140445152", "Nietzsche's autobiographical self-assessment of his works and intellectual growth."),
        ("Being and Nothingness", "Jean-Paul Sartre", "9780671867805", "Sartre's foundational text on existentialist ontology, bad faith, and radical human freedom."),
        ("Existentialism is a Humanism", "Jean-Paul Sartre", "9780300115468", "Sartre's public lecture defending existentialism against accusations of quietism."),
        ("Nausea", "Jean-Paul Sartre", "9780811220309", "Antoine Roquentin experiences overwhelming existential nausea realizing the contingency of existence."),
        ("No Exit", "Jean-Paul Sartre", "9780679725169", "Three deceased souls locked in a room discover that hell is other people."),
        ("The Age of Reason", "Jean-Paul Sartre", "9780679738954", "Philosophy professor Mathieu seeks money for his mistress's abortion during the 1930s."),
        ("The Words", "Jean-Paul Sartre", "9780679750505", "Sartre's witty autobiography of his early childhood reading and writing obsessions."),
        ("Critique of Dialectical Reason", "Jean-Paul Sartre", "9781844673896", "Sartre's attempt to synthesize existentialism with Marxist historical materialism."),
        ("The Myth of Sisyphus", "Albert Camus", "9780679733737", "Camus explores the absurd and concludes that one must imagine Sisyphus happy."),
        ("The Rebel", "Albert Camus", "9780679733713", "An essay on historical revolution, terrorism, and the metaphysical refusal of injustice."),
        ("The Stranger", "Albert Camus", "9780679720201", "Meursault shoots an Arab man on an Algiers beach and faces execution for emotional detachment."),
        ("The Plague", "Albert Camus", "9780679720218", "Dr. Bernard Rieux leads medical resistance against a bubonic plague quarantine in Oran."),
        ("The Fall", "Albert Camus", "9780679720225", "Former lawyer Jean-Baptiste Clamence delivers a confession in an Amsterdam bar."),
        ("Resistance, Rebellion, and Death", "Albert Camus", "9780679764014", "Collected political journalism and anti-death penalty essays."),
        ("The First Man", "Albert Camus", "9780679768166", "Camus's unfinished autobiographical novel of his working-class childhood in Algeria."),
        ("Meditations", "Marcus Aurelius", "9780812968255", "Personal Stoic journal entries on duty, mortality, and inner tranquility."),
        ("Enchiridion", "Epictetus", "9780486433592", "The Stoic manual of advice on focusing solely on what is within our control."),
        ("Letters from a Stoic", "Seneca", "9780140442106", "Epistolary wisdom on overcoming grief, wealth temptations, and anger."),
        ("Critique of Pure Reason", "Immanuel Kant", "9780521558303", "Kant's investigation into synthetic a priori knowledge and limits of human perception."),
        ("The Republic", "Plato", "9780140455113", "Socratic dialogue on justice, ideal city-state, philosopher kings, and the Cave allegory.")
    ],
    "Young Adult": [
        ("Looking for Alaska", "John Green", "9780142402511", "Miles 'Pudge' Halter attends Culver Creek boarding school, falling for elusive Alaska Young."),
        ("An Abundance of Katherines", "John Green", "9780142410707", "Child prodigy Colin Singleton takes a road trip after being dumped by his 19th Katherine."),
        ("Paper Towns", "John Green", "9780142414934", "Quentin searches for his eccentric neighbor Margo Roth Spiegelman after she leaves clues and disappears."),
        ("The Fault in Our Stars", "John Green", "9780142424179", "Sixteen-year-old Hazel Grace meets Augustus Waters at a cancer patient support group in Indianapolis."),
        ("Turtles All the Way Down", "John Green", "9780525555360", "Sixteen-year-old Aza Holmes navigates OCD while investigating a fugitive billionaire reward."),
        ("The Anthropocene Reviewed", "John Green", "9780593300909", "Essay reviews rating various facets of the human-centered planet on a five-star scale."),
        ("Eleanor & Park", "Rainbow Rowell", "9781250012579", "Two teenage misfits bond over comic books and mixtape cassettes on a 1986 school bus."),
        ("Fangirl", "Rainbow Rowell", "9781250030955", "Cath navigates her freshman year of college while writing massively popular Simon Snow fan fiction."),
        ("Carry On", "Rainbow Rowell", "9781250135810", "Simon Snow attends Watford School of Magicks while dealing with his vampire roommate Baz."),
        ("Wayward Son", "Rainbow Rowell", "9781250146076", "Simon, Baz, and Penelope take an American West road trip after saving the magical world."),
        ("Any Way the Wind Blows", "Rainbow Rowell", "9781250146083", "Simon and Baz return to London to settle magic mysteries and their own romantic future."),
        ("Attachments", "Rainbow Rowell", "9780452297869", "IT guy Lincoln reads Beth and Jennifer's work emails and falls in love with Beth sight unseen."),
        ("Landline", "Rainbow Rowell", "9781250049377", "TV writer Georgie discovers her rotary landline phone lets her speak to her husband in the past."),
        ("Pumpkinheads", "Rainbow Rowell & Faith Erin Hicks", "9781626721623", "Best friends Deja and Josiah work their final shift together at an autumnal pumpkin patch."),
        ("The Hate U Give", "Angie Thomas", "9780062498533", "Starr Carter witnesses her unarmed childhood best friend shot by a police officer."),
        ("On the Come Up", "Angie Thomas", "9780062498564", "Sixteen-year-old Bri aspires to become a legendary rap star while facing eviction threats."),
        ("Concrete Rose", "Angie Thomas", "9780062838582", "Maverick Carter learns what it means to be a young father in Garden Heights seventeen years earlier."),
        ("Nic Blake and the Remarkables", "Angie Thomas", "9780063225138", "Nic Blake discovers she is a Remarkable possessing natural magic in the American South."),
        ("Ghost", "Jason Reynolds", "9781481450157", "Castle 'Ghost' Cranshaw joins an elite middle school track team while coping with traumatic family past."),
        ("Patina", "Jason Reynolds", "9781481450188", "Patina runs track to handle stress while taking care of her younger sister after her mother's illness."),
        ("Sunny", "Jason Reynolds", "9781481450218", "Sunny quit track long-jumping to pursue his true passion of dance and discus throwing."),
        ("Lu", "Jason Reynolds", "9781481450249", "Track co-captain Lu faces personal hurdles as championship meet approaches."),
        ("Long Way Down", "Jason Reynolds", "9781481438254", "Sixty seconds in an elevator as Will decides whether to avenge his brother's shooting."),
        ("Look Both Ways", "Jason Reynolds", "9781481438285", "Ten short stories following ten different kids walking home after the school bell rings."),
        ("Stamped: Racism, Antiracism, and You", "Jason Reynolds & Ibram X. Kendi", "9780316453691", "A young adult reimagining of Kendi's history of racist ideas in America."),
        ("The Poet X", "Elizabeth Acevedo", "9780062662804", "Dominican girl Xiomara Batista expresses her frustration through slam poetry in Harlem."),
        ("With the Fire on High", "Elizabeth Acevedo", "9780062662835", "Teen mother Emoni Santiago balances high school, daughter care, and culinary aspirations."),
        ("Clap When You Land", "Elizabeth Acevedo", "9780062882769", "Two sisters who didn't know the other existed learn their father died in a plane crash."),
        ("Family Lore", "Elizabeth Acevedo", "9780063207264", "A Dominican-American family gathers for a living wake organized by an aunt who foresees deaths."),
        ("Wonder", "R.J. Palacio", "9780375869020", "Auggie Pullman enters fifth grade at Beecher Prep with facial differences."),
        ("Perks of Being a Wallflower", "Stephen Chbosky", "9780671027346", "Charlie writes letters to an anonymous friend about freshman high school trials."),
        ("Speak", "Laurie Halse Anderson", "9780312674397", "Melinda stops speaking after a traumatic high school summer party assault."),
        ("Monster", "Walter Dean Myers", "9780064407311", "Sixteen-year-old Steve Harmon writes his murder trial as a movie screenplay.")
    ],
    "Poetry": [
        ("Twenty Love Poems and a Song of Despair", "Pablo Neruda", "9780140186482", "Neruda's celebrated early collection of passionate, nature-infused love poetry."),
        ("Canto General", "Pablo Neruda", "9780520073036", "An epic poetic chronicle of Latin America's history, flora, fauna, and political struggles."),
        ("100 Love Sonnets", "Pablo Neruda", "9780292705685", "Sonnets dedicated to his wife Matilde Urrutia divided into Morning, Afternoon, Evening, and Night."),
        ("Residence on Earth", "Pablo Neruda", "9780811208912", "Surrealist poetry exploring despair, decay, and alienation during Neruda's diplomatic travels."),
        ("The Captain's Verses", "Pablo Neruda", "9780811215800", "Poem collection written in secret during Neruda's exile on Capri island."),
        ("Odes to Common Things", "Pablo Neruda", "9780821220801", "Celebrating everyday objects like onions, scissors, socks, and tomatoes."),
        ("Book of Questions", "Pablo Neruda", "9781556590412", "Unanswered poetic questions probing nature, time, dreams, and existence."),
        ("Extravagaria", "Pablo Neruda", "9780811215008", "Whimsical reflections on mortality, quietude, and personal freedom."),
        ("American Primitive", "Mary Oliver", "9780316634502", "Pulitzer Prize-winning collection celebrating American wilderness, animals, and silence."),
        ("New and Selected Poems", "Mary Oliver", "9780807068182", "Comprehensive selection of thirty years of nature-centered, spiritual poetry."),
        ("Wild Geese", "Mary Oliver", "9780143135388", "Iconic poems reminding readers of their place in the family of things."),
        ("Why I Wake Early", "Mary Oliver", "9780807068793", "Forty-seven new poems celebrating dawn, birdsong, sunlight, and quiet devotion."),
        ("Thirst", "Mary Oliver", "9780807068960", "Poem reflections dealing with grief following her partner's death and Christian faith."),
        ("A Thousand Mornings", "Mary Oliver", "9780143124054", "Morning walks along Provincetown shores noticing marsh grass and herons."),
        ("Devotions", "Mary Oliver", "9780399563249", "The definitive curated collection of over 200 poems selected by Mary Oliver herself."),
        ("Upstream", "Mary Oliver", "9780143130086", "Collected prose essays on nature writing, Walt Whitman, and artistic discipline."),
        ("Dog Songs", "Mary Oliver", "9780143125839", "Heartwarming, whimsical poems honoring canine companions and loyalty."),
        ("Felicity", "Mary Oliver", "9780143129332", "Late-life poems celebrating newfound love and quiet contentment."),
        ("And Still I Rise", "Maya Angelou", "9780394502526", "Empowering poems of endurance, Black female pride, and personal resilience."),
        ("Just Give Me a Cool Drink of Water 'fore I Diiie", "Maya Angelou", "9780394471426", "Angelou's debut poetry collection divided into warm love poems and social protest."),
        ("I Shall Not Be Moved", "Maya Angelou", "9780394586182", "Reflections on African American historical survival, work, and community strength."),
        ("Phenomenal Woman", "Maya Angelou", "9780679449249", "Four famous poems celebrating female grace, beauty, and unshakeable confidence."),
        ("On the Pulse of Morning", "Maya Angelou", "9780679748380", "The inaugural poem delivered at President Bill Clinton's 1993 inauguration."),
        ("The Weary Blues", "Langston Hughes", "9780375713019", "Hughes's 1926 Harlem Renaissance debut weaving blues musical rhythm into verse."),
        ("Fine Clothes to the Jew", "Langston Hughes", "9780375713026", "Frank poetic portraits of working-class Harlem night life, cabaret, and struggle."),
        ("Shakespeare in Harlem", "Langston Hughes", "9780375713033", "Blues poems reflecting urban frustration and Great Depression economic stress."),
        ("Montage of a Dream Deferred", "Langston Hughes", "9780375713040", "A book-length poem sequence exploring jazz, bebop, and deferred dreams in Harlem."),
        ("The Panther and the Lash", "Langston Hughes", "9780375713057", "Late-life civil rights poems published posthumously during the 1960s movement."),
        ("Ariel", "Sylvia Plath", "9780060931728", "Plath's famous posthumous collection containing Lady Lazarus and Daddy."),
        ("The Colossus and Other Poems", "Sylvia Plath", "9780375704468", "Plath's only poetry volume published during her lifetime."),
        ("Crossing the Water", "Sylvia Plath", "9780060902506", "Transitional poems written between The Colossus and Ariel."),
        ("Winter Trees", "Sylvia Plath", "9780060902513", "Final poems written in the last months of Plath's life."),
        ("The Collected Poems", "Sylvia Plath", "9780060909000", "Pulitzer Prize-winning comprehensive collection of Plath's complete poetry.")
    ],
    "Classic Literature": [
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "Orphan Jane becomes governess at Thornfield Hall, falling for Mr. Rochester despite his attic secret."),
        ("Shirley", "Charlotte Brontë", "9780141441382", "Independent heiress Shirley Keeldar and quiet Caroline Helstone navigate Luddite riots in Yorkshire."),
        ("Villette", "Charlotte Brontë", "9780141439792", "Lucy Snowe travels to French-speaking Villette to teach at a girls' pensionnat, falling for M. Paul."),
        ("The Professor", "Charlotte Brontë", "9780141441542", "William Crimsworth seeks his fortune as a schoolmaster in Brussels."),
        ("Wuthering Heights", "Emily Brontë", "9780141439556", "The passionate, destructive love between Heathcliff and Catherine Earnshaw on Yorkshire moors."),
        ("Agnes Grey", "Anne Brontë", "9780141441559", "An impoverished minister's daughter works as a governess for wealthy cruel families."),
        ("The Tenant of Wildfell Hall", "Anne Brontë", "9780141439600", "Helen Graham flees her abusive alcoholic husband to protect her young son as an artist."),
        ("Mary Barton", "Elizabeth Gaskell", "9780141441443", "Trade unionism, murder, and working-class Victorian poverty in industrial Manchester."),
        ("Cranford", "Elizabeth Gaskell", "9780141450254", "Witty vignettes of spinster life in a quiet Cheshire village."),
        ("North and South", "Elizabeth Gaskell", "9780141441252", "Southern Margaret Hale moves to northern industrial Milton, clashing with mill owner John Thornton."),
        ("Wives and Daughters", "Elizabeth Gaskell", "9780141439624", "Molly Gibson navigates her father's remarriage, step-sister Cynthia, and love for Roger Hamley."),
        ("Ruth", "Elizabeth Gaskell", "9780141441566", "A fallen seamstress is taken in by a Dissenting minister and builds a respectable life."),
        ("Sylvia's Lovers", "Elizabeth Gaskell", "9780141441573", "Press-gangs during the Napoleonic Wars disrupt Sylvia Robson's love between two men."),
        ("Adam Bede", "George Eliot", "9780141439662", "Carpenter Adam Bede loves Hetty Sorrel, who is seduced by local squire Arthur Donnithorne."),
        ("The Mill on the Floss", "George Eliot", "9780141439679", "Maggie Tulliver's passionate nature conflicts with her rigid brother Tom and family mill downfall."),
        ("Silas Marner", "George Eliot", "9780141439754", "Reclusive linen weaver Silas Marner is transformed when gold stolen from him is replaced by baby Eppie."),
        ("Romola", "George Eliot", "9780141441580", "Historical novel set in 15th-century Florence during Savonarola's religious rule."),
        ("Felix Holt, the Radical", "George Eliot", "9780141441597", "Political reform and estate inheritance disputes during the 1832 Reform Act."),
        ("Middlemarch", "George Eliot", "9780141439587", "Dorothea Brooke, Tertius Lydgate, and provincial town lives during Victorian social change."),
        ("Daniel Deronda", "George Eliot", "9780141439839", "Gwendolen Harleth's tragic marriage contrasts with Daniel Deronda's search for Jewish heritage."),
        ("Far from the Madding Crowd", "Thomas Hardy", "9780141439655", "Independent Bathsheba Everdene is courted by Gabriel Oak, William Boldwood, and Sergeant Troy."),
        ("The Return of the Native", "Thomas Hardy", "9780141439693", "Eustacia Vye longs to escape Egdon Heath while Clym Yeobright returns home to teach."),
        ("The Mayor of Casterbridge", "Thomas Hardy", "9780141439785", "Michael Henchard sells his wife in a drunken fit, rising to mayor before past sins destroy him."),
        ("Tess of the d'Urbervilles", "Thomas Hardy", "9780141439594", "Pure country girl Tess Durbeyfield suffers from Alec d'Urberville's assault and Angel Clare's hypocrisy."),
        ("Jude the Obscure", "Thomas Hardy", "9780141439709", "Working-class Jude Fawley dreams of university study while living outside marriage with Sue Bridehead."),
        ("Under the Greenwood Tree", "Thomas Hardy", "9780141441603", "Tranter Reuben's Mellstock parish choir and Dick Dewey's romance with schoolmistress Fancy Day."),
        ("A Pair of Blue Eyes", "Thomas Hardy", "9780141441610", "Elfride Swancourt's tragic love triangle between architect Stephen Smith and critic Henry Knight."),
        ("Two on a Tower", "Thomas Hardy", "9780141441627", "Astronomer Swithin St Cleeve and older noblewoman Lady Constantine study stars in secret love."),
        ("The Woodlanders", "Thomas Hardy", "9780141439853", "Timber trader Giles Winterborne loses Grace Melbury to sophisticated Doctor Fitzpiers."),
        ("Pride and Prejudice", "Jane Austen", "9780141439518", "Elizabeth Bennet and Fitzwilliam Darcy overcome pride and social prejudice in Hertfordshire."),
        ("Sense and Sensibility", "Jane Austen", "9780141439686", "Elinor and Marianne Dashwood navigate heartbreak and financial strain."),
        ("Emma", "Jane Austen", "9780141439587", "Well-meaning matchmaker Emma Woodhouse learns lessons in romance and humility from Mr. Knightley."),
        ("Mansfield Park", "Jane Austen", "9780141439808", "Quiet Fanny Price is raised by wealthy relatives at Mansfield Park, holding fast to her morals.")
    ],
    "Non-Fiction": [
        ("The Devil in the White City", "Erik Larson", "9780375725609", "Architect Daniel Burnham builds the 1893 Chicago World's Fair while serial killer H.H. Holmes traps victims."),
        ("Thunderstruck", "Erik Larson", "9781400034529", "Wireless telegraphy inventor Marconi intersects with murderer Hawley Crippen's transatlantic escape."),
        ("In the Garden of Beasts", "Erik Larson", "9780307408853", "William E. Dodd, first American ambassador to Nazi Germany, witnesses Hitler's consolidation of power in 1930s Berlin."),
        ("Dead Wake", "Erik Larson", "9780307408877", "The tragic last crossing of the Lusitania ocean liner struck by a German U-boat in 1915."),
        ("The Splendid and the Vile", "Erik Larson", "9780385348713", "Winston Churchill's family and inner circle during the German Blitz bombardment of Britain."),
        ("The Demon of Unrest", "Erik Larson", "9780385348744", "The harrowing five months between Lincoln's election and the outbreak of the American Civil War at Fort Sumter."),
        ("Isaac's Storm", "Erik Larson", "9780375708275", "The devastating 1900 hurricane that destroyed Galveston, Texas and meteorologist Isaac Cline's miscalculation."),
        ("The Orchid Thief", "Susan Orlean", "9780449003718", "John Laroche's obsession with poaching rare ghost orchids from Florida swamps."),
        ("The Library Book", "Susan Orlean", "9781476740195", "The unsolved 1986 catastrophic fire at the Los Angeles Public Library and history of libraries."),
        ("Rin Tin Tin", "Susan Orlean", "9781439190142", "The life and legacy of the famous German Shepherd rescued from WWI battlefield to Hollywood star."),
        ("Saturday Night", "Susan Orlean", "9780671761004", "How different Americans across small towns and big cities spend their Saturday nights."),
        ("On Animals", "Susan Orlean", "9781501185847", "Collected profiles of extraordinary human-animal relationships from show chickens to whales."),
        ("Into the Wild", "Jon Krakauer", "9780385486804", "Christopher McCandless leaves society to live off the land in the Alaskan wilderness."),
        ("Into Thin Air", "Jon Krakauer", "9780385494786", "Krakauer's firsthand account of the catastrophic 1996 Mount Everest climbing disaster."),
        ("Under the Banner of Heaven", "Jon Krakauer", "9781400032808", "Religious fundamentalism and a shocking double murder committed by Mormon fundamentalist brothers."),
        ("Where Men Win Glory", "Jon Krakauer", "9780307387189", "NFL star Pat Tillman leaves football to serve in Afghanistan and the military cover-up of his friendly fire death."),
        ("Missoula", "Jon Krakauer", "9780385539630", "Investigating college town sexual assault cases and justice system failures in Montana."),
        ("The Tipping Point", "Malcolm Gladwell", "9780316346627", "How little things can make a big difference in social epidemics and trends."),
        ("Blink", "Malcolm Gladwell", "9780316172325", "The power of thinking without thinking and snap judgment intuition."),
        ("Outliers", "Malcolm Gladwell", "9780316017930", "Why some people succeed based on cultural background, birth month, and 10,000 hours of practice."),
        ("What the Dog Saw", "Malcolm Gladwell", "9780316075848", "Collected New Yorker essays exploring minor geniuses, hair dye, and dog training."),
        ("David and Goliath", "Malcolm Gladwell", "9780316204361", "Underdogs, misfits, and the art of battling giants."),
        ("Talking to Strangers", "Malcolm Gladwell", "9780316478526", "What we should know about the people we don't know and communication breakdowns."),
        ("Bomber Mafia", "Malcolm Gladwell", "9780316296830", "Precision bombing technology innovation during WWII and strategic debates."),
        ("The Perfect Storm", "Sebastian Junger", "9780060977474", "The Andrea Gail fishing boat caught in the 1991 Halloween mega-storm off Gloucester."),
        ("A Death in Belmont", "Sebastian Junger", "9780060598815", "The Boston Strangler murders and a suspicious handyman working at Junger's childhood home."),
        ("War", "Sebastian Junger", "9780061859724", "Fifteen months embedded with a US infantry platoon in Afghanistan's dangerous Korengal Valley."),
        ("Tribe", "Sebastian Junger", "9781455566389", "On homecoming, tribal belonging, and post-traumatic stress in modern society."),
        ("Freedom", "Sebastian Junger", "9781538719879", "A 400-mile walking journey along East Coast railroad tracks exploring autonomy."),
        ("The Emperor of All Maladies", "Siddhartha Mukherjee", "9781439170915", "A biography of cancer from ancient Egyptian tumor descriptions to modern immunotherapy."),
        ("The Gene: An Intimate History", "Siddhartha Mukherjee", "9781476733500", "The history of genetics, heredity, and human gene editing ethics."),
        ("The Song of the Cell", "Siddhartha Mukherjee", "9781501198977", "Cellular biology, medical innovation, and the new human organism."),
        ("Thinking, Fast and Slow", "Daniel Kahneman", "9780374533557", "System 1 fast intuitive thinking versus System 2 slow deliberative reasoning.")
    ]
}

def escape_sql(text):
    return text.replace("'", "''")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "seed_books_batch_7.sql")
    
    total_books = 0
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- PageMind Database Seed Script: Batch 7 of 10 (500 Books across 15 Genres)\n")
        f.write("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
        f.write("USE pagemind;\n\n")
        
        for genre, books in genres_data.items():
            f.write(f"-- =======================================================\n")
            f.write(f"-- Genre: {genre} ({len(books)} books)\n")
            f.write(f"-- =======================================================\n")
            for title, author, isbn, desc in books:
                t_esc = escape_sql(title)
                a_esc = escape_sql(author)
                d_esc = escape_sql(desc)
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
                
                # Build buy links JSON
                search_term = f"{title} {author}".replace(" ", "%20")
                buy_links = {
                    "amazon": f"https://www.amazon.in/s?k={search_term}",
                    "flipkart": f"https://www.flipkart.com/search?q={search_term}"
                }
                buy_json = escape_sql(json.dumps(buy_links))
                
                pub_year = get_published_year(title, author, genre, desc, isbn)

                
                rating = get_rating(title, author)

                
                sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{t_esc}', '{a_esc}', '{genre}', '{d_esc}', '{cover_url}', '{buy_json}', {pub_year}, {rating});\n"
                f.write(sql)
                total_books += 1
            f.write("\n")
            
    print(f"Successfully generated {output_path} with {total_books} book insert statements across {len(genres_data)} genres!")

if __name__ == "__main__":
    main()
