from book_metadata_utils import get_rating, get_published_year
import json
import urllib.parse
import os

# Batch 2: 500 Real, Published Books across 15 Genres (33-34 books per genre)
# Using lesser-known, deep-catalog published titles to avoid duplicates from top-500 lists

GENRE_DATA_BATCH_2 = {
    "Fiction": [
        ("Station Eleven", "Emily St. John Mandel", "9780804172448", "A nomadic theater troupe performs Shakespeare in the Great Lakes region years after a devastating swine flu pandemic."),
        ("Cloud Atlas", "David Mitchell", "9780375507250", "Six nested stories spanning from 19th-century New Zealand to a post-apocalyptic Hawaiian future."),
        ("The Sense of an Ending", "Julian Barnes", "9780307957054", "A middle-aged man confronts imperfect memories of his youth when a mysterious bequest reopens past wounds."),
        ("Lincoln in the Bardo", "George Saunders", "9780812995343", "A chorus of ghosts speaks in an American cemetery during the Civil War as Abraham Lincoln grieves his son."),
        ("Piranesi", "Susanna Clarke", "9781635575637", "A man lives in a grand, infinite labyrinth house with thousands of statues and tides sweeping through its halls."),
        ("A Fine Balance", "Rohinton Mistry", "9780679776031", "Four strangers in an unnamed Indian city form an unexpected bond amidst the turmoil of the 1975 State of Emergency."),
        ("White Teeth", "Zadie Smith", "9780375703867", "Two wartime friends in post-colonial London navigate family dynamics, religion, and cultural identity across generations."),
        ("Drive Your Plow Over the Bones of the Dead", "Olga Tokarczuk", "9780525541332", "An eccentric Polish woman investigating mysterious deaths of local hunters believes animals are taking revenge."),
        ("The Overstory", "Richard Powers", "9780393635522", "Nine Americans whose unique life experiences with trees bring them together to address natural destruction."),
        ("Shuggie Bain", "Douglas Stuart", "9780802148049", "A young boy in 1980s Glasgow supports his mother as she struggles with addiction and poverty."),
        ("Hamnet", "Maggie O'Farrell", "9780525656012", "A luminous story of marriage, grief, and maternal tenderness surrounding the death of Shakespeare's 11-year-old son."),
        ("The Remains of the Day", "Kazuo Ishiguro", "9780679731726", "An elderly English butler reflects on his life of loyal service and suppressed feelings for a former housekeeper."),
        ("Never Let Me Go", "Kazuo Ishiguro", "9781400078776", "Students at a seemingly idyllic English boarding school discover a dark truth about their purpose in society."),
        ("Klara and the Sun", "Kazuo Ishiguro", "9780593318171", "An Artificial Friend with extraordinary observational qualities observes the human world from a store window."),
        ("On Earth We're Briefly Gorgeous", "Ocean Vuong", "9780525562023", "A son writes a letter to his illiterate mother, exploring family history, trauma, and identity."),
        ("The Vanishing Half", "Brit Bennett", "9780525536291", "Twin Black sisters choose different paths in 1960s America—one living as Black, the other passing as white."),
        ("Homegoing", "Yaa Gyasi", "9781101947135", "Two half-sisters in 18th-century Ghana trace seven generations of descendants through slavery and freedom."),
        ("Transcendent Kingdom", "Yaa Gyasi", "9780525658184", "A neuroscience Ph.D. candidate at Stanford studies addiction and depression to understand her family's suffering."),
        ("Pachinko", "Min Jin Lee", "9781455563937", "Four generations of a poor Korean immigrant family fight to control their destiny in 20th-century Japan."),
        ("Free Food for Millionaires", "Min Jin Lee", "9780446581080", "A Princeton graduate navigates ambition, romance, and Korean-American family expectations in Manhattan."),
        ("The Memory Police", "Yoko Ogawa", "9781101870600", "On an unnamed island, objects vanish from memory and the Memory Police enforce complete oblivion."),
        ("Convenience Store Woman", "Sayaka Murata", "9780802128256", "A 36-year-old Tokyo woman finds comfort and order working at a convenience store for eighteen years."),
        ("Earthlings", "Sayaka Murata", "9780802157010", "A young woman who believes she is an alien alienates herself from social norms in modern Japan."),
        ("Before the Coffee Gets Cold", "Toshikazu Kawaguchi", "9781335010131", "A small Tokyo cafe allows customers to travel back in time, provided they return before the coffee cools."),
        ("Tales from the Cafe", "Toshikazu Kawaguchi", "9781335430991", "Four new customers visit the secret Tokyo cafe to reconnect with loved ones in the past."),
        ("The Narrow Road to the Deep North", "Richard Flanagan", "9780804171472", "An Australian surgeon in a WWII Japanese POW camp finds solace in memories of a love affair."),
        ("Flight Behavior", "Barbara Kingsolver", "9780062124272", "A young Appalachian mother discovers millions of monarch butterflies roosting in her small valley."),
        ("Demon Copperhead", "Barbara Kingsolver", "9780063251922", "A modern reimagining of David Copperfield set in the mountains of southern Appalachia amidst the opioid epidemic."),
        ("The Poisonwood Bible", "Barbara Kingsolver", "9780060786502", "An evangelical minister takes his wife and four daughters on a mission to the Belgian Congo in 1959."),
        ("Trust", "Hernan Diaz", "9780593420317", "Four different manuscripts tell conflicting stories of a 1920s Wall Street tycoon and his brilliant wife."),
        ("In the Distance", "Hernan Diaz", "9781566894883", "A young Swedish immigrant travels east across 19th-century America searching for his brother."),
        ("The Glass Hotel", "Emily St. John Mandel", "9780525521143", "A story of money, ghost sightings, and a massive Ponzi scheme collapsing on Vancouver Island."),
        ("Sea of Tranquility", "Emily St. John Mandel", "9780593321447", "A detective investigates an anomaly in the North American wilderness connecting time travelers across centuries."),
        ("The Sea, The Sea", "Iris Murdoch", "9780141186160", "An aging playwright retreats to a seaside cottage where past obsessions resurface.")
    ],

    "Mystery": [
        ("The Seven Deaths of Evelyn Hardcastle", "Stuart Turton", "9781492657965", "A guest at a country estate must solve a murder by reliving the same day in eight different bodies."),
        ("The Devil and the Dark Water", "Stuart Turton", "9781786893857", "A detective aboard a 1634 East Indiaman ship fights a demon promising slaughter to the crew."),
        ("The Moonstone", "Wilkie Collins", "9780140434088", "A priceless sacred diamond stolen in India vanishes from an English country house."),
        ("The Woman in White", "Wilkie Collins", "9780141439617", "A drawing master encounters a distressed woman dressed in white on a moonlit London road."),
        ("In a Dark, Dark Wood", "Ruth Ware", "9781501112331", "A reclusive crime writer attends a bachelorette weekend in a remote glass house in the woods."),
        ("The Woman in Cabin 10", "Ruth Ware", "9781501132957", "A travel journalist on a luxury cruise witnesses a woman thrown overboard, but all guests are accounted for."),
        ("The Turn of the Key", "Ruth Ware", "9781501188770", "A nanny accepts a position at a smart home in the Scottish Highlands, where children are tormented by ghosts."),
        ("The Hunting Party", "Lucy Foley", "9780062868824", "A group of Oxford friends celebrate New Year's Eve in a remote Scottish estate, where one ends up dead."),
        ("The Paris Apartment", "Lucy Foley", "9780063003033", "A broke young woman visits her brother's apartment in Paris only to find him missing."),
        ("A Sunlit Weapon", "Jacqueline Winspear", "9780063003002", "Maisie Dobbs investigates the shooting down of a British pilot carrying vital military intelligence in 1942."),
        ("Maisie Dobbs", "Jacqueline Winspear", "9780312429010", "A former WWI nurse sets up a private inquiry business in 1929 London."),
        ("The Decagon House Murders", "Yukito Ayatsuji", "9781786893857", "Members of a university mystery club visit an isolated island where a famous architect died."),
        ("The Tokyo Zodiac Murders", "Soji Shimada", "9781786893857", "An astrologer detective investigates an unsolved 1936 ritual murder of an artist and his daughters."),
        ("Newcomer", "Keigo Higashino", "9781250170163", "Detective Kaga investigates the murder of a woman in the traditional Nihonbashi district of Tokyo."),
        ("Malice", "Keigo Higashino", "9780312606305", "A bestselling author is found murdered in his locked home, setting off a battle of wits."),
        ("A Midsummer's Equation", "Keigo Higashino", "9781250080004", "Physics professor Manabu Yukawa investigates an accidental death at a seaside inn."),
        ("The Red House Mystery", "A.A. Milne", "9780486401645", "Amateur sleuth Antony Gillingham investigates a sudden gunshot during a country house party."),
        ("The Daughter of Time", "Josephine Tey", "9780684803869", "A bedridden Scotland Yard detective investigates whether King Richard III truly murdered the Princes in the Tower."),
        ("The Franchise Affair", "Josephine Tey", "9780060875480", "A small-town lawyer defends two women accused of kidnapping a teenage girl."),
        ("Gaudy Night", "Dorothy L. Sayers", "9780061043642", "Harriet Vane visits Oxford University to investigate poison-pen letters targeting female scholars."),
        ("Whose Body?", "Dorothy L. Sayers", "9780061043574", "Lord Peter Wimsey inspects an unidentified naked body found wearing only a pince-nez in a bath."),
        ("The Club Dumas", "Arturo Pérez-Reverte", "9780156032834", "A rare book dealer tracks down two mysterious medieval manuscripts linked to Alexandre Dumas."),
        ("The Flanders Panel", "Arturo Pérez-Reverte", "9780156029582", "An art restorer uncovers a hidden chess match in a 15th-century painting linked to real-life murders."),
        ("The Word Is Murder", "Anthony Horowitz", "9780062676788", "A woman plans her own funeral and is murdered six hours later, investigated by ex-detective Hawthorne."),
        ("The Sentence Is Death", "Anthony Horowitz", "9780062883070", "A celebrity divorce lawyer is found bludgeoned to death with a bottle of wine."),
        ("A Line to Kill", "Anthony Horowitz", "9780062883094", "A literary festival on a small Channel Island is disrupted by a sudden brutal murder."),
        ("The Dry", "Jane Harper", "9781250105608", "Federal Agent Aaron Falk returns to his drought-stricken hometown to attend his childhood friend's funeral."),
        ("Force of Nature", "Jane Harper", "9781250105639", "Five women enter the Australian bush on a corporate retreat, but only four return."),
        ("The Lost Man", "Jane Harper", "9781250105684", "Two brothers meet at the remote fence line dividing their vast cattle stations in outback Queensland."),
        ("The Survivors", "Jane Harper", "9781250229588", "Kieran Elliott returns to his coastal hometown where a body is discovered on the beach."),
        ("Magpie", "Jane Fallon", "9781405948332", "A woman moves into her dream home with her boyfriend, but his mother's interference turns sinister."),
        ("The Chestnut Man", "Søren Sveistrup", "9780062895363", "A serial killer leaves matchstick-chestnut figurines at brutal crime scenes in Copenhagen."),
        ("Silverview", "John le Carré", "9780593490594", "A small-town bookstore owner forms a friendship with an eccentric customer harboring espionage secrets."),
        ("The Monogram Murders", "Sophie Hannah", "9780062291592", "Hercule Poirot investigates a triple murder at a fashionable London hotel in 1929.")
    ],

    "Thriller": [
        ("The Chain", "Adrian McKinty", "9781538732601", "A mother receives a phone call stating her daughter has been kidnapped, and she must kidnap another child to free her."),
        ("The Island", "Adrian McKinty", "9781538753767", "A family vacationing on an isolated Australian island is relentlessly hunted by hostile locals after an accident."),
        ("The Quiet American", "Graham Greene", "9780143039549", "A British journalist and an idealist American CIA officer clash over love and covert war in 1950s Vietnam."),
        ("Our Man in Havana", "Graham Greene", "9780140184938", "A vacuum cleaner salesman in Cuba is recruited by British intelligence and invents fake military blueprints."),
        ("The Odessa File", "Frederick Forsyth", "9780451204226", "A German journalist investigates a secret organization protecting former SS officers in post-WWII Germany."),
        ("The Dogs of War", "Frederick Forsyth", "9780451204233", "A British mining tycoon hires a team of mercenaries to stage a violent coup in a mineral-rich African republic."),
        ("The Whisper Man", "Alex North", "9781250318008", "A widowed father and his son move to a town where a serial killer kidnapped children twenty years ago."),
        ("The Shadows", "Alex North", "9781250318039", "A man returns home to care for his mother and is drawn back to a dark murder committed by teenagers."),
        ("The Angel's Game", "Carlos Ruiz Zafón", "9780061584060", "In 1920s Barcelona, a young writer accepts a lucrative proposal from a mysterious publisher to write a sacred book."),
        ("The Prisoner of Heaven", "Carlos Ruiz Zafón", "9780062206244", "Daniel Sempere and his friend Fermín confront dark secrets from Montjuïc Castle prison in 1950s Spain."),
        ("The Labyrinth of the Spirits", "Carlos Ruiz Zafón", "9780062668691", "Alicia Gris investigates the sudden disappearance of Spain's Minister of Culture in Francoist Madrid."),
        ("The Kind Worth Killing", "Peter Swanson", "9780062267529", "Two strangers meet on a flight from London to Boston and joke about murdering an unfaithful spouse."),
        ("Eight Perfect Murders", "Peter Swanson", "9780062838209", "A mystery bookstore owner is questioned by the FBI when a killer copies classic fictional murders from his blog."),
        ("Her Every Fear", "Peter Swanson", "9780062427021", "A young woman swap apartments with a cousin in Boston and discovers his neighbor was brutally murdered."),
        ("Before She Knew Him", "Peter Swanson", "9780062838155", "A woman with bipolar disorder suspects her suburban neighbor is a murderer, but no one believes her."),
        ("The Push", "Ashley Audrain", "9781984881663", "A mother struggles with her dark relationship with her daughter, convinced something is wrong with the child."),
        ("Rock Paper Scissors", "Alice Feeney", "9781250266101", "A married couple wins a weekend getaway in a converted Scottish chapel, but both hold dangerous secrets."),
        ("His & Hers", "Alice Feeney", "9781250266071", "A news anchor and a detective investigate a murder in their hometown, but both give conflicting stories."),
        ("Daisy Darker", "Alice Feeney", "9781250843937", "A dysfunctional family gathers on an isolated island for Nana's 80th birthday, and members die one by one."),
        ("Good Rich People", "Eliza Jane Brazier", "9780593198278", "A wealthy couple living in Beverly Hills plays a sadistic game of destroying the lives of their tenants."),
        ("My Lovely Wife", "Samantha Downing", "9780451491725", "A suburban couple keeps their fifteen-year marriage alive by getting away with serial murder."),
        ("He Started It", "Samantha Downing", "9780451491756", "Three siblings take a cross-country road trip to claim their grandfather's inheritance, hiding deadly secrets."),
        ("For Your Own Good", "Samantha Downing", "9780593100974", "An arrogant Teacher of the Year at a prestigious academy targets students and staff who don't meet standards."),
        ("The Maidens", "Alex Michaelides", "9781250304452", "A group therapist becomes obsessed with proving a charismatic Cambridge professor murdered a female student."),
        ("The Fury", "Alex Michaelides", "9781250842060", "A reclusive ex-movie star invites close friends to her private Greek island, resulting in a sudden murder."),
        ("The Family Upstairs", "Lisa Jewell", "9781501190100", "A young woman inherits a million-dollar London mansion where three dead bodies were found twenty-five years ago."),
        ("Then She Was Gone", "Lisa Jewell", "9781501190070", "A mother searching for answers ten years after her golden daughter vanished meets a man with a familiar daughter."),
        ("The Night She Disappeared", "Lisa Jewell", "9781982137366", "A teenage mother vanishes after attending a party at a mansion in the woods of a country boarding school."),
        ("None of This Is True", "Lisa Jewell", "9781982137397", "A popular podcaster meets a birthday twin at a pub and starts recording her disturbing life story."),
        ("The Passenger", "Lisa Lutz", "9781476786490", "A woman assumes a dead neighbor's identity and flees across the country when her husband dies mysteriously."),
        ("The Survivalist", "Jack Carr", "9781982123741", "A former operative tracks down black-market operations selling stolen military technology."),
        ("Without Remorse", "Tom Clancy", "9780425143322", "John Clark embarks on a personal mission of vengeance against a drug ring before joining the CIA."),
        ("Red Rabbit", "Tom Clancy", "9780425191644", "Jack Ryan works as a CIA analyst in London assisting a Soviet officer defecting with papal assassination plans."),
        ("The Snowman", "Jo Nesbø", "9780307742995", "Inspector Harry Hole investigates the disappearance of a woman whose pink scarf is found wrapped around an ominous snowman.")
    ],

    "Romance": [
        ("One Italian Summer", "Rebecca Serle", "9781982143947", "A woman grieving her mother's death travels to Positano and meets a thirty-year-old version of her mother."),
        ("In Five Years", "Rebecca Serle", "9781982137441", "A Manhattan lawyer wakes up five years in the future for one hour, living in a different apartment with a new man."),
        ("Evvie Drake Starts Over", "Linda Holmes", "9780593129418", "A recent widow in Maine forms a friendship with a major-league pitcher struggling with the yips."),
        ("The Switch", "Beth O'Leary", "9781250295720", "A stressed London professional and her grandmother swap houses and lives for two months."),
        ("The Road Trip", "Beth O'Leary", "9781250295751", "Two exes and their friends are forced to share a car on a long road trip to a wedding in Spain."),
        ("The No-Show", "Beth O'Leary", "9781250809223", "Three different women discover they are all dating the same charming man on Valentine's Day."),
        ("One Last Stop", "Casey McQuiston", "9781250244499", "A cynical twenty-three-year-old moves to Brooklyn and falls for a girl displaced from the 1970s on the Q train."),
        ("I Kissed Shara Wheeler", "Casey McQuiston", "9781250244451", "A high school senior searches for her missing rival by following mysterious notes left behind."),
        ("The Soulmate Equation", "Christina Lauren", "9781982123963", "A single mother tests a genetic matchmaking company and matches 98% with the company's stubborn founder."),
        ("Something Wilder", "Christina Lauren", "9781982173401", "A tour guide leads a treasure hunt in the Utah canyons alongside her former teenage love."),
        ("The True Love Experiment", "Christina Lauren", "9781982173432", "A romance novelist agrees to star in a dating reality show produced by her handsome friend."),
        ("Happy Place", "Emily Henry", "9780593441275", "An ex-couple pretends to still be together during their annual friend group week in Maine."),
        ("Funny Story", "Emily Henry", "9780593441282", "A children's librarian moves in with the ex-fiancé of the woman her former partner left her for."),
        ("The Bodyguard", "Katherine Center", "9781250219367", "An executive protection agent is hired to pose as the fake girlfriend of a famous action star."),
        ("Things We Never Got Over", "Lucy Score", "9781035402076", "A runaway bride arrives in a small town to help her twin sister and butts heads with a brooding barber."),
        ("Things We Hide from the Light", "Lucy Score", "9781035402106", "A police chief struggling with recovery falls for an independent new neighbor in Knockemout."),
        ("Things We Left Behind", "Lucy Score", "9781035402137", "A high-powered lawyer and a wealthy business mogul confront decades of unresolved small-town hatred."),
        ("Just for the Summer", "Abby Jimenez", "9781538704462", "Two people cursed to have their exes find true love right after dating agree to date each other."),
        ("Love, Theoretically", "Ali Hazelwood", "9780593336847", "An adjunct professor of theoretical physics fake-dates a rival experimental physicist's brother."),
        ("Check & Mate", "Ali Hazelwood", "9780593638903", "A former chess prodigy returns to the board and accidentally defeats the reigning world champion."),
        ("Not in Love", "Ali Hazelwood", "9780593638934", "A biotech researcher enters a no-strings arrangement with the executive executing a hostile takeover."),
        ("The Cheat Sheet", "Sarah Adams", "9780593358788", "A ballet dancer and her NFL quarterback best friend participate in a fake dating PR stunt."),
        ("Practice Makes Perfect", "Sarah Adams", "9780593500804", "A small-town florist asks a handsome visitor to help her practice dating skills."),
        ("When in Rome", "Sarah Adams", "9780593500774", "A burnt-out pop star drives to a small town named Rome, Kentucky, and breaks down in a local's yard."),
        ("Two Wrongs Make a Right", "Chloe Liese", "9780593547281", "Two opposites plan a fake relationship to get revenge on match-making friends."),
        ("Better Than the Movies", "Lynn Painter", "9781534467637", "A romantic teen enlists her annoying next-door neighbor to help get her childhood crush to notice her."),
        ("The Spanish Love Deception", "Elena Armas", "9781668002520", "Catalina needs a fake boyfriend for her sister's wedding in Spain and recruits her arrogant coworker."),
        ("The American Roommate Experiment", "Elena Armas", "9781668002551", "Rosie spends four weeks sharing a tiny NYC apartment with her best friend's handsome Spanish cousin."),
        ("Seven Days in June", "Tia Williams", "9781538719107", "Two bestselling authors who shared a passionate teenage week reunite fifteen years later in Brooklyn."),
        ("A Holly Jolly Diabla", "Tia Williams", "9781538719138", "A film producer reconnects with a handsome actor on set during a holiday movie production."),
        ("Weather Girl", "Rachel Lynn Solomon", "9780593200148", "A TV meteorologist and a sports reporter scheme to get their difficult bosses back together."),
        ("Business Trip", "Rachel Lynn Solomon", "9780593200179", "Two rival corporate trainers spend an eventful business week navigating shared travel plans."),
        ("Today Tonight Tomorrow", "Rachel Lynn Solomon", "9781534440265", "High school rivals spend their last night before graduation completing a citywide scavenger hunt.")
    ],

    "Fantasy": [
        ("A Day of Fallen Night", "Samantha Shannon", "9781635577921", "Four women shape the fate of a world five hundred years before the events of The Priory of the Orange Tree."),
        ("The Bone Season", "Samantha Shannon", "9781620402368", "In a dystopian 2059 London, a clairvoyant woman is kidnapped to a secret penal colony ruled by alien beings."),
        ("The Mime Order", "Samantha Shannon", "9781620402405", "Paige Mahoney rises through the ranks of London's criminal underworld after escaping Scion."),
        ("The Song Rising", "Samantha Shannon", "9781620402436", "Clairvoyant rebels fight against Scion's oppressive security systems across Britain."),
        ("The City of Brass", "S.A. Chakraborty", "9780062678102", "A con artist in 18th-century Cairo accidentally summons a djinn warrior who takes her to a magical city."),
        ("The Kingdom of Copper", "S.A. Chakraborty", "9780062678133", "Nahri navigates political intrigue and magical warfare in Daevabad after five years of peace."),
        ("The Empire of Gold", "S.A. Chakraborty", "9780062678164", "Daevabad falls into chaos as Nahri and Ali fight to restore magic and end tribal conflict."),
        ("The Adventures of Amina al-Sirafi", "S.A. Chakraborty", "9780593496732", "A retired pirate captain returns to the Indian Ocean for one last crew mission to rescue a kidnapped daughter."),
        ("The Bear and the Nightingale", "Katherine Arden", "9781101885932", "A young girl in medieval Russia communicates with mythological spirits to protect her village from a dark god."),
        ("The Girl in the Tower", "Katherine Arden", "9781101885963", "Vasilisa disguises herself as a boy and travels to Moscow to protect her family from royal court plots."),
        ("The Winter of the Witch", "Katherine Arden", "9781101885994", "Vasya uses her magical heritage to rally human and spirit allies against evil forces threatening Muscovy."),
        ("Uprooted", "Naomi Novik", "9780804179805", "A village girl is chosen to serve a cold wizard who defends the valley against a corrupted, sentient forest."),
        ("Spinning Silver", "Naomi Novik", "9780425290293", "A moneylender's daughter boasts she can turn silver into gold, attracting the attention of a winter king."),
        ("A Deadly Education", "Naomi Novik", "9780593128480", "A student with dark destructive power struggles to survive a magical school with no teachers or holidays."),
        ("The Last Graduate", "Naomi Novik", "9780593128510", "El and her classmates prepare for the fatal graduation ceremony of the Scholomance."),
        ("The Golden Enclaves", "Naomi Novik", "9780593128541", "El travels the world to save magical enclaves from collapse after leaving the Scholomance."),
        ("Jonathan Strange & Mr Norrell", "Susanna Clarke", "9780765356154", "Two 19th-century magicians restore practical magic to England during the Napoleonic Wars."),
        ("The House in the Cerulean Sea", "TJ Klune", "9781250217288", "A caseworker for magical youth visits an isolated orphanage housing six dangerous children."),
        ("Under the Whispering Door", "TJ Klune", "9781250217349", "A deceased lawyer is given seven days at a mysterious tea shop to cross over to the afterlife."),
        ("In the Lives of Puppets", "TJ Klune", "9781250217370", "A human youth raised by androids in a forest treehouse embarks on a quest to rescue his father."),
        ("Legends & Lattes", "Travis Baldree", "9781250886088", "A tired female orc barbarian hangs up her sword to open the first coffee shop in a fantasy city."),
        ("Bookshops & Bonedust", "Travis Baldree", "9781250886101", "A wounded young mercenary spends her recovery assisting a small-town bookshop owner."),
        ("The Jasmine Throne", "Tasha Suri", "9780316536287", "An imprisoned princess and a maid with secret plant magic team up to overthrow an emperor."),
        ("The Oleander Sword", "Tasha Suri", "9780316536300", "Malini fights to claim the throne while Priya wields dangerous waters of life magic."),
        ("Yellowface", "R.F. Kuang", "9780063250833", "A struggling writer steals her deceased friend's unpublished manuscript about Chinese laborers."),
        ("A Darker Shade of Magic", "V.E. Schwab", "9780765376459", "A magician capable of traveling between parallel Londons smuggles a dangerous artifact."),
        ("A Gathering of Shadows", "V.E. Schwab", "9780765376473", "Four Londons prepare for the Element Games while an ancient dark magic awakens."),
        ("A Conjuring of Light", "V.E. Schwab", "9780765376497", "Kell and Lila fight to save Red London from consumption by Black London magic."),
        ("The Invisible Life of Addie LaRue", "V.E. Schwab", "9780765387561", "A young French woman makes a bargain to live forever but is cursed to be forgotten by everyone she meets."),
        ("Gallant", "V.E. Schwab", "9780062835772", "A mute girl returns to her family estate and discovers a shadow wall leading to a dark realm."),
        ("Babel", "R.F. Kuang", "9780063021426", "A Chinese scholar at Oxford's translation institute confronts the moral cost of Britain's silver magic."),
        ("She Who Became the Sun", "Shelley Parker-Chan", "9781250621801", "A peasant girl assumes her dead brother's identity to enter a monastery and achieve greatness."),
        ("He Who Drowned the World", "Shelley Parker-Chan", "9781250621825", "Zhu Yuanzhang fights to solidify her throne against rival warlords in 14th-century China."),
        ("The Shadow of What Was Lost", "James Islington", "9780356507750", "A young gift-user travels north to face an ancient dark army while discovering his forgotten past.")
    ],

    "Science Fiction": [
        ("Children of Ruin", "Adrian Tchaikovsky", "9780316452533", "Explorers discover a terraformed ocean world inhabited by intelligent octopuses and an alien parasite."),
        ("Children of Memory", "Adrian Tchaikovsky", "9780316460064", "Human colonists on a harsh world receive help from synthetic intelligence carrying memories of Earth."),
        ("Shards of Earth", "Adrian Tchaikovsky", "9780316705844", "Humanity's scattered survivors hire a modified scout to investigate giant alien city-destroyers."),
        ("Eyes of the Void", "Adrian Tchaikovsky", "9780316705882", "Idris travels into un-space to find a weapon against the architect ships destroying planets."),
        ("Lords of Uncreation", "Adrian Tchaikovsky", "9780316705929", "The final battle to destroy the alien Architects and preserve intelligent space faring species."),
        ("A Memory Called Empire", "Arkady Martine", "9781250186430", "An ambassador from a mining station investigates her predecessor's murder at the imperial capital."),
        ("A Desolation Called Peace", "Arkady Martine", "9781250186461", "Mahit Dzmare and Three Seagrass attempt communication with an incomprehensible alien armada."),
        ("A Closed and Common Orbit", "Becky Chambers", "9780062569400", "A former ship AI installed in a synthetic body learns to navigate independent life."),
        ("Record of a Spaceborn Few", "Becky Chambers", "9780062699220", "Citizens of the Fleet adapt to modern galactic civilization while maintaining ancient Earth traditions."),
        ("The Galaxy, and the Ground Within", "Becky Chambers", "9780062936042", "Five alien travelers are stranded together at a remote waystation when a planet's grid goes down."),
        ("To Be Taught, If Fortunate", "Becky Chambers", "9780062936011", "Four astronauts explore exoplanets, modifying their bodies to survive diverse environments."),
        ("A Psalm for the Wild-Built", "Becky Chambers", "9781250236210", "A tea monk wandering human settlements meets a robot who returned from the wilderness."),
        ("A Prayer for the Crown-Shy", "Becky Chambers", "9781250236234", "Sibling Dex and Mosscap travel human territories together, answering what people need."),
        ("Gideon the Ninth", "Tamsyn Muir", "9781250313195", "Necromancers and their sword-wielding cavaliers explore a haunted space station for immortality."),
        ("Harrow the Ninth", "Tamsyn Muir", "9781250313225", "Harrowhark Nonagesimus serves the Emperor in deep space while struggling with fractured memories."),
        ("Nona the Ninth", "Tamsyn Muir", "9781250854117", "A simple girl living in a besieged city tries to lead a peaceful life despite necromantic war."),
        ("The Dark Forest", "Cixin Liu", "9780765377081", "Humanity appoints four Wallfacers to create secret defense plans against the Trisolaran fleet."),
        ("Death's End", "Cixin Liu", "9780765377104", "An aerospace engineer from the 21st century awakens to guide human civilization across light-years."),
        ("Ball Lightning", "Cixin Liu", "9780765394071", "A researcher obsessed with ball lightning develops high-energy physics military applications."),
        ("The Wandering Earth", "Cixin Liu", "9781250796868", "Humanity builds giant planetary engines to move Earth out of the expanding Sun's path."),
        ("Ninefox Gambit", "Yoon Ha Lee", "9780857666208", "A disgraced captain bonded with a undead tactical genius recaptures a fortress station."),
        ("Raven Stratagem", "Yoon Ha Lee", "9780857666574", "General Shuos Jedao takes control of a fleet to defend the High Calendar against rebels."),
        ("Revenant Gun", "Yoon Ha Lee", "9780857666598", "A resurrected general with missing memories must decide whether to serve a tyrant regime."),
        ("The Space Between Worlds", "Micaiah Johnson", "9780593135051", "A traveler visits parallel Earths where her alternate selves have died to collect data."),
        ("Semiosis", "Sue Burke", "9780765391353", "Human colonists land on a planet where sentient plant life dominates the ecosystem."),
        ("Interference", "Sue Burke", "9780765391384", "New Earth settlers and sentient plants encounter a second wave of human explorers."),
        ("Binti", "Nnedi Okorafor", "9780765385253", "A Himba girl leaves Earth to attend a galactic university, but her ship is attacked by jellyfish aliens."),
        ("Binti: Home", "Nnedi Okorafor", "9780765393112", "Binti returns to Earth with an alien friend to face family traditions and ancient heritage."),
        ("Binti: The Night Masquerade", "Nnedi Okorafor", "9780765393136", "Binti attempts to prevent war between her people and the Meduse species."),
        ("Remote Control", "Nnedi Okorafor", "9781250772800", "A girl imbued with green glowing energy becomes the adopted daughter of Death in near-future Ghana."),
        ("Noor", "Nnedi Okorafor", "9781250820464", "A cybernetically enhanced woman and a shepherd flee corporate forces across Nigeria."),
        ("Light From Uncommon Stars", "Ryka Aoki", "9781250789068", "A violin teacher who sold her soul to demons meets a runaway violinist and a space captain."),
        ("The Mount", "Carol Emshwiller", "9781931520027", "A young boy raised as a riding mount for alien conquerors struggles for freedom.")
    ],

    "Horror": [
        ("My Heart Is a Chainsaw", "Stephen Graham Jones", "9781982137632", "A slasher-obsessed outcast teenager recognizes real-life warning signs as bodies pile up at a lake town."),
        ("Don't Fear the Reaper", "Stephen Graham Jones", "9781982137663", "Jade Daniels returns home four years later just as an escaped serial killer arrives during a blizzard."),
        ("The Angel of Indian Lake", "Stephen Graham Jones", "9781982137694", "Jade Daniels faces the final tragic confrontation with the curse haunting Proofrock."),
        ("Certain Dark Things", "Silvia Moreno-Garcia", "9780593355374", "A street kid and a neo-Aztec vampire flee dangerous rival vampire clans in Mexico City."),
        ("Silver Nitrate", "Silvia Moreno-Garcia", "9780593355336", "A 1990s sound editor in Mexico City uncovers a cursed horror film linked to occult magic."),
        ("The Southern Book Club's Guide to Slaying Vampires", "Grady Hendrix", "9781683691433", "A southern suburban housewife suspects a newcomer to her neighborhood is a vampire targeting local children."),
        ("My Best Friend's Exorcism", "Grady Hendrix", "9781594748622", "In 1988 high school, a girl fights to save her best friend from demonic possession."),
        ("Horrorstör", "Grady Hendrix", "9781594745263", "Employees staying overnight at a Scandinavian furniture store encounter supernatural horrors."),
        ("The Final Girl Support Group", "Grady Hendrix", "9780593201237", "Real-life survivors of infamous slasher killings are targeted one by one by a new murderer."),
        ("How to Sell a Haunted House", "Grady Hendrix", "9780593201268", "Estranged siblings clearing out their late parents' house encounter vengeful puppets."),
        ("Survivor Song", "Paul Tremblay", "9780062679161", "A doctor and her pregnant friend navigate Massachusetts during an outbreak of fast-acting rabies."),
        ("The Pallbearers Club", "Paul Tremblay", "9780063069916", "An awkward high school student forms a friendship with a girl who might be a parasite vampire."),
        ("The Deep", "Nick Cutter", "9781476717746", "A researcher descends to a research station at the bottom of the Mariana Trench to find a cure for a global plague."),
        ("Little Heaven", "Nick Cutter", "9781501104169", "Three mercenaries hired to check on a nephew in a remote religious cult encounter an ancient evil."),
        ("The Handyman Method", "Nick Cutter & Andrew Sullivan", "9781668000007", "A homeowner watching online DIY repair videos is corrupted by sinister instructions."),
        ("Slewfoot: A Tale of Hexery", "Brom", "9781250265968", "In 1666 Connecticut, a young widow forms an alliance with an ancient spirit of the forest."),
        ("Lost Gods", "Brom", "9780062095688", "A fresh corpse descends into Purgatory to rescue his wife and unborn child from demon lords."),
        ("The Child Thief", "Brom", "9780061671340", "A dark reimagining of Peter Pan who lures troubled youth to a dying magical island."),
        ("Krampus: The Yule Lord", "Brom", "9780062095657", "A struggling musician in West Virginia is caught in a war between Santa Claus and Krampus."),
        ("The Fisherman", "John Langan", "9781939905215", "Two grieving widowers fishing at Dutchman's Creek uncover dark cosmic lore and lost loved ones."),
        ("Penpal", "Dathan Auerbach", "9780985545505", "A man reconstructs childhood memories to understand a stalker who haunted him for years."),
        ("Bad Man", "Dathan Auerbach", "9781524742492", "A young man takes a job at the supermarket where his little brother vanished five years ago."),
        ("The Sun Down Motel", "Simone St. James", "9780440000174", "A young woman takes a job at a haunted motel in 2017 where her aunt disappeared in 1982."),
        ("The Book of Cold Cases", "Simone St. James", "9780440000211", "A true crime blogger interviews an heiress acquitted of two 1977 murders and encounters paranormal phenomena."),
        ("The Haunting of Maddy Clare", "Simone St. James", "9780451235688", "A temp assistant joins ghost hunters investigating a vengeful female spirit in a rural barn."),
        ("Sundial", "Catriona Ward", "9781250812681", "A woman takes her daughter to her childhood home in the Mojave Desert, where dark experiments took place."),
        ("The Last House on Needless Street", "Catriona Ward", "9781250812629", "A lonely man, his cat, and a young girl live in a boarded-up house hiding a dark secret."),
        ("Looking Glass Sound", "Catriona Ward", "9781250812742", "A writer retreats to a seaside cottage to finish a book about a tragedy that broke his teenage friendships."),
        ("A House With Good Bones", "T. Kingfisher", "9781250829795", "An entomologist visiting her mother in North Carolina notices weird underground activity and dark family magic."),
        ("What Moves the Dead", "T. Kingfisher", "9781250830753", "A retired soldier visits the Usher estate and discovers fungal infection corrupting wildlife and residents."),
        ("The Hollow Places", "T. Kingfisher", "9781982122393", "A divorced woman finds a hole in a wall in her uncle's museum leading to a dangerous parallel dimension."),
        ("The Twisted Ones", "T. Kingfisher", "9781982122362", "A woman cleaning out her late grandmother's hoard in North Carolina discovers a manuscript of unnatural creatures."),
        ("The Spite House", "Johnny Compton", "9781250860217", "A father takes a job living in a haunted house to record paranormal activity in exchange for safety for his daughters.")
    ],

    "Self-Help": [
        ("Four Thousand Weeks: Time Management for Mortals", "Oliver Burkeman", "9780865479593", "Embracing human finitude and choosing what truly matters in a typical human lifespan of 4,000 weeks."),
        ("The Antidote: Happiness for People Who Can't Stand Positive Thinking", "Oliver Burkeman", "9780865479418", "Exploring the negative path to happiness through accepting uncertainty and vulnerability."),
        ("Stolen Focus: Why You Can't Pay Attention", "Johann Hari", "9780593138519", "Investigating systemic causes of declining attention spans and how to reclaim focus."),
        ("Lost Connections: Uncovering the Real Causes of Depression", "Johann Hari", "9781632868305", "Exploring social and environmental factors driving anxiety and depression beyond chemical imbalances."),
        ("Breath: The New Science of a Lost Art", "James Nestor", "9780735213616", "Discovering how proper breathing techniques transform physical health, sleep, and longevity."),
        ("Range: Why Generalists Triumph in a Specialized World", "David Epstein", "9780735214484", "Arguing that broad interest and diverse experience lead to greater innovation and long-term success."),
        ("The Sports Gene: Inside the Science of Extraordinary Athletic Performance", "David Epstein", "9781591845119", "Exploring the debate between genetic talent and deliberate practice in athletic achievement."),
        ("Indistractable: How to Control Your Attention and Choose Your Life", "Nir Eyal", "9781948836302", "A practical four-step framework to overcome internal and external distractions."),
        ("Hooked: How to Build Habit-Forming Products", "Nir Eyal", "9781591847786", "Understanding the Hook Model driving modern consumer technology engagement."),
        ("Building a Second Brain", "Tiago Forte", "9781982167387", "A personal system for organizing digital information to increase productivity and creative output."),
        ("The PARA Method", "Tiago Forte", "9781668024447", "Organizing digital life into Projects, Areas, Resources, and Archives."),
        ("Effortless: Make It Easier to Do What Matters Most", "Greg McKeown", "9780593135648", "Actionable advice to turn essential activities into easier tasks and prevent burnout."),
        ("Super Attractor", "Gabrielle Bernstein", "9781401957162", "Methods for manifesting confidence, peace, and abundance through spiritual alignment."),
        ("The Universe Has Your Back", "Gabrielle Bernstein", "9781401946548", "Transforming fear into faith to live with grace and purpose."),
        ("Happy Days: The Guided Path to Anxiety Recovery", "Gabrielle Bernstein", "9781401965457", "A guided path to healing trauma, releasing anxiety, and finding peace."),
        ("Set Boundaries, Find Peace", "Nedra Glover Tawwab", "9780593192092", "A guide to expressing needs, establishing healthy boundaries, and overcoming codependency."),
        ("Drama Free: A Guide to Managing Unhealthy Family Relationships", "Nedra Glover Tawwab", "9780593539279", "Practical tools to handle unsupportive family dynamics and heal emotional wounds."),
        ("The Comfort Book", "Matt Haig", "9780593297742", "A short collection of notes, lists, and stories offering hope and mental clarity."),
        ("Notes on a Nervous Planet", "Matt Haig", "9780525538295", "Looking at how modern technology and lifestyle drive stress and anxiety."),
        ("Reasons to Stay Alive", "Matt Haig", "9780143128724", "A moving memoir exploring depression and how to rediscover joy."),
        ("The Extended Mind: The Power of Thinking Outside the Brain", "Annie Murphy Paul", "9780544947665", "Using body sensations, physical spaces, and social interactions to boost intelligence."),
        ("Soundtracks: The Surprising Solution to Overthinking", "Jon Acuff", "9780982967058", "Overcoming broken mental soundtracks and replacing overthinking with action."),
        ("Finish: Give Yourself the Gift of Done", "Jon Acuff", "9781591880493", "Strategies to eliminate perfectionism and complete personal goals."),
        ("All in Startup", "Diana Kander", "9781118857663", "A business novel teaching customer validation and lean startup principles."),
        ("The Art of Learning", "Josh Waitzkin", "9780743277457", "A chess prodigy and martial arts champion shares mental habits for peak performance."),
        ("Peak: Secrets from the New Science of Expertise", "Anders Ericsson", "9780544456235", "Scientific insights into deliberate practice and unlocking human potential."),
        ("Mastery", "Robert Greene", "9780143124177", "Analyzing historical masters to unlock the path to individual excellence."),
        ("The Laws of Human Nature", "Robert Greene", "9780525428144", "Understanding human motivations, cognitive biases, and emotional drives."),
        ("Think Like a Monk", "Jay Shetty", "9781982134488", "Applying ancient monk wisdom to lower stress, improve focus, and deepen relationships."),
        ("8 Rules of Love", "Jay Shetty", "9781982183066", "Mindful steps for finding, keeping, and letting go of love."),
        ("Do Hard Things", "Steve Magness", "9780063098619", "Rethinking toughness through grounded confidence, emotional intelligence, and mindfulness."),
        ("The Practice", "Seth Godin", "9780593328972", "Shipping creative work consistently by trusting your process over outcomes."),
        ("Page One: Writing Your Future", "Cal Newport", "9780525536512", "Practical strategies for focus and deliberate execution.")
    ],

    "Biography": [
        ("The Code Breaker", "Walter Isaacson", "9781982115852", "Jennifer Doudna, CRISPR gene editing, and the future of human biology."),
        ("Kissinger: A Biography", "Walter Isaacson", "9780671663230", "The comprehensive life story of controversial diplomat Henry Kissinger."),
        ("Crying in H Mart", "Michelle Zauner", "9780525657743", "A powerful memoir about motherly love, Korean food, identity, and grief."),
        ("I'm Glad My Mom Died", "Jennette McCurdy", "9781982185824", "A former child star details eating disorders, abuse, and her overbearing mother."),
        ("Solito: A Memoir", "Javier Zamora", "9780593498163", "A 9-year-old boy's 3,000-mile migration from El Salvador to the US to reunite with parents."),
        ("Stay True: A Memoir", "Hua Hsu", "9780593315194", "A story of intense college friendship, sudden tragic loss, and art in 1990s California."),
        ("Finding Me: A Memoir", "Viola Davis", "9781400228270", "Oscar-winning actress Viola Davis shares her journey from poverty to artistic triumph."),
        ("Spare", "Prince Harry", "9780593593806", "Prince Harry tells his personal story of royal life, grief, military service, and marriage."),
        ("Pageboy: A Memoir", "Elliot Page", "9780593448786", "Actor Elliot Page reflects on fame, queer identity, gender transition, and self-discovery."),
        ("Friends, Lovers, and the Big Terrible Thing", "Matthew Perry", "9781250866448", "The Friends star shares his struggle with addiction and path to recovery."),
        ("The Woman in Me", "Britney Spears", "9781668009048", "A pop icon shares her journey through stardom, conservatorship, freedom, and motherhood."),
        ("The Storyteller: Tales of Life and Music", "Dave Grohl", "9781797127927", "Foo Fighters founder and Nirvana drummer Dave Grohl shares stories from music history."),
        ("Taste: My Life Through Food", "Stanley Tucci", "9781982168018", "Actor Stanley Tucci reflects on food, family, and culinary adventures in London and Italy."),
        ("Heavy: An American Memoir", "Kiese Laymon", "9781501125652", "Reflections on weight, eating disorders, gambling, violence, and mother-son relationships in Mississippi."),
        ("Know My Name: A Memoir", "Chanel Miller", "9780735223707", "The survivor of a high-profile assault reclaims her identity and shares her trial experience."),
        ("Untamed", "Glennon Doyle", "9781984801258", "A memoir exploring self-trust, breaking societal expectations, and finding love."),
        ("Love Warrior", "Glennon Doyle", "9781250075734", "Navigating infidelity, marital destruction, and emotional healing."),
        ("Memorial Drive: A Daughter's Memoir", "Natasha Trethewey", "9780525559023", "A Pulitzer-winning poet explores the tragic murder of her mother by her stepfather."),
        ("Minor Feelings: An Asian American Reckoning", "Cathy Park Hong", "9781984820365", "Cultural essays on Asian American identity, racial consciousness, and artistic expression."),
        ("The Light We Carry", "Michelle Obama", "9780593237465", "Former First Lady shares practical wisdom and strategies for staying hopeful in uncertain times."),
        ("Punching the Air", "Ibi Zoboi & Yusef Salaam", "9780062996480", "Novel in verse about a young artist wrongfully incarcerated, co-written by Exonerated Five member."),
        ("In Love: A Memoir of Love and Loss", "Amy Bloom", "9780593243947", "A wife details her husband's early-onset Alzheimer's diagnosis and their final journey to Switzerland."),
        ("Wave", "Sonali Deraniyagala", "9780345804310", "A heartbreaking firsthand account of surviving the 2004 Indian Ocean tsunami that took her family."),
        ("Small Fry", "Lisa Brennan-Jobs", "9780374265724", "Steve Jobs' daughter details her complex, distant relationship with her famous father."),
        ("Wild Game: My Mother, Her Lover, and Me", "Adrienne Brodeur", "9781328519030", "A daughter is enlisted as a confidante in her mother's secret affair at Cape Cod."),
        ("High-Risk Homosexual", "Gabriel Gomez", "9780593311653", "Memoir exploring queer Latino identity and upbringing in the American South."),
        ("Chasing Me to My Grave", "Winifred Rembert", "9781635576597", "An artist recalls surviving a near-lynching and civil rights activism in Georgia."),
        ("The Fact of a Body", "Alexandria Marzano-Lesnevich", "9781250079022", "A law student interning on a death penalty case uncovers parallels to her own family secrets."),
        ("All That Remains", "Sue Black", "9781982103323", "A leading forensic anthropologist reflects on death, crime scenes, and human anatomy."),
        ("Working", "Robert A. Caro", "9780525656340", "The Pulitzer-winning biographer reveals his research techniques and interview methods."),
        ("The Years of Lyndon Johnson: Means of Ascent", "Robert A. Caro", "9780679733713", "LBJ's 1948 Senate primary race and ruthless rise to political power."),
        ("The Power Broker", "Robert A. Caro", "9780394720241", "How Robert Moses shaped New York City infrastructure and wielded unchecked power for decades."),
        ("Every Good Boy Does Fine", "Jeremy Denk", "9780812996074", "A concert pianist shares his classical education, music lessons, and love for piano masterpieces.")
    ],

    "History": [
        ("White Mughals", "William Dalrymple", "9780143030461", "Love and betrayal in 18th-century India between a British diplomat and a Deccani noblewoman."),
        ("Koh-i-Noor", "William Dalrymple & Anita Anand", "9781635570762", "The history of the world's most infamous diamond across Persian, Sikh, and British empires."),
        ("The Golden Road", "William Dalrymple", "9781635570786", "How ancient Indian mathematical, religious, and trade ideas transformed Asia and the West."),
        ("Debt: The First 5,000 Years", "David Graeber", "9781612191294", "An anthropological history of credit, money, and social debt relationships since ancient times."),
        ("Bullshit Jobs: A Theory", "David Graeber", "9781501143311", "Analyzing societal growth of meaningless employment and its psychological toll."),
        ("Pirate Enlightenment, or the Real Libertalia", "David Graeber", "9780374610197", "Exploring democratic pirate societies off the coast of 18th-century Madagascar."),
        ("The Templars", "Dan Jones", "9780525428304", "The rise, military exploits, and sudden destruction of the Knights Templar."),
        ("Crusaders", "Dan Jones", "9780525428328", "A human history of the medieval holy wars told through diverse eyewitness accounts."),
        ("Henry V", "Dan Jones", "9780525428342", "The rise and military victory at Agincourt of England's greatest warrior king."),
        ("Say Nothing", "Patrick Radden Keefe", "9780385521314", "A true story of murder, memory, and IRA secret operations in Northern Ireland."),
        ("Empire of Pain", "Patrick Radden Keefe", "9780385545686", "The secret history of the Sackler dynasty behind Valium, OxyContin, and the opioid crisis."),
        ("Rogues: True Stories of Grifters, Killers, Rebels and Outlaws", "Patrick Radden Keefe", "9780593466322", "Twelve investigative articles profiling international arms dealers, fakes, and criminals."),
        ("The Wager", "David Grann", "9780593489413", "A shipwreck, mutiny, and court martial following HMS Wager's disaster off Patagonia in 1742."),
        ("Killers of the Flower Moon", "David Grann", "9780307742483", "The Osage Indian murders in 1920s Oklahoma and the early investigations of J. Edgar Hoover's FBI."),
        ("The Lost City of Z", "David Grann", "9781400078455", "British explorer Percy Fawcett's fatal 1925 quest into the Amazon looking for an ancient city."),
        ("Agent Sonya", "Ben Macintyre", "9780241408506", "The true story of Ursula Kuczynski, a suburban housewife who served as a Soviet super-spy."),
        ("Operation Mincemeat", "Ben Macintyre", "9780307453298", "How British intelligence used a dead tramp carrying fake papers to deceive Hitler in 1943."),
        ("The Spy and the Traitor", "Ben Macintyre", "9781101904213", "KGB officer Oleg Gordievsky's covert work for MI6 during the Cold War."),
        ("SAS: Rogue Heroes", "Ben Macintyre", "9781101904183", "The secret WWII origins of Britain's Special Air Service elite commando force."),
        ("Colditz: Prisoners of the Castle", "Ben Macintyre", "9780241408520", "The high-security German castle holding allied POW officers and their escape attempts."),
        ("Prisoners of Geography", "Tim Marshall", "9781501121470", "Ten maps explaining global geopolitics, conflict, and economic power."),
        ("The Power of Geography", "Tim Marshall", "9781982167035", "Ten regions shaping the future of global politics in the 21st century."),
        ("The Looming Tower", "Lawrence Wright", "9781400030842", "Al-Qaeda and the road to 9/11 tracing intelligence failures and fundamentalist origins."),
        ("God Save Texas", "Lawrence Wright", "9780525435006", "A journey through political, economic, and cultural dynamics in modern Texas."),
        ("The Blood of Heroes", "James Donovan", "9780316053730", "The 13-day siege of the Alamo and the fight for Texas independence."),
        ("A World Undone", "G.J. Meyer", "9780553382402", "Comprehensive single-volume history of World War I from 1914 to 1918."),
        ("The Sleepwalkers", "Christopher Clark", "9780061146664", "How Europe went to war in 1914 through diplomatic miscalculations."),
        ("Iron Kingdom", "Christopher Clark", "9780674031968", "The rise and fall of Prussia from 1600 to 1947."),
        ("Revolutions: 1848", "Christopher Clark", "9780061146688", "The spring of nations uprisings across European capitals."),
        ("The Facemaker", "Lindsey Fitzharris", "9780374257224", "How Harold Gillies pioneered modern plastic surgery to rebuild disfigured WWI soldiers."),
        ("The Butcher's Trail", "Julian Borger", "9781501152191", "The manhunt for Balkan war criminals responsible for ethnic cleansing in the 1990s."),
        ("Voices from Chernobyl", "Svetlana Alexievich", "9780312424183", "Oral history of the 1986 nuclear disaster recorded by the Belarusian Nobel laureate."),
        ("The Unwomanly Face of War", "Svetlana Alexievich", "9780399588723", "Firsthand testimonies of Soviet women who fought on the frontlines during World War II.")
    ],

    "Philosophy": [
        ("Justice: What's the Right Thing to Do?", "Michael J. Sandel", "9780374532505", "Exploring ethical dilemmas through utilitarianism, Kantian ethics, and civic virtue."),
        ("What Money Can't Buy", "Michael J. Sandel", "9780374533656", "Examining the moral limits of free markets in civic life and personal decisions."),
        ("The Tyranny of Merit", "Michael J. Sandel", "9780374289980", "How meritocracy creates hubris among winners and resentment among the left behind."),
        ("The Righteous Mind", "Jonathan Haidt", "9780307455772", "Why good people are divided by politics and religion through moral foundation theory."),
        ("The Coddling of the American Mind", "Jonathan Haidt & Greg Lukianoff", "9780735224896", "How good intentions and bad ideas are setting up a generation for failure."),
        ("The Anxious Generation", "Jonathan Haidt", "9780593655030", "How the rewiring of childhood through smartphones drove a youth mental health crisis."),
        ("Thinking in Bets", "Annie Duke", "9780735316354", "Making decision framework under uncertainty from a World Series of Poker champion."),
        ("Quit: The Power of Knowing When to Walk Away", "Annie Duke", "9780593422991", "The skill of quitting early to make room for better opportunities."),
        ("How to Think Like a Roman Emperor", "Donald Robertson", "9781250196620", "Integrating Stoic philosophy with modern cognitive behavioral therapy principles."),
        ("Courage Is Calling", "Ryan Holiday", "9780593191675", "Overcoming fear and practicing physical, moral, and everyday courage."),
        ("Discipline Is Destiny", "Ryan Holiday", "9780593191699", "The power of self-control, temperament, and habits in achieving greatness."),
        ("Right Thing Right Now", "Ryan Holiday", "9780593191712", "Living a life of character, integrity, and daily moral duty."),
        ("Drunk: How We Sipped, Danced, and Stumbled", "Edward Slingerland", "9780316453387", "An evolutionary inquiry into why humans consume alcohol and its role in civilization."),
        ("What We Owe the Future", "William MacAskill", "9781541618626", "The case for longtermism and protecting the future of humanity across millennia."),
        ("Doing Good Better", "William MacAskill", "9781594634017", "How effective altruism can help you make a measurable difference with your career and donations."),
        ("The Precipice: Existential Risk", "Toby Ord", "9781541675407", "Evaluating natural and anthropogenic existential risks facing human survival."),
        ("Rationality: What It Is, Why It Seems Scarce", "Steven Pinker", "9780525561996", "Exploring logic, probability, and critical thinking tools for daily life."),
        ("Enlightenment Now", "Steven Pinker", "9780525427575", "The case for reason, science, humanism, and global progress."),
        ("The Better Angels of Our Nature", "Steven Pinker", "9780143122012", "Why global violence has declined throughout human history."),
        ("The Blank Slate", "Steven Pinker", "9780142003343", "The modern denial of human nature and its political and moral implications."),
        ("The Stuff of Thought", "Steven Pinker", "9780143114246", "How language acts as a window into human nature and thought structure."),
        ("The Sense of Style", "Steven Pinker", "9780143127796", "A cognitive scientist's guide to writing clear, engaging prose in the 21st century."),
        ("Philosophy of Mind", "Jaegwon Kim", "9780813344584", "Epistemological inquiry into the mind-body problem and physicalism."),
        ("Ethics: Inventing Right and Wrong", "J.L. Mackie", "9780140135589", "Formulating error theory and anti-realist moral philosophy."),
        ("Naming and Necessity", "Saul Kripke", "9780631128014", "Landmark lectures in analytic philosophy on rigid designators and necessary truths."),
        ("Word and Object", "Willard Van Orman Quine", "9780262670012", "Indeterminacy of translation and ontological relativity."),
        ("The View From Nowhere", "Thomas Nagel", "9780195056440", "Reconciling subjective personal viewpoints with objective reality."),
        ("Mortal Questions", "Thomas Nagel", "9780521406031", "Essays on death, moral luck, absurdities, and ethics."),
        ("Reasons and Persons", "Derek Parfit", "9780198249085", "Challenging conventional theories of personal identity and ethics."),
        ("On What Matters", "Derek Parfit", "9780199572809", "Converging Kantianism, Contractualism, and Consequentialism into one peak."),
        ("The Sovereignty of Good", "Iris Murdoch", "9780415253994", "Moral philosophy arguing for attention to reality and unselfish goodness."),
        ("Practical Ethics", "Peter Singer", "9780521707688", "Applying preference utilitarianism to modern ethical challenges."),
        ("Animal Liberation", "Peter Singer", "9780061711305", "The founding text of the modern animal rights movement.")
    ],

    "Young Adult": [
        ("Firekeeper's Daughter", "Angeline Boulley", "9781250766564", "An Ojibwe teen goes undercover to investigate a deadly new drug threatening her native community."),
        ("Warrior Girl Unearthed", "Angeline Boulley", "9781250766588", "Perry Firekeeper-Birch uncovers stolen tribal remains and missing indigenous women."),
        ("Legendborn", "Tracy Deonn", "9781534441606", "A grieving Black teen infiltrates a secret Arthurian society at UNC Chapel Hill."),
        ("Bloodmarked", "Tracy Deonn", "9781534441637", "Bree fights the Order of the Scion while mastering her ancestral rootcraft magic."),
        ("Cemetery Boys", "Aiden Thomas", "9781250250667", "A trans Latinx boy summons a ghost to prove his brujo identity, but the spirit refuses to leave."),
        ("The Sunbearer Trials", "Aiden Thomas", "9781250822130", "Semideoses compete in divine trials to select a sacrificed lightbearer to keep the sun alive."),
        ("Ain't Burned Bright", "Jason Reynolds", "9781534439351", "A poetic, three-breath reflection on family, race, and breathing during a global crisis."),
        ("Look Both Ways", "Jason Reynolds", "9781481438285", "Ten stories following different middle schoolers walking home after the dismissal bell."),
        ("Ghost", "Jason Reynolds", "9781481450157", "A boy with natural running talent joins an elite middle school track team while fleeing his past."),
        ("Patina", "Jason Reynolds", "9781481450188", "Patina copes with family pressure and competitive track relay team dynamics."),
        ("Sunny", "Jason Reynolds", "9781481450218", "Sunny quits track to pursue dancing while honoring his late mother's legacy."),
        ("Lu", "Jason Reynolds", "9781481450249", "Lu faces gold-medal expectations and personal honesty on and off the track."),
        ("Felix Ever After", "Kacen Callender", "9780062820259", "A Black, trans, queer teen plots revenge against a bully, accidentally discovering true love."),
        ("King and the Dragonflies", "Kacen Callender", "9780544802162", "A twelve-year-old in Louisiana believes his late brother has been reincarnated as a dragonfly."),
        ("Iron Widow", "Xiran Jay Zhao", "9781643750866", "Zetian pilot-mates gigantean Mechas to avenge her sister in a patriarchal sci-fi China."),
        ("Zachary Ying and the Dragon Emperor", "Xiran Jay Zhao", "9781534483774", "A Chinese-American boy is possessed by the First Emperor of China to complete an AR quest."),
        ("A Snake Falls to Earth", "Darcie Little Badger", "9781646140923", "A Lipan Apache girl and a cottonmouth snake-person unite to save a dying ecosystem."),
        ("Elatsoe", "Darcie Little Badger", "9781646140053", "An Lipan Apache teen who can raise ghost animals investigates her cousin's murder in a magical town."),
        ("The Marrow Thieves", "Cherie Dimaline", "9781770864863", "Indigenous people are hunted for their bone marrow, which holds the key to lost dreams."),
        ("Hunting By Stars", "Cherie Dimaline", "9781419753473", "Frenchie is captured by government agents operating residential schools."),
        ("The Grace Year", "Kim Liggett", "9781250145444", "Sixteen-year-old girls are banished to the wilderness for one year to rid themselves of dangerous magic."),
        ("Sadie", "Courtney Summers", "9781250105714", "A girl relentlessly hunts down her sister's killer while a true-crime podcaster tracks her trail."),
        ("I'm Not Your Perfect Mexican Daughter", "Erika L. Sánchez", "9781524715809", "Julia tries to piece together her sister's secret life after a tragic accident in Chicago."),
        ("Clap When You Land", "Elizabeth Acevedo", "9780062882769", "Two sisters in NYC and the Dominican Republic learn of each other after their father dies in a plane crash."),
        ("The Poet X", "Elizabeth Acevedo", "9780062662804", "Xiomara pours her feelings into slam poetry to navigate her mother's strict religious rules."),
        ("With the Fire on High", "Elizabeth Acevedo", "9780062662835", "A teen mother in Philadelphia pursues her passion for culinary arts."),
        ("Family Lore", "Elizabeth Acevedo", "9780063207264", "Four Dominican women with supernatural gifts gather for a living wake in NYC."),
        ("The Astonishing Color of After", "Emily X.R. Pan", "9780316463997", "Leigh travels to Taiwan convinced her mother turned into a red bird after committing suicide."),
        ("An Arrow to the Moon", "Emily X.R. Pan", "9780316464055", "Romeo and Juliet meets Chinese mythology as two high schoolers face family rivalries."),
        ("Legendborn", "Tracy Deonn", "9781534441606", "A teenager uncovers Arthurian magic and ancestral rootcraft."),
        ("Raybearer", "Jordan Ifueko", "9781419739828", "Tarisai is bound by a magical spell to kill the crown prince she was trained to protect."),
        ("Redemptor", "Jordan Ifueko", "9781419749896", "Empress Tarisai must earn the respect of the underworld spirits to prevent sacrifice."),
        ("A Blade So Black", "L.L. McKinney", "9781250153906", "An Atlanta teen battles nightmares in Wonderland while keeping up her high school grades.")
    ],

    "Poetry": [
        ("Time Is a Mother", "Ocean Vuong", "9780593300237", "A luminous collection examining grief, memory, and personal recovery after his mother's death."),
        ("Citizen: An American Lyric", "Claudia Rankine", "9781556594625", "Poetic commentary on microaggressions, racial violence, and national identity."),
        ("Just Us: An American Conversation", "Claudia Rankine", "9781644450215", "Essays, poems, and images interrogating whiteness, privilege, and social discourse."),
        ("Don't Call Us Dead", "Danez Smith", "9781556595158", "Poems reimagining an afterlife for Black men free from police violence and illness."),
        ("Homie", "Danez Smith", "9781644450109", "An anthem of friendship, community, and solidarity amidst grief and systemic loss."),
        ("The Tradition", "Jericho Brown", "9781556595868", "Pulitzer Prize-winning collection introducing the duplex poetic form to address terror and intimacy."),
        ("The New Testament", "Jericho Brown", "9781556594571", "Musings on illness, race, brotherly love, and physical desire."),
        ("Deaf Republic", "Ilya Kaminsky", "9781556595318", "A parable in verse set in an occupied town where citizens strike back by pretending to be deaf."),
        ("Dancing in Odessa", "Ilya Kaminsky", "9781556591860", "Lyrical reflections on childhood in Ukraine, family exile, and memory."),
        ("Postcolonial Love Poem", "Natalie Diaz", "9781644450086", "Pulitzer-winning poems honoring indigenous bodies, river ecosystems, and queer desire."),
        ("When My Brother Was an Aztec", "Natalie Diaz", "9781556593833", "Raw verse addressing addiction's toll on a Mojave family."),
        ("An American Sunrise", "Joy Harjo", "9780393652116", "The US Poet Laureate reflects on the Trail of Tears, ancestral lands, and resilience."),
        ("Life on Mars", "Tracy K. Smith", "9780551120017", "Sci-fi imagery, Bowie tributes, and space probes examine cosmic existence and loss."),
        ("Wade in the Water", "Tracy K. Smith", "9780525521754", "Historic letters and poems examining American slavery, civil rights, and empathy."),
        ("Keep Moving: Notes on Loss, Creativity, and Change", "Maggie Smith", "9781982141554", "Quotes and essays encouraging daily hope and transformation after divorce."),
        ("You Could Make This Place Beautiful", "Maggie Smith", "9781982185855", "A moving memoir exploring marriage breakdown, motherhood, and rebuilding."),
        ("Good Bones", "Maggie Smith", "9781942683452", "Poetry embracing the beauty and darkness of the world for the sake of our children."),
        ("The Hurting Kind", "Ada Limón", "9781644450826", "Exploring connected ecosystems, family histories, and deep empathy for animals."),
        ("The Carrying", "Ada Limón", "9781556595387", "National Book Critics Circle winner on fertility, chronic pain, and quiet moments."),
        ("Bright Dead Things", "Ada Limón", "9781556594830", "Examining wild landscapes, urban transitions, and finding home."),
        ("Float", "Anne Carson", "9781101947722", "A collection of twenty individual chapbooks meant to be read in any order."),
        ("Red Doc>", "Anne Carson", "9780307959775", "A verse sequel to Autobiography of Red following Geryon into adulthood."),
        ("Autobiography of Red", "Anne Carson", "9780375701290", "A novel in verse adapting Greek myth to tell the story of a winged red monster."),
        ("Decreation", "Anne Carson", "9781400043491", "Essays, poems, and opera librettos exploring love and self-effacement."),
        ("The Crying Book", "Heather Christle", "9781948226400", "A poetic study on the science, history, and emotion of tears."),
        ("Obit", "Victoria Chang", "9781556595745", "Obituaries written in verse for objects, emotions, and memories lost after her mother's death."),
        ("Dearly", "Margaret Atwood", "9780063032491", "Reflections on aging, environmental decay, time, and love."),
        ("Call Us What We Carry", "Amanda Gorman", "9780593465066", "Poetry examining collective grief, memory, and healing after global crises."),
        ("The Hill We Climb", "Amanda Gorman", "9780593465271", "The historic presidential inauguration poem celebrating hope and unity."),
        ("Catalog of Unabashed Gratitude", "Ross Gay", "9780822963493", "Celebrating gardens, orchard trees, laughter, and community joy."),
        ("The Book of Delights", "Ross Gay", "9781616207922", "Daily essays detailing small moments of delight recorded over one year."),
        ("Inciting Joy", "Ross Gay", "9781643753041", "Exploring how caring for one another through grief builds lasting joy."),
        ("Finna", "Nate Marshall", "9780593132845", "Verse celebrating Black dialect, Chicago neighborhoods, and cultural heritage.")
    ],

    "Classic Literature": [
        ("The Master and Margarita", "Mikhail Bulgakov", "9780143108283", "The Devil visits 1930s Soviet Moscow with a talking black cat, disrupting bureaucratic life."),
        ("Heart of a Dog", "Mikhail Bulgakov", "9780060731878", "A Moscow scientist implants human organs into a stray dog, creating a rude Soviet citizen."),
        ("The Death of Ivan Ilyich", "Leo Tolstoy", "9780307951335", "A high court judge reflects on the insincerity of his past life as he faces terminal illness."),
        ("The Kreutzer Sonata", "Leo Tolstoy", "9780140449198", "A man on a train recounts the jealous rage that led to his wife's murder."),
        ("Notes from Underground", "Fyodor Dostoevsky", "9780679734529", "A bitter, isolated ex-civil servant delivers a monologue on free will and spite."),
        ("The Idiot", "Fyodor Dostoevsky", "9780375702419", "The saintly Prince Myshkin encounters corruption and passionate intrigue in Saint Petersburg."),
        ("Demons (The Possessed)", "Fyodor Dostoevsky", "9780679734567", "A provincial town is thrown into political chaos by a radical revolutionary cell."),
        ("Fathers and Sons", "Ivan Turgenev", "9780140441475", "Nihilist student Bazarov challenges traditional aristocratic values of the older generation."),
        ("Dead Souls", "Nikolai Gogol", "9780679776451", "Chichikov travels through rural Russia buying up deceased serfs to secure a land loan."),
        ("The Overcoat and Other Tales", "Nikolai Gogol", "9780486270579", "Surreal Russian tales including a stolen overcoat that haunts Saint Petersburg officials."),
        ("Oblomov", "Ivan Goncharov", "9780140449181", "A young Russian nobleman spends his days lying in bed, incapable of taking action."),
        ("The Cherry Orchard", "Anton Chekhov", "9780486266824", "An aristocratic family loses their beloved estate and cherry orchard to a rising merchant."),
        ("Cousin Bette", "Honoré de Balzac", "9780140445145", "A poor relative plots the ruin of her wealthy Parisian family out of jealousy."),
        ("Père Goriot", "Honoré de Balzac", "9780140449723", "An old man sacrifices everything for his ungrateful daughters in 1819 Paris."),
        ("The Red and the Black", "Stendhal", "9780140447644", "Julien Sorel uses charm and intellect to climb French social strata during the Restoration."),
        ("Germinal", "Émile Zola", "9780140447422", "A violent coal miners' strike in northern France highlights working-class suffering."),
        ("Nana", "Émile Zola", "9780140447538", "A high-class Parisian courtesan drives wealthy aristocrats to financial ruin."),
        ("Bel-Ami", "Guy de Maupassant", "9780140443158", "An ambitious journalist uses wealthy mistresses to rise in Paris media society."),
        ("The Way We Live Now", "Anthony Trollope", "9780140433937", "A fraudulent financier cons London high society in 19th-century Britain."),
        ("Barchester Towers", "Anthony Trollope", "9780140432039", "Clerical politics and romantic intrigue disrupt a quiet English cathedral town."),
        ("Middlemarch", "George Eliot", "9780141439549", "The lives, marriages, and idealisms of residents in a provincial English town."),
        ("Silas Marner", "George Eliot", "9780141439600", "A reclusive weaver regains faith in humanity when he adopts a golden-haired orphan girl."),
        ("The Mill on the Floss", "George Eliot", "9780141439624", "Maggie Tulliver struggles against Victorian conventions along the River Floss."),
        ("Tess of the d'Urbervilles", "Thomas Hardy", "9780141439594", "A poor country girl suffers social hypocrisy after being seduced by a wealthy relative."),
        ("Far from the Madding Crowd", "Thomas Hardy", "9780141439655", "Independent Bathsheba Everdene manages her inherited farm while courted by three men."),
        ("The Mayor of Casterbridge", "Thomas Hardy", "9780141439785", "A man sells his wife in a drunken fit and rises to mayor, only for his past to return."),
        ("Jude the Obscure", "Thomas Hardy", "9780141439655", "A working-class scholar is denied university admission and faces social tragedy."),
        ("The House of Mirth", "Edith Wharton", "9780140187298", "Lily Bart attempts to secure a wealthy husband in NYC high society while staying true to herself."),
        ("The Age of Innocence", "Edith Wharton", "9780140189704", "Newland Archer torn between his conventional fiancee and her unconventional cousin."),
        ("Ethan Frome", "Edith Wharton", "9780140188042", "A bitter New England farmer falls in love with his wife's cousin with tragic results."),
        ("Nostromo", "Joseph Conrad", "9780141441269", "Silver mining and political corruption in a fictional South American republic."),
        ("The Secret Agent", "Joseph Conrad", "9780141441580", "An anarchist store owner in London is coerced into bombing the Greenwich Observatory."),
        ("The Custom of the Country", "Edith Wharton", "9780140187106", "Undine Spragg uses charm and social ambition to climb international high society.")
    ],

    "Non-Fiction": [
        ("Chip War", "Chris Miller", "9781982172008", "The geopolitical fight for semiconductor microchips that power modern computing and defense."),
        ("Ultra-Processed People", "Chris van Tulleken", "9781399801263", "The science behind industrially processed food and its impact on human metabolism."),
        ("Outlive: The Science and Art of Longevity", "Peter Attia", "9780593236598", "Preventative medicine strategies to extend healthspan and prevent chronic illness."),
        ("Lifespan", "David A. Sinclair", "9781501191978", "Harvard geneticist explains cellular aging mechanisms and potential interventions."),
        ("Why We Sleep", "Matthew Walker", "9781501144318", "Neuroscientist explores how sleep impacts memory, immunity, and overall health."),
        ("The Obesity Code", "Jason Fung", "9781771641258", "Understanding insulin resistance and intermittent fasting to manage weight."),
        ("Fiber Fueled", "Will Bulsiewicz", "9780593084564", "Gastroenterologist's plant-based guide to gut microbiome health."),
        ("The Mind-Gut Connection", "Emeran Mayer", "9780062436702", "How communication between gut microbes and the brain influences mood and health."),
        ("Brain Maker", "David Perlmutter", "9780316380102", "The connection between gut microbes and neurological health."),
        ("The Culture Code", "Daniel Coyle", "9780804176989", "Secrets of safety, vulnerability, and purpose behind world-class teams."),
        ("The Premonition", "Michael Lewis", "9780393881554", "A band of rogue medical visionaries anticipates and fights global pandemic threats."),
        ("The Big Short", "Michael Lewis", "9780393338829", "The eccentric investors who foresaw the 2008 subprime mortgage housing collapse."),
        ("Flash Boys", "Michael Lewis", "9780393351590", "How high-frequency traders rigged the US stock market and the team that exposed it."),
        ("Going Infinite", "Michael Lewis", "9781324074335", "The rapid rise and catastrophic collapse of Sam Bankman-Fried and FTX."),
        ("The Fifth Risk", "Michael Lewis", "9780393357455", "The dedicated federal employees managing critical risks in US government departments."),
        ("The Undoing Project", "Michael Lewis", "9780393354775", "The groundbreaking friendship between psychologists Daniel Kahneman and Amos Tversky."),
        ("Code Girls", "Liza Mundy", "9780316352536", "The untold story of 10,000 American women cryptanalysts who broke Axis codes in WWII."),
        ("The Signal and the Noise", "Nate Silver", "9780143125082", "Why so many predictions fail—but some don't—in politics, sports, and weather."),
        ("Bad Samaritans", "Ha-Joon Chang", "9781596915985", "Challenging free-market dogma and explaining economic development history."),
        ("Economics: The User's Guide", "Ha-Joon Chang", "9781620408124", "An accessible overview of competing economic schools of thought."),
        ("The Silk Roads", "Peter Frankopan", "9781101912379", "Re-centering world history on the trade networks connecting Asia, Europe, and Africa."),
        ("The New Silk Roads", "Peter Frankopan", "9780525565055", "Examining modern economic power shifts toward Central Asia and China."),
        ("The Earth Transformed", "Peter Frankopan", "9780525659167", "How climate change shaped human history from ancient times to the present."),
        ("Vaxxers", "Sarah Gilbert & Catherine Green", "9780063116801", "The Oxford scientists who developed the Oxford-AstraZeneca COVID-19 vaccine."),
        ("An Elegant Defense", "Matt Richtel", "9780062698582", "Exploring the science of the human immune system through patient stories."),
        ("I Contain Multitudes", "Ed Yong", "9780062368607", "The grand tour of microbes living inside animals and shaping ecosystems."),
        ("An Immense World", "Ed Yong", "9780593133231", "How animal senses reveal the hidden realms around us."),
        ("Entangled Life", "Merlin Sheldrake", "9780525510314", "How fungi make our worlds, change our minds, and shape our futures."),
        ("The Hidden Life of Trees", "Peter Wohlleben", "9781771642484", "What trees feel and how they communicate through underground fungal networks."),
        ("The Feather Thief", "Kirk Wallace Johnson", "9781101981610", "A natural history museum heist involving rare salmon flies and Victorian bird skins."),
        ("The Orchid Thief", "Susan Orlean", "9780449003718", "A journey through Florida swamps exploring orchid obsession and eccentric poachers."),
        ("The Library Book", "Susan Orlean", "9781476740195", "Investigating the disastrous 1986 Los Angeles Public Library fire."),
        ("On Writing", "Stephen King", "9781439156810", "A memoir of the craft and practical advice for writers."),
        ("The Art of Memoir", "Mary Karr", "9780062236692", "Master class on truth, memory, and writing personal narrative.")
    ]
}

def escape_sql_str(val):
    return val.replace("'", "''")

def main():
    target_path = r"c:\pdd1\database\seed_books_batch_2.sql"
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    statements = []
    statements.append("-- PageMind Database Seed Script: Batch 2 of 10 (500 Books across 15 Genres)\n")
    statements.append("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
    statements.append("USE pagemind;\n\n")

    count = 0
    for genre, books in GENRE_DATA_BATCH_2.items():
        statements.append(f"-- =======================================================\n")
        statements.append(f"-- Genre: {genre} ({len(books)} books)\n")
        statements.append(f"-- =======================================================\n")
        
        for title, author, isbn, desc in books:
            count += 1
            e_title = escape_sql_str(title)
            e_author = escape_sql_str(author)
            e_genre = escape_sql_str(genre)
            e_desc = escape_sql_str(desc)
            
            if isbn:
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
            else:
                cover_url = f"https://via.placeholder.com/300x450/1e1b4b/a5b4fc?text={urllib.parse.quote(title)}"
            e_cover_url = escape_sql_str(cover_url)
            
            amazon_url = f"https://www.amazon.in/s?k={urllib.parse.quote(f'{title} {author}')}"
            flipkart_url = f"https://www.flipkart.com/search?q={urllib.parse.quote(f'{title} {author}')}"
            
            buy_links_dict = {
                "amazon": amazon_url,
                "flipkart": flipkart_url
            }
            buy_links_json = json.dumps(buy_links_dict)
            e_buy_links_json = escape_sql_str(buy_links_json)
            
            pub_year = get_published_year(title, author, genre, desc, isbn)

            
            rating = get_rating(title, author)

            
            sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{e_title}', '{e_author}', '{e_genre}', '{e_desc}', '{e_cover_url}', '{e_buy_links_json}', {pub_year}, {rating});\n"
            statements.append(sql)
            
        statements.append("\n")

    with open(target_path, "w", encoding="utf-8") as f:
        f.writelines(statements)

    print(f"Successfully generated {target_path} with {count} book insert statements across {len(GENRE_DATA_BATCH_2)} genres!")

if __name__ == "__main__":
    main()
