# generate_batch_8.py
# Generates seed_books_batch_8.sql containing 500 unique book insert statements across 15 genres

from book_metadata_utils import get_rating, get_published_year
import json
import os

genres_data = {
    "Fiction": [
        ("Wolf Hall", "Hilary Mantel", "9780312429980", "Thomas Cromwell navigates Tudor court politics to secure Henry VIII's annulment from Catherine of Aragon."),
        ("Bring Up the Bodies", "Hilary Mantel", "9780312430030", "Cromwell orchestrates the trial and downfall of Anne Boleyn at the King's command."),
        ("The Mirror & the Light", "Hilary Mantel", "9780525658603", "Cromwell reaches the pinnacle of wealth and power before facing envy and royal betrayal."),
        ("Beyond Black", "Hilary Mantel", "9780007157761", "Psychic medium Alison Hart travels suburban halls while haunted by her grotesque spirit guide Morris."),
        ("A Place of Greater Safety", "Hilary Mantel", "9780140171037", "Danton, Robespierre, and Camille Desmoulins ignite and are consumed by the French Revolution."),
        ("Eight Months on Ghazzah Street", "Hilary Mantel", "9780071577780", "Frances Shore lives in a restrictive apartment block in Jeddah, uncovering suspicious neighboring activities."),
        ("Fludd", "Hilary Mantel", "9780805063004", "Mysterious Father Fludd arrives in a dreary Lancashire village, sparking bizarre transformations."),
        ("A Change of Climate", "Hilary Mantel", "9780805063011", "Ralph and Anna Eldred struggle with a traumatic secret stemming from their missionary work in Africa."),
        ("An Experiment in Love", "Hilary Mantel", "9780805063028", "Three working-class girls attend London University in the 1970s dealing with ambition and eating disorders."),
        ("The Giant, O'Brien", "Hilary Mantel", "9780805063035", "Irish giant Charles O'Brien arrives in 1780s London, pursued by surgeon John Hunter."),
        ("The English Patient", "Michael Ondaatje", "9780679745204", "Four people bonded by WWII trauma reside in a ruined Tuscan villa caring for a burned pilot."),
        ("In the Skin of a Lion", "Michael Ondaatje", "9780679770305", "Patrick Lewis works on Toronto bridges and tunnels alongside immigrant laborers in the 1920s."),
        ("Anil's Ghost", "Michael Ondaatje", "9780375724374", "Forensic anthropologist Anil Tissera returns to civil-war-torn Sri Lanka to investigate extrajudicial killings."),
        ("Divisadero", "Michael Ondaatje", "9780307266354", "Anna, Claire, and Coop's childhood in Northern California is shattered by a sudden act of violence."),
        ("The Cat's Table", "Michael Ondaatje", "9780307743534", "Eleven-year-old Michael embarks on a twenty-one day ocean liner voyage from Colombo to England."),
        ("Warlight", "Michael Ondaatje", "9780525521198", "Fourteen-year-old Nathaniel and his sister are left in post-WWII London under the care of enigmatic guardians."),
        ("Coming Through Slaughter", "Michael Ondaatje", "9780679767855", "A fictionalized biography of jazz cornet pioneer Buddy Bolden in turn-of-the-century New Orleans."),
        ("Running in the Family", "Michael Ondaatje", "9780679746690", "Ondaatje's poetic memoir exploring his eccentric family history in colonial Ceylon."),
        ("The Remains of the Day", "Kazuo Ishiguro", "9780679731726", "Stevens, an English butler at Darlington Hall, reflects on his life of loyal service and suppressed love."),
        ("Never Let Me Go", "Kazuo Ishiguro", "9781400078776", "Kathy, Tommy, and Ruth grow up at Hailsham boarding school preparing for their tragic human donor destiny."),
        ("The Buried Giant", "Kazuo Ishiguro", "9780307271037", "Elderly couple Axl and Beatrice travel through mist-shrouded post-Arthurian Britain to find their lost son."),
        ("Klara and the Sun", "Kazuo Ishiguro", "9780593318171", "Klara, an Artificial Friend with solar power, observes human emotion while caring for sick Josie."),
        ("An Artist of the Floating World", "Kazuo Ishiguro", "9780679722663", "Retired painter Masuji Ono reflects on his pre-WWII imperialist propaganda artwork in post-war Japan."),
        ("A Pale View of Hills", "Kazuo Ishiguro", "9780679722670", "Etsuko, a Japanese woman living in England, copes with her daughter Keiko's suicide by remembering Nagasaki."),
        ("The Unconsoled", "Kazuo Ishiguro", "9780679744184", "Pianist Ryder arrives in a surreal Central European city for a concert surrounded by demanding citizens."),
        ("When We Were Orphans", "Kazuo Ishiguro", "9780375724497", "1930s London detective Christopher Banks returns to Shanghai to solve his parents' childhood disappearance."),
        ("Atonement", "Ian McEwan", "9780385721790", "Thirteen-year-old Briony Tallis makes a false accusation that ruins her sister Cecilia and Robbie's lives."),
        ("Enduring Love", "Ian McEwan", "9780385494144", "A tragic hot air balloon accident leads Jed Parry to develop obsessive erotomania for Joe Rose."),
        ("On Chesil Beach", "Ian McEwan", "9780307386175", "Newlyweds Edward and Florence spend a awkward, fateful wedding night on Dorset coast in 1962."),
        ("Amsterdam", "Ian McEwan", "9780385494243", "Composer Clive and editor Vernon make a euthanasia pact following their mutual lover's funeral."),
        ("Saturday", "Ian McEwan", "9781400076192", "Neurosurgeon Henry Perowne's peaceful day off in 2003 London is disrupted by a minor traffic altercation."),
        ("Solar", "Ian McEwan", "9780307390394", "Nobel laureate Michael Beard steals a deceased colleague's solar energy technology to revamp his career."),
        ("Sweet Tooth", "Ian McEwan", "9780345803450", "Serena Frome is recruited by MI5 in 1972 to fund anti-communist writers, falling for author Tom Haley.")
    ],
    "Mystery": [
        ("The Bat", "Jo Nesbø", "9780062068408", "Inspector Harry Hole travels to Sydney to help Australian police investigate a Norwegian girl's murder."),
        ("Cockroaches", "Jo Nesbø", "9780062068446", "Harry Hole is sent to Bangkok to quietly solve the murder of Norway's ambassador to Thailand."),
        ("The Redbreast", "Jo Nesbø", "9780062068415", "Harry uncovers WWII Norwegian Nazi sympathizers and a rare sniper rifle imported to Oslo."),
        ("Nemesis", "Jo Nesbø", "9780062068422", "Harry investigates a fatal bank robbery and the suspicious suicide of his ex-girlfriend Ellen."),
        ("Devil's Star", "Jo Nesbø", "9780062068439", "A five-pointed diamond star and cut finger are left at murder scenes during an Oslo heatwave."),
        ("The Redeemer", "Jo Nesbø", "9780062068453", "A Salvation Army officer is shot dead in Oslo square by a Croatian hitman who targeted the wrong brother."),
        ("Snowman", "Jo Nesbø", "9780307742995", "Oslo women disappear when the first winter snow falls, leaving snowmen facing their homes."),
        ("The Leopard", "Jo Nesbø", "9780307743008", "Harry Hole is brought back from Hong Kong to hunt a serial killer using a torture device called Leopold's Apple."),
        ("Phantom", "Jo Nesbø", "9780307743015", "Harry returns to Oslo to defend his surrogate son Oleg accused of killing a fellow drug addict."),
        ("Police", "Jo Nesbø", "9780307743022", "Police officers investigating unsolved murder cases are killed at the original crime scenes."),
        ("The Thirst", "Jo Nesbø", "9780385542020", "Harry Hole hunts a killer targeting Tinder users who drinks his victims' blood with iron teeth."),
        ("Knife", "Jo Nesbø", "9780525655398", "Harry wakes up with blood on his hands and no memory after an unspeakable personal tragedy."),
        ("Blood on Snow", "Jo Nesbø", "9780385354196", "Fixer Olav Johansen is hired to assassinate his boss's wife, falling in love with her instead."),
        ("Midnight Sun", "Jo Nesbø", "9780385354219", "Hitman Jon Hansen flees to a remote Arctic village, hiding among a strict religious sect."),
        ("Macbeth", "Jo Nesbø", "9780735221291", "A modern reimagining of Shakespeare's Macbeth set in a drug-ravaged 1970s industrial town."),
        ("The Kingdom", "Jo Nesbø", "9780525657323", "Brothers Roy and Carl Opgard defend their mountain village business from dark family secrets."),
        ("Moon Sun", "Jo Nesbø", "9780593536841", "Harry Hole works as a private investigator in Los Angeles to pay off his late mother's debts."),
        ("The Night House", "Jo Nesbø", "9780593700761", "14-year-old Richard sees a classmate sucked into a telephone receiver in a dark forest town."),
        ("Blood Tie", "Jo Nesbø", "9780593802311", "Roy and Carl Opgard face new police scrutiny over their mountain hotel developments."),
        ("A Judgement in Stone", "Ruth Rendell", "9780307406859", "Eunice Parchment killed the Coverdale family because she could not read or write."),
        ("Live Flesh", "Ruth Rendell", "9780345341259", "Rapist Victor Jenner is released from prison, pursuing the woman engaged to the officer he paralyzed."),
        ("Talking to Strange Men", "Ruth Rendell", "9780061001857", "Schoolboy spy games accidentally intersect with real-world blackmail and murder plots."),
        ("Going Wrong", "Ruth Rendell", "9780446361736", "Guy Curran maintains an obsessive, delusional lifelong obsession with childhood friend Leonora."),
        ("The Crocodile Bird", "Ruth Rendell", "9780061008061", "Liza grows up in isolated Gatehouse mansion unaware her mother Eve murders intrusive men."),
        ("The Keys to the Street", "Ruth Rendell", "9780345408457", "Homeless men in London Regent's Park are murdered and impaled on iron park railings."),
        ("A Sight for Sore Eyes", "Ruth Rendell", "9780345432094", "Obsessive handyman Teddy meets beautiful neglected Francine in a grim story of aesthetic obsession."),
        ("The Lake of Darkness", "Ruth Rendell", "9780345330833", "Martin Winney wins the football pool and buys a house, becoming targeted by a hitman."),
        ("Master of the Moor", "Ruth Rendell", "9780061004117", "Stephen Whalby finds young women strangled on the desolate mist-covered Yorkshire moor."),
        ("The Tree of Hands", "Ruth Rendell", "9780345327291", "Bereaved mother Benet's mentally ill mother kidnaps a child from a London park."),
        ("Harm Done", "Ruth Rendell", "9780446608930", "Inspector Wexford investigates missing teenage girls in a low-income housing estate."),
        ("End in Tears", "Ruth Rendell", "9780307262967", "A brick dropped from a highway bridge kills a teenager, leading Wexford to pregnant girls' secrets."),
        ("The Monster in the Box", "Ruth Rendell", "9780307272713", "Inspector Wexford believes Eric Targo is a lifelong serial killer who has stalked him for decades."),
        ("No Man's Nightingale", "Ruth Rendell", "9781476744872", "Wexford investigates the strangulation murder of female vicar Sarah Hussein in Kingsmarkham.")
    ],
    "Thriller": [
        ("Killing Floor", "Lee Child", "9780451208415", "Ex-military cop Jack Reacher is arrested for murder minutes after stepping off a bus in Margrave, Georgia."),
        ("Die Trying", "Lee Child", "9780451208422", "Reacher is kidnapped off a Chicago street alongside FBI agent Holly Johnson by a militia group."),
        ("Tripwire", "Lee Child", "9780451200266", "Reacher digs pools in Key West until a private investigator searching for him turns up murdered."),
        ("Running Blind", "Lee Child", "9780451200549", "Women who worked with Reacher in the army are being murdered without leaving any physical cause of death."),
        ("Echo Burning", "Lee Child", "9780451206466", "Reacher hitches a ride in Texas with Carmen Greer, who claims her abusive husband wants her dead."),
        ("Without Fail", "Lee Child", "9780451207609", "Reacher is hired by Secret Service agent M.E. Froelich to audit the Vice President's security detail."),
        ("Persuader", "Lee Child", "9780451210845", "Reacher goes undercover in a Maine estate to settle a score with rogue agent Francis Xavier Quinn."),
        ("The Enemy", "Lee Child", "9780451212351", "New Year's Day 1990: Major Reacher investigates a two-star general's death in a sleazy motel."),
        ("One Shot", "Lee Child", "9780451215437", "A sniper kills five people in Indiana, and the arrested suspect tells police: 'Get Jack Reacher.'"),
        ("The Hard Way", "Lee Child", "9780451218551", "Reacher is hired by private military contractor Edward Lane to rescue his kidnapped wife in NYC."),
        ("Bad Luck and Trouble", "Lee Child", "9780451221711", "Members of Reacher's former 110th MP unit are thrown out of helicopters in the California desert."),
        ("Nothing to Lose", "Lee Child", "9780451224880", "Reacher walks between two small Colorado towns—Hope and Despair—and is run out by hostile cops."),
        ("Gone Tomorrow", "Lee Child", "9780451226990", "Reacher spots a woman exhibiting all twelve signs of a suicide bomber on a late-night NYC subway car."),
        ("61 Hours", "Lee Child", "9780451230492", "A tour bus crashes in a South Dakota blizzard, leaving Reacher to protect a key federal trial witness."),
        ("Worth Dying For", "Lee Child", "9780451234032", "Reacher arrives in rural Nebraska and steps between a battered wife and the powerful Duncan clan."),
        ("The Affair", "Lee Child", "9780451234711", "1997: Reacher is sent undercover to a Mississippi town to investigate a murder linked to an army base."),
        ("A Wanted Man", "Lee Child", "9780451238061", "Reacher hitches a ride with three strangers in Nebraska, realizing one passenger is a hostage."),
        ("Never Go Back", "Lee Child", "9780451414199", "Reacher finally reaches HQ in Virginia to meet Major Susan Turner, only to find her arrested."),
        ("Personal", "Lee Child", "9780345544933", "Someone shot at the French president in Paris, and Reacher tracks his old sniper nemesis Rick Shoemaker."),
        ("Make Me", "Lee Child", "9780345544964", "Reacher steps off a train at Mother's Rest, a tiny wheat town hiding a dark dark-web operation."),
        ("Night School", "Lee Child", "9780345544995", "1996: Reacher is sent back to school in Hamburg to stop a $100 million terrorist transaction."),
        ("The Midnight Line", "Lee Child", "9780345545022", "Reacher buys a West Point 2005 class ring in a pawn shop and sets out to return it to its owner."),
        ("Past Tense", "Lee Child", "9780399593482", "Reacher explores his father's birthplace in New Hampshire while young lovers are trapped in a motel."),
        ("Blue Moon", "Lee Child", "9780399593543", "Reacher protects an elderly man on a bus, plunging into a gang war between Ukrainian and Albanian mobs."),
        ("Sentinel", "Lee Child & Andrew Child", "9781984818461", "Reacher rescues an IT manager in Tennessee who uncovered ransomware corruption in city records."),
        ("Better Off Dead", "Lee Child & Andrew Child", "9781984818508", "Reacher comes across a wrecked car in the desert, helping an ex-army officer find her kidnapped brother."),
        ("No Plan B", "Lee Child & Andrew Child", "9781984818546", "Reacher witnesses a woman pushed under a bus in Colorado, uncovering an arson and private prison scheme."),
        ("The Secret", "Lee Child & Andrew Child", "9781984818584", "1992: Reacher investigates a series of mysterious deaths of scientists involved in a 1969 secret project."),
        ("Tell No One", "Harlan Coben", "9780440236702", "Eight years after his wife Elizabeth was murdered, Dr. David Beck receives an email showing her alive."),
        ("Gone for Good", "Harlan Coben", "9780440236733", "Will Klein's brother disappeared eleven years ago after a neighbor was murdered; now his girlfriend vanishes."),
        ("No Second Chance", "Harlan Coben", "9780440240983", "Dr. Marc Seidman wakes from a coma to discover his wife killed and six-month-old daughter kidnapped."),
        ("Just One Look", "Harlan Coben", "9780440241775", "Grace Lawson picks up family photo prints and finds an old photo showing her husband with a strange woman."),
        ("The Woods", "Harlan Coben", "9780440243915", "Paul Copeland's sister vanished in the woods twenty years ago; now a murdered man connects to that night.")
    ],
    "Romance": [
        ("Vision in White", "Nora Roberts", "9780425230008", "Wedding photographer Mackensie Elliot falls for safe, reliable English teacher Carter Maguire."),
        ("Bed of Roses", "Nora Roberts", "9780425238011", "Florist Emma Grant discovers romance with longtime friend and architect Jack Cooke."),
        ("Savor the Moment", "Nora Roberts", "9780425238028", "Pastry chef Laurel McBane risks her heart with her best friend's older brother Delaney Caine."),
        ("Happy Ever After", "Nora Roberts", "9780425238035", "Wedding executive Parker Brown falls for tough mechanics business owner Malcolm Kavanaugh."),
        ("The Next Always", "Nora Roberts", "9780425246023", "Architect Beckett Montgomery renovates a historic Boonsboro inn alongside widowed mother Clare Brewster."),
        ("The Last Boyfriend", "Nora Roberts", "9780425246030", "Owen Montgomery helps Avery MacTavish run her pizza shop while haunted by ghost Lizzie."),
        ("The Hope Chest", "Nora Roberts", "9780425246047", "Ryder Montgomery clashes with social media manager Hope Hewitt at the Boonsboro Inn."),
        ("Dance Upon the Air", "Nora Roberts", "9780451203410", "Nell Channing flees an abusive husband to Three Sisters Island, finding safety with Sheriff Zack Todd."),
        ("Heaven and Earth", "Nora Roberts", "9780451204226", "Deputy Ripley Todd battles her growing witchcraft powers and falls for researcher MacAllister Booke."),
        ("Face the Fire", "Nora Roberts", "9780451206893", "Mia Devlin reconciles with Sam Logan to break an ancient three-century island curse."),
        ("Blue Dahlia", "Nora Roberts", "9780451213198", "Widow Stella Rothchild moves to Harper House garden center, meeting landscaper Logan Kitridge."),
        ("Black Rose", "Nora Roberts", "9780451214225", "Rosalind Harper digs into family history with genealogist Dr. Mitchell Carnegie while haunted by the Harper Bride."),
        ("Red Lily", "Nora Roberts", "9780451218940", "Single mother Hayley Phillips falls for Harper family cousin Stephen Small while resolving ghost grief."),
        ("Blood Magick", "Nora Roberts", "9780425259871", "Branna O'Dwyer guards her heart from Finbar Burke due to their shared ancestor's blood curse."),
        ("Shadow Spell", "Nora Roberts", "9780425259864", "Falconer Connor O'Dwyer fights dark sorcerer Cabhan alongside childhood friend Meara Quinn."),
        ("Dark Witch", "Nora Roberts", "9780425259857", "Iona Sheehan travels to County Mayo, Ireland, finding love with stable owner Boyle McGrath."),
        ("The Awakening", "Nora Roberts", "9781250207265", "Breen Kelly discovers a portal to the magical world of Talamh, learning her true heritage."),
        ("The Becoming", "Nora Roberts", "9781250207296", "Breen trains in magic and sword combat to defend Talamh against her dark grandfather Odran."),
        ("The Choice", "Nora Roberts", "9781250207326", "The final battle for Talamh as Breen unites dragon riders and witches against evil forces."),
        ("Inheritance", "Nora Roberts", "9781250284074", "Sonya MacTavish inherits a Victorian manor in Maine with a centuries-old wedding curse."),
        ("The Mirror", "Nora Roberts", "9781250284104", "Sonya travels through an enchanted mirror into 1800s Ireland to undo the family curse."),
        ("A Court of Thorns and Roses", "Sarah J. Maas", "9781619634442", "Feyre Archeron kills a wolf in the woods and is dragged to Prythian by High Lord Tamlin."),
        ("A Court of Mist and Fury", "Sarah J. Maas", "9781619634466", "Feyre escapes Tamlin's oppressive control to live in the Night Court with High Lord Rhysand."),
        ("A Court of Wings and Ruin", "Sarah J. Maas", "9781619634480", "Feyre plays a dangerous spy game inside the Spring Court to prepare Prythian for King Hybern's war."),
        ("A Court of Frost and Starlight", "Sarah J. Maas", "9781681196312", "Feyre, Rhys, and their Inner Circle rebuild Velaris during Solstice celebrations following the war."),
        ("A Court of Silver Flames", "Sarah J. Maas", "9781681196282", "Nesta Archeron and Cassian train in Valkyrie blade tactics while battling ancient magical artifacts."),
        ("House of Earth and Blood", "Sarah J. Maas", "9781635574043", "Bryce Quinlan teams up with fallen angel Hunt Athalar to avenge her friends' demon murder in Crescent City."),
        ("House of Sky and Breath", "Sarah J. Maas", "9781635574074", "Bryce and Hunt infiltrate Asteri secrets, discovering shocking truths about their world's origin."),
        ("House of Flame and Shadow", "Sarah J. Maas", "9781635574104", "Bryce lands in Prythian while Hunt is imprisoned in Crescent City during global rebellion."),
        ("Throne of Glass", "Sarah J. Maas", "9781619630345", "Assassin Celaena Sardothien competes in a royal tournament to become King's Champion in Adarlan."),
        ("Crown of Midnight", "Sarah J. Maas", "9781619630628", "Celaena serves the king while secretly aiding rebels, discovering her true identity as Aelin Galathynius."),
        ("Heir of Fire", "Sarah J. Maas", "9781619630659", "Aelin travels to Wendlyn to train her Fae fire magic with prince Rowan Whitethorn."),
        ("Queen of Shadows", "Sarah J. Maas", "9781619636040", "Aelin returns to Rifthold to free Chaol, destroy the King's Wyrdkey tower, and rescue Lysandra.")
    ],
    "Fantasy": [
        ("The Name of the Wind", "Patrick Rothfuss", "9780756404741", "Kvothe recounts his youth from troupe performer to University arcana student and legendary wizard."),
        ("The Wise Man's Fear", "Patrick Rothfuss", "9780756407919", "Kvothe seeks court patronage in Vintas, visits the Fae realm of Felurian, and learns Adem mercenary fighting."),
        ("The Slow Regard of Silent Things", "Patrick Rothfuss", "9780756411329", "A standalone novella following Auri's solitary, meticulous existence in the Underthing beneath the University."),
        ("The Narrow Road Between Desires", "Patrick Rothfuss", "9780756419172", "Bast spends a single day making deals and navigating human favors in the village of Newarre."),
        ("The Lies of Locke Lamora", "Scott Lynch", "9780553588942", "Locke Lamora leads the Gentlemen Bastards in high-stakes confidence heists across canal-city Camorr."),
        ("Red Seas Under Red Skies", "Scott Lynch", "9780553588959", "Locke and Jean Tannen rob a floating casino in Tal Verrar and get forced into pirate captaincy."),
        ("The Republic of Thieves", "Scott Lynch", "9780553804690", "Locke and Jean compete in rigged elections in Karthain against Locke's lost love Sabetha."),
        ("Mistborn: The Final Empire", "Brandon Sanderson", "9780765350381", "Street thief Vin is recruited by Kelsier to use metal Allomancy to overthrow the immortal Lord Ruler."),
        ("The Well of Ascension", "Brandon Sanderson", "9780765356138", "Elend Venture and Vin defend Luthadel against three besieging armies while investigating ashfalls."),
        ("The Hero of Ages", "Brandon Sanderson", "9780765356145", "Sazed and Vin fulfill ancient prophecies to save Scadrial from Ruin's world-ending destruction."),
        ("The Alloy of Law", "Brandon Sanderson", "9780765330420", "Waxillium Ladrian leaves the Roughs for Elendel to solve train robberies using Twinborn magic."),
        ("Shadows of Self", "Brandon Sanderson", "9780765378552", "Wax and Wayne hunt a shapeshifting Kandra terrorist threatening Elendel's industrial peace."),
        ("The Bands of Mourning", "Brandon Sanderson", "9780765378576", "Wax travels to New Seran to find the mythical metal armbands once worn by the Lord Ruler."),
        ("The Lost Metal", "Brandon Sanderson", "9780765391193", "Wax, Wayne, and Marasi stop the Set from detonating a bomb that would destroy Elendel."),
        ("The Way of Kings", "Brandon Sanderson", "9780765365279", "Kaladin the slave bridgeman, Dalinar the highprince, and Shallan the scholar battle highstorms on Roshar."),
        ("Words of Radiance", "Brandon Sanderson", "9780765365286", "Shallan arrives at the Shattered Plains while Kaladin guards Dalinar from Assassin in White Szeth."),
        ("Oathbringer", "Brandon Sanderson", "9780765365293", "Dalinar Kholin refounds the Knights Radiant at Urithiru while the Voidbringer Desolation begins."),
        ("Rhythm of War", "Brandon Sanderson", "9780765365309", "Navani and Kaladin defend the fallen tower of Urithiru against Fused Singer occupier Raboniel."),
        ("Warbreaker", "Brandon Sanderson", "9780765360038", "Princesses Siri and Vivenna navigate BioChromatic Breath magic and living gods in Hallandren."),
        ("Elantris", "Brandon Sanderson", "9780765350374", "Prince Raoden contracts the glowing Shaod curse and is thrown into the ruined city of Elantris."),
        ("Edgedancer", "Brandon Sanderson", "9781250166548", "Lift and her spain Wyndle travel to Yeddaw to stop Darkness from killing a fellow Radiant."),
        ("Dawnshard", "Brandon Sanderson", "9781255018698", "Rysn and Lopen sail to the hidden island of Akinah to protect an ancient cosmic artifact."),
        ("Steelheart", "Brandon Sanderson", "9780385743570", "David Charleston joins the Reckoners to assassinate Steelheart, the invincible Epic ruling Chicago."),
        ("Firefight", "Brandon Sanderson", "9780385743594", "David travels to submerged Babylon Restored (NYC) to hunt High Epic Regalia."),
        ("Calamity", "Brandon Sanderson", "9780385743617", "The Reckoners travel to the salt city of Ildakar to free Prof from dark Epic corruption."),
        ("Skyward", "Brandon Sanderson", "9780399555770", "Spensa dreams of becoming a starfighter pilot defending planet Detritus from Krell alien attacks."),
        ("Starsight", "Brandon Sanderson", "9780399555817", "Spensa infiltrates the alien alliance coalition station Starsight disguised as an alien pilot."),
        ("Cytonic", "Brandon Sanderson", "9780399555855", "Spensa journeys into the Nowhere dimension to discover the origins of her cytonic powers."),
        ("Sunlit Man", "Brandon Sanderson", "9781250899682", "Nomad jumps between worlds running from the Night Brigade, landing on sun-scorched Canticle."),
        ("Tress of the Emerald Sea", "Brandon Sanderson", "9781250899651", "Tress stows away on a pirate ship sailing spore oceans to rescue her love Charlie from a Sorceress."),
        ("Yumi and the Nightmare Painter", "Brandon Sanderson", "9781250899699", "Yumi stacks spirits while Nikaro paints nightmares until their souls become entangled across dimensions."),
        ("The Grace of Kings", "Ken Liu", "9781481424271", "Kuni Garu and Mata Zyndu team up to overthrow an emperor before turning against each other."),
        ("The Wall of Storms", "Ken Liu", "9781481424301", "Dara island kingdom faces an invasion of dragon-riding Lyucu barbarians from across the sea wall.")
    ],
    "Science Fiction": [
        ("Dune", "Frank Herbert", "9780441172719", "Paul Atreides travels to desert planet Arrakis, becoming the Fremen messiah Muad'Dib."),
        ("Dune Messiah", "Frank Herbert", "9780441172696", "Emperor Paul Atreides faces conspiracy and blindness twelve years into his galactic jihad."),
        ("Children of Dune", "Frank Herbert", "9780441104024", "Paul's twin children Leto II and Ghanima navigate Alia's possession and the Golden Path destiny."),
        ("God Emperor of Dune", "Frank Herbert", "9780441294671", "3,500 years later, sandworm-human hybrid Leto II enforces peace across the universe."),
        ("Heretics of Dune", "Frank Herbert", "9780441328000", "Mother Superior Taraza and Darwi Odrade protect a ghola of Duncan Idaho from the Honored Matres."),
        ("Chapterhouse: Dune", "Frank Herbert", "9780441102679", "Bene Gesserit terraform Chapterhouse into a new desert planet while fighting off the Honored Matres."),
        ("The Dosadi Experiment", "Frank Herbert", "9780425048252", "Jorj X. McKie investigates a walled, overpopulated prison planet where billions are subjected to stress testing."),
        ("Whipping Star", "Frank Herbert", "9780425046869", "McKie must save a glowing Calebaban star-entity named Fanny Mae from torture."),
        ("The Santaroga Barrier", "Frank Herbert", "9780425046876", "Psychologist Gilbert Dasein investigates a California valley town where inhabitants share collective consciousness."),
        ("The White Plague", "Frank Herbert", "9780425068229", "Molecular biologist John O'Neill creates a genetically engineered plague that kills only women."),
        ("Destination: Void", "Frank Herbert", "9780425046883", "A starship crew forced to build an artificial intelligence brain to replace their dead organic control unit."),
        ("Foundation", "Isaac Asimov", "9780553293357", "Hari Seldon uses psychohistory to establish a Foundation to preserve human knowledge during galactic dark ages."),
        ("Foundation and Empire", "Isaac Asimov", "9780553293371", "The Foundation survives imperial general Bel Riose and confronts the telepathic mutant known as the Mule."),
        ("Second Foundation", "Isaac Asimov", "9780553293364", "The Mule searches for the hidden Second Foundation of mentalists guided by Seldon's plan."),
        ("Foundation's Edge", "Isaac Asimov", "9780553293388", "Golan Trevize travels the galaxy to decide whether human evolution belongs to Gaia collective consciousness."),
        ("Foundation and Earth", "Isaac Asimov", "9780553587579", "Trevize searches for humanity's forgotten birthplace Earth, guided by R. Daneel Olivaw."),
        ("Prelude to Foundation", "Isaac Asimov", "9780553278392", "Young mathematician Hari Seldon flees across Trantor's dome sectors to develop psychohistory."),
        ("Forward the Foundation", "Isaac Asimov", "9780553565072", "Seldon completes psychohistory equations while his family suffers tragic losses on falling Trantor."),
        ("I, Robot", "Isaac Asimov", "9780553294385", "Dr. Susan Calvin recounts classic short stories exploring the Three Laws of Robotics."),
        ("The Caves of Steel", "Isaac Asimov", "9780553293401", "Detective Elijah Baley and Spacer robot R. Daneel Olivaw solve a murder in enclosed city-domes."),
        ("The Naked Sun", "Isaac Asimov", "9780553293395", "Baley and Daneel travel to sparse planet Solaria where humans communicate only through holograms."),
        ("The Robots of Dawn", "Isaac Asimov", "9780553299496", "Baley investigates roboticide on Aurora, saving Daneel and meeting human-like robot R. Giskard."),
        ("Robots and Empire", "Isaac Asimov", "9780553380279", "Giskard and Daneel formulate the Zeroth Law of Robotics to protect humanity as a whole."),
        ("The Gods Themselves", "Isaac Asimov", "9780553288100", "Humanity exchanges matter with a parallel universe, discovering their Electron Pump threatens the Sun."),
        ("The End of Eternity", "Isaac Asimov", "9780553298092", "Andrew Harlan works for Eternity, a time-manipulating agency that erases human tragedies."),
        ("Nemesis", "Isaac Asimov", "9780553286281", "Settler colony Rotor travels to red dwarf star Nemesis, discovering a sentient planetary mind Megas."),
        ("Nightfall", "Isaac Asimov & Robert Silverberg", "9780553290998", "Planet Kalgash, illuminated by six suns, faces total darkness and cosmic madness every 2,040 years."),
        ("Fantastic Voyage", "Isaac Asimov", "9780553275728", "A submarine crew is miniaturized and injected into a dying scientist's bloodstream to destroy a brain clot."),
        ("Pebble in the Sky", "Isaac Asimov", "9780553293425", "Retired tailor Joseph Schwartz is accidentally teleported into Earth's radioactive far future."),
        ("The Stars, Like Dust", "Isaac Asimov", "9780553293432", "Biron Farrill flees assassins to help rebels hide the United States Constitution from Tyrannian overlords."),
        ("The Currents of Space", "Isaac Asimov", "9780553293418", "Spatio-analyst Rik recovers lost memory of an impending nova destruction on cotton planet Florina."),
        ("The Bicentennial Man", "Isaac Asimov", "9780553269826", "Robot NDR-114 Andrew spends two centuries pursuing legal human recognition through art and organ creation."),
        ("Gold", "Isaac Asimov", "9780061056581", "Collected final short stories and essays on writing, robotics, and sci-fi world-building.")
    ],
    "Horror": [
        ("The Haunting of Hill House", "Shirley Jackson", "9780143039983", "Dr. Montague, Eleanor Vance, Theodora, and Luke stay at Hill House, where Eleanor succumbs to evil."),
        ("We Have Always Lived in the Castle", "Shirley Jackson", "9780143039976", "Merricat Blackwood protects her sister Constance in their isolated house years after arsenic poisoning."),
        ("The Sundial", "Shirley Jackson", "9780143126348", "The Halloran family locks themselves inside their grand estate expecting global apocalyptic destruction."),
        ("The Bird's Nest", "Shirley Jackson", "9780143126355", "Elizabeth Jones suffers from four distinct fractured personalities under Dr. Wright's hypnosis."),
        ("Hangsaman", "Shirley Jackson", "9780143126362", "College freshman Natalie Waite descends into loneliness, dissociation, and dark fantasy."),
        ("The Road Through the Wall", "Shirley Jackson", "9780143126379", "Suburban gossip and malice exposed when a wall dividing Pepper Street neighborhood is knocked down."),
        ("The Lottery and Other Stories", "Shirley Jackson", "9780374529536", "Famous chilling title story of a small town annual stoning ritual alongside twenty-four short stories."),
        ("Red Dragon", "Thomas Harris", "9780451168665", "FBI profiler Will Graham comes out of retirement to hunt Tooth Fairy serial killer Francis Dolarhyde."),
        ("The Silence of the Lambs", "Thomas Harris", "9780312924584", "FBI trainee Clarice Starling consults imprisoned cannibal psychiatrist Dr. Hannibal Lecter to catch Buffalo Bill."),
        ("Hannibal", "Thomas Harris", "9780440224679", "Disfigured survivor Mason Verger plots revenge against Hannibal Lecter, who resurfaces in Florence."),
        ("Hannibal Rising", "Thomas Harris", "9780385514231", "Young Hannibal Lecter suffers WWII trauma in Lithuania before embarking on revenge murders in Paris."),
        ("Cari Mora", "Thomas Harris", "9780525557579", "Refugee Cari Mora defends a Miami mansion holding $25 million in cartel gold from psychopath Hans-Peter."),
        ("Heart-Shaped Box", "Joe Hill", "9780061147937", "Aging rock star Judas Coyne buys a dead man's suit on an online auction that comes with a vengeful ghost."),
        ("Horns", "Joe Hill", "9780061147951", "Ig Perrish wakes up with horns growing from his temples that compel people to confess dark sins."),
        ("NOS4A2", "Joe Hill", "9780062200570", "Vic Rides rescues her son Wayne from Charlie Manx, who abducts children to Christmasland in his Wraith."),
        ("The Fireman", "Joe Hill", "9780062200631", "Pregnant nurse Harper Willow fights Dragonscale spore infection that causes victims to spontaneously combust."),
        ("Strange Weather", "Joe Hill", "9780062664419", "Four short novellas including cloud monsters, rain of nails, and a camera that erases memories."),
        ("Full Throttle", "Joe Hill", "9780062200679", "Thirteen short horror stories including a biker gang chased by a semi-truck co-written with Stephen King."),
        ("Locke & Key: Welcome to Lovecraft", "Joe Hill & Gabriel Rodriguez", "9781600103841", "The Locke children move to Keyhouse in Lovecraft, Mass., discovering magical keys and an imposter demon."),
        ("20th Century Ghosts", "Joe Hill", "9780061147975", "Debut short story collection featuring an inflatable ghost, a boy turned into a locust, and theater haunts."),
        ("Behind Her Eyes", "Sarah Pinborough", "9780062459176", "Single mother Louise enters a love triangle with boss David and his wife Adele, leading to a twist ending."),
        ("Dead to Her", "Sarah Pinborough", "9780062883025", "High-society Savannah wives battle second-wife rivals using voodoo magic secrets."),
        ("Insomnia", "Sarah Pinborough", "9780062883063", "Emma turns forty and suffers severe sleep deprivation, suspecting she will go mad like her mother."),
        ("Cross Her Heart", "Sarah Pinborough", "9780062883001", "Lisa's quiet suburban life protecting her daughter Ava falls apart when her past returns."),
        ("13 Minutes", "Sarah Pinborough", "9781250122704", "Popular girl Natasha is rescued from a frozen river after being dead for 13 minutes."),
        ("The Death House", "Sarah Pinborough", "9781783292547", "Toby lives in a secluded island facility for terminally defective youth, falling for newcomer Clara."),
        ("Ring", "Koji Suzuki", "9781932234411", "Journalist Kazuyuki Asakawa watches a cursed videotape that promises death in seven days."),
        ("Spiral", "Koji Suzuki", "9781932234428", "Pathologist Mitsuo Ando performs an autopsy on Ryuji Takayama, uncovering genetic virus mutations."),
        ("Loop", "Koji Suzuki", "9781932234435", "Medical student Kaoru discovers the Ring virus is connected to a simulated digital universe project."),
        ("Dark Water", "Koji Suzuki", "9781932234220", "Seven short horror stories revolving around water, damp apartments, and abandoned boats."),
        ("Bird Box", "Josh Malerman", "9780062259653", "Malorie navigates a river blindfolded with two children to escape unseen creatures that drive humans mad."),
        ("Malorie", "Josh Malerman", "9780593156858", "Twelve years later, Malorie receives news that her parents might still be alive in a blind sanctuary."),
        ("The Only Good Indians", "Stephen Graham Jones", "9781982136451", "Four Blackfeet men are hunted by an entity seeking revenge for an illegal elk hunt years earlier.")
    ],
    "Self-Help": [
        ("The 7 Habits of Highly Effective People", "Stephen R. Covey", "9780743269513", "Principle-centered approach for solving personal and professional problems."),
        ("First Things First", "Stephen R. Covey", "9780684802039", "Time management framework prioritizing important tasks over urgent distractions."),
        ("Principle-Centered Leadership", "Stephen R. Covey", "9780671792800", "Applying eternal principles to organizational ethics, trust, and personal growth."),
        ("The 8th Habit", "Stephen R. Covey", "9780743287937", "From effectiveness to greatness: finding your voice and inspiring others to find theirs."),
        ("The Speed of Trust", "Stephen M.R. Covey", "9781416564157", "How trust speeds up execution and lowers costs in business and personal relationships."),
        ("How to Win Friends and Influence People", "Dale Carnegie", "9780671027032", "Timeless advice on interpersonal relationships, communication, and persuasion."),
        ("How to Stop Worrying and Start Living", "Dale Carnegie", "9780671733353", "Practical formulas to eliminate anxiety, fatigue, and financial stress."),
        ("The Quick and Easy Way to Effective Speaking", "Dale Carnegie", "9780671724009", "Overcoming stage fright and delivering confident public presentations."),
        ("The Power of Now", "Eckhart Tolle", "9781577314806", "A guide to spiritual enlightenment by anchoring consciousness in the present moment."),
        ("A New Earth", "Eckhart Tolle", "9780452289963", "Awakening to your life's purpose by transcending ego-based thinking."),
        ("Stillness Speaks", "Eckhart Tolle", "9781577314004", "Short meditative passages on silence, suffering, and quiet awareness."),
        ("Practicing the Power of Now", "Eckhart Tolle", "9781577311959", "Essential teachings, meditations, and exercises from The Power of Now."),
        ("Man's Search for Meaning", "Viktor E. Frankl", "9780807014295", "Psychiatrist Frankl's memoir of surviving Auschwitz and founding logotherapy."),
        ("The Will to Meaning", "Viktor E. Frankl", "9780452286054", "Foundational lectures on logotherapy and existential analysis."),
        ("Yes to Life: In Spite of Everything", "Viktor E. Frankl", "9780807065549", "Posthumously published 1946 lectures on finding hope amidst catastrophe."),
        ("The Monk Who Sold His Ferrari", "Robin Sharma", "9780062515674", "A fable about lawyer Julian Mantle who abandons corporate stress for Himalayan wisdom."),
        ("The 5 AM Club", "Robin Sharma", "9780062388094", "Own your morning, elevate your life using the 20/20/20 morning routine formula."),
        ("The Leader Who Had No Title", "Robin Sharma", "9781439198322", "How to influence and excel at work regardless of your position in an organization."),
        ("Everyday Hero Manifesto", "Robin Sharma", "9780063220492", "Systematic playbook for elite performance, positivity, and spiritual peace."),
        ("Rich Dad Poor Dad", "Robert T. Kiyosaki", "9781612680194", "What the rich teach their kids about money that the poor and middle class do not."),
        ("Cashflow Quadrant", "Robert T. Kiyosaki", "9781612680057", "Guide to financial freedom moving from Employee to Business Owner and Investor."),
        ("Guide to Investing", "Robert T. Kiyosaki", "9781612680217", "What the rich invest in that the poor and middle class do not."),
        ("Increase Your Financial IQ", "Robert T. Kiyosaki", "9781612680651", "Get smarter with your money through five key financial intelligences."),
        ("Think and Grow Rich", "Napoleon Hill", "9781585424337", "Thirteen principles of personal achievement distilled from Carnegie and Ford interviews."),
        ("Outwitting the Devil", "Napoleon Hill", "9781454900672", "Suppressed 1938 manuscript detailing how fear and drifting prevent human success."),
        ("The Law of Success", "Napoleon Hill", "9781585446006", "The original sixteen-lesson masterwork on individual achievement."),
        ("The Richest Man in Babylon", "George S. Clason", "9780451205360", "Ancient financial parables teaching saving 10%, investing, and eliminating debt."),
        ("The Millionaire Fastlane", "MJ DeMarco", "9780984358106", "Crack the code to wealth by building scalable business systems rather than slow saving."),
        ("Unscripted", "MJ DeMarco", "9780984358168", "Life, liberty, and the pursuit of entrepreneurship beyond the traditional job script."),
        ("$100M Offers", "Alex Hormozi", "9781737475736", "How to make offers so good people feel stupid saying no."),
        ("$100M Leads", "Alex Hormozi", "9781737475705", "How to get strangers to show interest in buying your products."),
        ("The Science of Getting Rich", "Wallace D. Wattles", "9781585426010", "1910 classic text proposing a definite mathematical law of attraction and creation."),
        ("As a Man Thinketh", "James Allen", "9781585440092", "Victorian classic on how thoughts mold character, health, and life circumstances.")
    ],
    "Biography": [
        ("Unbroken", "Laura Hillenbrand", "9780739319697", "Louis Zamperini's survival on a Pacific raft and endurance in Japanese POW camps."),
        ("Seabiscuit: An American Legend", "Laura Hillenbrand", "9780449005613", "An knobby-kneed racehorse and three underdog men captivate Great Depression America."),
        ("The Glass Castle", "Jeannette Walls", "9780743247542", "Jeannette Walls remembers her nomadic, impoverished upbringing by nonconformist parents."),
        ("Half Broke Horses", "Jeannette Walls", "9781416586296", "A true-life novel based on Walls's tough, independent grandmother Lily Casey Smith."),
        ("Silver Star", "Jeannette Walls", "9781451661545", "Sisters Bean and Liz leave California for their family's Virginia ancestral estate in the 1970s."),
        ("Hang the Moon", "Jeannette Walls", "9781501117298", "Sallie Kincaid fights for control of her family's Virginia timber and moonshine empire."),
        ("Educated", "Tara Westover", "9780399590504", "Tara Westover leaves her survivalist Idaho family at seventeen, educating herself to earn a Cambridge PhD."),
        ("Wild", "Cheryl Strayed", "9780307476074", "Strayed hikes 1,100 miles on the Pacific Crest Trail alone to heal after her mother's death."),
        ("Tiny Beautiful Things", "Cheryl Strayed", "9780307948649", "Advice essays from the beloved Dear Sugar column covering grief, love, and forgiveness."),
        ("Torch", "Cheryl Strayed", "9780307280800", "A Minnesota family's life fractures when their matriarch is diagnosed with terminal cancer."),
        ("Born a Crime", "Trevor Noah", "9780399588174", "Comedian Trevor Noah's childhood growing up mixed-race under South African apartheid laws."),
        ("Becoming", "Michelle Obama", "9781524763138", "The former First Lady's memoir from Chicago South Side childhood to the White House."),
        ("The Light We Carry", "Michelle Obama", "9780593237465", "Practical wisdom and strategies for staying hopeful in uncertain, changing times."),
        ("Dreams from My Father", "Barack Obama", "9781400082773", "Barack Obama searches for identity, community, and his Kenyan heritage."),
        ("The Audacity of Hope", "Barack Obama", "9780307237699", "Obama's political philosophy on reclaiming the American dream and bipartisan values."),
        ("A Promised Land", "Barack Obama", "9781524763169", "Volume one of Obama's presidential memoirs covering his 2008 campaign and first term."),
        ("I Am Malala", "Malala Yousafzai", "9780316322409", "The girl who stood up for education in Swat Valley and was shot by the Taliban."),
        ("Long Walk to Freedom", "Nelson Mandela", "9780316541428", "Mandela's autobiography from anti-apartheid leader to 27 years on Robben Island and presidency."),
        ("I Know Why the Caged Bird Sings", "Maya Angelou", "9780345514400", "Angelou's classic memoir of childhood trauma, resilience, and literary discovery in Arkansas."),
        ("Gather Together in My Name", "Maya Angelou", "9780345321435", "Volume two of Angelou's autobiography navigating post-WWII employment and single motherhood."),
        ("Singin' and Swingin' and Gettin' Merry Like Christmas", "Maya Angelou", "9780345321442", "Volume three following Angelou's touring European career in Porgy and Bess."),
        ("The Heart of a Woman", "Maya Angelou", "9780345321459", "Volume four exploring Angelou's civil rights work with Martin Luther King Jr. and Malcolm X."),
        ("All God's Children Need Traveling Shoes", "Maya Angelou", "9780679734048", "Volume five detailing Angelou's life among American expatriates in Accra, Ghana."),
        ("A Song Flown Up to Heaven", "Maya Angelou", "9780375727412", "Volume six coping with the assassinations of Malcolm X and King while writing her first book."),
        ("Mom & Me & Mom", "Maya Angelou", "9781400066117", "Angelou's reconciliation and lifelong connection with her glamorous mother Vivian Baxter."),
        ("Chronicles: Volume One", "Bob Dylan", "9780743230766", "Bob Dylan's candid reflections on arriving in Greenwich Village in 1961 and making records."),
        ("Just Kids", "Patti Smith", "9780060936228", "Patti Smith remembers her young romantic partnership with photographer Robert Mapplethorpe in NYC."),
        ("M Train", "Patti Smith", "9781101946954", "A poetic journey through coffee shops, dreams, and literary pilgrimages across the world."),
        ("Year of the Monkey", "Patti Smith", "9780525657682", "A solitary year of wandering, loss, and reflection following her 70th birthday."),
        ("Life", "Keith Richards", "9780316034388", "Rolling Stones guitarist Keith Richards recounts rock 'n' roll history, riffs, and survival."),
        ("Me: Elton John Official Autobiography", "Elton John", "9781250147608", "Elton John's honest memoir covering chart successes, addiction recovery, and AIDS foundation."),
        ("Greenlights", "Matthew McConaughey", "9780593139134", "McConaughey's journal notes on bumper stickers, red lights, and living with outlaw grace."),
        ("Friends, Lovers, and the Big Terrible Thing", "Matthew Perry", "9781250866448", "Friends star Matthew Perry opens up about fame, severe addiction, and health battles.")
    ],
    "History": [
        ("The Decline and Fall of the British Aristocracy", "David Cannadine", "9780300060430", "How taxes, land reform, and WWI destroyed British noble land-owning power."),
        ("Ornamentalism", "David Cannadine", "9780195157949", "How the British Empire projected domestic class hierarchies onto colonial territories."),
        ("Class in Britain", "David Cannadine", "9780140280456", "A historical study of how social class was perceived and structured in Britain over centuries."),
        ("Victorian Empire", "David Cannadine", "9780141036328", "The culture, institutions, and global reach of Britain during Queen Victoria's reign."),
        ("Citizens: A Chronicle of the French Revolution", "Simon Schama", "9780679726104", "A narrative history of the French Revolution emphasizing violence and romantic idealism."),
        ("The Embarrassment of Riches", "Simon Schama", "9780679781240", "An interpretation of Dutch golden age culture, wealth, and Calvinist morality in 17th century."),
        ("Landscape and Memory", "Simon Schama", "9780679735120", "How rivers, trees, and rocks shaped Western mythology and cultural memory."),
        ("A History of Britain", "Simon Schama", "9780563487142", "Schama's three-volume history of the British Isles from prehistoric times to 20th century."),
        ("The Story of the Jews", "Simon Schama", "9780060539184", "Finding the words 1000 BCE to 1492 CE across global Jewish diaspora culture."),
        ("SPQR: A History of Ancient Rome", "Mary Beard", "9781631492228", "A thousand years of Roman history from small village to global empire master."),
        ("Pompeii: The Life of a Roman Town", "Mary Beard", "9780195161441", "Daily life, graffiti, shops, and baths in Pompeii before Mount Vesuvius eruption."),
        ("Women & Power", "Mary Beard", "9781631494734", "A manifesto examining how female voices have been silenced from Homer to modern politics."),
        ("Twelve Caesars", "Mary Beard", "9780691222363", "Images of Roman emperors in Western art from antiquity to the modern world."),
        ("Rubicon", "Tom Holland", "9781400078974", "The last years of the Roman Republic and its bloody collapse into military dictatorship."),
        ("Persian Fire", "Tom Holland", "9780307279484", "The epic war between the Persian Empire and defending Greek city-states at Thermopylae and Salamis."),
        ("Millennium", "Tom Holland", "9780307278708", "The shaping of the West in the centuries surrounding the year 1000 CE."),
        ("Dynasty", "Tom Holland", "9780385537841", "The rise and fall of Rome's first imperial family from Augustus to Nero."),
        ("Dominion", "Tom Holland", "9780399593048", "How the Christian revolution remade the Western mind and modern secular values."),
        ("Pax", "Tom Holland", "9780465093526", "War and peace in Rome's golden age from Nero to Hadrian."),
        ("The Plantagenets", "Dan Jones", "9780143124924", "The English dynasty that forged the nation from Henry II through Richard II."),
        ("The Hollow Crown", "Dan Jones", "9780143127888", "The Wars of the Roses and the rise of the Tudor dynasty."),
        ("The Templars", "Dan Jones", "9780525428305", "The rise and spectacular fall of God's holy warrior monks."),
        ("Crusaders", "Dan Jones", "9780525428312", "An epic history of the medieval holy wars told through individual participants."),
        ("Powers and Thrones", "Dan Jones", "9781984880871", "A new history of the Middle Ages from the fall of Rome to the Renaissance."),
        ("Essex Dogs", "Dan Jones", "9780593493809", "A gritty historical novel following ten archers during the Hundred Years' War Crecy campaign."),
        ("The Silk Roads", "Peter Frankopan", "9781101912379", "A new history of the world centered on the trade routes connecting East and West."),
        ("The New Silk Roads", "Peter Frankopan", "9780525656401", "The present and future of global power shifting back toward Eurasia."),
        ("1177 B.C.: The Year Civilization Collapsed", "Eric H. Cline", "9780691168388", "How Late Bronze Age empires collapsed in a domino effect of sea invaders and earthquakes."),
        ("Late Victorian Holocausts", "Mike Davis", "9781859843826", "El Niño famines and the making of the third world under British imperialism."),
        ("City of Quartz", "Mike Davis", "9781844675685", "Excavating the dark, militarized social landscape of Los Angeles."),
        ("Heart of Darkness: A History of the Congo", "Adam Hochschild", "9780618001668", "King Leopold II of Belgium's brutal plunder of the Congo Free State."),
        ("Bury the Chains", "Adam Hochschild", "9780618619696", "The British abolitionist movement that ended the transatlantic slave trade."),
        ("Rebel Rising", "Adam Hochschild", "9780358448204", "How WWI anti-war dissidents were persecuted by the British government.")
    ],
    "Philosophy": [
        ("Discourse on Method", "René Descartes", "9780140448788", "Descartes proposes rational deduction and his famous statement: 'I think, therefore I am.'"),
        ("Meditations on First Philosophy", "René Descartes", "9780140447019", "Six meditations establishing Cartesian dualism, mind-body separation, and God's existence."),
        ("Principles of Philosophy", "René Descartes", "9780915144365", "A comprehensive statement of Cartesian metaphysics and mechanical physics."),
        ("Passions of the Soul", "René Descartes", "9780872200258", "Descartes's last work analyzing human emotions, pineal gland interaction, and ethics."),
        ("Ethics", "Baruch Spinoza", "9780140435719", "A pantheistic geometric system asserting God and Nature are one single substance."),
        ("Theological-Political Treatise", "Baruch Spinoza", "9780024143808", "A defense of freedom of speech, secular democracy, and biblical criticism."),
        ("On the Improvement of the Understanding", "Baruch Spinoza", "9780486420547", "Spinoza's unfinished essay on epistemological method and true knowledge."),
        ("Monadology", "Gottfried Wilhelm Leibniz", "9780872220133", "A metaphysical system where the universe consists of infinite simple soul-like substances called monads."),
        ("Discourse on Metaphysics", "Gottfried Wilhelm Leibniz", "9780872200364", "Leibniz's essay on divine perfection, pre-established harmony, and individual substance."),
        ("New Essays on Human Understanding", "Gottfried Wilhelm Leibniz", "9780521576604", "Leibniz's line-by-line critique of John Locke's empiricism defending innate ideas."),
        ("Theodicy", "Gottfried Wilhelm Leibniz", "9780812691474", "Defending God's goodness and arguing that ours is the best of all possible worlds."),
        ("An Essay Concerning Human Understanding", "John Locke", "9780140434828", "Locke asserts the human mind starts as a blank slate (tabula rasa) shaped by experience."),
        ("Two Treatises of Government", "John Locke", "9780521357302", "Foundational political text proposing natural rights to life, liberty, and property."),
        ("A Letter Concerning Toleration", "John Locke", "9780872202986", "Locke's argument for religious freedom and the separation of church and state."),
        ("A Treatise Concerning the Principles of Human Knowledge", "George Berkeley", "9780140432930", "Subjective idealism: to be is to be perceived (esse est percipi)."),
        ("Three Dialogues between Hylas and Philonous", "George Berkeley", "9780872200326", "Philosophical dialogues defending idealist metaphysics against physical materialism."),
        ("An Enquiry Concerning Human Understanding", "David Hume", "9780199549900", "Hume's empiricist investigation into causation, custom, habit, and skepticism."),
        ("A Treatise of Human Nature", "David Hume", "9780199596331", "Hume's masterwork attempting to introduce experimental method into moral subjects."),
        ("An Enquiry Concerning the Principles of Morals", "David Hume", "9780199549917", "Hume argues that moral distinctions derive from sentiment and utility rather than pure reason."),
        ("Dialogues Concerning Natural Religion", "David Hume", "9780140445367", "Cleanthes, Philo, and Demea debate the teleological argument and God's nature."),
        ("Leviathan", "Thomas Hobbes", "9780140431957", "Hobbes argues that solitary, poor, nasty, brutish life requires an absolute sovereign."),
        ("De Cive", "Thomas Hobbes", "9780521424097", "Hobbes's early political work on civic duty, state power, and church authority."),
        ("De Corpore", "Thomas Hobbes", "9780898380279", "Hobbes's materialist philosophy of body, motion, and scientific geometry."),
        ("The Social Contract", "Jean-Jacques Rousseau", "9780140444254", "Man is born free, and everywhere he is in chains; proposing rule by the General Will."),
        ("Emile, or On Education", "Jean-Jacques Rousseau", "9780465019311", "Rousseau's treatise on raising a natural child free from corrupting civilization."),
        ("Discourse on Inequality", "Jean-Jacques Rousseau", "9780140444391", "Tracing private property as the origin of social inequality and moral decay."),
        ("Confessions", "Jean-Jacques Rousseau", "9780140440331", "Rousseau's groundbreaking, ruthlessly honest autobiographical confession."),
        ("Phenomenology of Spirit", "G.W.F. Hegel", "9780198245971", "Hegel's dialectical movement of consciousness toward Absolute Knowing."),
        ("Elements of the Philosophy of Right", "G.W.F. Hegel", "9780521348881", "Hegel's political philosophy of freedom, civil society, ethical life, and the state."),
        ("The World as Will and Representation", "Arthur Schopenhauer", "9780486217611", "Schopenhauer asserts the world is driven by a blind, insatiable irrational Will."),
        ("On the Suffering of the World", "Arthur Schopenhauer", "9780141395593", "Pessimistic essays on human misery, aesthetic contemplation, and ascetic liberation."),
        ("Fear and Trembling", "Søren Kierkegaard", "9780140444490", "Kierkegaard analyzes Abraham's sacrifice of Isaac and the leap of faith."),
        ("The Sickness Unto Death", "Søren Kierkegaard", "9780140445336", "An investigation of Christian despair, sin, and selfhood.")
    ],
    "Young Adult": [
        ("The Hunger Games", "Suzanne Collins", "9780439023481", "Katniss Everdeen volunteers to replace her sister in Panem's televised fight to the death."),
        ("Catching Fire", "Suzanne Collins", "9780439023498", "Katniss and Peeta become sparks for revolution, forced back into the Quarter Quell arena."),
        ("Mockingjay", "Suzanne Collins", "9780439023511", "Katniss becomes the symbol of District 13's rebellion against President Snow's Capitol."),
        ("The Ballad of Songbirds and Snakes", "Suzanne Collins", "9781338635171", "Eighteen-year-old Coriolanus Snow mentors District 12 tribute Lucy Gray Baird in the 10th Hunger Games."),
        ("Divergent", "Veronica Roth", "9780062024039", "Tris Prior chooses Dauntless in a faction-divided Chicago, discovering she is Divergent."),
        ("Insurgent", "Veronica Roth", "9780062024046", "Tris fights Erudite faction leader Jeanine Matthews while grief-stricken by family loss."),
        ("Allegiant", "Veronica Roth", "9780062024060", "Tris and Four venture beyond the city fence, discovering Chicago is a genetic experiment."),
        ("Four", "Veronica Roth", "9780062345219", "Four short stories detailing Tobias Eaton's transition from Abnegation to Dauntless leader."),
        ("Legend", "Marie Lu", "9780399256752", "Prodigy military officer June Iparis hunts fifteen-year-old street criminal Day in flood-ravaged LA."),
        ("Prodigy", "Marie Lu", "9780399256769", "Day and June join the Patriot rebels in Las Vegas to assassinate the new Elector Primo."),
        ("Champion", "Marie Lu", "9780399256776", "Day and June face war between the Republic and Colonies while a deadly plague strikes."),
        ("Rebel", "Marie Lu", "9781250221704", "Ten years later, Eden Iparis and his brother Day navigate social credit inequality in Ross City."),
        ("The Young Elites", "Marie Lu", "9780399167836", "Adelina Amouteru survives blood fever with dark powers, joining the Dagger Society of outcasts."),
        ("The Rose Society", "Marie Lu", "9780399167843", "Adelina forms her own society of Young Elites to take revenge on the Inquisition Axis."),
        ("The Midnight Star", "Marie Lu", "9780399167850", "Queen Adelina faces a dark threat that forces her to team up with former enemies."),
        ("Warcross", "Marie Lu", "9780399547966", "Hacker Emika Chen accidentally glitches into the international Warcross game championship."),
        ("Wildcard", "Marie Lu", "9780399547997", "Emika uncovers Hideo Tanaka's brainwashing algorithm, racing to save world free will."),
        ("Six of Crows", "Leigh Bardugo", "9781627792127", "Kaz Brekker leads six dangerous Ketterdam outcasts in an impossible Ice Court heist."),
        ("Crooked Kingdom", "Leigh Bardugo", "9781627792134", "The Crows fight for their lives and stolen rewards against merchant rival Jan Van Eck."),
        ("Shadow and Bone", "Leigh Bardugo", "9780805094596", "Alina Starkov discovers she is a Sun Summoner Grisha who can destroy the Shadow Fold."),
        ("Siege and Storm", "Leigh Bardugo", "9780805094602", "Alina and Mal flee across the True Sea while hunted by the Darkling and Sturmhond."),
        ("Ruin and Rising", "Leigh Bardugo", "9780805094619", "Alina hunts the final firebird amplifier to defeat the Darkling once and for all."),
        ("King of Scars", "Leigh Bardugo", "9781250142283", "Nikolai Lantsov fights the dark monster within his body while defending Ravka."),
        ("Rule of Wolves", "Leigh Bardugo", "9781250142306", "Nikolai, Zoya, and Nina battle Fjerda invader armies in a high-stakes war for Ravka."),
        ("Ninth House", "Leigh Bardugo", "9781250313072", "Alex Stern uses her ghost-seeing ability to oversee Yale's eight secret occult societies."),
        ("Hell Bent", "Leigh Bardugo", "9781250313102", "Alex Stern breaks into Hell to rescue Darlington's soul from demon torment."),
        ("Cinder", "Marissa Meyer", "9780374312893", "Cyborg mechanic Cinder in New Beijing uncovers her identity as the lost Lunar Princess Selene."),
        ("Scarlet", "Marissa Meyer", "9780374364861", "Scarlet teams up with street fighter Wolf to find her missing grandmother in France."),
        ("Cress", "Marissa Meyer", "9780374315481", "Hacker Cress trapped in a satellite aids Cinder's team in stopping Queen Levana's wedding."),
        ("Winter", "Marissa Meyer", "9780374321970", "Princess Winter and Jacin join Cinder's revolution on Luna to overthrow Levana."),
        ("Heartless", "Marissa Meyer", "9781250097743", "Catherine dreams of opening a bakery but is groomed to become the tragic Queen of Hearts."),
        ("Caraval", "Stephanie Garber", "9781250095251", "Scarlett Dragna receives invitations to Caraval, a magical interactive game performance."),
        ("Legendary", "Stephanie Garber", "9781255009528", "Tella Dragna enters Caraval to win a debt payment to an elusive mysterious benefactor.")
    ],
    "Poetry": [
        ("The Complete Poems of Emily Dickinson", "Emily Dickinson", "9780316184137", "The complete 1,775 dash-punctuated poems exploring death, nature, love, and immortality."),
        ("Selected Poems", "Emily Dickinson", "9780486264660", "Essential collection including 'Because I could not stop for Death' and 'Hope is the thing with feathers'."),
        ("Final Harvest", "Emily Dickinson", "9780316184151", "Thomas H. Johnson's classic selection of Dickinson's most powerful lyric poems."),
        ("The Road Not Taken and Other Poems", "Robert Frost", "9780486275505", "Famous rural New England poems celebrating choices, apple-picking, and snowy woods."),
        ("A Boy's Will", "Robert Frost", "9780486457185", "Frost's debut 1913 poetry collection exploring nature, youth, and rustic life."),
        ("North of Boston", "Robert Frost", "9780486475080", "Dramatic narrative poems including 'Mending Wall' and 'The Death of the Hired Man'."),
        ("Mountain Interval", "Robert Frost", "9780486498904", "1916 collection featuring 'Birches' and 'Out, Out—'."),
        ("New Hampshire", "Robert Frost", "9780805069860", "Pulitzer Prize-winning book featuring 'Stopping by Woods on a Snowy Evening'."),
        ("West-Running Brook", "Robert Frost", "9780805069877", "Poem reflections on stoicism, nature streams, and philosophical perseverance."),
        ("A Witness Tree", "Robert Frost", "9780805069884", "1942 Pulitzer volume written during personal grief and WWII anxieties."),
        ("Leaves of Grass", "Walt Whitman", "9780140421996", "Whitman's groundbreaking free-verse celebration of democracy, body, and American spirit."),
        ("Song of Myself", "Walt Whitman", "9780486447957", "The epic 52-section poem proclaiming 'I celebrate myself, and sing myself'."),
        ("Drum-Taps", "Walt Whitman", "9780814794210", "Civil War field hospital poems including 'O Captain! My Captain!' and 'When Lilacs Last in the Dooryard Bloom'd'."),
        ("Democratic Vistas", "Walt Whitman", "9780874513578", "Whitman's passionate prose essay calling for a true democratic national culture."),
        ("Songs of Innocence and of Experience", "William Blake", "9780486270517", "Illustrated poems contrasting the gentle Lamb with the fiery Tyger."),
        ("The Marriage of Heaven and Hell", "William Blake", "9780486280387", "Prose and verse satire mocking Swedenborgian morality and proclaiming energy as eternal delight."),
        ("The Book of Thel", "William Blake", "9780486275833", "Allegorical poem about a maiden soul entering the world of mortal suffering."),
        ("Jerusalem", "William Blake", "9780691029078", "Blake's giant prophetic illuminated book of spiritual redemption."),
        ("Childe Harold's Pilgrimage", "Lord Byron", "9780140422245", "Byron's famous narrative poem introducing the brooding Byronic hero wandering Europe."),
        ("Don Juan", "Lord Byron", "9780140422160", "Satirical epic poem reversing the Don Juan legend into an easily seduced young man."),
        ("Manfred", "Lord Byron", "9780486419893", "A dramatic poem featuring a tortured nobleman living in the Alps invoking spirits."),
        ("Hebrew Melodies", "Lord Byron", "9780854966608", "Lyrics written to Jewish sacred tunes including 'She Walks in Beauty'."),
        ("Prometheus Unbound", "Percy Bysshe Shelley", "9780486270524", "A lyrical drama celebrating the overthrow of Jupiter tyrant by love and endurance."),
        ("Ozymandias and Other Poems", "Percy Bysshe Shelley", "9780486455587", "Famous political and romantic poems on temporal power ruins and West Wind flight."),
        ("Adonais", "Percy Bysshe Shelley", "9780486455594", "Shelley's pastoral elegy mourning the untimely death of John Keats."),
        ("The Defense of Poetry", "Percy Bysshe Shelley", "9780486455600", "Prose essay proclaiming poets as the unacknowledged legislators of the world."),
        ("Endymion", "John Keats", "9780486286013", "Poetic romance beginning 'A thing of beauty is a joy forever'."),
        ("Hyperion", "John Keats", "9780486286020", "Unfinished epic poem detailing the overthrow of the Titans by Apollo."),
        ("Odes and Other Poems", "John Keats", "9780486290003", "Famous 1819 odes including 'Ode to a Nightingale' and 'Ode on a Grecian Urn'."),
        ("Lamia, Isabella, The Eve of St. Agnes", "John Keats", "9780486290010", "Narrative romance poems of tragical love, snake enchantresses, and winter dreams."),
        ("The Rime of the Ancient Mariner", "Samuel Taylor Coleridge", "9780486223056", "A sailor shoots an albatross and suffers supernatural curse across seas."),
        ("Kubla Khan and Christabel", "Samuel Taylor Coleridge", "9780486263007", "Opium-dream vision of Xanadu pleasure dome alongside gothic vampire ballad."),
        ("Lyrical Ballads", "William Wordsworth & Samuel Taylor Coleridge", "9780415358484", "The 1798 landmark collection launching English Romanticism.")
    ],
    "Classic Literature": [
        ("War and Peace", "Leo Tolstoy", "9780140447934", "Five Russian aristocratic families navigate Napoleon's 1812 invasion of Russia."),
        ("Anna Karenina", "Leo Tolstoy", "9780143035008", "Anna's tragic affair with Count Vronsky contrasts with Levin's search for spiritual faith."),
        ("The Death of Ivan Ilyich", "Leo Tolstoy", "9780140448016", "High court judge Ivan Ilyich confronts existential horror and hypocrisy on his deathbed."),
        ("Resurrection", "Leo Tolstoy", "9780140449242", "Nobleman Nekhlyudov seeks moral redemption by following a wrongfully condemned woman to Siberia."),
        ("The Kingdom of God Is Within You", "Leo Tolstoy", "9780486470856", "Tolstoy's Christian pacifist treatise advocating non-violent resistance that inspired Gandhi."),
        ("Family Happiness", "Leo Tolstoy", "9780140448023", "Young Masha marries her older guardian Sergey, discovering marriage changes over time."),
        ("Hadji Murad", "Leo Tolstoy", "9780140449259", "A Avar chieftain breaks with Imam Shamil and allies with Russians in the Caucasus."),
        ("The Cossacks", "Leo Tolstoy", "9780140449266", "Wealthy Olenin joins the army in the Caucasus, falling in love with a Cossack girl."),
        ("Master and Man", "Leo Tolstoy", "9780140449273", "Landowner Vasili Brekhunov and his servant Nikita are trapped in a deadly blizzard."),
        ("Crime and Punishment", "Fyodor Dostoevsky", "9780143107637", "Impoverished student Raskolnikov murders a pawnbroker to prove his extraordinary theory."),
        ("The Brothers Karamazov", "Fyodor Dostoevsky", "9780375761218", "Fyodor Karamazov's murder exposes faith, free will, and morality in his three sons."),
        ("The Idiot", "Fyodor Dostoevsky", "9780375702921", "Saintly Prince Myshkin's innocence is destroyed by corrupt St. Petersburg high society."),
        ("Notes from Underground", "Fyodor Dostoevsky", "9780060833336", "A bitter retired civil servant delivers a monologue attacking rational utilitarianism."),
        ("Demons (The Possessed)", "Fyodor Dostoevsky", "9780679734567", "Pyotr Verkhovensky leads a nihilist political cell planning revolution in a provincial town."),
        ("The House of the Dead", "Fyodor Dostoevsky", "9780140444568", "Fictionalized memoir of Dostoevsky's four years of hard labor in a Siberian prison camp."),
        ("The Gambler", "Fyodor Dostoevsky", "9780140447388", "Tutor Alexei Ivanovich succumbs to roulette gambling addiction in a German spa town."),
        ("White Nights", "Fyodor Dostoevsky", "9780141441634", "A lonely dreamer spends four sentimental nights in St. Petersburg talking to Nastenka."),
        ("Poor Folk", "Fyodor Dostoevsky", "9780140445053", "Epistolary debut novel detailing low-ranking clerk Devushkin's love for seamstress Barbara."),
        ("The Double", "Fyodor Dostoevsky", "9780140447395", "Government clerk Golyadkin meets his charismatic double who steals his career and life."),
        ("The Cherry Orchard", "Anton Chekhov", "9780486266824", "Aristocratic Madame Ranevskaya returns to her estate before it is auctioned to build summer cottages."),
        ("Uncle Vanya", "Anton Chekhov", "9780486282558", "Vanya and Sonia manage a rural estate while bitter retired professor Serebryakov visits."),
        ("Three Sisters", "Anton Chekhov", "9780486275574", "Olga, Masha, and Irina yearn to return to Moscow while languishing in a provincial town."),
        ("The Seagull", "Anton Chekhov", "9780486272634", "Artistic rivalries and romantic heartbreak between Nina, Konstantin, Arkadina, and Trigorin."),
        ("The Lady with the Dog and Other Stories", "Anton Chekhov", "9780140449761", "Gurov and Anna Sergeyevna begin a quiet affair in Yalta that deepens into real love."),
        ("Ward No. 6", "Anton Chekhov", "9780140449778", "Dr. Ragin converse with asylum patient Gromov until Ragin himself is committed."),
        ("The Steppe", "Anton Chekhov", "9780140449785", "Nine-year-old Yegorushka travels across the vast Ukrainian steppe in a horse-drawn wagon."),
        ("Fathers and Sons", "Ivan Turgenev", "9780140441475", "Nihilist student Bazarov rejects traditional values, clashing with Pavel Petrovich Kirsanov."),
        ("A Sportsman's Sketches", "Ivan Turgenev", "9780140440676", "Vignettes of Russian peasant life that influenced Tsar Alexander II to emancipate the serfs."),
        ("Rudin", "Ivan Turgenev", "9780140443042", "An eloquent idealist arrives at a country estate but lacks the willpower to take action."),
        ("Home of the Gentry", "Ivan Turgenev", "9780140443059", "Lavretsky returns to his estate seeking peace, falling for pious Liza before his wife returns."),
        ("First Love", "Ivan Turgenev", "9780140443066", "Sixteen-year-old Vladimir falls for Zinaida, discovering his own father is her secret lover."),
        ("On the Eve", "Ivan Turgenev", "9780140443073", "Elena Insarova marries Bulgarian revolutionary Insarov on the eve of the Crimean War."),
        ("Torrents of Spring", "Ivan Turgenev", "9780140443080", "Dmitry Sanin falls for Italian pastry shop girl Gemma but is seduced by wealthy Maria.")
    ],
    "Non-Fiction": [
        ("Collapse", "Jared Diamond", "9780143036555", "How societies like Easter Island and Norse Greenland chose to fail or survive environmental stress."),
        ("The Third Chimpanzee", "Jared Diamond", "9780060845506", "The evolution and future of the human animal sharing 98% DNA with chimpanzees."),
        ("Why Is Sex Fun?", "Jared Diamond", "9780465031276", "The evolution of human sexuality including hidden ovulation and menopause."),
        ("Upheaval", "Jared Diamond", "9780316409131", "How nations cope with crises and change through structural resilience lessons."),
        ("The Language Instinct", "Jared Diamond & Steven Pinker", "9780060958336", "How the mind creates language as an innate biological adaptation."),
        ("How the Mind Works", "Steven Pinker", "9780393318487", "Reverse-engineering the human mind using cognitive science and evolutionary psychology."),
        ("The Blank Slate", "Steven Pinker", "9780142003343", "The modern denial of human nature and its political, social, and emotional consequences."),
        ("The Stuff of Thought", "Steven Pinker", "9780143114246", "Language as a window into human nature, physics, causation, and relationships."),
        ("The Better Angels of Our Nature", "Steven Pinker", "9780143122012", "Why global violence has declined over human history through state power and reason."),
        ("Enlightenment Now", "Steven Pinker", "9780525559023", "The case for reason, science, humanism, and progress in the modern world."),
        ("Rationality", "Steven Pinker", "9780525561996", "What rationality is, why it seems scarce, and why it matters for civic life."),
        ("The Man Who Mistook His Wife for a Hat", "Oliver Sacks", "9780679745655", "Neurological case studies of patients navigating agnosia, Tourette's, and phantom limbs."),
        ("Awakenings", "Oliver Sacks", "9780375704055", "Sacks treats encephalitis lethargica catatonic victims in 1969 using L-DOPA drug therapy."),
        ("An Anthropologist on Mars", "Oliver Sacks", "9780679756972", "Seven paradoxical tales of neurological adaptation including autistic professor Temple Grandin."),
        ("Musicophilia", "Oliver Sacks", "9781400033539", "Tales of music and the brain exploring musical earworms, amusia, and musical savants."),
        ("Uncle Tungsten", "Oliver Sacks", "9780375704048", "Sacks's chemical boyhood memories growing up in wartime London fascinated by metals."),
        ("Hallucinations", "Oliver Sacks", "9780307945723", "Exploring visual, auditory, and sensory hallucinations in neurological health and migraine."),
        ("Gratitude", "Oliver Sacks", "9780451496072", "Four final essays written by Sacks in the months following his terminal cancer diagnosis."),
        ("The River of Consciousness", "Oliver Sacks", "9780345808998", "Posthumous essays on Darwin, Freud, speed of thought, and memory fallibility."),
        ("A Short History of Nearly Everything", "Bill Bryson", "9780767908184", "Bryson's witty exploration of science from the Big Bang to human evolution."),
        ("Notes from a Small Island", "Bill Bryson", "9780380727506", "A humorous farewell tour of Great Britain traveling by public transport."),
        ("A Walk in the Woods", "Bill Bryson", "9780307279460", "Bryson hikes the Appalachian Trail with his out-of-shape friend Stephen Katz."),
        ("The Body: A Guide for Occupants", "Bill Bryson", "9780385539258", "A head-to-toe tour of how the human body functions and heals itself."),
        ("At Home", "Bill Bryson", "9780767919395", "A short history of private life traced through the rooms of an old English rectory."),
        ("In a Sunburned Country", "Bill Bryson", "9780385259415", "Bryson travels across Australia encountering dangerous wildlife and friendly locals."),
        ("The Mother Tongue", "Bill Bryson", "9780380715435", "The eccentric history and quirks of the English language."),
        ("One Summer: America 1927", "Bill Bryson", "9780767919418", "Charles Lindbergh, Babe Ruth, Al Capone, and landmark events of summer 1927."),
        ("Thinking, Fast and Slow", "Daniel Kahneman", "9780374533557", "System 1 intuitive thinking versus System 2 slow deliberative reasoning."),
        ("Predictably Irrational", "Dan Ariely", "9780061353246", "The hidden irrational forces that shape our everyday purchasing and personal decisions."),
        ("Freakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060731335", "A rogue economist explores the hidden side of everything from sumo wrestlers to drug dealers."),
        ("SuperFreakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060889570", "Global warming, altruism, and prostitute economics explored through data incentives."),
        ("Outliers: The Story of Success", "Malcolm Gladwell", "9780316017930", "Why some people succeed based on culture, timing, and 10,000 hours of practice."),
        ("The Black Swan", "Nassim Nicholas Taleb", "9781400063512", "The impact of highly improbable, high-consequence events on history and financial markets.")
    ]
}

def escape_sql(text):
    return text.replace("'", "''")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(script_dir, "seed_books_batch_8.sql")
    
    total_books = 0
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- PageMind Database Seed Script: Batch 8 of 10 (500 Books across 15 Genres)\n")
        f.write("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
        f.write("USE pagemind;\n\n")
        
        for genre, books in genres_data.items():
            f.write(f"-- =======================================================\n")
            f.write(f"-- Genre: {genre} ({len(books)} books)\n")
            f.write(f"-- =======================================================\n")
            for title, author, isbn, desc in books:
                t_esc = escape_sql(title)
                a_esc = escape_sql(author)
                d_esc = escape_sql(desc)
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
                
                # Build buy links JSON
                search_term = f"{title} {author}".replace(" ", "%20")
                buy_links = {
                    "amazon": f"https://www.amazon.in/s?k={search_term}",
                    "flipkart": f"https://www.flipkart.com/search?q={search_term}"
                }
                buy_json = escape_sql(json.dumps(buy_links))
                
                pub_year = get_published_year(title, author, genre, desc, isbn)

                
                rating = get_rating(title, author)

                
                sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{t_esc}', '{a_esc}', '{genre}', '{d_esc}', '{cover_url}', '{buy_json}', {pub_year}, {rating});\n"
                f.write(sql)
                total_books += 1
            f.write("\n")
            
    print(f"Successfully generated {output_path} with {total_books} book insert statements across {len(genres_data)} genres!")

if __name__ == "__main__":
    main()
