from book_metadata_utils import get_rating, get_published_year
import json
import urllib.parse
import os

# Batch 3: 500 Real, Published Books across 15 Genres (33-34 books per genre)
# Using lesser-known and deep-catalog published titles distinct from Batch 1 and Batch 2

GENRE_DATA_BATCH_3 = {
    "Fiction": [
        ("The God of Small Things", "Arundhati Roy", "9780679457312", "Estha and Rahel navigate family tragedies and social taboos in 1969 Kerala, India."),
        ("Midnight's Children", "Salman Rushdie", "9780812976533", "Saleem Sinai, born at the exact moment of India's independence, possesses telepathic powers."),
        ("The Shadow of the Wind", "Carlos Ruiz Zafón", "9780143034902", "A boy discovers a forgotten book in post-war Barcelona, plunging him into a tragic mystery."),
        ("The Inheritance of Loss", "Kiran Desai", "9780802142818", "In the Himalayas, a retired judge and his granddaughter confront revolution and post-colonial identity."),
        ("The White Tiger", "Aravind Adiga", "9781416562604", "Balram Halwai narrates his darkly comedic rise from village driver to Bangalore entrepreneur."),
        ("A Suitable Boy", "Vikram Seth", "9780060786625", "A mother searches for a suitable husband for her daughter in post-independence India."),
        ("The Namesake", "Jhumpa Lahiri", "9780618485222", "Gogol Ganguli struggles with his unusual name and Indian-American cultural identity."),
        ("Unaccustomed Earth", "Jhumpa Lahiri", "9780307265739", "Short stories exploring Bengali-American families across generations and continents."),
        ("Interpreter of Maladies", "Jhumpa Lahiri", "9780395957394", "Pulitzer-winning stories examining emotional distance and cultural roots between India and America."),
        ("The Guide", "R.K. Narayan", "9780143039648", "A tour guide turned reluctant holy man in Malgudi reflects on love, fraud, and redemption."),
        ("Malgudi Days", "R.K. Narayan", "9780140185805", "Charming short stories capturing life, humor, and quirky characters in the fictional Indian town of Malgudi."),
        ("Train to Pakistan", "Khushwant Singh", "9780143065883", "A quiet border village is torn apart by religious conflict during the 1947 Partition of India."),
        ("The Blue Umbrella", "Ruskin Bond", "9788171673407", "A young village girl in the Himalayan foothills receives a beautiful blue umbrella that draws envy."),
        ("Room on the Roof", "Ruskin Bond", "9780140116151", "Rusty, an orphaned Anglo-Indian boy, runs away from his strict guardian to live with Indian friends."),
        ("The Shadow Lines", "Amitav Ghosh", "9780618059881", "A young man explores family bonds, national borders, and violence between Calcutta and London."),
        ("The Glass Palace", "Amitav Ghosh", "9780375758775", "An epic saga spanning Burma, India, and Malaya following an orphan boy who becomes a teak tycoon."),
        ("Sea of Poppies", "Amitav Ghosh", "9780312428594", "Diverse sailors, coolies, and convicts board the schooner Ibis in 19th-century Calcutta during the Opium Wars."),
        ("River of Smoke", "Amitav Ghosh", "9780312538460", "Traders and sailors weather a typhoon while carrying opium into Guangzhou, China."),
        ("Flood of Fire", "Amitav Ghosh", "9780374156121", "The climax of the Ibis trilogy during the First Opium War in 1839 China."),
        ("The Hungry Tide", "Amitav Ghosh", "9780618711666", "A cetologist and a translator explore the dangerous, tide-swept Sundarbans mangrove islands."),
        ("A Golden Age", "Tahmima Anam", "9780061478758", "A widowed mother in East Pakistan makes desperate sacrifices during the 1971 Bangladesh Liberation War."),
        ("The Good Muslim", "Tahmima Anam", "9780061478796", "Brother and sister navigate religious conservatism and trauma in post-war Bangladesh."),
        ("Brick Lane", "Monica Ali", "9780743243315", "A young Bangladeshi woman enters an arranged marriage and adjusts to life in East London."),
        ("Shadow City", "Tarek El-Ariss", "9781501198762", "Reflections on memory, war, and displacement across Mediterranean coastal towns."),
        ("Disgrace", "J.M. Coetzee", "9780140296402", "A disgraced South African professor seeks refuge on his daughter's farm after a scandal."),
        ("Life & Times of Michael K", "J.M. Coetzee", "9780140074482", "A hare-lipped gardener travels across war-torn South Africa to return his mother's ashes to her birthplace."),
        ("Waiting for the Barbarians", "J.M. Coetzee", "9780140061109", "A magistrate at a frontier settlement faces moral crisis when imperial torturers arrive."),
        ("Half of a Yellow Sun", "Chimamanda Ngozi Adichie", "9781400095209", "Three characters are swept up in the struggle to establish the Republic of Biafra in 1960s Nigeria."),
        ("Purple Hibiscus", "Chimamanda Ngozi Adichie", "9781616202415", "A Nigerian teenager grows up under a fanatically religious father before finding freedom at her aunt's home."),
        ("Americanah", "Chimamanda Ngozi Adichie", "9780307455925", "A young Nigerian woman emigrates to America for university and reflects on race, love, and identity."),
        ("Girl, Woman, Other", "Bernardine Evaristo", "9780802156983", "Twelve interconnected Black British women navigate identity, feminism, and love across generations."),
        ("Mr Loverman", "Bernardine Evaristo", "9781617752889", "A 74-year-old Antiguan-Londoner contemplates coming out as gay to his wife of fifty years."),
        ("The Seven Moons of Maali Almeida", "Shehan Karunatilaka", "9780593537138", "A dead war photographer wakes up in a celestial visa office and has seven moons to solve his murder in 1989 Sri Lanka."),
        ("Chinaman: The Legend of Pradeep Mathew", "Shehan Karunatilaka", "9780241957448", "An aging sports journalist searches Sri Lanka for a legendary spin bowler who vanished in the 1980s.")
    ],

    "Mystery": [
        ("The Devotion of Suspect X", "Keigo Higashino", "9780312375065", "A brilliant math teacher helps his neighbor cover up her abusive ex-husband's murder in Tokyo."),
        ("Salvation of a Saint", "Keigo Higashino", "9780312606312", "Physics professor Manabu Yukawa investigates a man poisoned by coffee while his wife was miles away."),
        ("The Silent Patient", "Alex Michaelides", "9781250301697", "A famous painter shoots her husband and never speaks another word; a psychotherapist tries to uncover why."),
        ("The Redbreast", "Jo Nesbø", "9780060833213", "Inspector Harry Hole tracks a rare assassin rifle smuggled into Norway linked to WWII veterans."),
        ("The Bat", "Jo Nesbø", "9780345807090", "Harry Hole travels to Sydney to assist Australian police in investigating the murder of a Norwegian girl."),
        ("The Cockroaches", "Jo Nesbø", "9780345807106", "Harry Hole is dispatched to Bangkok to investigate the murder of the Norwegian ambassador."),
        ("Nemesis", "Jo Nesbø", "9780061132438", "Harry Hole investigates a series of bank robberies in Oslo and the death of a former girlfriend."),
        ("The Devil's Star", "Jo Nesbø", "9780061132452", "A serial killer leaves diamond stars under victims' eyelids during an Oslo heatwave."),
        ("The Beekeeper's Apprentice", "Laurie R. King", "9780312427368", "A teenage girl in 1915 Sussex meets retired Sherlock Holmes and becomes his brilliant apprentice."),
        ("A Monstrous Regiment of Women", "Laurie R. King", "9780312427375", "Mary Russell investigates a mysterious feminist cult in post-WWI London where heiresses die unnaturally."),
        ("Letter from Gaza", "Ghassan Kanafani", "9780894103827", "A teacher reflects on tragedy, resilience, and resistance through letters written from Palestine."),
        ("The No. 1 Ladies' Detective Agency", "Alexander McCall Smith", "9780375705670", "Precious Ramotswe opens Botswana's first female-run private detective agency in Gaborone."),
        ("Tears of the Giraffe", "Alexander McCall Smith", "9780375705687", "Mma Ramotswe investigates the disappearance of an American university student years prior."),
        ("Morality for Beautiful Girls", "Alexander McCall Smith", "9780375705694", "Mma Ramotswe takes on poisoning allegations at a safari lodge and beauty pageant scandals."),
        ("The Kalahari Typing School for Men", "Alexander McCall Smith", "9780375705700", "A rival male detective agency opens in Gaborone, pushing Mma Ramotswe to expand her services."),
        ("The Full Cupboard of Life", "Alexander McCall Smith", "9781400031801", "Mma Ramotswe helps a wealthy businesswoman evaluate the intentions of several suitors."),
        ("In the Woods", "Tana French", "9780143113492", "Detective Rob Ryan investigates a child murder in Dublin in the exact woods where his friends vanished twenty years ago."),
        ("The Likeness", "Tana French", "9780143115687", "Detective Cassie Maddox goes undercover as a murdered graduate student who looks identical to her."),
        ("Faithful Place", "Tana French", "9780143119494", "Frank Mackey returns to his old Dublin neighborhood after his childhood sweetheart's suitcase is found in a derelict house."),
        ("Broken Harbor", "Tana French", "9780143123309", "Scorcher Kennedy investigates a horrific crime in a half-built, ghost estate outside Dublin."),
        ("The Secret Place", "Tana French", "9780143127697", "Stephen Moran reopens a cold murder case at an elite Dublin girls' boarding school."),
        ("The Trespasser", "Tana French", "9780143129578", "Antoinette Conway and Stephen Moran investigate what looks like a routine domestic murder."),
        ("The Searcher", "Tana French", "9780735224650", "A retired Chicago cop moves to a quiet Irish village and is asked to find a missing teenager."),
        ("The Hunter", "Tana French", "9780593493434", "Cal Hooper's quiet life in western Ireland is disrupted when a missing local's father returns looking for gold."),
        ("Case Histories", "Kate Atkinson", "9780316010702", "Private investigator Jackson Brodie looks into three unsolved cold cases in Cambridge, England."),
        ("One Good Turn", "Kate Atkinson", "9780316011747", "Jackson Brodie witnesses a road rage attack at the Edinburgh Festival that leads to dark secrets."),
        ("When Will There Be Good News?", "Kate Atkinson", "9780316166546", "A doctor's family is targeted on a country road, bringing Jackson Brodie back into action."),
        ("Started Early, Took My Dog", "Kate Atkinson", "9780316053860", "Jackson Brodie uncovers a trail of police corruption and stolen children in Yorkshire."),
        ("Big Sky", "Kate Atkinson", "9780316523097", "Jackson Brodie relocates to a quiet seaside town in Yorkshire and stumbles upon a human trafficking ring."),
        ("The Shadow of the Examiner", "Satyajit Ray", "9780140237931", "Feluda investigates suspicious exam paper leakages and murder in Kolkata."),
        ("The Complete Adventures of Feluda", "Satyajit Ray", "9780143032779", "Satyajit Ray's iconic Bengal detective Feluda solves mysteries across India with Topshe and Jatayu."),
        ("The Emperor's Ring", "Satyajit Ray", "9780140237924", "Feluda tracks down a stolen Mughal ring belonging to Emperor Aurangzeb in Lucknow."),
        ("The Mystery of the Elephant God", "Satyajit Ray", "9780140237948", "Feluda investigates the theft of a priceless golden Ganesh idol in Varanasi."),
        ("Trouble in Gangtok", "Satyajit Ray", "9780140237955", "Feluda uncovers corporate espionage and murder while vacationing in Sikkim.")
    ],

    "Thriller": [
        ("The Alienist", "Caleb Carr", "9780345417626", "In 1896 New York, criminal psychologist Laszlo Kreizler uses early forensic science to catch a serial killer."),
        ("The Angel of Darkness", "Caleb Carr", "9780345427632", "Dr. Laszlo Kreizler and Sara Howard investigate the kidnapping of a Spanish diplomat's infant daughter."),
        ("The Day of the Jackal", "Frederick Forsyth", "9780451204394", "A professional hitman known as the Jackal is hired by OAS French extremists to assassinate Charles de Gaulle."),
        ("The Fist of God", "Frederick Forsyth", "9780553572421", "A covert British agent infiltrates Baghdad to discover Saddam Hussein's secret superweapon."),
        ("I Am Pilgrim", "Terry Hayes", "9781439177730", "A former head of a secret US intelligence unit is called back to stop a lone terrorist's biological attack."),
        ("The Spy Who Came in from the Cold", "John le Carré", "9780143124757", "Alec Leamas accepts one final fake-defection assignment into East Germany during the height of the Cold War."),
        ("Tinker Tailor Soldier Spy", "John le Carré", "9780143119784", "George Smiley is brought out of retirement to uncover a Soviet mole operating at the top of British intelligence."),
        ("The Honourable Schoolboy", "John le Carré", "9780143119739", "George Smiley mounts a covert operation in Hong Kong to dismantle a Soviet money-laundering network."),
        ("Smiley's People", "John le Carré", "9780143119746", "George Smiley engages in a final duel of wits against his Soviet nemesis Karla in Cold War Berlin."),
        ("A Perfect Spy", "John le Carré", "9780143119753", "Magnus Pym vanishes after his father's funeral, revealing his double life as an intelligence officer."),
        ("The Constant Gardener", "John le Carré", "9780743287203", "A mild-mannered British diplomat in Kenya investigates his activist wife's brutal murder, uncovering pharmaceutical corruption."),
        ("The Night Manager", "John le Carré", "9780143119760", "Jonathan Pine, a luxury hotel manager and former soldier, infiltrates the inner circle of an international arms dealer."),
        ("Defending Jacob", "William Landay", "9780345533661", "A suburban assistant district attorney's life shatters when his 14-year-old son is accused of murdering a classmate."),
        ("Bird Box", "Josh Malerman", "9780062259653", "A mother and two children navigate a river blindfolded to escape unseen creatures that drive humans to suicide."),
        ("Malorie", "Josh Malerman", "9780593156858", "Twelve years after the creatures arrived, Malorie receives news that her own family members might still be alive."),
        ("The Girl with the Dragon Tattoo", "Stieg Larsson", "9780307949486", "Journalist Mikael Blomkvist and hacker Lisbeth Salander investigate a 40-year-old missing person case on a Swedish island."),
        ("The Girl Who Played with Fire", "Stieg Larsson", "9780307949455", "Lisbeth Salander is framed for three murders in Stockholm and Mikael Blomkvist fights to clear her name."),
        ("The Girl Who Kicked the Hornets' Nest", "Stieg Larsson", "9780307949462", "Lisbeth Salander plots vengeance against corrupt government agents from a hospital bed while preparing for trial."),
        ("The Girl in the Spider's Web", "David Lagercrantz", "9780451495044", "Lisbeth Salander and Mikael Blomkvist reunite to protect a cybernetics researcher from international assassins."),
        ("The Ghost Writer", "Robert Harris", "9781416595670", "A ghostwriter hired to finish the memoirs of a former British Prime Minister stumbles upon national secrets."),
        ("Fatherland", "Robert Harris", "9780345426260", "In an alternate 1964 Berlin where Germany won WWII, a detective investigates a high-ranking Nazi murder."),
        ("Enigma", "Robert Harris", "9780345426253", "Bletchley Park codebreaker Tom Jericho struggles to break the German naval Enigma cipher while investigating a spy."),
        ("Archangel", "Robert Harris", "9780345426246", "A historian in Moscow uncovers a secret notebook belonging to Joseph Stalin detailing a hidden heir."),
        ("Munich", "Robert Harris", "9780525520269", "Two former university friends represent Britain and Germany at the fateful 1938 Munich conference."),
        ("V2", "Robert Harris", "9780525656715", "A German rocket engineer and a British WAAF radar technician clash during the 1944 V2 rocket attacks."),
        ("Act of Oblivion", "Robert Harris", "9780593535974", "In 1660 England, a royalist officer hunts down two regicide judges who signed King Charles I's death warrant."),
        ("The Memory Man", "David Baldacci", "9781455586387", "Amos Decker, a former detective with hyperthymesia, returns to solve the murder of his own family."),
        ("The Last Mile", "David Baldacci", "9781455586431", "Amos Decker investigates a death row inmate granted a last-minute reprieve when another man confesses."),
        ("The Fix", "David Baldacci", "9781455586462", "Amos Decker witnesses a sudden murder-suicide right outside FBI headquarters."),
        ("The Fallen", "David Baldacci", "9781538761397", "Amos Decker investigates mysterious deaths in a rust-belt town plagued by economic collapse and opioids."),
        ("Red Dragon", "Thomas Harris", "9780440206156", "FBI profiler Will Graham comes out of retirement to catch a serial killer known as the Tooth Fairy."),
        ("The Silence of the Lambs", "Thomas Harris", "9780312924584", "FBI trainee Clarice Starling interviews imprisoned cannibalistic psychiatrist Hannibal Lecter to catch Buffalo Bill."),
        ("Hannibal", "Thomas Harris", "9780440224679", "Seven years after escaping, Dr. Hannibal Lecter lives in Florence while targeted by a surviving victim seeking revenge.")
    ],

    "Romance": [
        ("The Rosie Project", "Graeme Simsion", "9780385679381", "A genetics professor creates a scientific questionnaire to find the perfect wife, but meets unconventional Rosie."),
        ("The Rosie Effect", "Graeme Simsion", "9781476776880", "Don and Rosie navigate unexpected pregnancy and married life in New York City."),
        ("The Rosie Result", "Graeme Simsion", "9781982110291", "Don Tillman helps his 11-year-old son Hudson navigate school challenges while learning about himself."),
        ("Red, White & Royal Blue", "Casey McQuiston", "9781250316776", "The First Son of the United States falls in love with the Prince of Wales after a staged fake friendship."),
        ("The Kiss Quotient", "Helen Hoang", "9780451490803", "An econometrician with Asperger's hires an attractive male escort to teach her about intimacy and dating."),
        ("The Bride Test", "Helen Hoang", "9780451490827", "Khai Diep's mother brings a young woman from Vietnam to California hoping she can open his heart to love."),
        ("The Heart Principle", "Helen Hoang", "9780451490841", "A violinist facing burnout enters a no-strings relationship with a motorcycle enthusiast."),
        ("The Unhoneymooners", "Christina Lauren", "9781501171345", "Two mortal enemies go on an all-expenses-paid Hawaiian honeymoon after the rest of the wedding party gets food poisoning."),
        ("Love and Other Words", "Christina Lauren", "9781501128012", "Childhood sweethearts reconnect years after a devastating misunderstanding separated them."),
        ("Book Lovers", "Emily Henry", "9780593440871", "A cutthroat literary agent keeps bumping into an arrogant rival editor in a small North Carolina town."),
        ("Beach Read", "Emily Henry", "9781984806734", "A romance writer and a literary fiction author swap genres for the summer while living in neighboring beach houses."),
        ("People We Meet on Vacation", "Emily Henry", "9781984806758", "Two best friends who haven't spoken since a trip two years ago take one last vacation together to fix their friendship."),
        ("The Flatshare", "Beth O'Leary", "9781250295690", "Tiffy and Leon share an apartment and a bed without ever meeting in person, communicating solely through post-it notes."),
        ("Get a Life, Chloe Brown", "Talia Hibbert", "9780062941206", "A chronically ill woman creates a list to help her live wildly and enlists her tattooed handyman landlord to help."),
        ("Take a Hint, Dani Brown", "Talia Hibbert", "9780062941237", "A PhD student and a former rugby player fake date after a video of him rescuing her goes viral."),
        ("Act Your Age, Eve Brown", "Talia Hibbert", "9780062941268", "A chaotic young woman accidentally hits a strict bed-and-breakfast owner with her car and steps in as chef."),
        ("Seven Days in August", "Tia Williams", "9781538719114", "A romantic tale of second chances and unexpected summer reunions."),
        ("Pride, Prejudice, and Other Flavors", "Sonali Dev", "9780062839053", "A brain surgeon from a famous Indian family clashes with an arrogant British chef."),
        ("Recipe for Persuasion", "Sonali Dev", "9780062839077", "A chef on a celebrity cooking show is paired with her former high school heartbreak."),
        ("Incense and Sensibility", "Sonali Dev", "9780063057050", "A politician recovering from trauma seeks stress relief from a yoga therapist he once loved."),
        ("The Rajes Series: The Wedding Planner", "Sonali Dev", "9780063057081", "A wedding designer and a reclusive heir navigate family expectations in California."),
        ("The Love Hypothesis", "Ali Hazelwood", "9780593336823", "A biology Ph.D. candidate fake-dates a young, notoriously strict professor to convince her friend she's dating."),
        ("Love on the Brain", "Ali Hazelwood", "9780593336861", "A neuroengineer is forced to co-lead a NASA project with her arch-nemesis from grad school."),
        ("An Unconditional Freedom", "Alyssa Cole", "9781496712523", "Two secret agents during the American Civil War infiltrate a Confederate network."),
        ("A Hope Divided", "Alyssa Cole", "9781496712509", "An enslaved woman with botanical knowledge aids a wounded Union soldier in North Carolina."),
        ("An Extraordinary Union", "Alyssa Cole", "9781496707444", "A freed Black woman working as a Union spy poses as an enslaved servant in the Confederate White House."),
        ("A Princess in Theory", "Alyssa Cole", "9780062685544", "An epidemiologist in NYC ignores emails claiming she is betrothed to an African prince until he arrives in person."),
        ("A Duke by Default", "Alyssa Cole", "9780062685568", "An assistant working in a Scottish armory discovers her grumpy boss is an heir to a dukedom."),
        ("Once Ghosted, Twice Shy", "Alyssa Cole", "9780062934277", "Two women who separated reconnect unexpectedly on a NYC subway car during a delay."),
        ("A Tale of Two Lizzies", "Alyssa Cole", "9780062685582", "A high-society romance of rivalries, misunderstandings, and second chances."),
        ("Delilah Green Doesn't Care", "Ashley Herring Blake", "9780593335130", "A photographer returns to her hometown for her stepsister's wedding and falls for her stepsister's best friend."),
        ("Astrid Parker Doesn't Fail", "Ashley Herring Blake", "9780593335154", "An interior designer renovating an inn clashes with a lead carpenter who questions her decisions."),
        ("Iris Kelly Doesn't Date", "Ashley Herring Blake", "9780593335178", "An actress suffering writer's block fake-dates a woman she met at a romance book club.")
    ],

    "Fantasy": [
        ("The Name of the Wind", "Patrick Rothfuss", "9780756404741", "Kvothe recounts his legendary life from orphaned musician to infamous arcanist and fugitive innkeeper."),
        ("The Wise Man's Fear", "Patrick Rothfuss", "9780756407919", "Kvothe continues his education at the University, travels to the Vintas court, and enters the Fae realm."),
        ("The Slow Regard of Silent Things", "Patrick Rothfuss", "9780756411329", "A quiet, lyrical window into the subterranean life of Auri in the Underthing beneath the University."),
        ("The Way of Kings", "Brandon Sanderson", "9780765365279", "Kaladin, Shallan, and Dalinar fight for survival and honor in the highstorm-wracked world of Roshar."),
        ("Words of Radiance", "Brandon Sanderson", "9780765365286", "Shallan travels to the Shattered Plains while Kaladin guards the king against assassin Szeth."),
        ("Oathbringer", "Brandon Sanderson", "9780765365293", "Dalinar Kholin attempts to unite humanity's kingdoms against the Desolation while uncovering voidbringer history."),
        ("Rhythm of War", "Brandon Sanderson", "9780765365309", "Humanity's scholars and Radiants defend Urithiru against an occupational force of Fused."),
        ("Mistborn: The Final Empire", "Brandon Sanderson", "9780765350381", "Vin, a street urchin, is recruited by thief master Kelsier to overthrow an immortal Lord Ruler."),
        ("The Well of Ascension", "Brandon Sanderson", "9780765356130", "Elend Venture and Vin rule Luthadel while besieged by three armies and deep magical mysteries."),
        ("The Hero of Ages", "Brandon Sanderson", "9780765356147", "Vin and Elend race against ash falls and world destruction to understand Ruin and Preservation."),
        ("The Alloy of Law", "Brandon Sanderson", "9780765330421", "Waxillium Ladrian uses Allomancy and gunplay to fight crime in an industrial age Scadrial."),
        ("Shadows of Self", "Brandon Sanderson", "9780765378552", "Wax and Wayne investigate a political assassination threatening religious peace in Elendel."),
        ("The Bands of Mourning", "Brandon Sanderson", "9780765378576", "Waxillium travels south to recover legendary metalminds belonging to the Lord Ruler."),
        ("The Lost Metal", "Brandon Sanderson", "9780765391193", "Wax, Wayne, and Marasi fight an extradimensional invasion threatening all of Scadrial."),
        ("Warbreaker", "Brandon Sanderson", "9780765360038", "Two Hallandren princesses navigate BioChromatic magic, god-kings, and living statues."),
        ("Elantris", "Brandon Sanderson", "9780765350374", "A cursed prince is exiled to a fallen city of mud and magic while his fiancee fights religious zealots."),
        ("Tress of the Emerald Sea", "Brandon Sanderson", "9781250899651", "A simple girl leaves her island home on a spore-filled ocean to rescue her true love from a sorceress."),
        ("Yumi and the Nightmare Painter", "Brandon Sanderson", "9781250899699", "A ritual maiden and a nightmare painter find their minds mysteriously connected across different worlds."),
        ("The Sunlit Man", "Brandon Sanderson", "9781250899712", "Nomad flees across planets powered by sunlight, fighting to protect local dwellers from a tyrant."),
        ("Freesia", "Brandon Sanderson", "9781250899736", "An adventurous tale of magical discoveries and cosmic mysteries."),
        ("The Priory of the Orange Tree", "Samantha Shannon", "9781635570298", "Ead Duryan protects an un-godly queen while Tané trains to be a dragon rider in East and West empires."),
        ("The Grace of Kings", "Ken Liu", "9781481424271", "A charming bandit and an austere nobleman unite to overthrow a tyrannical empire in Silkpunk Dara."),
        ("The Wall of Storms", "Ken Liu", "9781481424301", "Kuni Garu's children face political intrigue and an invasion of scaled sea monsters."),
        ("The Veiled Throne", "Ken Liu", "9781481424332", "Dara adapts to Lyucu occupation as inventors and scholars build mechanical weapons."),
        ("Speaking Bone", "Ken Liu", "9781481424363", "The epic conclusion to the Dandelion Dynasty as human ingenuity faces ancient magic."),
        ("Black Sun", "Rebecca Roanhorse", "9781534437678", "In a Mesoamerican-inspired continent, a blind avatar and a sun priestess prepare for a winter solstice eclipse."),
        ("Fevered Star", "Rebecca Roanhorse", "9781534437708", "Cuexca is thrown into political chaos following the sun eclipse as god avatars awaken."),
        ("Mirrored Heavens", "Rebecca Roanhorse", "9781534437739", "The epic climax as Tova, Xiala, and Otoa fight for the fate of Tova and the Sun God."),
        ("The Fifth Season", "N.K. Jemisin", "9780316229296", "In a world plagued by catastrophic climate shifts, Essun searches for her kidnapped daughter."),
        ("The Obelisk Gate", "N.K. Jemisin", "9780316229265", "Essun learns to control obelisk power while Nassun trains under an ancient stone eater."),
        ("The Stone Sky", "N.K. Jemisin", "9780316229241", "Mother and daughter clash over whether to heal or destroy the broken Earth."),
        ("The Hundred Thousand Kingdoms", "N.K. Jemisin", "9780316043922", "Yeine Darr is summoned to the floating city of Sky to compete for the throne alongside enslaved gods."),
        ("The Broken Kingdoms", "N.K. Jemisin", "9780316043960", "Oree Shoth, a blind artist, harbors a fallen god in the city of Shadow."),
        ("The Kingdom of Gods", "N.K. Jemisin", "9780316043939", "Sieh, god of childhood, finds himself aging and mortal as a new god war approaches.")
    ],

    "Science Fiction": [
        ("Hyperion", "Dan Simmons", "9780553283686", "Seven pilgrims travel to the Time Tombs on Hyperion to petition the terrifying Shrike creature."),
        ("The Fall of Hyperion", "Dan Simmons", "9780553288209", "The Hegemony of Man faces total destruction as the Time Tombs open and the AI TechnoCore betrays humanity."),
        ("Endymion", "Dan Simmons", "9780553572940", "Raul Endymion is tasked with rescuing Aenea, the Messiah, from Pax inquisitors."),
        ("The Rise of Endymion", "Dan Simmons", "9780553572988", "Aenea reveals the true nature of the Void Which Binds and the ultimate fate of human consciousness."),
        ("Red Mars", "Kim Stanley Robinson", "9780553560732", "The First Hundred colonists land on Mars, sparking fierce political and ecological debates on terraforming."),
        ("Green Mars", "Kim Stanley Robinson", "9780553568004", "Terraforming accelerates on Mars as underground rebel factions fight Earth corporate rule."),
        ("Blue Mars", "Kim Stanley Robinson", "9780553573351", "Mars develops breathable oceans and atmospheres while humanity spreads outward across the solar system."),
        ("The Years of Rice and Salt", "Kim Stanley Robinson", "9780553580761", "An alternate history spanning centuries where the Black Death wiped out 99 percent of Europe's population."),
        ("2312", "Kim Stanley Robinson", "9780316098045", "Swan Er Hong investigates an assassination on Mercury that threatens solar system stability."),
        ("Aurora", "Kim Stanley Robinson", "9780316225298", "A generation ship traveling to Tau Ceti faces biological and physical hurdles upon arrival."),
        ("Ministry for the Future", "Kim Stanley Robinson", "9780316300131", "A near-future UN agency works to mitigate climate change through policy, technology, and economic reform."),
        ("Snow Crash", "Neal Stephenson", "9780553380958", "Hiro Protagonist, a pizza delivery driver and hacker, investigates a virtual drug infecting hackers' minds in the Metaverse."),
        ("The Diamond Age", "Neal Stephenson", "9780553380965", "In a nanotechnology-dominated future, an interactive primer educates a young working-class girl."),
        ("Cryptonomicon", "Neal Stephenson", "9780060512804", "WWII Bletchley Park codebreakers and 1990s tech entrepreneurs build a data haven in Southeast Asia."),
        ("Anathem", "Neal Stephenson", "9780061474095", "Monk-like intellectuals living in secluded avows are called upon to handle an extraterrestrial crisis."),
        ("Seveneves", "Neal Stephenson", "9780062334510", "When the Moon disintegrates without warning, humanity builds an ark in orbit to survive Earth's bombardment."),
        ("Fall; or, Dodge in Hell", "Neal Stephenson", "9780062458711", "A tech billionaire's brain is scanned after death, creating a sprawling digital afterlife realm."),
        ("Termination Shock", "Neal Stephenson", "9780063028081", "A Texas oil tycoon builds a giant solar geoengineering gun to cool Earth's climate."),
        ("Old Man's War", "John Scalzi", "9780765315243", "75-year-old John Scalzi joins the Colonial Defense Force and receives a genetically enhanced young body."),
        ("The Ghost Brigades", "John Scalzi", "9780765354068", "Special Forces soldiers created from dead DNA investigate a traitor aiding alien species."),
        ("The Last Colony", "John Scalzi", "9780765356185", "John and Jane lead a new human colony world targeted by an alien alliance."),
        ("Zoe's Tale", "John Scalzi", "9780765316981", "Zoe Boutin Perry retells the events of Roanoke colony from her perspective as an adopted teenager."),
        ("The Human Division", "John Scalzi", "9780765333514", "Earth discovers the Colonial Union kept it isolated and diplomatic teams work to prevent war."),
        ("The End of All Things", "John Scalzi", "9780765376077", "The Colonial Union faces dissolution while secret factions plot interstellar dominance."),
        ("Redshirts", "John Scalzi", "9780765334795", "Ensigns aboard an exploration starship realize junior crew members die mysteriously on away missions."),
        ("Lock In", "John Scalzi", "9780765338861", "FBI agents investigate crimes involving people locked in their own bodies who operate robotic surrogates."),
        ("Head On", "John Scalzi", "9780765388834", "Agents Chris Shane and Leslie Vance investigate the death of an athlete playing a violent virtual sport."),
        ("The Collapsing Empire", "John Scalzi", "9780765388889", "The Flow, streams connecting star systems, begins to collapse, threatening the interstellar empire."),
        ("The Consuming Fire", "John Scalzi", "9780765388902", "Emperex Cardenia searches for ways to save human worlds as star systems lose connection."),
        ("The Last Emperox", "John Scalzi", "9780765388926", "Cardenia rushes to evacuate planets before the Flow collapses entirely."),
        ("Starter Villain", "John Scalzi", "9780765388971", "A down-on-his-luck journalist inherits his uncle's supervillain empire complete with talking cats."),
        ("The Kaiju Preservation Society", "John Scalzi", "9781250191786", "A delivery driver joins an animal rights organization protecting giant monsters in an alternate Earth."),
        ("Fuzzy Nation", "John Scalzi", "9780765367037", "A contractor on a remote planet discovers intelligent fluffy creatures threatening mining contracts.")
    ],

    "Horror": [
        ("House of Leaves", "Mark Z. Danielewski", "9780375703768", "A photojournalist discovers his house is impossibly larger on the inside than the outside, leading to endless dark hallways."),
        ("Inspection", "Josh Malerman", "9781524796990", "Boys and girls are raised in twin secluded tower academies in the woods without knowing the other sex exists."),
        ("Goblin", "Josh Malerman", "9781524797041", "Six interconnected novellas detailing mysterious and eerie occurrences in the rainy town of Goblin."),
        ("Incidents Around the House", "Josh Malerman", "9780593723128", "An eight-year-old girl is visited by an entity called Other Mommy asking to enter her heart."),
        ("The Troop", "Nick Cutter", "9781476717715", "A Cub Scout troop stranded on a deserted Canadian island encounters a bioengineered parasitic worm."),
        ("Heart-Shaped Box", "Joe Hill", "9780061147975", "An aging rock star buys a dead man's suit online and receives a vengeful ghost with it."),
        ("Horns", "Joe Hill", "9780061147999", "A man wakes up after a night of drinking with horns sprouting from his head that compel people to confess sins."),
        ("NOS4A2", "Joe Hill", "9780062200570", "Vic McQueen uses her supernatural bike to rescue children taken to Christmasland by Charlie Manx."),
        ("The Fireman", "Joe Hill", "9780062200631", "A global spore causes people to spontaneously combust, and a nurse joins a group led by a man controlling fire."),
        ("Full Throttle", "Joe Hill", "9780062200679", "Thirteen terrifying short stories featuring trucker gangs, mechanical beasts, and haunted places."),
        ("Strange Weather", "Joe Hill", "9780062663412", "Four novellas featuring cloud solidifications, instant cameras taking memories, and rain of needles."),
        ("Locke & Key: Welcome to Lovecraft", "Joe Hill & Gabriel Rodríguez", "9781600103841", "Three siblings move to Keyhouse estate where magic keys unlock supernatural doors."),
        ("The Ruins", "Scott Smith", "9781400079339", "Two American couples vacationing in Mexico explore Mayan ruins overgrown with killer vine plants."),
        ("A Simple Plan", "Scott Smith", "9780375706240", "Brothers find four million dollars inside a crashed plane in snow and turn to paranoia and murder."),
        ("The Only Good Indians", "Stephen Graham Jones", "9781982136451", "Four Blackfeet men are stalked by an elk entity seeking revenge for a hunting transgression years ago."),
        ("Mexican Gothic", "Silvia Moreno-Garcia", "9780593128367", "A glamorous socialite visits her cousin at a remote Mexican estate dominated by toxic mold and mind control."),
        ("The Elementals", "Michael McDowell", "9780486494920", "Two wealthy families vacation at a Victorian beach resort in Alabama where sand dunes swallow houses."),
        ("Cold Moon Over Babylon", "Michael McDowell", "9780486801827", "A drowned girl's ghost haunts a small Alabama town seeking vengeance against her murderer."),
        ("Blackwater: The Complete Saga", "Michael McDowell", "9780486814988", "A Southern gothic family horror saga spanning decades starting with a mysterious flood in 1919."),
        ("Ghost Story", "Peter Straub", "9780307472182", "Four elderly members of the Chowder Society in New York are haunted by a past mistake."),
        ("Julia", "Peter Straub", "9780307472199", "A grieving mother moves into a London townhouse haunted by the vengeful spirit of a child."),
        ("Shadowland", "Peter Straub", "9780307472205", "Two boarding school boys spend summer at an uncle's remote estate where dark stage magic becomes real."),
        ("Dragon", "Peter Straub", "9780307472212", "A dark tale of secret violence and lingering psychological trauma."),
        ("The Talisman", "Stephen King & Peter Straub", "9781501192272", "Jack Sawyer travels across parallel Americas to find a magical talisman that can save his dying mother."),
        ("Black House", "Stephen King & Peter Straub", "9781501192296", "Retired detective Jack Sawyer investigates a serial killer in Wisconsin linked to the Territories."),
        ("Head Full of Ghosts", "Paul Tremblay", "9780062363238", "A suburban family films a reality show as their 14-year-old daughter displays signs of schizophrenia or possession."),
        ("The Cabin at the End of the World", "Paul Tremblay", "9780062679109", "Four armed strangers invade a secluded cabin, forcing a family to make an impossible choice to prevent the apocalypse."),
        ("Disappearance at Devil's Rock", "Paul Tremblay", "9780062363269", "A 13-year-old boy vanishes from a local park and his mother receives visits from a shadow."),
        ("Dark Harvest", "Norman Partridge", "9780765319104", "On Halloween in 1963, teenage boys hunt Sawtooth Jack, a creature rising from cornfields."),
        ("The Loney", "Andrew Michael Hurley", "9781328745507", "A man recalls a childhood trip to a remote Lancashire coast where his family sought a miracle cure."),
        ("Devil's Day", "Andrew Michael Hurley", "9781328511737", "A man returns to his family's sheep farm in the Yorkshire Moors during a ritualistic autumn gathering."),
        ("Starve Acre", "Andrew Michael Hurley", "9780593188736", "Parents grieving their son's death dig into local folklore on their isolated English farm."),
        ("The Ritual", "Adam Nevill", "9780312641849", "Four university friends hiking through Swedish wilderness are stalked by an ancient Norse beast.")
    ],

    "Self-Help": [
        ("Atomic Habits", "James Clear", "9780735211292", "An easy framework for building good habits and breaking bad ones through tiny 1% daily improvements."),
        ("Deep Work", "Cal Newport", "9781455586691", "Rules for focused success in a distracted world to master hard information and produce elite results."),
        ("Digital Minimalism", "Cal Newport", "9780525536512", "Choosing a focused life in a noisy digital landscape by paring down phone and screen habits."),
        ("So Good They Can't Ignore You", "Cal Newport", "9781455509126", "Why skill and career capital matter more than passion in finding fulfilling work."),
        ("Slow Productivity", "Cal Newport", "9780593544853", "The lost art of accomplishment without burnout by doing fewer things at a higher quality."),
        ("Essentialism", "Greg McKeown", "9780804137386", "The disciplined pursuit of less to invest energy only in high-value activities."),
        ("The Subtle Art of Not Giving a F*ck", "Mark Manson", "9780062457714", "A counterintuitive approach to living a good life by choosing what values actually matter."),
        ("Everything Is F*cked: A Book About Hope", "Mark Manson", "9780062888433", "Exploring hope, technology, and emotional maturity in modern society."),
        ("Can't Hurt Me", "David Goggins", "9781544514215", "Master your mind and defy the odds from Navy SEAL and endurance athlete David Goggins."),
        ("Never Finished", "David Goggins", "9781544536828", "Unshackle your mind and win the war within through relentless self-discipline."),
        ("The Psychology of Money", "Morgan Housel", "9780857197689", "Timeless lessons on wealth, greed, and happiness across 20 short chapters."),
        ("Same As Ever", "Morgan Housel", "9780593332702", "A guide to what never changes in a world that's always changing."),
        ("Make Your Bed", "William H. McRaven", "9781455570249", "Little things that can change your life and maybe the world from a Navy Admiral."),
        ("The Wisdom of the Bullfrog", "William H. McRaven", "9781538707944", "Leadership lessons from a lifetime of Special Operations service."),
        ("The Sea Stories", "William H. McRaven", "9781538719879", "Memorable operational tales and personal lessons in courage."),
        ("Mindset: The New Psychology of Success", "Carol S. Dweck", "9780345472328", "How fixed versus growth mindsets transform learning, relationships, and business."),
        ("Grit: The Power of Passion and Perseverance", "Angela Duckworth", "9781501111105", "Why effort and resilience predict success more than innate talent."),
        ("Daring Greatly", "Brené Brown", "9781594631580", "How the courage to be vulnerable transforms the way we live, love, parent, and lead."),
        ("Gifts of Imperfection", "Brené Brown", "9781592858491", "Let go of who you think you're supposed to be and embrace who you are."),
        ("Rising Strong", "Brené Brown", "9780812995824", "How overcoming struggle and failure cultivates resilience and emotional strength."),
        ("Dare to Lead", "Brené Brown", "9780399592522", "Brave work, tough conversations, and whole hearts in organizational leadership."),
        ("Atlas of the Heart", "Brené Brown", "9780399592553", "Mapping 87 human emotions and experiences to build deep connection."),
        ("Quiet: The Power of Introverts", "Susan Cain", "9780307352156", "Celebrating introverts in a world that can't stop talking."),
        ("Bittersweet", "Susan Cain", "9780451499783", "How sorrow and longing make us whole and spur creativity."),
        ("The Power of Habit", "Charles Duhigg", "9780812981605", "Why we do what we do in life and business through the Cue-Routine-Reward loop."),
        ("Smarter Faster Better", "Charles Duhigg", "9780812993011", "The transformative science of productivity in organizations and personal life."),
        ("Supercommunicators", "Charles Duhigg", "9780593243916", "How to unlock the secret language of connection in conversations."),
        ("Thinking, Fast and Slow", "Daniel Kahneman", "9780374533557", "System 1 intuitive thinking versus System 2 slow deliberative logic."),
        ("Predictably Irrational", "Dan Ariely", "9780061353246", "The hidden forces that shape our decisions in economic and daily life."),
        ("The Upside of Irrationality", "Dan Ariely", "9780061995040", "Unexpected benefits of defying logic at work and at home."),
        ("The Honest Truth About Dishonesty", "Dan Ariely", "9780062183590", "How we lie to everyone, especially ourselves, and how to stay ethical."),
        ("Misbelief", "Dan Ariely", "9780593491423", "What makes rational people believe irrational conspiracy theories."),
        ("Show Your Work!", "Austin Kleon", "9780761178972", "Ten ways to share your creativity and get discovered online.")
    ],

    "Biography": [
        ("Steve Jobs", "Walter Isaacson", "9781451648539", "The definitive biography of Apple co-founder Steve Jobs based on forty interviews."),
        ("Einstein: His Life and Universe", "Walter Isaacson", "9780743264730", "How Albert Einstein's imaginative mind reshaped modern physics."),
        ("Benjamin Franklin: An American Life", "Walter Isaacson", "9780684807614", "The life of printer, inventor, diplomat, and founding father Benjamin Franklin."),
        ("Leonardo da Vinci", "Walter Isaacson", "9781501139154", "Connecting art and science through the notebooks of history's greatest genius."),
        ("Elon Musk", "Walter Isaacson", "9781398527492", "An intimate biography of the controversial tech entrepreneur behind SpaceX and Tesla."),
        ("Shoe Dog", "Phil Knight", "9781501135927", "Nike founder Phil Knight shares the early struggles and chaotic growth of his footwear empire."),
        ("Becoming", "Michelle Obama", "9781524763138", "Former First Lady of the US reflects on her roots, family, career, and White House years."),
        ("Educated", "Tara Westover", "9780399590504", "A young woman raised by survivalist parents in Idaho earns a Ph.D. from Cambridge without attending school."),
        ("Born a Crime", "Trevor Noah", "9780399588174", "Comedian Trevor Noah shares stories of growing up mixed-race in apartheid-era South Africa."),
        ("Greenlights", "Matthew McConaughey", "9780593139134", "Academy Award-winning actor shares journal insights, life lessons, and catching greenlights."),
        ("Will", "Will Smith & Mark Manson", "9781984877925", "Will Smith opens up about fame, outer success, inner growth, and family expectations."),
        ("The Glass Castle", "Jeannette Walls", "9780571260386", "A memoir of growing up in a nonconformist, nomadic family driven by eccentric parents."),
        ("Half Broke Horses", "Jeannette Walls", "9781439169605", "A real-life novel depicting the fierce life of Jeannette Walls' grandmother in West Texas."),
        ("Silver Tears", "Jeannette Walls", "9781439169629", "Exploring family history, resilience, and survival across rural America."),
        ("Open", "Andre Agassi", "9780307388407", "Tennis legend Andre Agassi reveals his hatred of tennis and his journey to self-realization."),
        ("Kitchen Confidential", "Anthony Bourdain", "9780060899226", "Adventures in the culinary underbelly detailing kitchen chaos and drug-fueled line cooking."),
        ("A Cook's Tour", "Anthony Bourdain", "9780060012786", "In search of the perfect meal across Vietnam, Cambodia, Russia, and Morocco."),
        ("Medium Raw", "Anthony Bourdain", "9780061718953", "A candid follow-up examining how food culture changed over ten years."),
        ("World Travel", "Anthony Bourdain & Laurie Woolever", "9780062802798", "A travel guide to the world's most fascinating places based on Bourdain's notes."),
        ("When Breath Becomes Air", "Paul Kalanithi", "9780812988406", "A 36-year-old neurosurgeon facing stage IV lung cancer reflects on living a meaningful life."),
        ("Wild", "Cheryl Strayed", "9780307476074", "A young woman hikes 1,100 miles alone along the Pacific Crest Trail to heal from personal loss."),
        ("Tiny Beautiful Things", "Cheryl Strayed", "9780307949332", "Advice on love and life collected from the 'Dear Sugar' column."),
        ("Brave Enough", "Cheryl Strayed", "9781101946909", "A collection of short, inspiring quotes on resilience and empathy."),
        ("Torch", "Cheryl Strayed", "9780307949356", "A novel about a family coping with sudden loss in rural Minnesota."),
        ("Alexander Hamilton", "Ron Chernow", "9780143034759", "The landmark biography of the illegitimate orphan from the Caribbean who built America's financial system."),
        ("Washington: A Life", "Ron Chernow", "9780143119968", "Pulitzer Prize-winning biography of George Washington's military leadership and presidency."),
        ("Grant", "Ron Chernow", "9780143110637", "The epic life story of Union general and 18th US President Ulysses S. Grant."),
        ("Titan: The Life of John D. Rockefeller, Sr.", "Ron Chernow", "9781400077304", "The rise of Standard Oil and the world's first billionaire philanthropist."),
        ("House of Morgan", "Ron Chernow", "9780802144652", "A history of modern finance following the Morgan banking dynasty."),
        ("Churchill: Walking with Destiny", "Andrew Roberts", "9781101980996", "Definitive single-volume biography of Winston Churchill based on King George VI's diaries."),
        ("Napoleon: A Life", "Andrew Roberts", "9780143127857", "The military tactics, civil codes, and downfall of Emperor Napoleon Bonaparte."),
        ("The Storm of War", "Andrew Roberts", "9780061228605", "A strategic history of World War II analyzing military blunders and leadership."),
        ("George III", "Andrew Roberts", "9780525560661", "Re-evaluating Britain's most misunderstood monarch during the American Revolution.")
    ],

    "History": [
        ("Sapiens: A Brief History of Humankind", "Yuval Noah Harari", "9780062316097", "Tracing human history from the Cognitive Revolution 70,000 years ago to modern technology."),
        ("Homo Deus: A Brief History of Tomorrow", "Yuval Noah Harari", "9780062464316", "Examining humanity's future goals of immortality, happiness, and godlike technological creation."),
        ("21 Lessons for the 21st Century", "Yuval Noah Harari", "9780525512172", "Navigating current challenges of technological disruption, fake news, and political polarization."),
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "How environmental and geographical factors shaped human civilizations over 13,000 years."),
        ("Collapse: How Societies Choose to Fail or Succeed", "Jared Diamond", "9780143036555", "Analyzing past societal collapses like Easter Island and Norse Greenland to draw lessons for today."),
        ("Upheaval: Turning Points for Nations in Crisis", "Jared Diamond", "9780316409131", "How nations handle national crises through selective change and psychological coping."),
        ("The Third Chimpanzee", "Jared Diamond", "9780060845506", "Exploring how human genetics, language, and culture diverged from our primate relatives."),
        ("The Dawn of Everything", "David Graeber & David Wengrow", "9780374157357", "A new history of humanity challenging traditional theories about agriculture and social hierarchy."),
        ("SPQR: A History of Ancient Rome", "Mary Beard", "9780871404237", "A history of Rome's rise from obscure village to global superpower across 1,000 years."),
        ("Emperor of Rome", "Mary Beard", "9780871404251", "Inside the lives, court politics, and daily power dynamics of Roman emperors."),
        ("Pompeii: The Life of a Roman Town", "Mary Beard", "9780141018096", "Daily life, graffiti, and culture preserved under volcanic ash in 79 AD."),
        ("The First Crusade", "Peter Frankopan", "9780199583058", "Re-evaluating the Call from the East that launched the medieval crusades."),
        ("1177 B.C.: The Year Civilization Collapsed", "Eric H. Cline", "9780691168388", "How invasion, earthquakes, and drought brought down Late Bronze Age empires."),
        ("After 1177 B.C.: The Survival of Civilizations", "Eric H. Cline", "9780691240329", "How Eastern Mediterranean societies rebuilt out of the ashes of the Bronze Age collapse."),
        ("Postwar: A History of Europe Since 1945", "Tony Judt", "9780143037750", "The reconstruction, political division, and reunification of Europe after WWII."),
        ("Thinking the Twentieth Century", "Tony Judt & Timothy Snyder", "9780143123040", "Intellectual history of 20th-century political ideas, fascism, and social democracy."),
        ("On Tyranny: Twenty Lessons from the Twentieth Century", "Timothy Snyder", "9780804190114", "Historical lessons on protecting democratic institutions against authoritarianism."),
        ("Bloodlands: Europe Between Hitler and Stalin", "Timothy Snyder", "9780465031474", "The tragic history of mass violence in Eastern Europe from 1933 to 1945."),
        ("Black Earth: The Holocaust as History and Warning", "Timothy Snyder", "9781101904121", "Analyzing the destruction of state structures that enabled the Holocaust."),
        ("The Road to Unfreedom", "Timothy Snyder", "9780525574477", "Tracing modern cyber-warfare, disinformation, and authoritarian drift."),
        ("The Anarchy", "William Dalrymple", "9781635573954", "How the East India Company conquered India and built a corporate empire."),
        ("The Last Mughal", "William Dalrymple", "9781400096107", "The fall of Delhi and the end of the Mughal Dynasty during the 1857 Indian Uprising."),
        ("Return of a King", "William Dalrymple", "9780307948533", "The First Anglo-Afghan War of 1839–1842 and Britain's greatest military disaster."),
        ("The Splendid and the Vile", "Erik Larson", "9780385348713", "Winston Churchill, his family, and London enduring the German Blitz in 1940."),
        ("The Devil in the White City", "Erik Larson", "9780375725609", "The 1893 Chicago World's Fair and serial killer H.H. Holmes' hotel of horrors."),
        ("Dead Wake: The Last Crossing of the Lusitania", "Erik Larson", "9780307408877", "The sinking of the ocean liner Lusitania by a German U-boat in 1915."),
        ("In the Garden of Beasts", "Erik Larson", "9780307408853", "The American ambassador and his family in 1930s Nazi Berlin as Hitler rises to power."),
        ("Thunderstruck", "Erik Larson", "9781400034512", "Marconi's wireless telegraph invention intersecting with a famous London murder case."),
        ("Isaac's Storm", "Erik Larson", "9780375708275", "The devastating 1900 Galveston hurricane and meteorologist Isaac Cline's warnings."),
        ("Genghis Khan and the Making of the Modern World", "Jack Weatherford", "9780609809648", "How Genghis Khan's conquests connected trade, religious freedom, and global communication."),
        ("The Secret History of the Mongol Queens", "Jack Weatherford", "9780307407160", "How Genghis Khan's daughters ruled the Silk Road trade networks."),
        ("Salt: A World History", "Mark Kurlansky", "9780142001615", "How a common rock shaped economies, wars, trade routes, and culinary traditions."),
        ("Cod: A Biography of the Fish That Changed the World", "Mark Kurlansky", "9780140275018", "The thousand-year history of cod fishing and European exploration of North America.")
    ],

    "Philosophy": [
        ("Meditations", "Marcus Aurelius", "9780812968255", "Personal Stoic journal entries on duty, resilience, mortality, and emotional control."),
        ("Letters from a Stoic", "Seneca", "9780140442106", "Epistolary wisdom on overcoming anger, enduring illness, and valuing time."),
        ("Discourses and Selected Writings", "Epictetus", "9780140449464", "Stoic lectures on controlling internal judgments and accepting external events."),
        ("The Enchiridion", "Epictetus", "9780486433592", "A short Stoic handbook for daily ethical living and mental tranquility."),
        ("On the Shortness of Life", "Seneca", "9780143036326", "Essays urging individuals to stop wasting time on trivial ambitions."),
        ("The Nicomachean Ethics", "Aristotle", "9780140449495", "Developing virtue ethics, practical wisdom, and achieving eudaimonia (human flourishing)."),
        ("The Republic", "Plato", "9780140455113", "Dialogue on justice, the philosopher-king, and the Allegory of the Cave."),
        ("The Symposium", "Plato", "9780140449273", "Dinner party speeches exploring the true nature and ladder of love."),
        ("Apology", "Plato", "9780872206335", "Socrates' defense speech at his trial in Athens for corrupting the youth."),
        ("Critias and Timaeus", "Plato", "9780140444551", "Dialogues introducing the origin of the cosmos and the legend of Atlantis."),
        ("Beyond Good and Evil", "Friedrich Nietzsche", "9780140449235", "Critique of traditional morality, dogmatic philosophy, and the Will to Power."),
        ("Thus Spoke Zarathustra", "Friedrich Nietzsche", "9780140441185", "Philosophical novel introducing the Übermensch, Will to Power, and Eternal Recurrence."),
        ("On the Genealogy of Morals", "Friedrich Nietzsche", "9780679724629", "Tracing master-slave morality, guilt, bad conscience, and ascetic ideals."),
        ("The Gay Science", "Friedrich Nietzsche", "9780679724636", "Celebrating joyful wisdom, perspective, and the death of god phrase."),
        ("The Antichrist", "Friedrich Nietzsche", "9780486434483", "A polemic critique of institutional Christianity and altruism."),
        ("Ecce Homo", "Friedrich Nietzsche", "9780140445152", "Nietzsche's autobiographical reflection on his works, thought, and legacy."),
        ("The Myth of Sisyphus", "Albert Camus", "9780679733737", "Existential essay on facing the absurd universe with defiance and passion."),
        ("The Rebel", "Albert Camus", "9780679733843", "Examining historical revolution, terrorism, and the bounds of moral rebellion."),
        ("Being and Nothingness", "Jean-Paul Sartre", "9780671867805", "Foundational text on existential freedom, bad faith, and radical personal responsibility."),
        ("Existentialism Is a Humanism", "Jean-Paul Sartre", "9780300115468", "A public lecture explaining why existence precedes essence."),
        ("Nausea", "Jean-Paul Sartre", "9780811220309", "Philosophical novel on Antoine Roquentin's sudden dread at the raw existence of matter."),
        ("The Second Sex", "Simone de Beauvoir", "9780307277787", "Landmark feminist philosophy on how society constructs womanhood as the Other."),
        ("Ethics of Ambiguity", "Simone de Beauvoir", "9780806501604", "Applying existentialist philosophy to moral action and human freedom."),
        ("Man's Search for Meaning", "Viktor E. Frankl", "9780807014295", "Psychiatrist recalls surviving concentration camps and developing logotherapy."),
        ("The Art of War", "Sun Tzu", "9781590302255", "Ancient Chinese treatise on military strategy, conflict avoidance, and deception."),
        ("Tao Te Ching", "Lao Tzu", "9780140441314", "Classical Chinese text on natural harmony, non-action (wu wei), and balance."),
        ("The Analects", "Confucius", "9780140443868", "Sayings and ideas attributed to Confucius on ritual, filial piety, and governance."),
        ("Zhuangzi: Basic Writings", "Zhuangzi", "9780231129596", "Daoist fables and humor questioning rigid logic and fixed categories."),
        ("Bhagavad Gita", "Vyasa", "9780140449181", "Prince Arjuna and Lord Krishna converse on duty (dharma), action, and devotion on the battlefield."),
        ("The Dhammapada", "Buddha", "9780140449419", "Core teachings of the Buddha on mindfulness, desire, and suffering."),
        ("Upanishads", "Anonymous", "9780140441635", "Vedic philosophical texts exploring Brahman (ultimate reality) and Atman (soul)."),
        ("Critique of Pure Reason", "Immanuel Kant", "9780521558303", "Exploring the synthetic a priori, transcendental idealism, and limits of human knowledge."),
        ("Groundwork of the Metaphysics of Morals", "Immanuel Kant", "9780521514576", "Formulating the Categorical Imperative as the supreme principle of duty.")
    ],

    "Young Adult": [
        ("The Hunger Games", "Suzanne Collins", "9780439023481", "Katniss Everdeen volunteers to replace her sister in a televised death match in Panem."),
        ("Catching Fire", "Suzanne Collins", "9780439023498", "Katniss and Peeta are forced back into the arena for the 75th Quarter Quell."),
        ("Mockingjay", "Suzanne Collins", "9780439023511", "Katniss becomes the symbol of rebellion against President Snow's Capitol."),
        ("The Ballad of Songbirds and Snakes", "Suzanne Collins", "9781338635171", "Young Coriolanus Snow mentors a District 12 tribute during the 10th Hunger Games."),
        ("Sunrise on the Reaping", "Suzanne Collins", "9781546171461", "Haymitch Abernathy competes in the 50th Hunger Games Quarter Quell."),
        ("The Fault in Our Stars", "John Green", "9780525478812", "Cancer patients Hazel and Augustus fall in love after meeting at a support group."),
        ("Looking for Alaska", "John Green", "9780142402511", "Miles moves to an Alabama boarding school and falls for unpredictable Alaska Young."),
        ("Paper Towns", "John Green", "9780142414934", "Quentin follows clues left behind by his mysterious neighbor Margo after she vanishes."),
        ("An Abundance of Katherines", "John Green", "9780142410707", "A child prodigy dumped by nineteen Katherines takes a road trip to invent a breakup formula."),
        ("Turtles All the Way Down", "John Green", "9780525555360", "A sixteen-year-old girl with OCD searches for a fugitive billionaire for a cash reward."),
        ("The Book Thief", "Markus Zusak", "9780375842207", "Death narrates the story of Liesel, a young girl stealing books in Nazi Germany."),
        ("I Am the Messenger", "Markus Zusak", "9780375836671", "A 19-year-old taxi driver receives playing cards in the mail with cryptic addresses."),
        ("Six of Crows", "Leigh Bardugo", "9781627792127", "Kaz Brekker leads six dangerous outcasts on an impossible heist inside an impenetrable fortress."),
        ("Crooked Kingdom", "Leigh Bardugo", "9781627792134", "The Crows fight for survival and revenge on the streets of Ketterdam."),
        ("Shadow and Bone", "Leigh Bardugo", "9780374346577", "Alina Starkov discovers sun-summoning power capable of destroying the Shadow Fold."),
        ("Siege and Storm", "Leigh Bardugo", "9780374371494", "Alina tries to escape the Darkling with Mal while hunting magical amplifiers."),
        ("Ruin and Rising", "Leigh Bardugo", "9780374384753", "Alina searches for the Firebird amplifier in a final showdown against the Darkling."),
        ("King of Scars", "Leigh Bardugo", "9781250142283", "Nikolai Lantsov struggles to contain a dark monster growing inside him."),
        ("Rule of Wolves", "Leigh Bardugo", "9781250142306", "Ravka faces war on two fronts as Zoya and Nikolai fight for their kingdom."),
        ("Ninth House", "Leigh Bardugo", "9781250313072", "Alex Stern monitors Yale's secret occult societies while investigating a campus murder."),
        ("Hell Bent", "Leigh Bardugo", "9781250313102", "Alex Stern journeys into hell to rescue Darlington's soul."),
        ("The Hate U Give", "Angie Thomas", "9780062498533", "Starr Carter witnesses the fatal shooting of her childhood best friend by a police officer."),
        ("On the Come Up", "Angie Thomas", "9780062498564", "Sixteen-year-old Bri pours her frustrations into rap music after her mother loses her job."),
        ("Concrete Rose", "Angie Thomas", "9780062846716", "Maverick Carter navigates teenage fatherhood and street life in 1990s Garden Heights."),
        ("Dear Martin", "Nic Stone", "9781101939499", "Justyce McAllister writes letters to Dr. Martin Luther King Jr. after being handcuffed by police."),
        ("Dear Justyce", "Nic Stone", "9781101939529", "Quan writes letters to Justyce while incarcerated at a youth detention center."),
        ("One of Us Is Lying", "Karen M. McManus", "9781524714680", "Five students enter detention, but only four leave alive after the creator of a gossip app dies."),
        ("One of Us Is Next", "Karen M. McManus", "9781524714758", "A new truth-or-dare game targets Bayview High students one year after Simon's death."),
        ("Two Can Keep a Secret", "Karen M. McManus", "9781524714727", "Ellery moves to a town famous for missing girls right as a new threat emerges."),
        ("The Cousins", "Karen M. McManus", "9780593175828", "Three cousins receive an invitation to work at their estranged grandmother's island resort."),
        ("You'll Be the Death of Me", "Karen M. McManus", "9780593175866", "Three high school seniors ditching school stumble upon a classmate's murder scene."),
        ("Nothing More to Tell", "Karen M. McManus", "9780593175903", "An intern at a true-crime show re-investigates her favorite teacher's unsolved murder."),
        ("One of Us Is Back", "Karen M. McManus", "9780593485019", "The Bayview Crew unites when a dangerous threat targets someone from the original detention group.")
    ],

    "Poetry": [
        ("Milk and Honey", "Rupi Kaur", "9781449474256", "A poetry collection on violence, abuse, love, loss, and femininity."),
        ("The Sun and Her Flowers", "Rupi Kaur", "9781449486792", "Poems exploring wilting, falling, rooting, rising, and blooming."),
        ("Home Body", "Rupi Kaur", "9781449486808", "A reflective journey walking through past memories, acceptance, and self-love."),
        ("Healing Through Words", "Rupi Kaur", "9781501191985", "Guided writing exercises and poetry prompts for self-exploration."),
        ("Pillow Thoughts", "Courtney Peppernell", "9781449489755", "Short poems and affirmations split into sections for raw emotions."),
        ("Pillow Thoughts II: Healing the Heart", "Courtney Peppernell", "9781449495084", "Moving forward and healing after heartbreak."),
        ("Pillow Thoughts III: Mending the Mind", "Courtney Peppernell", "9781524850852", "Finding light, self-worth, and mental peace in tough times."),
        ("Pillow Thoughts IV: Stitching the Soul", "Courtney Peppernell", "9781524854584", "Lyrical reflections on inner growth and enduring love."),
        ("Shine Your Light", "Courtney Peppernell", "9781524869854", "Inspirational poems on courage and self-discovery."),
        ("I Hope This Reaches Her in Time", "R.H. Sin", "9781449495114", "Verses encouraging women to walk away from toxic relationships and know their worth."),
        ("Whiskey Words & a Shovel I", "R.H. Sin", "9781449480349", "Raw modern poetry on modern romance, pain, and resilience."),
        ("Whiskey Words & a Shovel II", "R.H. Sin", "9781449480356", "Reflections on self-care, heartbreak, and emotional independence."),
        ("Whiskey Words & a Shovel III", "R.H. Sin", "9781449480363", "The final installation on letting go and protecting your mental health."),
        ("Empty Bottles Full of Stories", "R.H. Sin & Robert M. Drake", "9781449496030", "Collaborative collection examining solitude, growth, and love."),
        ("Black Book of Poems", "Vincent Hunanyan", "9781521444641", "Short, evocative poems detailing sorrow, hope, and existential thoughts."),
        ("Light Filters In", "Caroline Kaufman", "9780062844682", "Honest poetry about depression, body image, and mental health recovery."),
        ("When the Stars Wrote Back", "Trista Mateer", "9781524853877", "Poems addressing heartbreaks, mythologies, and rebuilding."),
        ("Aphrodite Made Me Do It", "Trista Mateer", "9781449498672", "Using Greek myth to process trauma, healing, and self-forgiveness."),
        ("Artemis Made Me Do It", "Trista Mateer", "9781524876029", "Verse centered on wildness, boundaries, and protection."),
        ("The Chaos of Longing", "K.Y. Robinson", "9781449489885", "Exploring trauma, mental illness, desire, and healing."),
        ("Subversive Beauty", "K.Y. Robinson", "9781449495046", "Poetry reclaiming power, body positivity, and self-acceptance."),
        ("She Fits Inside These Words", "R.H. Sin & Samantha King Holmes", "9781524860530", "Duet poems capturing two sides of love and shared lives."),
        ("Soft Thorns", "Bridgett Devoue", "9781732007802", "Poems addressing sexual assault, heartbreak, and self-love."),
        ("Soft Thorns Vol. II", "Bridgett Devoue", "9781732007826", "Continuing the journey through healing and vulnerability."),
        ("Note to Self", "Zellie Maniaci", "9781541094031", "Daily poetic reminders to practice grace and self-compassion."),
        ("Her", "Pierre Alex Jeanty", "9780996887212", "Verses celebrating women's strength, beauty, and emotional depth."),
        ("Him", "Pierre Alex Jeanty", "9780996887236", "Poetry exploring men's hidden vulnerability, love, and growth."),
        ("To the Men I Love Too Much", "Gabrielle Korn", "9780062965615", "Reflections on queer identity, feminism, and fashion world struggles."),
        ("Depression & Other Magic Tricks", "Sabrina Benaim", "9781943735204", "Spoken word poetry about mental health, family, and survival."),
        ("I Love My Love", "Reyna Biddy", "9781449490164", "Spoken word poetry on self-love, vulnerability, and spiritual growth."),
        ("A Beautiful Composition of Broken", "R.H. Sin", "9781449490171", "Encouraging readers to find peace amid emotional chaos."),
        ("She Felt Like Feeling Nothing", "R.H. Sin", "9781449494391", "Numbness, loss, and the journey back to feeling whole."),
        ("Winter of Summers", "R.H. Sin", "9781449495107", "Short reflections on growth, quiet strength, and patience.")
    ],

    "Classic Literature": [
        ("Crime and Punishment", "Fyodor Dostoevsky", "9780679734505", "Raskolnikov murders a pawnbroker to prove his extraordinary theory and suffers overwhelming guilt."),
        ("The Brothers Karamazov", "Fyodor Dostoevsky", "9780375702242", "Four brothers are implicated in the patricide of their corrupt father Fyodor Karamazov."),
        ("War and Peace", "Leo Tolstoy", "9781400079988", "Five aristocratic families navigate Napoleon's 1812 invasion of Russia and the search for meaning."),
        ("Anna Karenina", "Leo Tolstoy", "9780143035008", "Anna Karenina's tragic extramarital affair with Count Vronsky contrasts with Levin's rural search for faith."),
        ("Great Expectations", "Charles Dickens", "9780141439563", "Orphan Pip receives an anonymous fortune that transforms his social standing and values."),
        ("A Tale of Two Cities", "Charles Dickens", "9780141439600", "Sydney Carton sacrifices his life during the French Revolution in Paris and London."),
        ("Bleak House", "Charles Dickens", "9780141439723", "The endless Jarndyce and Jarndyce court battle destroys lives in Victorian London's Court of Chancery."),
        ("David Copperfield", "Charles Dickens", "9780141439570", "David Copperfield recounts his journey from abused childhood to successful novelist."),
        ("Oliver Twist", "Charles Dickens", "9780141439747", "An orphan escapes a parish workhouse and is taken in by a gang of London pickpockets."),
        ("Pride and Prejudice", "Jane Austen", "9780141439518", "Elizabeth Bennet and Mr. Darcy overcome pride and social prejudice in 19th-century England."),
        ("Sense and Sensibility", "Jane Austen", "9780141439662", "Elinor and Marianne Dashwood balance emotional restraint and passion after their father's death."),
        ("Emma", "Jane Austen", "9780141439587", "Clever Emma Woodhouse meddles in small-town match-making with disastrous results."),
        ("Persuasion", "Jane Austen", "9780141439686", "Anne Elliot reconnects with Captain Wentworth eight years after breaking their engagement."),
        ("Mansfield Park", "Jane Austen", "9780141439808", "Quiet Fanny Price lives with wealthy relatives at Mansfield Park while maintaining moral integrity."),
        ("Northanger Abbey", "Jane Austen", "9780141439792", "Gothic novel enthusiast Catherine Morland visits a spooky country estate."),
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "Orphaned governess Jane Eyre falls in love with Edward Rochester while discovering Thornfield Hall's secret."),
        ("Villette", "Charlotte Brontë", "9780141439730", "Lucy Snowe travels to a French-speaking city to teach at a girls' boarding school."),
        ("Wuthering Heights", "Emily Brontë", "9780141439556", "The obsessive, destructive love between Heathcliff and Catherine Earnshaw on the Yorkshire moors."),
        ("The Tenant of Wildfell Hall", "Anne Brontë", "9780141439761", "Helen Graham leaves her abusive alcoholic husband to protect her son in Victorian England."),
        ("Agnes Grey", "Anne Brontë", "9780141439693", "A minister's daughter takes positions as a governess to support her family."),
        ("Frankenstein", "Mary Shelley", "9780141439471", "Victor Frankenstein creates a living creature from body parts, triggering tragic consequences."),
        ("Dracula", "Bram Stoker", "9780141439846", "Count Dracula travels from Transylvania to England to spread the undead curse."),
        ("The Picture of Dorian Gray", "Oscar Wilde", "9780141442464", "A portrait ages and rots while Dorian Gray stays eternally young and corrupt."),
        ("Moby-Dick", "Herman Melville", "9780142437247", "Captain Ahab obsessively pursues the giant white whale Moby Dick across oceans."),
        ("Bartleby, the Scrivener", "Herman Melville", "9780486267357", "A Wall Street law clerk responds to all work requests with 'I would prefer not to'."),
        ("The Scarlet Letter", "Nathaniel Hawthorne", "9780142437261", "Hester Prynne is forced to wear a scarlet 'A' after bearing an illegitimate child in Puritan Boston."),
        ("The House of the Seven Gables", "Nathaniel Hawthorne", "9780142437339", "An ancestral curse haunts a Salem family living in a gabled mansion."),
        ("Madame Bovary", "Gustave Flaubert", "9780140449129", "Emma Bovary engages in affairs and spending sprees to escape rural boredom."),
        ("Sentimental Education", "Gustave Flaubert", "9780140447972", "Frédéric Moreau's romantic disillusionment during the French Revolution of 1848."),
        ("Les Misérables", "Victor Hugo", "9780140444308", "Ex-convict Jean Valjean seeks redemption while pursued by relentless inspector Javert."),
        ("The Hunchback of Notre-Dame", "Victor Hugo", "9780140443530", "Quasimodo, the bell-ringer of Notre-Dame, protects the gypsy dancer Esmeralda."),
        ("The Count of Monte Cristo", "Alexandre Dumas", "9780140449266", "Edmond Dantès escapes the Château d'If and exacts vengeance on those who betrayed him."),
        ("The Three Musketeers", "Alexandre Dumas", "9780140449204", "D'Artagnan travels to Paris to join the Musketeers of the Guard and protect the Queen.")
    ],

    "Non-Fiction": [
        ("The Body Keeps the Score", "Bessel van der Kolk", "9780143127741", "How trauma reshapes body and brain, and innovative treatments for healing."),
        ("Noise: A Flaw in Human Judgment", "Daniel Kahneman, Olivier Sibony, Cass R. Sunstein", "9780316451406", "Understanding how unwanted variability in human judgment affects medicine, law, and business."),
        ("Nudge: Improving Decisions About Health, Wealth, and Happiness", "Richard H. Thaler & Cass R. Sunstein", "9780143115267", "Choice architecture and subtle nudges to guide better decisions."),
        ("Misbehaving: The Making of Behavioral Economics", "Richard H. Thaler", "9780393352795", "How human quirks impact markets and traditional economic models."),
        ("Freakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060731335", "Rogue economist explores hidden incentives behind sumo wrestling, real estate, and crime."),
        ("SuperFreakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060889579", "Global warming, street prostitutes, and decision theory analyzed through economic data."),
        ("Think Like a Freak", "Steven D. Levitt & Stephen J. Dubner", "9780062218339", "How to think more creatively, productively, and rationally about modern problems."),
        ("When to Rob a Bank", "Steven D. Levitt & Stephen J. Dubner", "9780062427984", "A curated collection of observations, experiments, and economic insights."),
        ("Outliers: The Story of Success", "Malcolm Gladwell", "9780316017930", "Examining cultural background, family, timing, and the 10,000-hour rule behind extreme success."),
        ("The Tipping Point", "Malcolm Gladwell", "9780316346627", "How small ideas, social trends, and behaviors reach a critical mass and spread like wildfire."),
        ("Blink: The Power of Thinking Without Thinking", "Malcolm Gladwell", "9780316010665", "The science of snap judgments, thin-slicing, and rapid cognition."),
        ("David and Goliath", "Malcolm Gladwell", "9780316213080", "How underdogs, misfits, and disadvantages shape battle outcomes and innovation."),
        ("Talking to Strangers", "Malcolm Gladwell", "9780316478526", "What we should know about the people we don't know and why miscommunication happens."),
        ("The Bomber Mafia", "Malcolm Gladwell", "9780316296618", "World War II innovation, precision bombing, and moral dilemmas in technology."),
        ("Revenge of the Tipping Point", "Malcolm Gladwell", "9780316575805", "Overcoming social epidemics, group dynamics, and dark manipulation in modern society."),
        ("Quiet Power", "Susan Cain", "9780451477385", "Empowering introverted kids, teens, and educators to leverage quiet strengths."),
        ("The Gene: An Intimate History", "Siddhartha Mukherjee", "9781476733500", "The history of genetics from Mendel to CRISPR gene editing and ethical futures."),
        ("The Emperor of All Maladies", "Siddhartha Mukherjee", "9781439170915", "A biography of cancer tracing thousands of years of medical discoveries and battles."),
        ("The Song of the Cell", "Siddhartha Mukherjee", "9781797148564", "How cellular biology transformed medicine and our understanding of human health."),
        ("The Laws of Medicine", "Siddhartha Mukherjee", "9781476784847", "Field notes on uncertainty, precision, and intuition in clinical practice."),
        ("The Immortal Life of Henrietta Lacks", "Rebecca Skloot", "9781400052189", "How cancer cells taken without consent from Henrietta Lacks powered medical breakthroughs for decades."),
        ("Caste: The Origins of Our Discontents", "Isabel Wilkerson", "9780593230251", "Analyzing unspoken caste systems in America, Nazi Germany, and India."),
        ("The Warmth of Other Suns", "Isabel Wilkerson", "9780679763888", "The epic story of America's Great Migration of Black citizens fleeing the South."),
        ("Evicted: Poverty and Profit in the American City", "Matthew Desmond", "9780553447453", "Eight families in Milwaukee struggle to keep shelter amidst housing exploitation."),
        ("Poverty, by America", "Matthew Desmond", "9780593239919", "Why there is so much poverty in the wealthiest nation on earth and how to end it."),
        ("The New Jim Crow", "Michelle Alexander", "9781595581037", "Mass incarceration in the age of colorblindness and criminal justice reform."),
        ("Just Mercy", "Bryan Stevenson", "9780812984965", "A young lawyer founds the Equal Justice Initiative to defend the poor and wrongly condemned."),
        ("The Sun Does Shine", "Anthony Ray Hinton", "9781250309716", "How Anthony Ray Hinton spent 30 years on death row for a crime he didn't commit before being freed."),
        ("Behind the Beautiful Forevers", "Katherine Boo", "9781400064168", "Life, death, and hope in an Annawadi Mumbai slum near the international airport."),
        ("Factory Man", "Beth Macy", "9780316231435", "How one furniture maker fought off globalization to keep jobs in Virginia."),
        ("Dopesick", "Beth Macy", "9780316551243", "Dealers, doctors, and the drug company that addicted America to opioids."),
        ("Raising Lazarus", "Beth Macy", "9780316430227", "Grassroots activists and harm-reduction pioneers fighting the modern addiction crisis."),
        ("Paper: Paging Through History", "Mark Kurlansky", "9780393239614", "How paper technology transformed human literacy, bureaucracy, and art.")
    ]
}

def escape_sql_str(val):
    return val.replace("'", "''")

def main():
    target_path = r"c:\pdd1\database\seed_books_batch_3.sql"
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    statements = []
    statements.append("-- PageMind Database Seed Script: Batch 3 of 10 (500 Books across 15 Genres)\n")
    statements.append("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
    statements.append("USE pagemind;\n\n")

    count = 0
    for genre, books in GENRE_DATA_BATCH_3.items():
        statements.append(f"-- =======================================================\n")
        statements.append(f"-- Genre: {genre} ({len(books)} books)\n")
        statements.append(f"-- =======================================================\n")
        
        for title, author, isbn, desc in books:
            count += 1
            e_title = escape_sql_str(title)
            e_author = escape_sql_str(author)
            e_genre = escape_sql_str(genre)
            e_desc = escape_sql_str(desc)
            
            if isbn:
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
            else:
                cover_url = f"https://via.placeholder.com/300x450/1e1b4b/a5b4fc?text={urllib.parse.quote(title)}"
            e_cover_url = escape_sql_str(cover_url)
            
            amazon_url = f"https://www.amazon.in/s?k={urllib.parse.quote(f'{title} {author}')}"
            flipkart_url = f"https://www.flipkart.com/search?q={urllib.parse.quote(f'{title} {author}')}"
            
            buy_links_dict = {
                "amazon": amazon_url,
                "flipkart": flipkart_url
            }
            buy_links_json = json.dumps(buy_links_dict)
            e_buy_links_json = escape_sql_str(buy_links_json)
            
            pub_year = get_published_year(title, author, genre, desc, isbn)

            
            rating = get_rating(title, author)

            
            sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{e_title}', '{e_author}', '{e_genre}', '{e_desc}', '{e_cover_url}', '{e_buy_links_json}', {pub_year}, {rating});\n"
            statements.append(sql)
            
        statements.append("\n")

    with open(target_path, "w", encoding="utf-8") as f:
        f.writelines(statements)

    print(f"Successfully generated {target_path} with {count} book insert statements across {len(GENRE_DATA_BATCH_3)} genres!")

if __name__ == "__main__":
    main()
