from book_metadata_utils import get_rating, get_published_year
import json
import urllib.parse
import os

# Batch 4: 499 Real, Published Books across 15 Genres (33-34 books per genre)
# Deep-catalog titles completely distinct from Batches 1, 2, and 3.

GENRE_DATA_BATCH_4 = {
    "Fiction": [
        ("Pachinko", "Min Jin Lee", "9781455563937", "Four generations of a poor Korean immigrant family fight to control their destiny in 20th-century Japan."),
        ("Free Food for Millionaires", "Min Jin Lee", "9780446581080", "A Princeton graduate struggles to balance family expectations, luxury desires, and ambition in NYC."),
        ("Klara and the Sun", "Kazuo Ishiguro", "9780593318172", "An Artificial Friend with outstanding observational qualities watches the world from a store window."),
        ("The Remains of the Day", "Kazuo Ishiguro", "9780679731726", "An elderly butler reflects on his decades of devoted service at Darlington Hall."),
        ("Never Let Me Go", "Kazuo Ishiguro", "9781400078776", "Kathy, Ruth, and Tommy grow up at Hailsham, a secluded English boarding school with a dark secret."),
        ("The Buried Giant", "Kazuo Ishiguro", "9780307271082", "An elderly Briton couple journeys across post-Arthurian England in search of their forgotten son."),
        ("An Artist of the Floating World", "Kazuo Ishiguro", "9780679722663", "An aging Japanese painter looks back on his career during WWII and struggles with shifting social values."),
        ("A Pale View of Hills", "Kazuo Ishiguro", "9780679722670", "A Japanese widow living in England remembers her life in post-war Nagasaki after her daughter's suicide."),
        ("A Town Like Alice", "Nevil Shute", "9780307474001", "A young Englishwoman survives a WWII death march in Malaya and rebuilds a Australian Outback community."),
        ("On the Beach", "Nevil Shute", "9780307474018", "Survivors in Australia await the gradual arrival of deadly radioactive fallout after a global nuclear war."),
        ("Drive Your Plow Over the Bones of the Dead", "Olga Tokarczuk", "9780525541332", "An eccentric elderly Polish woman investigates mysterious murders of local hunters in a rural village."),
        ("Primeval and Other Times", "Olga Tokarczuk", "9780939010097", "Four generations of inhabitants live in a mythical Polish village guarded by archangels."),
        ("Flights", "Olga Tokarczuk", "9780525534204", "A philosophical exploration of travel, human anatomy, and body preservation across centuries."),
        ("The Books of Jacob", "Olga Tokarczuk", "9781101980408", "An epic historical novel following 18th-century charismatic leader Jacob Frank across Poland and Ottoman Empire."),
        ("A Fine Balance", "Rohinton Mistry", "9780679776819", "Four strangers bonded by fate navigate state emergency and social turmoil in 1975 India."),
        ("Such a Long Journey", "Rohinton Mistry", "9780679738763", "A bank clerk in 1971 Bombay is drawn into a covert political plot involving state intelligence."),
        ("Family Matters", "Rohinton Mistry", "9780375706172", "An elderly Parkinson's patient moves in with his daughter's family in a cramped Bombay apartment."),
        ("Tales from Firozsha Baag", "Rohinton Mistry", "9780679730347", "Interconnected stories portraying Parsi apartment building residents in Bombay."),
        ("The Ministry of Utmost Happiness", "Arundhati Roy", "9780735223745", "A sweeping tale of diverse souls seeking refuge across Delhi graveyards and Kashmiri valleys."),
        ("Small Things Like These", "Claire Keegan", "9780802158741", "A timber merchant in 1985 Ireland uncovers dark secrets kept by the local convent."),
        ("Foster", "Claire Keegan", "9780802160140", "A young girl sent to live with foster parents in rural Ireland discovers genuine affection for the first time."),
        ("Antarctica", "Claire Keegan", "9780802146441", "A collection of short stories depicting quiet desperation, love, and isolation in rural Ireland."),
        ("A Man Called Ove", "Fredrik Backman", "9781476738024", "A grumpy neighborhood curmudgeon's life is disrupted by a lively young family moving in next door."),
        ("Beartown", "Fredrik Backman", "9781501160769", "A small forest town pinned under economic hardship places all its hopes on a junior hockey team."),
        ("Us Against You", "Fredrik Backman", "9781501160790", "The aftermath of tragedy threatens to tear apart the rival towns of Beartown and Hed."),
        ("The Winners", "Fredrik Backman", "9781982112790", "Two years after the events of Beartown, long-standing rivalries ignite a final reckoning."),
        ("Anxious People", "Fredrik Backman", "9781501160837", "A failed bank robber holds eight hostages at an apartment open house, prompting unexpected bonding."),
        ("My Grandmother Asked Me to Tell You She's Sorry", "Fredrik Backman", "9781501115073", "A seven-year-old girl delivers apology letters left behind by her eccentric grandmother."),
        ("Britt-Marie Was Here", "Fredrik Backman", "9781501125790", "A fussy woman leaves her unfaithful husband and takes a job managing a youth center in a rundown town."),
        ("And Every Morning the Way Home Gets Longer and Longer", "Fredrik Backman", "9781501157844", "A grandfather and his grandson share quiet conversations while navigating memory loss."),
        ("The Memory Police", "Yoko Ogawa", "9781101911815", "Residents of an isolated island forget objects that disappear under the watchful eye of police."),
        ("The Housekeeper and the Professor", "Yoko Ogawa", "9780312427801", "A brilliant mathematician with 80-minute short-term memory forms a bond with his young housekeeper and her son."),
        ("Hotel Iris", "Yoko Ogawa", "9780312425258", "A young woman working at a seaside hotel embarks on a dark relationship with a reclusive translator."),
        ("Revenge: Eleven Dark Tales", "Yoko Ogawa", "9780312674465", "Interconnected macabre short stories exploring obsession, murder, and desire.")
    ],

    "Mystery": [
        ("The Malice of Fortune", "Michael Ennis", "9780307985477", "Machiavelli and Leonardo da Vinci team up to catch a serial killer stalking Romagna in 1502."),
        ("Magpie Murders", "Anthony Horowitz", "9780062645227", "An editor reads a mystery manuscript missing its final chapter and realizes the author was murdered."),
        ("Moonflower Murders", "Anthony Horowitz", "9780062955456", "Susan Ryeland investigates a disappearance at a hotel tied to a murder detailed in Atticus Pünd's novel."),
        ("The Word Is Murder", "Anthony Horowitz", "9780062676788", "Author Anthony Horowitz partners with ex-detective Daniel Hawthorne to solve a wealthy woman's murder."),
        ("The Sentence Is Death", "Anthony Horowitz", "9780062883070", "Hawthorne and Horowitz investigate the murder of a celebrity divorce lawyer killed with a bottle of wine."),
        ("A Line to Kill", "Anthony Horowitz", "9780062883100", "Hawthorne and Horowitz attend a literary festival on Alderney island where a murder halts proceedings."),
        ("The Twist of a Knife", "Anthony Horowitz", "9780063079366", "When a harsh theater critic is stabbed to death after reviewing Horowitz's play, Anthony becomes prime suspect."),
        ("Close to Death", "Anthony Horowitz", "9780063305618", "Hawthorne investigates a neighbor feud on a suburban street that leads to crossbow murder."),
        ("The House of Silk", "Anthony Horowitz", "9780312638993", "An authorized Sherlock Holmes novel involving a mysterious assassin in a flat cap."),
        ("Moriarty", "Anthony Horowitz", "9780062377180", "Pinkerton agent Frederick Chase and Inspector Jones investigate Moriarty's criminal network post-Reichenbach."),
        ("The Maid", "Nita Prose", "9780593356159", "Molly the hotel maid discovers a wealthy guest dead in his bed and finds herself targeted as suspect."),
        ("The Mystery Guest", "Nita Prose", "9780593356180", "Molly the Head Maid investigates the sudden death of a famous mystery author in the hotel tearoom."),
        ("Everyone in My Family Has Killed Someone", "Benjamin Stevenson", "9780063279025", "Ernie Cunningham explains how every member of his family committed a murder as bodies pile up at a ski resort."),
        ("Everyone on This Train Is a Suspect", "Benjamin Stevenson", "9780063279070", "Ernie attends a crime writers' festival aboard the Ghan train where an author is murdered in a locked carriage."),
        ("The Thursday Murder Club", "Richard Osman", "9781984880963", "Four retirement village residents meet weekly to investigate unsolved crimes and tackle a live murder."),
        ("The Man Who Died Twice", "Richard Osman", "9781984880994", "Elizabeth receives a letter from an ex-husband targeted by MI5 and stolen diamonds."),
        ("The Bullet That Missed", "Richard Osman", "9780593299395", "The Thursday Murder Club pursues a decade-old cold case of a news reporter whose body was never found."),
        ("The Last Devil to Die", "Richard Osman", "9780593299425", "The club races against time to recover an illegal package worth millions lost in transit."),
        ("We Solve Murders", "Richard Osman", "9780593653227", "A father-in-law ex-cop and his bodyguard daughter-in-law protect a famous author targeted by killers."),
        ("The Tokyo Zodiac Murders", "Soji Shimada", "9781782273950", "Kiyoshi Mitarai investigates a 40-year-old locked-room murder case involving an astrologer's family."),
        ("Murder in the Crooked House", "Soji Shimada", "9781782274568", "Guests visiting an eccentric maze-like mansion in snowy Hokkaido are murdered one by one."),
        ("Newcomer", "Keigo Higashino", "9781250170193", "Detective Kaga investigates a woman's murder in Nihonbashi by piecing together small secrets of neighborhood shopkeepers."),
        ("A Midsummer's Equation", "Keigo Higashino", "9780312606329", "Professor Yukawa investigates an accidental death at a seaside inn linked to an old Tokyo murder."),
        ("Silent Parade", "Keigo Higashino", "9781250232496", "A suspect in a young woman's disappearance is murdered during an autumn street parade."),
        ("The Name of the Rose", "Umberto Eco", "9780156001311", "Franciscan friar William of Baskerville investigates series of mysterious deaths at a 14th-century Italian monastery."),
        ("Foucault's Pendulum", "Umberto Eco", "9780156032971", "Three Milanese editors construct a fake Templar conspiracy secret plan that turns dangerously real."),
        ("The Island of the Day Before", "Umberto Eco", "9780156006330", "A 17th-century nobleman marooned on a ship off the International Date Line contemplates time and longitude."),
        ("Baudolino", "Umberto Eco", "9780156029254", "A peasant boy in 12th-century Italy fabricates legends and embarks on a quest for Prester John's kingdom."),
        ("The Prague Cemetery", "Umberto Eco", "9780547577531", "A 19th-century secret agent and master photographer crafts forged documents and anti-Semitic hoaxes across Europe."),
        ("Numero Zero", "Umberto Eco", "9780544635135", "A ghostwriter hired by a scandal newspaper uncovers conspiracy theories surrounding Mussolini's double."),
        ("The Decagon House Murders", "Yukito Ayatsuji", "9781782276340", "University mystery club members visiting an isolated island with a decagonal house are killed off in Agatha Christie homage."),
        ("The Honjin Murders", "Seishi Yokomizo", "9781782275008", "Detective Kosuke Kindaichi investigates a locked-room double murder on a snow-covered traditional estate."),
        ("The Inugami Curse", "Seishi Yokomizo", "9781782275039", "Kindaichi investigates a series of gruesome murders surrounding an eccentric silk tycoon's will.")
    ],

    "Thriller": [
        ("The Girl on the Train", "Paula Hawkins", "9780385682312", "A commuter watching a couple from her train window becomes entangled in a missing person investigation."),
        ("Into the Water", "Paula Hawkins", "9780735211209", "A single mother is found dead at the bottom of the river, bringing past secrets to light in a small town."),
        ("A Slow Fire Burning", "Paula Hawkins", "9780593418895", "The brutal murder of a young man on a London houseboat links three troubled women with motives."),
        ("The Woman in the Window", "A.J. Finn", "9780062678416", "An agoraphobic woman watching her neighbors from her window witnesses a violent crime across the street."),
        ("Before I Go to Sleep", "S.J. Watson", "9780062060556", "A woman waking up every morning with no memory of her past discovers her husband is hiding dark truths."),
        ("The Wife Between Us", "Greer Hendricks & Sarah Pekkanen", "9781250130921", "A psychological thriller exposing hidden truths about a wealthy husband and his former and current wives."),
        ("An Anonymous Girl", "Greer Hendricks & Sarah Pekkanen", "9781250133731", "A makeup artist joining an ethics study finds her answers manipulated by a ruthless psychiatrist."),
        ("You Are Not Alone", "Greer Hendricks & Sarah Pekkanen", "9781250202031", "A lonely woman is drawn into a glamorous clique of sisters with deadly intentions."),
        ("The Golden Couple", "Greer Hendricks & Sarah Pekkanen", "9781250273208", "A non-traditional therapist tackles a wealthy couple's marriage secrets after an admission of infidelity."),
        ("Dark Matter", "Blake Crouch", "9781101904220", "A physics professor is kidnapped and knocked unconscious, waking up in an alternate reality where he never married."),
        ("Recursion", "Blake Crouch", "9781524759780", "A detective investigates False Memory Syndrome while a neuroscientist invents technology to relive memories."),
        ("Upgrade", "Blake Crouch", "9781984819611", "A government agent's genome is hacked, enhancing his cognitive and physical capabilities for a bio-war."),
        ("Wayward Pines: Pines", "Blake Crouch", "9781477808719", "Secret Service agent Ethan Burke searches for two missing agents in a sinister Idaho mountain town."),
        ("Wayward Pines: Wayward", "Blake Crouch", "9781477808702", "Ethan discovers the terrifying truth behind the electric fences surrounding Wayward Pines."),
        ("Wayward Pines: The Last Town", "Blake Crouch", "9781477808726", "The electric fence fails, releasing mutated predators into the town of Wayward Pines."),
        ("Run", "Blake Crouch", "9781477808566", "A sudden aurora causes half of humanity to turn homicidally violent against the other half."),
        ("Abandon", "Blake Crouch", "9781477808573", "A journalist explores a deserted 19th-century mining town in the Rockies where residents vanished overnight."),
        ("Shutter Island", "Dennis Lehane", "9780060590314", "US Marshal Teddy Daniels investigates the disappearance of a murderess from an asylum on a remote island."),
        ("Mystic River", "Dennis Lehane", "9780060515126", "Three childhood friends in Boston are reunited when one's daughter is murdered and another becomes prime suspect."),
        ("Gone, Baby, Gone", "Dennis Lehane", "9780061154287", "Private investigators Patrick Kenzie and Angela Gennaro search for a kidnapped four-year-old girl in Dorchester."),
        ("Live by Night", "Dennis Lehane", "9780060004873", "Joe Coughlin rises from petty thief to powerful bootlegger in Prohibition-era Boston and Tampa."),
        ("World War Z", "Max Brooks", "9780307346612", "An oral history reporter collects global survivor accounts of the decade-long Zombie War."),
        ("The Zombie Survival Guide", "Max Brooks", "9781400049622", "A comprehensive tactical manual on surviving outbreaks of undead reanimation."),
        ("Devolution", "Max Brooks", "9781984826787", "High-tech eco-community journal entries describe terror when Mount Rainier erupts and Bigfoot attacks."),
        ("The Firm", "John Grisham", "9780385416344", "A young Harvard Law graduate joins a boutique Memphis law firm secretly owned by a Chicago mob family."),
        ("The Pelican Brief", "John Grisham", "9780385424714", "A law student writes a legal brief explaining the assassination of two Supreme Court Justices."),
        ("A Time to Kill", "John Grisham", "9780385472944", "A young Mississippi lawyer defends a father who took revenge on men who harmed his daughter."),
        ("The Client", "John Grisham", "9780385424738", "An 11-year-old boy witnesses a mob lawyer's suicide and learns where a US Senator's body is buried."),
        ("The Rainmaker", "John Grisham", "9780385424721", "An idealist law student takes on a predatory insurance company denying a leukemia patient's claim."),
        ("The Runaway Jury", "John Grisham", "9780385472975", "A tobacco trial in Mississippi is secretly manipulated by a mysterious jury insider."),
        ("The Partner", "John Grisham", "9780385472951", "A law firm partner fakes his death, steals ninety million dollars, and escapes to Brazil."),
        ("The Street Lawyer", "John Grisham", "9780385490993", "A corporate lawyer held hostage by a homeless man quits his firm to practice public interest law."),
        ("The Testament", "John Grisham", "9780385493802", "An eccentric billionaire leaves his fortune to a missionary daughter living deep in the Pantanal wetlands.")
    ],

    "Romance": [
        ("The Hating Game", "Sally Thorne", "9780062439598", "Executive assistants Lucy and Joshua compete for a promotion while trying to hide mutual attraction."),
        ("99 Percent Mine", "Sally Thorne", "9780062839954", "Darcy Barrett renovates her grandmother's cottage alongside her brother's handsome best friend."),
        ("Second First Impressions", "Sally Thorne", "9780062977229", "A quiet retirement village assistant manages a free-spirited handyman who moves into the complex."),
        ("Angelika Frankenstein Makes a Man", "Sally Thorne", "9780063238916", "Victor Frankenstein's sister uses science and romance to assemble her ideal suitor from body parts."),
        ("Check & Mate", "Ali Hazelwood", "9780593638903", "A former chess prodigy returns to competitive play and faces an arrogant world champion."),
        ("Bride", "Ali Hazelwood", "9780593638842", "A vampiric noblewoman enters an arranged political marriage with a werewolf alpha."),
        ("Loathe to Love You", "Ali Hazelwood", "9780593638880", "Three novellas featuring female scientists falling for rival engineers and colleagues."),
        ("Love, Theoretically", "Ali Hazelwood", "9780593336847", "A theoretical physicist fake-dates her best friend's brother who turns out to be an experimental physicist rival."),
        ("The Spanish Love Deception", "Elena Armas", "9781668002520", "Catalina Martin brings her annoying work colleague Aaron Blackford as a fake date to her sister's wedding in Spain."),
        ("The American Roommate Experiment", "Elena Armas", "9781668002544", "Rosie Graham shares a cramped NYC apartment with her best friend's handsome Spanish cousin Lucas."),
        ("Funny Story", "Emily Henry", "9780593441282", "Daphne and Miles become roommates after their respective exes leave them for each other."),
        ("Happy Place", "Emily Henry", "9780593441275", "A broken-up couple fake staying together during their college friend group's annual vacation in Maine."),
        ("Out on a Limb", "Hannah Bonam-Young", "9780063385733", "Two people with physical limb differences share a one-night stand that leads to unexpected pregnancy and love."),
        ("Next of Kin", "Hannah Bonam-Young", "9780063385719", "Two young adults co-adopt foster children while sharing a house to meet custody guidelines."),
        ("Drive", "Kate Stewart", "9781947395022", "A music reporter takes a road trip listening to a playlist that traces two profound loves."),
        ("The Fine Print", "Lauren Asher", "9781737507901", "Rowan, a cynical theme park executive, hires creative Zahra to redesign an attraction."),
        ("Terms and Conditions", "Lauren Asher", "9781737507918", "Declan must marry to secure his inheritance and convinces his assistant Iris to fake-marry him."),
        ("Final Offer", "Lauren Asher", "9781737507925", "Callahan attempts to sell his grandfather's lake house while reconnecting with his childhood love Alana."),
        ("Throttled", "Lauren Asher", "9781737507932", "Formula 1 driver Jaxson falls for his rival team driver's sister during a racing season."),
        ("Collided", "Lauren Asher", "9781737507949", "An F1 driver helps a bucket-list lover live life to the fullest."),
        ("Wrecked", "Lauren Asher", "9781737507956", "A dark and emotional story of secrets, speed, and romance."),
        ("Redeemed", "Lauren Asher", "9781737507963", "A disgraced F1 driver finds redemption with a dedicated physical therapist."),
        ("Things We Never Got Over", "Lucy Score", "9781035402687", "Naomi runs away from her wedding to rescue her estranged twin in Knockemout, meeting barber Knox."),
        ("Things We Hide from the Light", "Lucy Score", "9781035402700", "Police chief Nash recovers from a gunshot wound while forming a bond with neighbor Lina."),
        ("Things We Left Behind", "Lucy Score", "9781035402724", "Lucian and Sloane resolve decades of hostility and secret longing in Knockemout."),
        ("By a Thread", "Lucy Score", "9781945631832", "Ally takes a job at a fashion magazine where she clashes with arrogant executive Dominic."),
        ("Rock Bottom Girl", "Lucy Score", "9781945631801", "Marley returns to her hometown at thirty-eight and fake-dates former high school athlete Jake."),
        ("Maggie Moves On", "Lucy Score", "9781542036481", "House flipper Maggie renovates a Victorian mansion in Idaho with help from landscaper Silas."),
        ("The Worst Best Man", "Mia Sosa", "9780062909879", "A wedding planner forced to partner with her ex-fiance's brother on a career-making job."),
        ("The Marriage Code", "Nisha Sharma", "9780593101568", "A tech director in Mumbai collaborates with a former rival to build a legal app."),
        ("Dating Dr. Dil", "Nisha Sharma", "9780063001121", "A lawyer and a TV cardiologist fake-date to satisfy their traditional Indian families."),
        ("Tastes Like Shakkar", "Nisha Sharma", "9780063001152", "A wedding planner and an event coordinator clash and spark during a high-profile wedding season."),
        ("My Neighbor's Secret", "Sonali Dev", "9780063057111", "A heartwarming modern romance navigating second chances and family secrets.")
    ],

    "Fantasy": [
        ("The Legend of Black Shawane", "Evan Winter", "9780316489799", "Tau trains relentlessly to become a master swordsman in an Omehi dragon fantasy realm."),
        ("The Rage of Dragons", "Evan Winter", "9780316489768", "In a world of constant war, Tau sacrifices everything to avenge his father against nobles."),
        ("The Fires of Vengeance", "Evan Winter", "9780316489775", "Tau leads queen Tsiora's royal guard against rebellious noble houses and demon legions."),
        ("The Blade Itself", "Joe Abercrombie", "9780535456123", "Barbarian Logen Ninefingers, inquisitor Glokta, and nobleman Jezal are drawn together by wizard Bayaz."),
        ("Before They Are Hanged", "Joe Abercrombie", "9780535456130", "Logen and Bayaz travel across ruined lands while Glokta defends Dagoska against the Gurkish army."),
        ("Last Argument of Kings", "Joe Abercrombie", "9780535456147", "War engulfs the Union as Logen fights for the crown of the North and Glokta uncovers Bayaz's secrets."),
        ("Best Served Cold", "Joe Abercrombie", "9780316044967", "Mercenary captain Monza Murcatto plots brutal revenge against seven betrayers across Styria."),
        ("The Heroes", "Joe Abercrombie", "9780316044981", "Three days of bloody battle over a hilltop stone circle seen through soldiers on both sides."),
        ("Red Country", "Joe Abercrombie", "9780316044998", "Shy South and old man Lamb track kidnapped children across a lawless fantasy Western frontier."),
        ("A Little Hatred", "Joe Abercrombie", "9780316187169", "The industrial age dawns in the Circle of the World as machine mills trigger social rebellion."),
        ("The Trouble with Peace", "Joe Abercrombie", "9780316187152", "Conspiracies and civil war erupt as Leo dan Brock and Savine dan Glokta plot against the Crown."),
        ("The Wisdom of Crowds", "Joe Abercrombie", "9780316187145", "Chaos and terror reign under the Breakers as old powers manipulate the revolutionary tribunal."),
        ("Legends & Lattes", "Travis Baldree", "9781250886088", "A weary female orc adventurer hangs up her sword to open the first coffee shop in a fantasy city."),
        ("Bookshops & Bonedust", "Travis Baldree", "9781250886101", "Young Viv recovers from injury in a seaside town and helps a struggling bookshop owner."),
        ("The Jasmine Throne", "Tasha Suri", "9780316536287", "An exiled princess and a maid possessing forbidden plant magic conspire to overthrow a tyrannical emperor."),
        ("The Oleander Sword", "Tasha Suri", "9780316536300", "Empress Malini marches her army against her fanatical brother while Priya leads magical forces."),
        ("The Lotus Empire", "Tasha Suri", "9780316536324", "The epic resolution as Parijat magic blooms and empires crumble in a South-Asian inspired fantasy world."),
        ("Empire of Sand", "Tasha Suri", "9780316440929", "A noble's illegitimate daughter uses dance magic to survive forced marriage to a dark mystics leader."),
        ("Realm of Ash", "Tasha Suri", "9780316440936", "A disgraced noblewoman enters the ancestral spirit realm to stop a magical plague."),
        ("The Bone Shard Daughter", "Andrea Stewart", "9780316541411", "Lin tries to reclaim her father's bone-shard animal automaton magic while rebels attack the emperor."),
        ("The Bone Shard Emperor", "Andrea Stewart", "9780316541442", "Empress Lin seeks allies among island governors while construct beasts threaten the empire."),
        ("The Bone Shard War", "Andrea Stewart", "9780316541473", "Lin faces the returned ancient Alanga masters in a final conflict for the Phoenix Empire."),
        ("A Darker Shade of Magic", "V.E. Schwab", "9780765376450", "Kell, one of the last Antari magicians capable of traveling between parallel Londons, smuggles dangerous artifacts."),
        ("A Gathering of Shadows", "V.E. Schwab", "9780765376467", "Red London hosts the Element Games tournament while Black London's magic begins to stir."),
        ("A Conjuring of Light", "V.E. Schwab", "9780765376474", "Heroes across parallel worlds unite to defeat a dark shadow entity devouring Red London."),
        ("The Fragile Threads of Power", "V.E. Schwab", "9780765387493", "Seven years after the Element Games, new thieves and young Antari arise in London."),
        ("The Invisible Life of Addie LaRue", "V.E. Schwab", "9780765387561", "A young French woman makes a bargain to live forever but is cursed to be forgotten by everyone she meets."),
        ("Vicious", "V.E. Schwab", "9780765335340", "Two college roommates discover near-death experiences grant superpowers and become bitter enemies."),
        ("Vengeful", "V.E. Schwab", "9780765387523", "Eli and Victor clash again in Merit City alongside new ExtraOrdinary individuals."),
        ("Gallant", "V.E. Schwab", "9780062835772", "A mute orphan girl called to her family estate uncovers a shadowy mirror house behind a garden wall."),
        ("The Atlas Six", "Olivie Blake", "9781250854506", "Six extraordinary magicians compete for five spots in the secret Alexandrian Society."),
        ("The Atlas Paradox", "Olivie Blake", "9781250854537", "The initiates navigate betrayal, time travel, and world-shattering physics inside the Alexandrian archives."),
        ("The Atlas Complex", "Olivie Blake", "9781250854568", "The dramatic final battle for ultimate control over knowledge and reality."),
        ("Masters of Death", "Olivie Blake", "9781250884268", "A real estate agent who is a vampire hires a medium to solve a ghost's murder.")
    ],

    "Science Fiction": [
        ("Children of Time", "Adrian Tchaikovsky", "9780316452502", "Humanity's last survivors flee Earth in an ark ship, encountering a planet populated by uplifted jumping spiders."),
        ("Children of Ruin", "Adrian Tchaikovsky", "9780316452533", "Explorers encounter a terraformed water world dominated by intelligent octopuses and an ancient parasite."),
        ("Children of Memory", "Adrian Tchaikovsky", "9780316452571", "Spacefarers investigate a struggling human colony on a harsh world where reality seems strangely distorted."),
        ("Shards of Earth", "Adrian Tchaikovsky", "9780316705844", "An un-bonded ship crew uncovers clues to the mysterious moon-sized Architects that destroyed Earth."),
        ("Eyes of the Void", "Adrian Tchaikovsky", "9780316705882", "The Architects return to destroy human systems while Idris plunges into un-space to communicate."),
        ("Lords of Uncreation", "Adrian Tchaikovsky", "9780316705912", "Idris leads a final mission inside un-space to eliminate the Architect threat forever."),
        ("Elder Race", "Adrian Tchaikovsky", "9781250760142", "A junior anthropologist with advanced tech is viewed as a wizard by a medieval princess."),
        ("Cage of Souls", "Adrian Tchaikovsky", "9781788640527", "A political prisoner recounts life in Shadrapar, the last human city on a dying Earth."),
        ("A Memory Called Empire", "Arkady Martine", "9781250186430", "Ambassador Mahit Dzmare arrives at Teixcalaan capital to find her predecessor murdered and her imager mesh damaged."),
        ("A Desolation Called Peace", "Arkady Martine", "9781250186461", "Mahit Dzmare and Three Seagrass attempt first contact with an inscrutable alien armada on the frontier."),
        ("Project Hail Mary", "Andy Weir", "9780593135204", "Ryland Grace awakens from a coma on a solo space mission to save Earth from sun-eating Astrophage."),
        ("Artemis", "Andy Weir", "9780553448122", "A smuggler on the Moon's only city gets drawn into a conspiracy for control of aluminum production."),
        ("The Martian", "Andy Weir", "9780553418026", "Astronaut Mark Watney is stranded on Mars after a dust storm and uses botany and engineering to survive."),
        ("Ancillary Justice", "Ann Leckie", "9780316246620", "Breq, formerly the AI troop carrier Justice of Toren, pursues revenge against the ruler of the Radch empire."),
        ("Ancillary Sword", "Ann Leckie", "9780316246651", "Fleet Captain Breq travels to Athoek station to protect the sister of an officer she once killed."),
        ("Ancillary Mercy", "Ann Leckie", "9780316246682", "Breq defends Athoek station against Anaander Mianaai's warring imperial factions."),
        ("Provenance", "Ann Leckie", "9780316388672", "Ingray attempts to recover stolen historical vestiges to gain her adoptive mother's favor."),
        ("Translation State", "Ann Leckie", "9780316289702", "Three individuals' lives collide around the disappearance of a diplomat from the enigmatic Presger species."),
        ("The Long Way to a Small, Angry Planet", "Becky Chambers", "9780062444134", "Rosemary Harper joins the multi-species crew of the Wayfarer as they punch wormholes across deep space."),
        ("A Closed and Common Orbit", "Becky Chambers", "9780062444172", "A decommissioned ship AI in a synthetic body adapts to living on an alien planet with a tinkerer."),
        ("Record of a Spaceborn Few", "Becky Chambers", "9780062699220", "Life, culture, and death aboard the Exodus Fleet ships that rescued humanity from Earth."),
        ("The Galaxy, and the Ground Within", "Becky Chambers", "9780062936042", "Five alien travelers stranded at a five-star orbital stopover share food, stories, and perspectives."),
        ("To Be Taught, If Fortunate", "Becky Chambers", "9780062936011", "Four astronauts explore four extra-solar ecological worlds without altering native ecosystems."),
        ("A Psalm for the Wild-Built", "Becky Chambers", "9781250236210", "A tea monk meets a wild robot centuries after robots gained independence and walked into the forest."),
        ("A Prayer for the Crown-Shy", "Becky Chambers", "9781250236234", "Dex and Mosscap travel across human settlements answering what people need."),
        ("The Space Between Worlds", "Micaiah Johnson", "9780593135051", "Cara travels between alternate Earths as an investigator because her alter-egos on those worlds are dead."),
        ("Sea of Tranquility", "Emily St. John Mandel", "9780593321447", "Time travel, moon colonies, and a shared musical anomaly spanning 1912, 2020, and 2401."),
        ("Station Eleven", "Emily St. John Mandel", "9780385353304", "A traveling Shakespearean troupe performs in settlements 20 years after a devastating flu pandemic."),
        ("The Glass Hotel", "Emily St. John Mandel", "9780593080535", "A luxury hotel bartender, a Ponzi scheme collapse, and mysterious disappearances at sea."),
        ("Dead Astronauts", "Jeff VanderMeer", "9780374276805", "Three rebels fight a corrupt Biotech Company across ruined alternate timeline versions of a city."),
        ("Borne", "Jeff VanderMeer", "9780374115241", "Rachel scavenges a ruined future city and adopts a strange, shapeshifting sea-creature-like specimen named Borne."),
        ("The Strange Bird", "Jeff VanderMeer", "9780374270674", "A bioengineered bird-creature escapes a laboratory and searches for freedom in a broken landscape."),
        ("Hummingbird Salamander", "Jeff VanderMeer", "9780374173548", "A security consultant follows clues left by a dead eco-terrorist involving an extinct hummingbird.")
    ],

    "Horror": [
        ("The Fisherman", "John Langan", "9781939905215", "Two grieving widowers fishing in upstate New York discover a creek connected to an ocean of dark ancient myths."),
        ("Stolen Tongues", "Felix Blackwell", "9781717882516", "A couple staying at a remote cabin in the Rocky Mountains are haunted by a creature imitating voices."),
        ("Penpal", "Dathan Auerbach", "9780985545505", "A young man reconstructs childhood memories to understand a stalker who tracked him for years."),
        ("Bad Man", "Dathan Auerbach", "9780399586033", "Ben works night shifts at a grocery store where his toddler brother disappeared five years ago."),
        ("The Last Days of Jack Sparks", "Jason Arnopp", "9780316362283", "A skeptical journalist researching a book on the supernatural dies mysteriously while investigating a YouTube video."),
        ("Ghoster", "Jason Arnopp", "9780316362344", "A woman investigates her boyfriend's sudden disappearance after finding his phone loaded with disturbing app videos."),
        ("The Terror", "Dan Simmons", "9780316017442", "HMS Erebus and Terror are frozen in Arctic ice as crew members are hunted by a giant polar monster."),
        ("Abominable", "Dan Simmons", "9780316198837", "A 1925 Mount Everest climbing expedition searches for missing mountaineers while pursued up the peak."),
        ("Carrion Comfort", "Dan Simmons", "9780312567071", "A small group of mind-vampires manipulate world history, assassinations, and violence for entertainment."),
        ("Song of Kali", "Dan Simmons", "9780312868789", "An American poet travels to Kolkata to recover lost manuscripts of a dead writer and encounters dark cults."),
        ("The Pallbearers Club", "Paul Tremblay", "9780063069916", "A high school boy forms a friendship with an older girl who keeps a strange polaroid album and drinks blood."),
        ("Survivor Song", "Paul Tremblay", "9780062363320", "A fast-acting rabies-like virus ravages Massachusetts while an emergency doctor tries to protect her pregnant friend."),
        ("Growing Things and Other Stories", "Paul Tremblay", "9780062679130", "Nineteen unsettling stories exploring psychological dread, monsters, and family secrets."),
        ("Horrorstör", "Grady Hendrix", "9781594745263", "Employees working night shifts at an Orsk Swedish furniture store encounter haunted 19th-century panopticon ghosts."),
        ("My Best Friend's Exorcism", "Grady Hendrix", "9781594748622", "High school best friends in 1988 South Carolina face demonic possession after a night at a lake house."),
        ("The Southern Book Club's Guide to Slaying Vampires", "Grady Hendrix", "9781683691433", "Suburban mothers in 1990s Charleston suspect a charming newcomer is preying on local children."),
        ("The Final Girl Support Group", "Grady Hendrix", "9780593201237", "Six real-life final girls who survived famous slasher massacres are targeted by a killer decades later."),
        ("How to Sell a Haunted House", "Grady Hendrix", "9780593201268", "Estranged siblings clearing out their deceased parents' house are confronted by haunted puppets."),
        ("Paperbacks from Hell", "Grady Hendrix", "9781594749810", "An illustrated history of the 1970s and 80s boom in pulp horror fiction."),
        ("Slewfoot: A Tale of Hexery", "Brom", "9781250104212", "In 1666 Connecticut, a young Puritan widow forms an alliance with an ancient forest spirit."),
        ("Lost Gods", "Brom", "9780062092220", "A murdered man descends into Purgatory to retrieve a protective talisman for his pregnant wife."),
        ("The Child Thief", "Brom", "9780061671333", "A dark reimagining of Peter Pan set in a violent, dying island realm of Avalon."),
        ("Krampus: The Yule Lord", "Brom", "9780062092039", "Krampus awakens in modern West Virginia to reclaim Yule from Santa Claus."),
        ("Patient Zero", "Jonathan Maberry", "9780312384371", "Cop Joe Ledger is recruited into the Department of Military Sciences to stop a terrorist pathogen."),
        ("The Dragon Factory", "Jonathan Maberry", "9780312552176", "Joe Ledger battles rogue geneticists designing custom monster viruses."),
        ("Code Zero", "Jonathan Maberry", "9780312552190", "A rogue AI releases forgotten pathogens across top-secret facilities."),
        ("Predator One", "Jonathan Maberry", "9781250041753", "Terrorists take control of military drones and weapons platforms during a national event."),
        ("Kill Switch", "Jonathan Maberry", "9781250041777", "Joe Ledger races to recover an alien relic capable of shutting down global power grids."),
        ("Dogs of War", "Jonathan Maberry", "9781250041791", "Bio-engineered animal war beasts are turned against human populations."),
        ("Deep Silence", "Jonathan Maberry", "9781250192455", "Subterranean sonic weapon devices trigger mass madness across coastal cities."),
        ("Rage", "Jonathan Maberry", "9781250192486", "A synthetic rage-inducing virus turns citizens into mindless attackers."),
        ("Relic", "Douglas Preston & Lincoln Child", "9780812543261", "A beast slays museum visitors in dark exhibition corridors in the New York Museum of Natural History."),
        ("Reliquary", "Douglas Preston & Lincoln Child", "9780812542837", "Beheaded skeletons found in NYC subways reveal a horrifying chemical mutation formula.")
    ],

    "Self-Help": [
        ("The 7 Habits of Highly Effective People", "Stephen R. Covey", "9780743269513", "A principle-centered approach for solving personal and professional problems."),
        ("First Things First", "Stephen R. Covey", "9780684802039", "Time management techniques focused on quadrant II priorities and core values."),
        ("Principle-Centered Leadership", "Stephen R. Covey", "9780671792800", "Building organizational trust and long-term effectiveness through moral principles."),
        ("The 8th Habit: From Effectiveness to Greatness", "Stephen R. Covey", "9780684846651", "Finding your voice and inspiring others to find theirs in the knowledge worker age."),
        ("The Speed of Trust", "Stephen M.R. Covey", "9781416564003", "How trust accelerates business performance and strengthens personal relationships."),
        ("Drive: The Surprising Truth About What Motivates Us", "Daniel H. Pink", "9781594488849", "Autonomy, mastery, and purpose as the true drivers of human performance over carrot-and-stick rewards."),
        ("To Sell Is Human", "Daniel H. Pink", "9781594487156", "Modern persuasion skills and non-sales selling techniques for everyone."),
        ("When: The Scientific Secrets of Perfect Timing", "Daniel H. Pink", "9780735210622", "Using biological clocks, social rhythms, and timing research to optimize performance."),
        ("A Whole New Mind", "Daniel H. Pink", "9781594481710", "Why right-brain aptitude—empathy, design, play, and story—will rule the future economy."),
        ("Free Agent Nation", "Daniel H. Pink", "9780446678797", "The rise of independent workers, freelancers, and home-based entrepreneurs."),
        ("The Power of Regret", "Daniel H. Pink", "9780735210653", "How looking backward on regrets points the way forward to a meaningful life."),
        ("Designing Your Life", "Bill Burnett & Dave Evans", "9781101875322", "Applying design thinking to build a fulfilling career and balanced life."),
        ("Designing Your New Work Life", "Bill Burnett & Dave Evans", "9780593318615", "How to adapt and thrive in changing workplaces using design tools."),
        ("Tiny Habits", "BJ Fogg", "9780358003328", "The small changes that change everything through behavior design and anchor triggers."),
        ("Four Thousand Weeks: Time Management for Mortals", "Oliver Burkeman", "9780374159122", "Embracing human finitude and rejecting productivity anxiety in an average 80-year lifespan."),
        ("The Antidote: Happiness for People Who Can't Stand Positive Thinking", "Oliver Burkeman", "9780865479418", "Exploring the negative path to happiness through Stoicism, Buddhism, and failure acceptance."),
        ("Indistractable", "Nir Eyal", "9781948836531", "How to control your attention and choose your life against internal and external triggers."),
        ("Hooked: How to Build Habit-Forming Products", "Nir Eyal", "9781591847786", "The Hook Model explaining how successful apps engage users through trigger-action-reward-investment loops."),
        ("Range: Why Generalists Triumph in a Specialized World", "David Epstein", "9780735214484", "Why diverse experience, late starts, and broad interest lead to long-term success."),
        ("The Sports Gene", "David Epstein", "9781591845119", "Inside the science of extraordinary athletic performance and genetics."),
        ("Ultralearning", "Scott H. Young", "9780062852687", "Master hard skills, outsmart the competition, and accelerate your career through self-directed learning."),
        ("Get Different", "Mike Michalowicz", "9780593330975", "Marketing techniques to differentiate your business and grab customer attention."),
        ("Profit First", "Mike Michalowicz", "9780735214149", "Transform your business from a cash-eating monster to a profitable machine using envelope accounting."),
        ("Clockwork", "Mike Michalowicz", "9780593538197", "Design your business to run itself so you can step back."),
        ("The Pumpkin Plan", "Mike Michalowicz", "9781591844884", "Strategies for growing a colossal business by focusing on your best clients."),
        ("Fix This Next", "Mike Michalowicz", "9780593084410", "Change your business by tackling problems in the correct hierarchical order."),
        ("All In", "Mike Michalowicz", "9780593538227", "How to build a culture of ownership and buy-in across teams."),
        ("Surrounded by Idiots", "Thomas Erikson", "9781250255174", "Understanding human behavior and communication styles through four color types (Red, Yellow, Green, Blue)."),
        ("Surrounded by Psychopaths", "Thomas Erikson", "9781250764126", "How to protect yourself from manipulation and toxic people in workplace and personal life."),
        ("Surrounded by Narcissists", "Thomas Erikson", "9781250849205", "Identifying self-absorbed behavior and reclaiming peace."),
        ("Surrounded by Bad Bosses", "Thomas Erikson", "9781250764157", "How to deal with difficult leadership and improve workplace dynamics."),
        ("Stolen Focus", "Johann Hari", "9780593138519", "Why you can't pay attention and how to think deeply again."),
        ("Lost Connections", "Johann Hari", "9781632868305", "Uncovering the real causes of depression and unexpected solutions beyond medication.")
    ],

    "Biography": [
        ("The Snowball: Warren Buffett and the Business of Life", "Alice Schroeder", "9780553384611", "The authorized biography of legendary investor Warren Buffett and Berkshire Hathaway."),
        ("Alexander the Great", "Philip Freeman", "9781416592815", "The military genius, conquests, and short life of the Macedonian king."),
        ("Julius Caesar", "Philip Freeman", "9780743289542", "The rise of Rome's famous general, dictator, and political reformer."),
        ("Hannibal", "Philip Freeman", "9781501168581", "The Carthaginian general who marched elephants across the Alps to challenge Rome."),
        ("Stalin: Paradoxes of Power", "Stephen Kotkin", "9780143127864", "The first volume tracing Joseph Stalin's early life, Bolshevik rise, and state consolidation."),
        ("Stalin: Waiting for Hitler", "Stephen Kotkin", "9780143132158", "The second volume covering collectivization, terror purges, and WWII mobilization."),
        ("First Man: The Life of Neil A. Armstrong", "James R. Hansen", "9780743256315", "The official biography of the first human to step foot on the Moon."),
        ("Hidden Figures", "Margot Lee Shetterly", "9780062363597", "The untold story of the Black female mathematicians who calculated NASA's space race trajectories."),
        ("Lab Girl", "Hope Jahren", "9781101873724", "A geobiologist's memoir of trees, science, soil, and lifelong friendship with her lab partner."),
        ("The Code Breaker", "Walter Isaacson", "9781982115852", "Jennifer Doudna, gene editing, and the future of the human species through CRISPR."),
        ("American Prometheus: J. Robert Oppenheimer", "Kai Bird & Martin J. Sherwin", "9780375726262", "The Pulitzer Prize-winning biography of the father of the atomic bomb."),
        ("The Outlier: The Unfinished Presidency of Jimmy Carter", "Kai Bird", "9780451495235", "Re-evaluating Jimmy Carter's presidency, foreign policy achievements, and moral leadership."),
        ("The Good Spy: The Life and Death of Robert Ames", "Kai Bird", "9780307888938", "The biography of a CIA operative who built unprecedented contacts in the Middle East."),
        ("Che Guevara: A Revolutionary Life", "Jon Lee Anderson", "9780802144119", "The definitive biography of the Argentine guerrilla leader and Cuban Revolutionary figure."),
        ("Frida: A Biography of Frida Kahlo", "Hayden Herrera", "9780060085896", "The life, art, pain, and passions of Mexico's legendary painter."),
        ("Churchill's Ministry of Ungentlemanly Warfare", "Giles Milton", "9781250119842", "The secret WWII guerrilla team that pioneered black ops and sabotage against Nazi forces."),
        ("Nathaniel's Nutmeg", "Giles Milton", "9780312262334", "How one spice island sparked Anglo-Dutch wars and led to trading Manhattan for Run island."),
        ("Samurai William", "Giles Milton", "9780374253851", "The Englishman who opened trade with 17th-century Japan and became a trusted advisor to the Shogun."),
        ("Russian Roulettes", "Giles Milton", "9781472111166", "British secret agents in revolutionary Russia attempting to overthrow Lenin."),
        ("Checkmate in Berlin", "Giles Milton", "9781250247605", "The cold war battle between Allied powers for control of Berlin post-WWII."),
        ("The Wright Brothers", "David McCullough", "9781476728759", "How Wilbur and Orville Wright engineered the first powered, controlled human flight."),
        ("1776", "David McCullough", "9780743226721", "George Washington and the Continental Army surviving the perilous first year of the Revolutionary War."),
        ("John Adams", "David McCullough", "9780684813639", "The Pulitzer-winning life story of America's second president and champion of independence."),
        ("Truman", "David McCullough", "9780671869205", "The epic biography of Harry S. Truman's rise from Missouri farm boy to US President."),
        ("Mornings on Horseback", "David McCullough", "9780671447540", "The young life of Theodore Roosevelt and the family that shaped him."),
        ("The Great Bridge", "David McCullough", "9780671457112", "The epic engineering feat of building the Brooklyn Bridge against corruption and disease."),
        ("The Path Between the Seas", "David McCullough", "9780671244095", "The creation of the Panama Canal, overcoming disease, engineering challenges, and geopolitical turmoil."),
        ("Brave Companions", "David McCullough", "9780671792763", "Portraits of extraordinary figures in history including Alexander von Humboldt and Louis Agassiz."),
        ("The Johnstown Flood", "David McCullough", "9780671207144", "The tragic 1889 dam failure in Pennsylvania that destroyed a steel town."),
        ("River of the Gods", "Candice Millard", "9780871404244", "Richard Burton and John Hanning Speke's treacherous expedition to locate the source of the Nile."),
        ("The River of Doubt", "Candice Millard", "9780739323045", "Theodore Roosevelt's perilous 1913 exploration down an uncharted Amazon tributary."),
        ("Destiny of the Republic", "Candice Millard", "9780385526265", "The shooting of President James A. Garfield and Alexander Graham Bell's attempt to save him."),
        ("Hero of the Empire", "Candice Millard", "9780307948786", "Young Winston Churchill's daring escape from a Boer prisoner of war camp.")
    ],

    "History": [
        ("The Silk Roads: A New History of the World", "Peter Frankopan", "9781101912379", "A re-assessment of global history centered on the trade routes connecting East and West."),
        ("The New Silk Roads", "Peter Frankopan", "9780525566694", "The present and future of international trade, power shifts, and Central Asian geopolitics."),
        ("The Earth Transformed", "Peter Frankopan", "9780525659167", "How climate shifts and environmental forces shaped human civilizations across millennia."),
        ("Empires of the Sea", "Roger Crowley", "9780812977646", "The 16th-century siege of Malta and battle of Lepanto for Mediterranean dominance."),
        ("1453: The Holy War for Constantinople", "Roger Crowley", "9781400063192", "Mehmed II's Ottoman siege and conquest of Byzantine Constantinople."),
        ("City of Fortune: How Venice Ruled the Seas", "Roger Crowley", "9780812980226", "The five-hundred-year maritime empire of Venice across the Levant and Black Sea."),
        ("Conquerors: How Portugal Forged the First Global Empire", "Roger Crowley", "9780812994001", "Portuguese navigators Vasco da Gama and Afonso de Albuquerque opening Indian Ocean trade."),
        ("The Guns of August", "Barbara W. Tuchman", "9780345386236", "The military decisions, miscalculations, and outbreak of World War I in August 1914."),
        ("The Proud Tower", "Barbara W. Tuchman", "9780345405012", "A portrait of European and American society in the decades leading up to 1914."),
        ("A Distant Mirror: The Calamitous 14th Century", "Barbara W. Tuchman", "9780345349576", "Life, plague, schism, and war in 14th-century Europe through the noble Coucy family."),
        ("The March of Folly", "Barbara W. Tuchman", "9780345308238", "How governments pursue policies contrary to their own self-interest, from Troy to Vietnam."),
        ("Stalingrad: The Fateful Siege", "Antony Beevor", "9780140284584", "The brutal 1942–1943 WWII battle that turned the tide against Nazi Germany."),
        ("Berlin: The Downfall 1945", "Antony Beevor", "9780140286960", "The Soviet assault on Berlin and the collapse of the Third Reich."),
        ("D-Day: The Battle for Normandy", "Antony Beevor", "9780143118183", "The Allied invasion of France on June 6, 1944, and the grueling hedgerow fighting."),
        ("The Second World War", "Antony Beevor", "9780316023740", "A comprehensive single-volume global history of WWII across all theaters."),
        ("Ardennes 1944: The Battle of the Bulge", "Antony Beevor", "9780143109860", "Hitler's final desperate winter offensive in the snowy Ardennes forest."),
        ("The Crusades: The Authoritative History", "Thomas Asbridge", "9780060787295", "A balanced account of medieval holy wars between Christians and Muslims in the Levant."),
        ("The Greatest Knight", "Thomas Asbridge", "9780062262066", "The life of William Marshal, who served four English kings and saved the realm."),
        ("The Plantagenets", "Dan Jones", "9780143124924", "The dynasty that ruled England from Henry II through Richard II."),
        ("The Hollow Crown", "Dan Jones", "9780143127888", "The Wars of the Roses and the rise of the Tudor dynasty."),
        ("The Templars: The Rise and Spectacular Fall", "Dan Jones", "9780525428305", "The military order of crusader knights who built a medieval financial empire."),
        ("Powers and Thrones: A New History of the Middle Ages", "Dan Jones", "9781984880871", "A thousand years of European medieval history from Rome's fall to the Renaissance."),
        ("Essex Dogs", "Dan Jones", "9780593493724", "A gritty historical novel following an English company of soldiers during the Hundred Years' War."),
        ("The Map That Changed the World", "Simon Winchester", "9780060931803", "William Smith's quest to create the first geological map of England."),
        ("The Professor and the Madman", "Simon Winchester", "9780060839789", "How a convicted murderer in a lunatic asylum contributed thousands of entries to the Oxford English Dictionary."),
        ("Krakatoa: The Day the World Exploded", "Simon Winchester", "9780060838591", "The colossal 1883 volcanic eruption in Indonesia that triggered global climate effects."),
        ("Pacific: Silicon Chips, Man-Made Islands, and Coral Reef", "Simon Winchester", "9780062315410", "Ten crucial events shaping the modern history of the Pacific Ocean."),
        ("The Perfectionists: How Precision Engineers Created Modern World", "Simon Winchester", "9780062652553", "Tracing precision engineering from early steam pistons to microchips."),
        ("Land: How the Hunger for Ownership Shaped Modern World", "Simon Winchester", "9780062938336", "How boundary lines and land titles influenced human history and displacement."),
        ("Knowing What We Know", "Simon Winchester", "9780063142886", "The transmission of human knowledge from oral traditions to Wikipedia."),
        ("The Swimmer", "John Colapinto", "9780062835789", "A biography detailing endurance, water sports, and historical feats."),
        ("The Wager: A Tale of Shipwreck, Mutiny and Murder", "David Grann", "9780593419083", "The HMS Wager shipwreck off Patagonia in 1742 leading to mutiny and conflicting court-martial testimonies."),
        ("Killers of the Flower Moon", "David Grann", "9780307742483", "The Osage Indian murders in 1920s Oklahoma and the birth of the FBI.")
    ],

    "Philosophy": [
        ("Justice: What's the Right Thing to Do?", "Michael J. Sandel", "9780374532505", "Exploring moral dilemmas through utilitarianism, libertarianism, Kant, and Aristotle."),
        ("What Money Can't Buy: Moral Limits of Markets", "Michael J. Sandel", "9780374533656", "How market values have corrupted medicine, education, and civic life."),
        ("The Tyranny of Merit", "Michael J. Sandel", "9780374289980", "Rethinking the American dream, meritocracy, and social resentment."),
        ("The Pig That Wants to Be Eaten", "Julian Baggini", "9780452287440", "100 thought experiments to stretch your mind on ethics, consciousness, and identity."),
        ("How the World Thinks", "Julian Baggini", "9780062887245", "A global history of philosophy comparing Western, Chinese, Indian, Islamic, and African traditions."),
        ("The Edge of Reason", "Julian Baggini", "9780300208368", "Defending rationality and human reason against fundamentalism and relativism."),
        ("The Great Guide: What David Hume Can Teach Us", "Julian Baggini", "9780691205236", "Applying Humean empiricism and skepticism to daily living."),
        ("A Philosophy of Walking", "Frédéric Gros", "9781781682708", "How walking inspired Nietzsche, Rousseau, Kant, and Thoreau to think clearly."),
        ("Think: A Compelling Introduction to Philosophy", "Simon Blackburn", "9780192100245", "Explaining truth, mind, free will, knowledge, and ethics."),
        ("Being Good: A Short Introduction to Ethics", "Simon Blackburn", "9780192100528", "Addressing moral skepticism, religion, rights, and human nature."),
        ("Lust", "Simon Blackburn", "9780195168440", "A witty philosophical defense of desire against puritanism."),
        ("Truth: A Guide", "Simon Blackburn", "9780195168242", "Exploring absolutism vs relativism in modern debate."),
        ("Mirror, Mirror: Uses and Abuses of Self-Love", "Simon Blackburn", "9780691161907", "Differentiating healthy self-esteem from toxic narcissism."),
        ("On Bullshit", "Harry G. Frankfurt", "9780691122946", "A precise philosophical essay analyzing bullshit as indifferent to truth."),
        ("On Truth", "Harry G. Frankfurt", "9780691133058", "A companion essay explaining why truth matters for human culture."),
        ("On Inequality", "Harry G. Frankfurt", "9780691167145", "Arguing that poverty, not economic inequality itself, is the real moral challenge."),
        ("The Philosophy of Physical Science", "Arthur Eddington", "9780521092875", "Epistemological foundation of modern physics and quantum mechanics."),
        ("The Structure of Scientific Revolutions", "Thomas S. Kuhn", "9780226458120", "How scientific paradigms shift through crises rather than linear accumulation."),
        ("Against Method", "Paul Feyerabend", "9781844674428", "Anarchistic theory of knowledge arguing there is no single scientific method."),
        ("The Logic of Scientific Discovery", "Karl Popper", "9780415278447", "Falsifiability as the defining criterion distinguishing science from pseudo-science."),
        ("The Open Society and Its Enemies", "Karl Popper", "9780691158136", "Critique of totalitarian philosophy in Plato, Hegel, and Marx."),
        ("Conjectures and Refutations", "Karl Popper", "9780415285940", "Essays on the growth of scientific knowledge through trial and error."),
        ("Philosophy and the Mirror of Nature", "Richard Rorty", "9780691141367", "Critiquing foundational epistemology and advocating pragmatic conversation."),
        ("Contingency, Irony, and Solidarity", "Richard Rorty", "9780521367813", "Ironism, language games, and liberal solidarity in post-foundational ethics."),
        ("Achieving Our Country", "Richard Rorty", "9780674003118", "Leftist thought in 20th-century America and civic patriotism."),
        ("Philosophical Investigations", "Ludwig Wittgenstein", "9781405159289", "Language games, family resemblance, and meaning as use."),
        ("Tractatus Logico-Philosophicus", "Ludwig Wittgenstein", "9780415254083", "Seven propositions on logic, picture theory of language, and silence."),
        ("On Certainty", "Ludwig Wittgenstein", "9780631125518", "Notes on Moorean propositions, doubt, and bedrock human action."),
        ("Culture and Value", "Ludwig Wittgenstein", "9780631205715", "Personal aphorisms on art, music, religion, and culture."),
        ("Zettel", "Ludwig Wittgenstein", "9780631128113", "Fragmentary notes on psychology, sensation, and rule-following."),
        ("The View From Nowhere", "Thomas Nagel", "9780195056440", "Balancing subjective personal views with objective reality."),
        ("Mortal Questions", "Thomas Nagel", "9780521406765", "Essays on death, moral luck, absurdities, and animal consciousness."),
        ("What Does It All Mean?", "Thomas Nagel", "9780195052169", "A short, accessible introduction to nine classic philosophical problems.")
    ],

    "Young Adult": [
        ("Legend", "Marie Lu", "9780142422076", "15-year-olds June, a military prodigy, and Day, a notorious street criminal, collide in dystopian Los Angeles."),
        ("Prodigy", "Marie Lu", "9780142425657", "June and Day flee to Vegas to join the Patriots and assassinate the new Elector."),
        ("Champion", "Marie Lu", "9780147512284", "A deadly plague strikes the Republic as war with the Colonies looms."),
        ("Rebel", "Marie Lu", "9781250221704", "Ten years later in Ross City, Eden and Day face underground rebel factions."),
        ("Warcross", "Marie Lu", "9780399547966", "Hacker Emika Chen accidentally glitches herself into the global Warcross Championship game."),
        ("Wildcard", "Marie Lu", "9780399547997", "Emika discovers Hideo's sinister mind-control technology inside the Warcross algorithm."),
        ("Skyhunter", "Marie Lu", "9781250221681", "Strikers defend their last free nation against mutated war beasts."),
        ("Steelstriker", "Marie Lu", "9781250221711", "Talin fights from inside the enemy fortress to free her homelands."),
        ("The Cruel Prince", "Holly Black", "9780316310277", "Human girl Jude Duarte navigates deadly fae politics at the High Court of Elfhame."),
        ("The Wicked King", "Holly Black", "9780316310352", "Jude controls King Cardan behind the scenes while protecting Elfhame from undersea invasion."),
        ("The Queen of Nothing", "Holly Black", "9780316310420", "Exiled mortal queen Jude returns to Faerie to rescue her twin and claim the crown."),
        ("How the King of Elfhame Learned to Hate Stories", "Holly Black", "9780316540889", "Illustrated backstory of Cardan's childhood and life before The Cruel Prince."),
        ("The Stolen Heir", "Holly Black", "9780316592703", "Runaway queen Suren joins Prince Oak on a dangerous quest to the icy North."),
        ("The Prisoner's Throne", "Holly Black", "9780316592734", "Prince Oak stands trial in the High Court while trying to prevent war."),
        ("Tithe", "Holly Black", "9780689849213", "Sixteen-year-old Kaye discovers she is a faerie pixie caught between Court tithes."),
        ("Valiant", "Holly Black", "9780689868238", "Val runs away to NYC subways and meets homeless teenagers serving a faerie troll."),
        ("Ironside", "Holly Black", "9780689868245", "Kaye must complete impossible quests for the Queen of the Unseelie Court."),
        ("White Cat", "Holly Black", "9781416963929", "Cassel Comes comes from a family of magic curse workers who alter memories and luck."),
        ("Red Glove", "Holly Black", "9781416963943", "Cassel is recruited by the federal government to investigate mob curse workers."),
        ("Black Heart", "Holly Black", "9781416963967", "Cassel plays a dangerous double game between federal agents and mob bosses."),
        ("The Darkest Minds", "Alexandra Bracken", "9781484709603", "Ruby Daly escapes a government camp for kids who developed supernatural telepathic powers."),
        ("Never Fade", "Alexandra Bracken", "9781484709610", "Ruby leads dangerous missions for the Children's League while hunting an encrypted drive."),
        ("In the Afterlight", "Alexandra Bracken", "9781484709627", "Ruby and survivors march on Washington D.C. to free camp prisoners."),
        ("The Farther Shore", "Alexandra Bracken", "9781368023245", "Novellas detailing life after the camps across America."),
        ("Lore", "Alexandra Bracken", "9781484778203", "Greek gods fight as mortals in New York City every seven years during the Agon."),
        ("Silver in the Bone", "Alexandra Bracken", "9780593481653", "A hollower girl searches for King Arthur's ring in an un-blessed realm."),
        ("Cinder", "Marissa Meyer", "9780312641894", "A teenage cyborg mechanic in New Beijing encounters Prince Kai and a deadly plague."),
        ("Scarlet", "Marissa Meyer", "9780312641924", "Scarlet teams up with street fighter Wolf to rescue her grandmother in France."),
        ("Cress", "Marissa Meyer", "9780312641931", "A satellite hacker trapped in space helps Cinder and Scarlet plan an invasion."),
        ("Winter", "Marissa Meyer", "9780312641948", "Princess Winter defies her stepmother Queen Levana to aid the lunar rebellion."),
        ("Fairest", "Marissa Meyer", "9781250060556", "The backstory of Queen Levana's rise to power on Luna."),
        ("Stars Above", "Marissa Meyer", "9781250091840", "Nine short stories set in the Lunar Chronicles universe including wedding epilogue."),
        ("Heartless", "Marissa Meyer", "9781250044631", "The origin story of how a young woman who loved baking became the Queen of Hearts.")
    ],

    "Poetry": [
        ("The Essential Rumi", "Rumi", "9780062509598", "Ecstatic mystical love poetry by 13th-century Sufi master Rumi."),
        ("The Masnavi: Book One", "Rumi", "9780199552313", "The spiritual masterpiece of Persian literature containing moral parables and verse."),
        ("Love Poems from God", "Daniel Ladinsky", "9780140424492", "Sacred poems from Sufi, Christian, and Hindu mystics including Hafiz, Kabir, and Rumi."),
        ("The Gift", "Hafiz", "9780140195811", "Poems by 14th-century Persian poet Hafiz celebrating divine joy and love."),
        ("The Prophet", "Kahlil Gibran", "9780394404288", "26 poetic essays on love, marriage, work, freedom, and death by Almustafa."),
        ("Broken Wings", "Kahlil Gibran", "9780806511016", "A poetic novel of tragic young love set in early 20th-century Beirut."),
        ("The Madman", "Kahlil Gibran", "9780486822501", "Parables and poems exploring societal masks and freedom."),
        ("Sand and Foam", "Kahlil Gibran", "9780394404301", "A collection of spiritual maxims, aphorisms, and short prose poems."),
        ("Spur of the Moment", "Kahlil Gibran", "9780806511054", "Reflections on art, spirituality, and soul beauty."),
        ("The Complete Poems of Emily Dickinson", "Emily Dickinson", "9780316184137", "Nearly 1,800 poems exploring death, nature, immortality, and quiet emotion."),
        ("Leaves of Grass", "Walt Whitman", "9780140421996", "Landmark American poetry celebrating democracy, nature, body, and human connection."),
        ("Song of Myself", "Walt Whitman", "9780486282107", "The epic centerpiece poem of Leaves of Grass."),
        ("Selected Poems of Langston Hughes", "Langston Hughes", "9780679728184", "Harlem Renaissance poetry capturing Black life, jazz rhythms, and racial justice."),
        ("The Weary Blues", "Langston Hughes", "9780593319086", "Hughes' debut 1926 poetry collection inspired by blues music."),
        ("Montage of a Dream Deferred", "Langston Hughes", "9780805047806", "Jazz-structured verse capturing 1950s Harlem street life."),
        ("Collected Poems of W.B. Yeats", "W.B. Yeats", "9780684807317", "Irish folklore, political rebellion, mysticism, and aging across five decades of poetry."),
        ("The Waste Land and Other Poems", "T.S. Eliot", "9780156948777", "Modernist masterpiece reflecting post-WWI spiritual disillusionment."),
        ("Four Quartets", "T.S. Eliot", "9780156332095", "Philosophical poems exploring time, memory, consciousness, and transcendence."),
        ("Old Possum's Book of Practical Cats", "T.S. Eliot", "9780156687805", "Whimsical verse about feline psychology and antics that inspired the musical Cats."),
        ("Twenty Love Poems and a Song of Despair", "Pablo Neruda", "9780140186482", "Passionate, sensual Chilean poetry celebrating romantic love and nature."),
        ("100 Love Sonnets", "Pablo Neruda", "9780292705647", "Sonnets written for Matilde Urrutia divided into Morning, Afternoon, Evening, and Night."),
        ("Canto General", "Pablo Neruda", "9780520054332", "An epic history and geography of the American continent in verse."),
        ("Ariel", "Sylvia Plath", "9780060931728", "Intense, searing final collection of poems written before Plath's death."),
        ("The Colossus and Other Poems", "Sylvia Plath", "9780375704468", "Plath's first published collection exploring domesticity, nature, and identity."),
        ("Devotions: Selected Poems of Mary Oliver", "Mary Oliver", "9780399563249", "Over 200 nature poems celebrating birds, woods, rivers, and quiet awe."),
        ("A Thousand Mornings", "Mary Oliver", "9780143124054", "Morning walks along Cape Cod shores encouraging gratitude."),
        ("Dog Songs", "Mary Oliver", "9780143125754", "Charming poems celebrating dogs and the deep bonds between humans and pets."),
        ("Felicity", "Mary Oliver", "9780143129592", "Poems exploring human love, contentment, and living lightly."),
        ("Blue Horses", "Mary Oliver", "9780143127819", "Reflections on art, stillness, and nature's quiet wisdom."),
        ("Upstream: Selected Essays", "Mary Oliver", "9780143130086", "Prose reflections on literature, solitary walks, and creative life."),
        ("The Wild Iris", "Louise Glück", "9780880013345", "Pulitzer Prize-winning collection spoken through flowers, a gardener, and God."),
        ("Averno", "Louise Glück", "9780374107420", "Modern retelling of the Persephone myth examining death and mother-daughter bonds."),
        ("Faithful and Virtuous Night", "Louise Glück", "9780374152017", "Elegiac poems on mortality, aging, painterly visions, and memory.")
    ],

    "Classic Literature": [
        ("The Odyssey", "Homer", "9780393356250", "Odysseus' ten-year struggle to return home to Ithaca after the Trojan War."),
        ("The Iliad", "Homer", "9780140275360", "The rage of Achilles during the final weeks of the Siege of Troy."),
        ("The Aeneid", "Virgil", "9780143105138", "Aeneas flees burning Troy to settle in Italy and lay the foundations of Rome."),
        ("The Divine Comedy: Inferno", "Dante Alighieri", "9780142437223", "Dante's journey through nine concentric circles of Hell guided by Virgil."),
        ("The Divine Comedy: Purgatorio", "Dante Alighieri", "9780140444421", "Dante ascends the seven terraces of Mount Purgatory."),
        ("The Divine Comedy: Paradiso", "Dante Alighieri", "9780140444438", "Beatrice guides Dante through the celestial spheres of Heaven."),
        ("Don Quixote", "Miguel de Cervantes", "9780060934347", "An aging Spanish hidalgo becomes obsessed with chivalric romances and sets out with Sancho Panza."),
        ("Canterbury Tales", "Geoffrey Chaucer", "9780140424386", "24 stories told by a diverse group of pilgrims traveling from London to Canterbury Cathedral."),
        ("The Decameron", "Giovanni Boccaccio", "9780140449433", "100 tales told over ten days by ten young people sheltering from the Black Death outside Florence."),
        ("Gargantua and Pantagruel", "François Rabelais", "9780140445503", "Satirical, bawdy adventures of two giants mocking medieval scholasticism."),
        ("Essays", "Michel de Montaigne", "9780140446029", "Inventing the modern essay format with introspective writings on friendship, cannibalism, and experience."),
        ("Paradise Lost", "John Milton", "9780140424393", "The epic poem recounting Satan's rebellion and the fall of Adam and Eve in Eden."),
        ("The Tale of Genji", "Murasaki Shikibu", "9780142437148", "11th-century Japanese courtly saga of Prince Genji's romances, politics, and aesthetic refinement."),
        ("Journey to the West", "Wu Cheng'en", "9780140447194", "Monkey King Sun Wukong escorts monk Xuanzang to India to retrieve Buddhist sutras."),
        ("Romance of the Three Kingdoms", "Luo Guanzhong", "9780804834445", "Epic historical novel detailing feudal wars between Liu Bei, Cao Cao, and Sun Quan in ancient China."),
        ("Water Margin", "Shi Nai'an", "9780804834421", "108 outlaw heroes gather at Mount Liang to fight corrupt Song dynasty officials."),
        ("Dream of the Red Chamber", "Cao Xueqin", "9780140443264", "The decline of the aristocratic Jia family centered on Baoyu and Daiyu in Qing dynasty China."),
        ("Faust: Part One", "Johann Wolfgang von Goethe", "9780140449013", "Scholar Faust trades his soul to Mephistopheles in exchange for ultimate knowledge and earthly pleasure."),
        ("Faust: Part Two", "Johann Wolfgang von Goethe", "9780140440935", "Faust explores politics, classical antiquity, Helena of Troy, and ultimate redemption."),
        ("The Sorrows of Young Werther", "Johann Wolfgang von Goethe", "9780140445039", "Epistolary novel of passionate, unrequited love that launched the Sturm und Drang movement."),
        ("Elective Affinities", "Johann Wolfgang von Goethe", "9780140442427", "A married couple's estate is disrupted when two guests arrive, drawing chemical metaphors for attraction."),
        ("Wilhelm Meister's Apprenticeship", "Johann Wolfgang von Goethe", "9780691012933", "The foundational German Bildungsroman following a young man's self-development through theater."),
        ("Dead Souls", "Nikolai Gogol", "9780140448078", "Chichikov travels rural Russia buying up 'dead souls' (deceased serfs) to use as loan collateral."),
        ("The Overcoat and Other Tales", "Nikolai Gogol", "9780486270579", "St. Petersburg stories combining absurd bureaucracy, surrealism, and tragic comedy."),
        ("Fathers and Sons", "Ivan Turgenev", "9780140441475", "Nihilist student Bazarov clashes with traditional Russian gentry values in 1860s Russia."),
        ("A Sportsman's Sketches", "Ivan Turgenev", "9780140440089", "Short stories depicting serf life and Russian countryside that influenced emancipation."),
        ("Oblomov", "Ivan Goncharov", "9780140449198", "A young Russian nobleman is so indecisive and slothful he rarely leaves his bed."),
        ("First Love", "Ivan Turgenev", "9780140444582", "A 16-year-old boy falls in love with an older princess only to discover his father is her lover."),
        ("The Red and the Black", "Stendhal", "9780140447644", "Ambitious provincial Julien Sorel uses romantic intrigue and hypocrisy to climb French society."),
        ("The Charterhouse of Parma", "Stendhal", "9780140449259", "Fabrice del Dongo fights at Waterloo and navigates political intrigue at an Italian court."),
        ("Dangerous Liaisons", "Pierre Choderlos de Laclos", "9780140449570", "Rival ex-lovers Marquise de Merteuil and Vicomte de Valmont execute manipulative romantic wagers in pre-Revolution France."),
        ("Candide", "Voltaire", "9780140440140", "Satirical novel mocking Panglossian optimism as young Candide experiences war, earthquakes, and tragedy."),
        ("Zadig and Other Stories", "Voltaire", "9780140442298", "Philosophical tales exploring fate, justice, and human reason in ancient Babylon.")
    ],

    "Non-Fiction": [
        ("Thinking in Systems", "Donella H. Meadows", "9781603580557", "An essential primer on feedback loops, leverage points, and systemic thinking."),
        ("The Design of Everyday Things", "Don Norman", "9780465050659", "Cognitive psychology applied to product design, affordances, and user experience."),
        ("Emotional Design", "Don Norman", "9780465051359", "Why we love or hate everyday objects based on visceral, behavioral, and reflective design."),
        ("Living with Complexity", "Don Norman", "9780262528948", "Why complexity is necessary in life and how good design makes it manageable."),
        ("The Signal and the Noise", "Nate Silver", "9780143125082", "Why so many predictions fail—but some don't—in politics, weather, sports, and economics."),
        ("Algorithms to Live By", "Brian Christian & Tom Griffiths", "9781627790369", "How computer algorithms (optimal stopping, sorting, caching) can solve human decision-making problems."),
        ("The Most Human Human", "Brian Christian", "9780307476708", "What artificial intelligence teaches us about human conversation, empathy, and cognition."),
        ("The Alignment Problem", "Brian Christian", "9780393868333", "How AI machine learning systems learn human biases and how researchers strive to align AI with values."),
        ("Gödel, Escher, Bach: An Eternal Golden Braid", "Douglas R. Hofstadter", "9780465026562", "Pulitzer Prize-winning exploration of self-reference, strange loops, and consciousness across math, art, and music."),
        ("I Am a Strange Loop", "Douglas R. Hofstadter", "9780465030798", "Developing the concept of self-referential strange loops as the essence of human identity."),
        ("Fluid Concepts and Creative Analogies", "Douglas R. Hofstadter", "9780465024759", "Computer models of fundamental mechanisms of human thought and creative analogy."),
        ("Metamagical Themas", "Douglas R. Hofstadter", "9780465045662", "A collection of Scientific American columns on mind, pattern, music, and logic."),
        ("The Mind's I", "Douglas R. Hofstadter & Daniel C. Dennett", "9780465030910", "Fantasies and reflections on self, soul, and consciousness."),
        ("Consciousness Explained", "Daniel C. Dennett", "9780316180665", "The Multiple Drafts model of consciousness dismantling the Cartesian Theater illusion."),
        ("Intuition Pumps and Other Tools for Thinking", "Daniel C. Dennett", "9780393348780", "77 philosophical thought experiments and thinking tools for analyzing mind and evolution."),
        ("Darwin's Dangerous Idea", "Daniel C. Dennett", "9780684824710", "Evolution by natural selection as a universal solvent shaping life, mind, and culture."),
        ("Breaking the Spell: Religion as a Natural Phenomenon", "Daniel C. Dennett", "9780143038337", "Examining religion through evolutionary biology and social anthropology."),
        ("From Bacteria to Bach and Back", "Daniel C. Dennett", "9780393355505", "Tracing how un-comprehending competence evolved into conscious human comprehension."),
        ("The Blind Watchmaker", "Richard Dawkins", "9780393315707", "Why the evidence of evolution reveals a universe without supernatural design."),
        ("The Selfish Gene", "Richard Dawkins", "9780199291151", "The gene-centric view of evolution and coining the word 'meme'."),
        ("The Ancestor's Tale", "Richard Dawkins", "9780618619160", "A pilgrimage backward through evolutionary time meeting common ancestors of life."),
        ("The Magic of Reality", "Richard Dawkins", "9781451675047", "Explaining natural phenomena through science vs myths."),
        ("The Greatest Show on Earth", "Richard Dawkins", "9781416594796", "The physical, fossil, and genetic evidence for evolution."),
        ("Unweaving the Rainbow", "Richard Dawkins", "9780618056736", "How science enhances our sense of wonder rather than destroying poetry."),
        ("The Extended Phenotype", "Richard Dawkins", "9780192860880", "How genes exert effects far beyond the organism's physical body into the environment."),
        ("Cosmos", "Carl Sagan", "9780345331350", "The classic exploration of fifteen billion years of cosmic evolution and human discovery."),
        ("The Demon-Haunted World", "Carl Sagan", "9780345409461", "Science as a candle in the dark, equipping readers with a baloney detection kit against pseudoscience."),
        ("Pale Blue Dot", "Carl Sagan", "9780345392114", "A vision of the human future in space inspired by Voyager 1's photo of Earth."),
        ("Contact", "Carl Sagan", "9780671004101", "Radio astronomer Ellie Arroway detects humanity's first extraterrestrial signal from Vega."),
        ("Broca's Brain", "Carl Sagan", "9780345459855", "Reflections on science history, borderlands of knowledge, and human intelligence."),
        ("The Dragons of Eden", "Carl Sagan", "9780345346292", "Pulitzer-winning exploration of the evolution of human intelligence and brain biology."),
        ("Shadows of Forgotten Ancestors", "Carl Sagan & Ann Druyan", "9780345384720", "Exploring origins of human nature, aggression, and altruism through primate evolution."),
        ("Billions & Billions", "Carl Sagan", "9780345379184", "Sagan's final thoughts on science, global warming, abortion, and mortality.")
    ]
}

def escape_sql_str(val):
    return val.replace("'", "''")

def main():
    target_path = r"c:\pdd1\database\seed_books_batch_4.sql"
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    statements = []
    statements.append("-- PageMind Database Seed Script: Batch 4 of 10 (500 Books across 15 Genres)\n")
    statements.append("-- Uses INSERT IGNORE INTO books to safely skip any duplicate (title, author) entries\n\n")
    statements.append("USE pagemind;\n\n")

    count = 0
    for genre, books in GENRE_DATA_BATCH_4.items():
        statements.append(f"-- =======================================================\n")
        statements.append(f"-- Genre: {genre} ({len(books)} books)\n")
        statements.append(f"-- =======================================================\n")
        
        for title, author, isbn, desc in books:
            count += 1
            e_title = escape_sql_str(title)
            e_author = escape_sql_str(author)
            e_genre = escape_sql_str(genre)
            e_desc = escape_sql_str(desc)
            
            if isbn:
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
            else:
                cover_url = f"https://via.placeholder.com/300x450/1e1b4b/a5b4fc?text={urllib.parse.quote(title)}"
            e_cover_url = escape_sql_str(cover_url)
            
            amazon_url = f"https://www.amazon.in/s?k={urllib.parse.quote(f'{title} {author}')}"
            flipkart_url = f"https://www.flipkart.com/search?q={urllib.parse.quote(f'{title} {author}')}"
            
            buy_links_dict = {
                "amazon": amazon_url,
                "flipkart": flipkart_url
            }
            buy_links_json = json.dumps(buy_links_dict)
            e_buy_links_json = escape_sql_str(buy_links_json)
            
            pub_year = get_published_year(title, author, genre, desc, isbn)

            
            rating = get_rating(title, author)

            
            sql = f"INSERT IGNORE INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{e_title}', '{e_author}', '{e_genre}', '{e_desc}', '{e_cover_url}', '{e_buy_links_json}', {pub_year}, {rating});\n"
            statements.append(sql)
            
        statements.append("\n")

    with open(target_path, "w", encoding="utf-8") as f:
        f.writelines(statements)

    print(f"Successfully generated {target_path} with {count} book insert statements across {len(GENRE_DATA_BATCH_4)} genres!")

if __name__ == "__main__":
    main()
