from book_metadata_utils import get_rating, get_published_year
import json
import urllib.parse
import os

# 15 Genres with 35 authentic/well-known books per genre (525 books total)
GENRE_DATA = {
    "Fiction": [
        ("To Kill a Mockingbird", "Harper Lee", "9780061120084", "A compelling story of racial injustice and the destruction of innocence in the American South."),
        ("The Great Gatsby", "F. Scott Fitzgerald", "9780743273565", "A tragic tale of ambition, love, and the American Dream in the Roaring Twenties."),
        ("1984", "George Orwell", "9780451524935", "A dystopian vision of a totalitarian regime where Big Brother is always watching."),
        ("Pride and Prejudice", "Jane Austen", "9780141439518", "A classic romance exploring manners, upbringing, and marriage in 19th century England."),
        ("The Catcher in the Rye", "J.D. Salinger", "9780316769488", "A story of teenage rebellion, alienation, and identity in post-WWII America."),
        ("One Hundred Years of Solitude", "Gabriel García Márquez", "9780060883287", "The multi-generational story of the Buendía family in the fictional town of Macondo."),
        ("Brave New World", "Aldous Huxley", "9780060850524", "A futuristic society engineered for peace and stability at the cost of human freedom."),
        ("The Alchemist", "Paulo Coelho", "9780062315007", "An inspiring fable about an Andalusian shepherd boy following his dreams."),
        ("The Kite Runner", "Khaled Hosseini", "9781594631931", "A powerful story of friendship, redemption, and the devastating impacts of war in Afghanistan."),
        ("Life of Pi", "Yann Martel", "9780156027328", "An adventurous journey of survival at sea accompanied by a Bengal tiger."),
        ("Beloved", "Toni Morrison", "9781400033416", "A haunting narrative of the trauma of slavery and maternal love."),
        ("The Book Thief", "Markus Zusak", "9780375842207", "Narrated by Death, a young girl steals books to survive Nazi Germany."),
        ("Fahrenheit 451", "Ray Bradbury", "9781451673319", "A terrifying future where books are outlawed and firemen burn any that are found."),
        ("The Road", "Cormac McCarthy", "9780307387899", "A father and son walk through a burned, post-apocalyptic America."),
        ("Slaughterhouse-Five", "Kurt Vonnegut", "9780385333849", "A satirical anti-war novel focused on the Dresden firebombing."),
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "An orphaned governess fights for independence and love against social barriers."),
        ("Wuthering Heights", "Emily Brontë", "9780141439556", "A passionate and dark tale of intense love and revenge on the Yorkshire moors."),
        ("Lord of the Flies", "William Golding", "9780399501487", "A group of schoolboys stranded on a deserted island devolve into savagery."),
        ("Animal Farm", "George Orwell", "9780451526342", "An allegorical novella reflecting the events leading up to the Russian Revolution."),
        ("The Grapes of Wrath", "John Steinbeck", "9780143039433", "An epic dust-bowl narrative of the Joad family migrating westward during the Great Depression."),
        ("Of Mice and Men", "John Steinbeck", "9780140177398", "Two displaced migrant workers chase their dream of owning land during the Depression."),
        ("Catch-22", "Joseph Heller", "9781451626650", "A satirical masterpiece highlighting the absurdity of military bureaucracy in WWII."),
        ("The Color Purple", "Alice Walker", "9780156028356", "A poignant epistolary novel tracing the life of an African American woman in the rural South."),
        ("The God of Small Things", "Arundhati Roy", "9780812979657", "A story of fraternal twins whose lives are shattered by love laws in Kerala, India."),
        ("Midnight's Children", "Salman Rushdie", "9780812976533", "Children born at the exact moment of India's independence possess telepathic powers."),
        ("A Thousand Splendid Suns", "Khaled Hosseini", "9781594489501", "A heart-wrenching tale of two Afghan women united by shared hardship."),
        ("Where the Crawdads Sing", "Delia Owens", "9780735219090", "A young woman raised in the North Carolina marshes becomes a murder suspect."),
        ("Normal People", "Sally Rooney", "9781984822178", "An intimate exploration of subtle romance and complex social dynamics between two youths."),
        ("The Midnight Library", "Matt Haig", "9780525559474", "Nora Seed finds a magical library where every book offers a chance to try another life."),
        ("A Man Called Ove", "Fredrik Backman", "9781476786452", "A heartwarming story about a grumpy widower transformed by new neighbors."),
        ("The Shadow of the Wind", "Carlos Ruiz Zafón", "9780143034902", "A young boy discovers a forgotten book in Barcelona that changes his destiny."),
        ("All the Light We Cannot See", "Anthony Doerr", "9781476746586", "A blind French girl and a German boy cross paths in occupied France during WWII."),
        ("Little Fires Everywhere", "Celeste Ng", "9780735224292", "Intertwined fates of the picture-perfect Richardson family and an enigmatic mother-daughter duo."),
        ("Room", "Emma Donoghue", "9780316098335", "A five-year-old boy and his mother escape from years of captivity in a single room."),
        ("The Sympathizer", "Viet Thanh Nguyen", "9780802124944", "A communist double agent navigates life in Los Angeles after the fall of Saigon.")
    ],

    "Mystery": [
        ("The Girl with the Dragon Tattoo", "Stieg Larsson", "9780307949486", "A journalist and a computer hacker investigate a decades-old disappearance."),
        ("And Then There Were None", "Agatha Christie", "9780062073488", "Ten strangers are lured to an isolated island and killed off one by one."),
        ("Gone Girl", "Gillian Flynn", "9780307588371", "A husband becomes the chief suspect when his wife mysteriously vanishes on their anniversary."),
        ("The Da Vinci Code", "Dan Brown", "9780307474278", "A symbologist investigates a murder in the Louvre that unlocks ancient secret societies."),
        ("In the Woods", "Tana French", "9780143113492", "A detective investigates a child's murder in the same woods where his childhood friends disappeared."),
        ("Big Little Lies", "Liane Moriarty", "9780425274866", "A murder at a school trivia night unravels secrets among suburban mothers."),
        ("The Woman in the Window", "A.J. Finn", "9780062678416", "An agoraphobic woman believes she witnessed a crime in her neighbor's house."),
        ("The Silence of the Lambs", "Thomas Harris", "9780312924584", "FBI trainee Clarice Starling seeks the counsel of imprisoned killer Hannibal Lecter."),
        ("The Name of the Rose", "Umberto Eco", "9780547577531", "A medieval monk investigates mysterious deaths in a secluded Italian monastery."),
        ("The Alienist", "Caleb Carr", "9780812976144", "In 1896 New York, a psychologist uses groundbreaking criminal profiling to catch a killer."),
        ("Murder on the Orient Express", "Agatha Christie", "9780062073501", "Hercule Poirot solves a murder aboard a snowbound luxury train."),
        ("The Cuckoo's Calling", "Robert Galbraith", "9780316206846", "Private investigator Cormoran Strike examines the suspected suicide of a supermodel."),
        ("Presumed Innocent", "Scott Turow", "9780446359863", "A prosecutor is charged with the brutal murder of a female colleague."),
        ("The Girl on the Train", "Paula Hawkins", "9781594633669", "A commuter becomes entangled in a missing persons investigation."),
        ("Shutter Island", "Dennis Lehane", "9780061149023", "U.S. Marshals investigate the disappearance of a patient from a fortress-like hospital."),
        ("Mystic River", "Dennis Lehane", "9780062068408", "A tragic murder reopens old wounds for three childhood friends in Boston."),
        ("The Snowman", "Jo Nesbø", "9780307742995", "Inspector Harry Hole investigates a serial killer who leaves snowmen at crime scenes."),
        ("Defending Jacob", "William Landay", "9780345533661", "An assistant district attorney faces a crisis when his teenage son is accused of murder."),
        ("The Sweetness at the Bottom of the Pie", "Alan Bradley", "9780385343497", "Eleven-year-old amateur chemist Flavia de Luce solves a murder in 1950s England."),
        ("The Maid", "Nita Prose", "9780593356159", "A hotel maid with unique social skills finds herself accused of a wealthy guest's murder."),
        ("Magpie Murders", "Anthony Horowitz", "9780062645227", "An editor reads a mystery manuscript only to find the final chapter missing and the author dead."),
        ("The Guest List", "Lucy Foley", "9780525541905", "A celebrity wedding on a remote Irish island turns deadly when a body is discovered."),
        ("The Chestnut Man", "Søren Sveistrup", "9780062895363", "A psychopathic serial killer leaves figurines made of matchsticks and chestnuts at crime scenes."),
        ("One of Us Is Lying", "Karen M. McManus", "9781524714680", "Five students enter detention, but only four walk out alive after a high school gossip creator is murdered."),
        ("The Devotion of Suspect X", "Keigo Higashino", "9780312575236", "A brilliant math teacher helps a mother cover up a murder, setting off a battle of wits with a detective."),
        ("Before I Go to Sleep", "S.J. Watson", "9780062060563", "A woman with anterograde amnesia wakes up every day with no memory of her past 20 years."),
        ("The Postman Always Rings Twice", "James M. Cain", "9780679723257", "A drifter and a married woman plot to kill her husband for insurance money."),
        ("The Maltese Falcon", "Dashiell Hammett", "9780679722649", "Sam Spade takes on a case that plunges him into a deadly hunt for a jewel-encrusted statuette."),
        ("The Big Sleep", "Raymond Chandler", "9780394758282", "Private eye Philip Marlowe navigates blackmail, pornography, and murder in Los Angeles."),
        ("Red Dragon", "Thomas Harris", "9780440206156", "Retired profiler Will Graham tracks a killer known as the Tooth Fairy with Lecter's aid."),
        ("Postmortem", "Patricia Cornwell", "9780143115458", "Chief Medical Examiner Kay Scarpetta tracks a serial strangled terrorizing Richmond."),
        ("In Cold Blood", "Truman Capote", "9780679745587", "A chilling true crime narrative detailing the brutal murder of the Clutter family in Kansas."),
        ("The Couple Next Door", "Shari Lapena", "9780735221109", "A baby vanishes from her crib while parents attend a dinner party next door."),
        ("Sharp Objects", "Gillian Flynn", "9780307341556", "A journalist returns to her hometown to cover the murder of two young girls."),
        ("The No. 1 Ladies' Detective Agency", "Alexander McCall Smith", "9781400034772", "Precious Ramotswe establishes Botswana's premier female-run detective agency.")
    ],

    "Thriller": [
        ("The Bourne Identity", "Robert Ludlum", "9780553593549", "An amnesiac man pulled from the sea discovers he possesses lethal combat skills."),
        ("The Hunt for Red October", "Tom Clancy", "9781501134012", "A Soviet submarine captain attempts to defect to the United States with a stealth sub."),
        ("Patriot Games", "Tom Clancy", "9780425269404", "Jack Ryan thwarts a terrorist attack in London and targets a vengeful faction."),
        ("The Firm", "John Grisham", "9780385416344", "A young attorney discovers his high-paying law firm is a front for mob money laundering."),
        ("A Time to Kill", "John Grisham", "9780345531926", "A young lawyer defends a father who took revenge into his own hands in Mississippi."),
        ("The Pelican Brief", "John Grisham", "9780345531933", "A law student uncovers a conspiracy behind the assassination of two Supreme Court justices."),
        ("The Day of the Jackal", "Frederick Forsyth", "9780451203892", "A professional assassin is hired to kill French President Charles de Gaulle."),
        ("Bird Box", "Josh Malerman", "9780062259653", "A mother and children navigate a post-apocalyptic river blindfolded to escape unseen creatures."),
        ("Dark Matter", "Blake Crouch", "9781101904244", "A physicist is kidnapped and thrust into an alternate reality where his life took a different path."),
        ("Recursion", "Blake Crouch", "9781524759797", "A detective investigates False Memory Syndrome, a phenomenon that rewrites reality."),
        ("No Country for Old Men", "Cormac McCarthy", "9780307387134", "A hunter finds a drug deal gone wrong and is relentlessly pursued by a cold-blooded killer."),
        ("The Terminal List", "Jack Carr", "9781501180835", "A Navy SEAL seeks vengeance against high-level government conspirators who betrayed his team."),
        ("I Am Pilgrim", "Terry Hayes", "9781439177730", "A former secret agent is pulled out of retirement to stop a terrorist plot."),
        ("Digital Fortress", "Dan Brown", "9780312944926", "The NSA's supercomputer encounters an unbreakable code created by a disgruntled genius."),
        ("Angels & Demons", "Dan Brown", "9781416524793", "Robert Langdon races through Rome to prevent an antimatter bomb from destroying the Vatican."),
        ("The Third Twin", "Ken Follett", "9780445203365", "A scientist discovers identical twins born to different mothers as part of a cloning conspiracy."),
        ("Eye of the Needle", "Ken Follett", "9780143113928", "A ruthless German spy discovers crucial D-Day secrets in WWII England."),
        ("Marathon Man", "William Goldman", "9780345439703", "A graduate student is drawn into a deadly conspiracy involving a Nazi war criminal."),
        ("The Andromeda Strain", "Michael Crichton", "9781101974490", "A team of scientists races to contain a lethal extraterrestrial microorganism."),
        ("Jurassic Park", "Michael Crichton", "9780345538987", "Genetically engineered dinosaurs escape containment on a remote island park."),
        ("The Girl Who Played with Fire", "Stieg Larsson", "9780307454546", "Lisbeth Salander is framed for a triple murder as Lisbeth's past catches up to her."),
        ("The Girl Who Kicked the Hornet's Nest", "Stieg Larsson", "9780307474568", "Salander fights for her freedom while unraveling corrupt government conspiracies from her hospital bed."),
        ("Red Sparrow", "Jason Matthews", "9781501168918", "A Russian intelligence officer trained as a seductive 'sparrow' forms a bond with a CIA officer."),
        ("The Spy Who Came In from the Cold", "John le Carré", "9780143124757", "A British agent accepts a dangerous final mission behind the Iron Curtain in East Germany."),
        ("Tinker Tailor Soldier Spy", "John le Carré", "9780143119784", "George Smiley is brought out of retirement to uncover a Soviet mole in MI6."),
        ("The Silent Passenger", "David Baldacci", "9781538719701", "A high-octane thriller involving political intrigue and covert military intelligence operations."),
        ("Memory Man", "David Baldacci", "9781455586387", "Amos Decker uses his perfect memory to investigate the unsolved murder of his family."),
        ("The Gray Man", "Mark Greaney", "9780425241448", "A freelance assassin and former CIA operative is hunted by international hit squads."),
        ("Never Go Back", "Lee Child", "9780345543448", "Jack Reacher returns to his old military base only to face murder and paternity charges."),
        ("Killing Floor", "Lee Child", "9780451208415", "Ex-military cop Jack Reacher is arrested for murder in a small Georgia town he just entered."),
        ("The Sentinel", "Lee Child", "9781984818461", "Jack Reacher helps an IT guy uncover a massive cyber extortion plot."),
        ("The Escape Artist", "Brad Meltzer", "9781455559527", "A mortician working on military bodies stumbles upon a living victim of a cover-up."),
        ("Unsub", "Meg Gardiner", "9780399585647", "A detective chases a serial killer inspired by the Zodiac who has resurfaced after 20 years."),
        ("The Passenger", "Lisa Lutz", "9781476786490", "A woman assumes multiple identities while fleeing her mysterious past across the country."),
        ("Behind Closed Doors", "B.A. Paris", "9781250121004", "A picture-perfect marriage conceals a dark and terrifying secret behind locked doors.")
    ],

    "Romance": [
        ("Pride and Prejudice", "Jane Austen", "9780141439518", "Fitzwilliam Darcy and Elizabeth Bennet overcome pride and social judgment to find true love."),
        ("Outlander", "Diana Gabaldon", "9780553382563", "A WWII nurse is mysteriously transported back in time to 18th-century Scotland and falls for Jamie Fraser."),
        ("The Notebook", "Nicholas Sparks", "9780446605236", "An enduring love story between Noah and Allie spanning decades of trial and war."),
        ("Me Before You", "Jojo Moyes", "9780143124542", "A cheerful caregiver forms a profound bond with a paralyzed wealthy man."),
        ("The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid", "9781501161933", "Evelyn Hugo reveals the loves, heartbreaks, and compromises of her storied lifetime."),
        ("Beach Read", "Emily Henry", "9781984806734", "Two rival authors spend a summer living next door and swap writing genres."),
        ("Book Lovers", "Emily Henry", "9780593334836", "A literary agent and an executive editor repeatedly bump into each other in a small town."),
        ("Red, White & Royal Blue", "Casey McQuiston", "9781250316776", "The First Son of the US falls in love with the Prince of Wales in a secret romance."),
        ("The Love Hypothesis", "Ali Hazelwood", "9780593336823", "A Ph.D. student enters a fake relationship with a tyrannical young professor."),
        ("It Ends with Us", "Colleen Hoover", "9781501110368", "Lily struggles through emotional complexities, heartbreak, and resilience in love."),
        ("Verity", "Colleen Hoover", "9781408898413", "A struggling writer uncovers disturbing secrets while completing a famous author's series."),
        ("Ugly Love", "Colleen Hoover", "9781476753188", "Miles and Tate agree to an attraction with no strings attached until feelings deepen."),
        ("Bridgerton: The Duke and I", "Julia Quinn", "9780063022638", "Daphne Bridgerton and Simon Basset enter a fake courtship that blossoms into genuine passion."),
        ("Redeeming Love", "Francine Rivers", "9781601420619", "A historical romance retelling of Hosea set during the California Gold Rush."),
        ("Sense and Sensibility", "Jane Austen", "9780141439662", "The Dashwood sisters navigate financial distress and romantic disappointment with sense and emotion."),
        ("Emma", "Jane Austen", "9780141439587", "A well-meaning young woman meddles in small-town matchmaking with comedic results."),
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "Jane Eyre finds love with the brooding Mr. Rochester while discovering dark secrets at Thornfield."),
        ("The Hating Game", "Sally Thorne", "9780062439598", "Two executive assistants locked in workplace rivalry realize hatred and attraction are closely linked."),
        ("People We Meet on Vacation", "Emily Henry", "9781984806758", "Two best friends with opposite personalities take one final summer trip to fix their relationship."),
        ("The Unhoneymooners", "Christina Lauren", "9781501191954", "Two nemeses are forced to go on a free Hawaiian honeymoon together."),
        ("From Lukov with Love", "Mariana Zapata", "9781790403738", "A figure skater partners with her longtime rival in a slow-burn sports romance."),
        ("The Kiss Quotient", "Helen Hoang", "9780451490803", "An econometrician on the autism spectrum hires an escort to learn about dating."),
        ("Get a Life, Chloe Brown", "Talia Hibbert", "9780062941206", "A chronically ill woman makes a bucket list and recruits a brooding handyman to help."),
        ("The Rosie Project", "Graeme Simsion", "9781476729091", "A genetics professor designs a scientific survey to find the perfect wife, but meets Rosie."),
        ("Part of Your World", "Abby Jimenez", "9781538704394", "A city ER doctor falls for a small-town carpenter despite their vastly different worlds."),
        ("Yours Truly", "Abby Jimenez", "9781538704431", "Two ER doctors draft fake love letters that slowly become terrifyingly real."),
        ("One True Loves", "Taylor Jenkins Reid", "9781476776903", "A woman must choose between her returned long-lost husband and her new fiancé."),
        ("Love & Other Words", "Christina Lauren", "9781501128011", "Childhood sweethearts reunite years after an unexplained falling out."),
        ("Spanish Love Deception", "Elena Armas", "9781668002520", "Catalina needs a fake boyfriend for her sister's wedding in Spain and recruits her arrogant coworker."),
        ("Love and Gelato", "Jenna Evans Welch", "9781481432559", "A girl spends the summer in Tuscany uncovering her late mother's secret diary."),
        ("Flatshare", "Beth O'Leary", "9781250295690", "Two flatmates share a bed at different hours of the day and fall in love through sticky notes."),
        ("Crazy Rich Asians", "Kevin Kwan", "9780345803788", "An American professor travels to Singapore and discovers her boyfriend's family is absurdly wealthy."),
        ("The Time Traveler's Wife", "Audrey Niffenegger", "9780156029438", "A passionate love affair between a man with a genetic disorder that causes him to time-travel and his artist wife."),
        ("Vision in White", "Nora Roberts", "9780425227701", "A wedding photographer falls for her childhood friend's older brother in a heartwarming romance."),
        ("The Proposal", "Jasmine Guillory", "9780399587689", "A woman rejects a public scoreboard proposal at a baseball game and finds rescue in a handsome doctor.")
    ],

    "Fantasy": [
        ("The Hobbit", "J.R.R. Tolkien", "9780547928227", "Bilbo Baggins sets out on a quest with thirteen dwarves to reclaim their mountain home."),
        ("The Fellowship of the Ring", "J.R.R. Tolkien", "9780547928210", "Frodo Baggins inherits the One Ring and begins a journey to destroy it in Mordor."),
        ("A Game of Thrones", "George R.R. Martin", "9780553593716", "Noble houses clash for control of the Iron Throne of Westeros while an ancient evil awakens."),
        ("The Name of the Wind", "Patrick Rothfuss", "9780756404741", "Kvothe recounts his legendary youth from an orphaned troupe performer to a powerful arcanist."),
        ("The Way of Kings", "Brandon Sanderson", "9780765365279", "On a storm-swept world of Roshar, an enslaved soldier and a young scholar struggle for survival."),
        ("Mistborn: The Final Empire", "Brandon Sanderson", "9780765350381", "A street urchin discovers her magical Allomantic powers and joins a heist to overthrow an immortal tyrant."),
        ("Harry Potter and the Sorcerer's Stone", "J.K. Rowling", "9780590353427", "An orphaned boy discovers he is a wizard and attends Hogwarts School of Witchcraft and Wizardry."),
        ("The Golden Compass", "Philip Pullman", "9780440418320", "Lyra Belacqua travels to the Arctic to rescue kidnapped children and investigate Dust."),
        ("A Court of Thorns and Roses", "Sarah J. Maas", "9781619634459", "Feyre Archeron is dragged to a magical faerie land after slaying a wolf in the woods."),
        ("Throne of Glass", "Sarah J. Maas", "9781619630628", "An assassin competes in a deadly tournament to win her freedom from a tyrannical king."),
        ("The Lies of Locke Lamora", "Scott Lynch", "9780553588942", "Con artist Locke Lamora leads the Gentleman Bastards in elaborate high-stakes heists."),
        ("The Blade Itself", "Joe Abercrombie", "9780316387316", "A barbarian, a crippled inquisitor, and a vain nobleman are swept into brutal fantasy warfare."),
        ("The Eye of the World", "Robert Jordan", "9780812511818", "Five villagers flee their home when dark forces hunt the reincarnated Dragon Reborn."),
        ("The Priority of the Orange Tree", "Samantha Shannon", "9781635570298", "An unwed queen, a dragon rider, and a mage fight to protect their realms from a sleeping wyrm."),
        ("Circe", "Madeline Miller", "9780316556347", "The banished daughter of Helios transforms from a weak nymph into a formidable witch."),
        ("The Song of Achilles", "Madeline Miller", "9780062060624", "Patroclus recounts his bond and tragic love with Achilles during the Trojan War."),
        ("American Gods", "Neil Gaiman", "9780062572110", "An ex-con named Shadow Moon gets caught in a war between traditional mythological gods and new idols."),
        ("Stardust", "Neil Gaiman", "9780062564344", "Tristan Thorn crosses a magical wall into Faerie to retrieve a fallen star for his beloved."),
        ("Good Omens", "Terry Pratchett & Neil Gaiman", "9780060853983", "An angel and a demon team up to prevent the Apocalypse because they enjoy living on Earth."),
        ("The Color of Magic", "Terry Pratchett", "9780062225672", "Rincewind the inept wizard guides Discworld's very first tourist across a flat world."),
        ("Eragon", "Christopher Paolini", "9780375826696", "A farm boy finds a dragon egg and discovers his destiny as a Dragon Rider."),
        ("Ninth House", "Leigh Bardugo", "9781250313072", "A survivor with the ability to see ghosts is recruited to monitor Yale's secret occult societies."),
        ("Six of Crows", "Leigh Bardugo", "9781627791779", "Six dangerous outcasts attempt an impossible heist into an impenetrable military stronghold."),
        ("The Fifth Season", "N.K. Jemisin", "9780316229296", "On a continent torn by catastrophic climate cycles, an orogene mother searches for her daughter."),
        ("The Dragonbone Chair", "Tad Williams", "9780886772949", "A kitchen boy is drawn into an epic war across Osten Ard involving legendary swords."),
        ("The Poppy War", "R.F. Kuang", "9780062662569", "A war orphan enters an elite military academy and unlocks ancient shamanic fire gods."),
        ("Babel", "R.F. Kuang", "9780063021426", "A Chinese orphan in Victorian London learns silver-working magic and faces imperialist betrayal."),
        ("The Atlas Six", "Olivie Blake", "9781250854513", "Six talented magicians compete for five spots in the secret Alexandrian Society."),
        ("The Black Company", "Glen Cook", "9780765377074", "A mercenary band serves a dark sorceress in a gritty, realistic fantasy world."),
        ("Guards! Guards!", "Terry Pratchett", "9780062225757", "The Night Watch of Ankh-Morpork must save the city from a summoned dragon."),
        ("The Ocean at the End of the Lane", "Neil Gaiman", "9780062255655", "A man returns to his childhood home and remembers strange, dark magical events."),
        ("Daughter of Smoke & Bone", "Laini Taylor", "9780316134026", "An art student in Prague discovers her foster family collects teeth for chimera magic."),
        ("Legend", "David Gemmell", "9780345379061", "An aging warrior makes his final heroic stand at the fortress of Dros Delnoch."),
        ("Fable", "Adrienne Young", "9781250254368", "A sea trader's daughter fights for survival on a dangerous island of divers and pirates."),
        ("The Starless Sea", "Erin Morgenstern", "9780385541213", "A graduate student finds a mysterious book leading to an underground labyrinth of stories.")
    ],

    "Science Fiction": [
        ("Dune", "Frank Herbert", "9780441172719", "Paul Atreides navigates planetary politics, spice harvesting, and giant sandworms on Arrakis."),
        ("Neuromancer", "William Gibson", "9780441569564", "A washed-up computer hacker is hired for a ultimate cyberspace heist against a super-AI."),
        ("Foundation", "Isaac Asimov", "9780553293357", "Hari Seldon uses psychohistory to preserve human knowledge before the Galactic Empire collapses."),
        ("Hyperion", "Dan Simmons", "9780553283686", "Seven pilgrims travel to the Time Tombs on Hyperion to seek a wish from the mysterious Shrike."),
        ("Snow Crash", "Neal Stephenson", "9780553380958", "Hiro Protagonist delivers pizza in reality and battles a computer virus in the Metaverse."),
        ("The Left Hand of Darkness", "Ursula K. Le Guin", "9780441478125", "A human envoy visits Gethen, a world populated by ambisexual inhabitants with no fixed gender."),
        ("Do Androids Dream of Electric Sheep?", "Philip K. Dick", "9780345404473", "Bounty hunter Rick Deckard tracks rogue bio-engineered replicants in dystopian Los Angeles."),
        ("Ender's Game", "Orson Scott Card", "9780812550702", "A young boy is recruited into an orbital Battle School to prepare for an alien invasion."),
        ("The Three-Body Problem", "Cixin Liu", "9780765377067", "Humanity establishes contact with an alien civilization facing catastrophic orbital decay."),
        ("Project Hail Mary", "Andy Weir", "9780593135204", "A lone astronaut wakes up with amnesia on a mission to save the sun from extinction."),
        ("The Martian", "Andy Weir", "9780553418026", "Stranded on Mars, astronaut Mark Watney uses ingenuity and botany to survive."),
        ("Red Mars", "Kim Stanley Robinson", "9780553560732", "The First Hundred colonists terraform Mars amidst political and environmental conflicts."),
        ("Starship Troopers", "Robert A. Heinlein", "9780441783588", "Johnny Rico enlists in the Mobile Infantry to fight giant alien arachnids in interstellar war."),
        ("Stranger in a Strange Land", "Robert A. Heinlein", "9780441790340", "A human raised by Martians returns to Earth and challenges social and religious taboos."),
        ("The War of the Worlds", "H.G. Wells", "9780451530652", "Martian tripods invade Victorian England in a pioneer alien invasion narrative."),
        ("The Time Machine", "H.G. Wells", "9780451530706", "A Victorian scientist travels into the far future and encounters Eloi and Morlocks."),
        ("2001: A Space Odyssey", "Arthur C. Clarke", "9780451457998", "A mysterious monolith prompts a manned mission to Saturn guided by the AI HAL 9000."),
        ("Rendezvous with Rama", "Arthur C. Clarke", "9780553282580", "Humanity intercepts a massive cylindrical alien starship entering the solar system."),
        ("Solaris", "Stanisław Lem", "9780156027601", "Scientists aboard an orbital station attempt to communicate with an oceanic sentient planet."),
        ("The Expanse: Leviathan Wakes", "James S.A. Corey", "9780316129084", "An ice freighter officer and a detective uncover a system-wide alien protomolecule conspiracy."),
        ("Altered Carbon", "Richard K. Morgan", "9780345457684", "Takeshi Kovacs' consciousness is downloaded into a new body to solve a billionaire's murder."),
        ("Old Man's War", "John Scalzi", "9780765315243", "75-year-old citizens trade their bodies for enhanced military sleeves to defend space colonies."),
        ("All Systems Red (The Murderbot Diaries)", "Martha Wells", "9780765397539", "A security android who hacked its governor module just wants to watch soap operas in peace."),
        ("Ancillary Justice", "Ann Leckie", "9780316246620", "A troop carrier AI stripped of its ship seeks revenge against an immortal emperor."),
        ("Contact", "Carl Sagan", "9780671004101", "SETI researcher Ellie Arroway receives humanity's first interstellar transmission from Vega."),
        ("The Dispossessed", "Ursula K. Le Guin", "9780061054884", "A physicist travels between an anarchistic moon and a capitalist planet seeking unity."),
        ("I, Robot", "Isaac Asimov", "9780553382563", "Stories exploring the ethical dilemmas surrounding the Three Laws of Robotics."),
        ("Ringworld", "Larry Niven", "9780345336026", "Explorers travel to an artificial ring structure encircling a star million miles wide."),
        ("Dark Matter", "Blake Crouch", "9781101904244", "A man navigates alternate dimensions after being kidnapped from his own universe."),
        ("A Fire Upon the Deep", "Vernor Vinge", "9780812515281", "Children carrying a super-intelligence counter-measure land on a medieval canine world."),
        ("A Canticle for Leibowitz", "Walter M. Miller Jr.", "9780060892999", "Monks preserve scientific knowledge through centuries of darkness following a nuclear holocaust."),
        ("Children of Time", "Adrian Tchaikovsky", "9780316452502", "Humanity's last survivors encounter a terraformed planet inhabited by evolved spiders."),
        ("The Long Way to a Small, Angry Planet", "Becky Chambers", "9780062444134", "A diverse spaceship crew tunnels wormholes across peaceful galactic space."),
        ("Red Rising", "Pierce Brown", "9780345539786", "A low-caste miner infiltrates Mars' ruling elite to dismantle a color-coded caste system."),
        ("Station Eleven", "Emily St. John Mandel", "9780804172448", "A nomadic theater troupe performs Shakespeare in the Great Lakes region after a flu pandemic.")
    ],

    "Horror": [
        ("Dracula", "Bram Stoker", "9780486411095", "Count Dracula attempts to move from Transylvania to England to spread the undead curse."),
        ("Frankenstein", "Mary Shelley", "9780486282114", "Victor Frankenstein creates a living creature from reanimated corpses with tragic results."),
        ("The Shining", "Stephen King", "9780307743657", "Jack Torrance takes a winter caretaker job at the isolated Overlook Hotel as malevolent forces gather."),
        ("It", "Stephen King", "9781501142970", "Seven adults return to Derry, Maine to confront an ancient shape-shifting evil."),
        ("Carrie", "Stephen King", "9780307743664", "A bullied high school girl unleashes deadly telekinetic powers at her senior prom."),
        ("Pet Sematary", "Stephen King", "9781501156700", "A doctor buries his deceased family pet in an ancient burial ground with terrifying consequences."),
        ("Misery", "Stephen King", "9781501143106", "A famous author is held captive by his obsessed number-one fan following a car crash."),
        ("Bird Box", "Josh Malerman", "9780062259653", "Unseen entities drive anyone who looks at them into suicidal madness."),
        ("House of Leaves", "Mark Z. Danielewski", "9780375703768", "A family discovers their house is larger on the inside than on the outside."),
        ("The Exorcist", "William Peter Blatty", "9780061007224", "Two priests perform an exorcism on an 12-year-old girl possessed by a demon."),
        ("The Haunting of Hill House", "Shirley Jackson", "9780143039983", "Four paranormal researchers stay at Hill House, a mansion imbued with dark psychological dread."),
        ("We Have Always Lived in the Castle", "Shirley Jackson", "9780143039976", "Merricat Blackwood lives in isolation with her sister following a poison murder in the family."),
        ("The Call of Cthulhu", "H.P. Lovecraft", "9780141182346", "Short stories uncovering cosmic horror, ancient gods, and insanity."),
        ("At the Mountains of Madness", "H.P. Lovecraft", "9780812974416", "An Antarctic expedition discovers ruins of an ancient alien city and terrifying monsters."),
        ("Hell House", "Richard Matheson", "9780312868819", "Four investigators enter the Belasco House, the most haunted place on Earth."),
        ("I Am Legend", "Richard Matheson", "9780312865047", "The last human survivor on Earth fights vampires who were infected by a pandemic virus."),
        ("The Silence of the Lambs", "Thomas Harris", "9780312924584", "FBI agent Clarice Starling seeks the aid of Dr. Hannibal Lecter to catch serial killer Buffalo Bill."),
        ("The Terror", "Dan Simmons", "9780316008075", "Franklin's lost Arctic expedition is stalked by a monstrous predator on ice."),
        ("The Ruins", "Scott Smith", "9781400073849", "Tourists visiting a remote Mayan ruin become trapped by carnivorous vines."),
        ("Heart-Shaped Box", "Joe Hill", "9780061147937", "An aging rock star buys a dead man's suit online and inherits a vengeful ghost."),
        ("NOS4A2", "Joe Hill", "9780062200570", "Vic McQueen uses her supernatural bike to rescue children trapped in Christmasland."),
        ("Bird Box", "Josh Malerman", "9780062259653", "A terrifying journey blindfolded down a river to escape creatures that induce madness."),
        ("The Troop", "Nick Cutter", "9781476717715", "A Boy Scout troop on a remote island is infected by a genetically engineered parasite."),
        ("Mexican Gothic", "Silvia Moreno-Garcia", "9780525620785", "A glamorous socialite visits her cousin's gloomy mansion and uncovers fungal horror."),
        ("The Only Good Indians", "Stephen Graham Jones", "9781982136451", "Four Native American men are stalked by an entity seeking revenge for an elk hunt."),
        ("The Cabin at the End of the World", "Paul Tremblay", "9780062679109", "A family on vacation is taken hostage and forced to make an impossible choice to prevent the apocalypse."),
        ("A Head Full of Ghosts", "Paul Tremblay", "9780062363237", "A family copes with a daughter's possible demonic possession filmed for a reality TV show."),
        ("Ghost Story", "Peter Straub", "9780061007224", "Four old men in upstate New York are haunted by a tragic secret from their past."),
        ("Ring", "Koji Suzuki", "9781594973499", "A videotape kills anyone who watches it within seven days unless the curse is passed on."),
        ("Something Wicked This Way Comes", "Ray Bradbury", "9781451673319", "Two boys discover the dark secrets behind a traveling carnival run by Mr. Dark."),
        ("Interview with the Vampire", "Anne Rice", "9780345337665", "Vampire Louis de Pointe du Lac recounts two centuries of devotion and suffering."),
        ("Let the Right One In", "John Ajvide Lindqvist", "9780312355296", "A bullied Swedish boy forms a friendship with an ancient child vampire."),
        ("The Ritual", "Adam Nevill", "9780312641849", "Four old friends hiking in Sweden enter an ancient forest stalked by a Norse deity."),
        ("The Passage", "Justin Cronin", "9780345504968", "A military virus experiment transforms human subjects into bloodthirsty vampire-like creatures."),
        ("Fever Dream", "Samanta Schweblin", "9780399184598", "A dying woman and a boy piece together a terrifying rural eco-disaster.")
    ],

    "Self-Help": [
        ("Atomic Habits", "James Clear", "9780735211292", "Practical strategies to form good habits, break bad ones, and achieve 1% daily growth."),
        ("The 7 Habits of Highly Effective People", "Stephen R. Covey", "9781451639612", "Principles of personal and professional effectiveness focused on integrity and ethics."),
        ("How to Win Friends and Influence People", "Dale Carnegie", "9780671027032", "Timeless advice on communication, empathy, and building strong personal relationships."),
        ("Thinking, Fast and Slow", "Daniel Kahneman", "9780374533557", "Explores the two systems that drive the way we think: intuitive versus deliberate."),
        ("The Subtle Art of Not Giving a F*ck", "Mark Manson", "9780062457714", "A counterintuitive approach to living a good life by accepting human limitations."),
        ("Mindset: The New Psychology of Success", "Carol S. Dweck", "9780345472328", "Differentiates between fixed and growth mindsets in achieving fulfillment and success."),
        ("Deep Work", "Cal Newport", "9781455586691", "Rules for focused success in a distracted world to master complex information."),
        ("Digital Minimalism", "Cal Newport", "9780525536512", "A philosophy of technology use focused on intentional, value-aligned digital habits."),
        ("The Power of Now", "Eckhart Tolle", "9781577314806", "A guide to spiritual enlightenment and living fully in the present moment."),
        ("Man's Search for Meaning", "Viktor E. Frankl", "9780807014295", "Psychiatrist Viktor Frankl recounts his experiences in Auschwitz and introduces logotherapy."),
        ("You Are a Badass", "Jen Sincero", "9780984710881", "How to stop doubting your greatness and create a life you love."),
        ("Grit", "Angela Duckworth", "9781501111105", "The power of passion and perseverance as the primary predictor of success."),
        ("Can't Hurt Me", "David Goggins", "9781544512289", "Mastering your mind and defying odds through extreme physical and mental resilience."),
        ("Extreme Ownership", "Jocko Willink & Leif Babin", "9781250067050", "Navy SEAL leadership principles applied to business and personal discipline."),
        ("The Four Agreements", "Don Miguel Ruiz", "9781878424310", "A practical guide to personal freedom based on ancient Toltec wisdom."),
        ("Daring Greatly", "Brené Brown", "9781594631535", "How vulnerability transforms the way we live, love, parent, and lead."),
        ("The Gifts of Imperfection", "Brené Brown", "9781592858491", "Let go of who you think you're supposed to be and embrace who you are."),
        ("Quiet: The Power of Introverts", "Susan Cain", "9780307352156", "Celebrating the quiet strength and contributions of introverts in an extroverted world."),
        ("The Miracle Morning", "Hal Elrod", "9780979019715", "Six daily morning habits to transform your life before 8 AM."),
        ("Essentialism", "Greg McKeown", "9780804137386", "The disciplined pursuit of less to make your highest possible contribution."),
        ("Outliers: The Story of Success", "Malcolm Gladwell", "9780316017930", "Examining the environmental factors, timing, and practice that drive extraordinary success."),
        ("Blink: The Power of Thinking Without Thinking", "Malcolm Gladwell", "9780316010665", "How our brains make rapid split-second decisions and judgments."),
        ("Rich Dad Poor Dad", "Robert T. Kiyosaki", "9781612680194", "Financial education and mindset lessons on assets versus liabilities."),
        ("The Psychology of Money", "Morgan Housel", "9780857197689", "Timeless lessons on wealth, greed, and happiness through human behavior."),
        ("Show Your Work!", "Austin Kleon", "9780761178972", "Ten ways to share your creativity and get discovered in the digital age."),
        ("Steal Like an Artist", "Austin Kleon", "9780761169253", "Ten things nobody told you about being creative."),
        ("The 5 AM Club", "Robin Sharma", "9781443456623", "Own your morning and elevate your life through a revolutionary morning routine."),
        ("The Monk Who Sold His Ferrari", "Robin Sharma", "9780062515674", "A fable about fulfilling your dreams and reaching your highest destiny."),
        ("Make Your Bed", "William H. McRaven", "9781455570249", "Little things that can change your life and maybe the world."),
        ("The Body Keeps the Score", "Bessel van der Kolk", "9780143127741", "Brain, mind, and body in the healing of trauma."),
        ("12 Rules for Life", "Jordan B. Peterson", "9780345816023", "An antidote to chaos combining ancient mythologies and scientific research."),
        ("Influence: The Psychology of Persuasion", "Robert B. Cialdini", "9780061241896", "The six universal principles of ethical persuasion and how to apply them."),
        ("Design Your Life", "Bill Burnett & Dave Evans", "9781101875322", "How to use design thinking to build a well-lived, joyful life."),
        ("The War of Art", "Steven Pressfield", "9781936891023", "Break through creative blocks and win your inner battles against resistance."),
        ("Tiny Habits", "BJ Fogg", "9780358003328", "The small changes that change everything through behavioral design science.")
    ],

    "Biography": [
        ("Steve Jobs", "Walter Isaacson", "9781451648539", "The exclusive biography of the creative entrepreneur who revolutionized multiple industries."),
        ("Leonardo da Vinci", "Walter Isaacson", "9781501139154", "Connecting art to science, Isaacson explores Da Vinci's genius through his notebooks."),
        ("Einstein: His Life and Universe", "Walter Isaacson", "9780743264747", "How an imaginative patent clerk became the supreme genius of modern physics."),
        ("Elon Musk", "Walter Isaacson", "9781982181284", "An intimate story of the controversial innovator behind SpaceX, Tesla, and Neuralink."),
        ("Becoming", "Michelle Obama", "9781524763138", "A deeply personal memoir by the former First Lady of the United States."),
        ("A Promised Land", "Barack Obama", "9781524763169", "President Obama tells the story of his improbable odyssey from young man to president."),
        ("Long Walk to Freedom", "Nelson Mandela", "9780316548182", "The inspiring autobiography of South Africa's first democratically elected president."),
        ("The Diary of a Young Girl", "Anne Frank", "9780553296983", "The poignant journal kept by Anne Frank while hiding from the Nazis in Amsterdam."),
        ("Unbroken", "Laura Hillenbrand", "9780345544711", "Olympic runner Louis Zamperini survives 47 days on a raft and years in WWII POW camps."),
        ("Shoe Dog", "Phil Knight", "9781501135910", "A memoir by the creator of Nike sharing the early struggle and growth of the swoosh."),
        ("Churchill: A Life", "Martin Gilbert", "9780805023961", "The definitive single-volume biography of Britain's wartime Prime Minister."),
        ("Alexander Hamilton", "Ron Chernow", "9780143034759", "The masterpiece biography that inspired the hit Broadway musical Hamilton."),
        ("Washington: A Life", "Ron Chernow", "9780143119968", "A landmark portrait of George Washington as soldier, statesman, and human being."),
        ("Grant", "Ron Chernow", "9780143110637", "A comprehensive re-examination of General Ulysses S. Grant's presidency and military leadership."),
        ("Frida", "Hayden Herrera", "9780060085896", "The biography of Mexican painter Frida Kahlo detailing her art, pain, and passion."),
        ("When Breath Becomes Air", "Paul Kalanithi", "9780812988406", "A young neurosurgeon facing terminal lung cancer reflects on what makes life meaningful."),
        ("Educated", "Tara Westover", "9780399590504", "A young woman escapes an isolated survivalist family in Idaho to earn a Cambridge Ph.D."),
        ("The Glass Castle", "Jeannette Walls", "9780743273565", "A memoir of growing up in a eccentric, nomadic, and impoverished family."),
        ("Born a Crime", "Trevor Noah", "9780399588174", "Stories from a South African childhood during apartheid by the comedian and TV host."),
        ("Open", "Andre Agassi", "9780307388407", "The candid memoir of tennis legend Andre Agassi revealing his hatred of tennis."),
        ("Kitchen Confidential", "Anthony Bourdain", "9780060934910", "Adventures in the culinary underbelly by the beloved chef and storyteller."),
        ("The Snowball", "Alice Schroeder", "9780553384611", "The official biography of Warren Buffett detailing his investments and life philosophy."),
        ("Benjamin Franklin: An American Life", "Walter Isaacson", "9780743258074", "A portrait of Franklin as the founding father who defined American identity."),
        ("Open Book", "Jessica Simpson", "9780062899446", "A raw and open memoir about music, fame, and personal healing."),
        ("Greenlights", "Matthew McConaughey", "9780593139134", "Unconventional wisdom and life lessons from the Oscar-winning actor's journals."),
        ("The Autobiography of Malcolm X", "Malcolm X & Alex Haley", "9780345350688", "The seminal narrative of Malcolm X's transformation into a civil rights leader."),
        ("Night", "Elie Wiesel", "9780374500016", "A harrowing firsthand account of survival in Nazi concentration camps."),
        ("Wild: From Lost to Found on the Pacific Crest Trail", "Cheryl Strayed", "9780307476074", "A 1,100-mile solo hike undertaken to recover from personal tragedy."),
        ("I Am Malala", "Malala Yousafzai", "9780316322409", "The girl who stood up for education and was shot by the Taliban."),
        ("The Wright Brothers", "David McCullough", "9781476728759", "The dramatic story of Wilbur and Orville Wright building the airplane."),
        ("John Adams", "David McCullough", "9780684813639", "The Pulitzer-winning biography of America's second president."),
        ("Steve Jobs: The Man Who Thought Different", "Karen Blumenthal", "9781250014450", "A young adult biography of Apple's visionary founder."),
        ("Total Recall", "Arnold Schwarzenegger", "9781451662436", "Arnold Schwarzenegger's unbelievable life story from bodybuilder to movie star to governor."),
        ("Principles", "Ray Dalio", "9781501124020", "Life and work principles from the founder of Bridgewater Associates."),
        ("Surrender", "Bono", "9780525521044", "40 songs, one story: memoir by U2's lead singer Bono.")
    ],

    "History": [
        ("Sapiens: A Brief History of Humankind", "Yuval Noah Harari", "9780062316097", "Exploring how Homo sapiens conquered Earth through cognitive, agricultural, and scientific revolutions."),
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "Fates of human societies shaped by geographic and environmental factors rather than biology."),
        ("The Silk Roads", "Peter Frankopan", "9781101912379", "A new history of the world centering on the trade networks connecting East and West."),
        ("The History of the Ancient World", "Susan Wise Bauer", "9780393059748", "From the earliest written records to the fall of Rome across global civilizations."),
        ("A People's History of the United States", "Howard Zinn", "9780062397348", "American history told from the perspective of working class citizens, women, and minorities."),
        ("1776", "David McCullough", "9780743226714", "The intense story of the pivotal year of the American Revolutionary War."),
        ("The Guns of August", "Barbara W. Tuchman", "9780345386236", "The fatal decisions and outbreak of World War I in August 1914."),
        ("The Rise and Fall of the Third Reich", "William L. Shirer", "9781451651683", "The comprehensive history of Nazi Germany from its origins to ultimate defeat."),
        ("Postwar: A History of Europe Since 1945", "Tony Judt", "9780143037750", "Rebuilding Europe from the ashes of WWII through the fall of the Soviet Union."),
        ("The Peloponnesian War", "Donald Kagan", "9780142921210", "The tragic thirty-year conflict between Athens and Sparta."),
        ("The Splendid and the Vile", "Erik Larson", "9780385348713", "Winston Churchill and London during the German Blitz of 1940-1941."),
        ("The Devil in the White City", "Erik Larson", "9780679785897", "Intertwining the 1893 Chicago World's Fair architect with serial killer H.H. Holmes."),
        ("Dead Wake", "Erik Larson", "9780307408877", "The sinking of the Lusitania and the events bringing America into WWI."),
        ("Stalingrad: The Fateful Siege", "Antony Beevor", "9780140284584", "The epic and brutal battle that turned the tide of World War II on the Eastern Front."),
        ("D-Day: June 6, 1944", "Stephen E. Ambrose", "9780684801377", "The climax of WWII told through interviews with soldiers who stormed Normandy beaches."),
        ("Band of Brothers", "Stephen E. Ambrose", "9781501179402", "Easy Company, 506th Regiment, 101st Airborne from D-Day to Hitler's Eagle's Nest."),
        ("The Plantagenets", "Dan Jones", "9780143124924", "The king and queen dynasties that shaped medieval England."),
        ("The Hollow Crown", "Dan Jones", "9780143127888", "The bloody Wars of the Roses between the houses of Lancaster and York."),
        ("Powers and Thrones", "Dan Jones", "9781984880871", "A new history of the Middle Ages spanning fall of Rome to Protestant Reformation."),
        ("The Dawn of Everything", "David Graeber & David Wengrow", "9780374157357", "A new science-backed history of humanity challenging traditional theories of social evolution."),
        ("Caste: The Origins of Our Discontents", "Isabel Wilkerson", "9780593230251", "Examining unseen caste hierarchies in America, Nazi Germany, and India."),
        ("The Warmth of Other Suns", "Isabel Wilkerson", "9780679763888", "The epic story of America's Great Migration of Black citizens moving North and West."),
        ("Genghis Khan and the Making of the Modern World", "Jack Weatherford", "9780609809648", "How Genghis Khan's conquests spread trade, technology, and religious freedom."),
        ("The Crusades: The Authoritative History", "Thomas Asbridge", "9780060787295", "The two-hundred-year war for the Holy Land from Christian and Muslim perspectives."),
        ("The Romanovs: 1613-1918", "Simon Sebag Montefiore", "9780307280114", "The twenty tsars and tsarinas who ruled the Russian Empire."),
        ("Jerusalem: The Biography", "Simon Sebag Montefiore", "9780307280503", "The history of the Holy City through kings, conquerors, and prophets."),
        ("Empires of the Sea", "Roger Crowley", "9780812977646", "The final battle for the Mediterranean between Christian Europe and the Ottoman Empire."),
        ("1491: New Revelations of the Americas Before Columbus", "Charles C. Mann", "9781400032051", "Uncovering thriving pre-Columbian Western Hemisphere civilizations."),
        ("1493: Uncovering the World Columbus Created", "Charles C. Mann", "9780307278241", "How the Columbian Exchange permanently re-ordered global ecology and commerce."),
        ("The Anarchy", "William Dalrymple", "9781635573954", "How the East India Company overthrew the Mughal Empire and conquered India."),
        ("The Last Mughal", "William Dalrymple", "9781400078332", "The fall of Delhi and the end of the Mughal Dynasty during the 1857 Indian Uprising."),
        ("Return of a King", "William Dalrymple", "9780307948533", "The First Anglo-Afghan War and Britain's catastrophic 19th-century invasion."),
        ("Rubicon: The Last Years of the Roman Republic", "Tom Holland", "9781400078974", "The fall of the Roman Republic and the rise of Julius Caesar."),
        ("Persian Fire", "Tom Holland", "9780307279484", "The Greco-Persian Wars and the battle for the defense of the West."),
        ("Dynasty: The Rise and Fall of the House of Caesar", "Tom Holland", "9780385537841", "The reign of Augustus, Tiberius, Caligula, Claudius, and Nero.")
    ],

    "Philosophy": [
        ("Meditations", "Marcus Aurelius", "9780812968255", "Personal Stoic reflections on duty, virtue, and self-discipline by the Roman Emperor."),
        ("The Republic", "Plato", "9780140455113", "Socratic dialogue concerning justice, the ideal city-state, and the Allegory of the Cave."),
        ("Nicomachean Ethics", "Aristotle", "9780140449495", "Aristotle's inquiry into the highest human good and virtue ethics."),
        ("Beyond Good and Evil", "Friedrich Nietzsche", "9780140449235", "Challenging traditional morality and introducing the concept of the Will to Power."),
        ("Thus Spoke Zarathustra", "Friedrich Nietzsche", "9780140441185", "Philosophical novel introducing the Ubermensch and eternal recurrence."),
        ("Critique of Pure Reason", "Immanuel Kant", "9780140447477", "Investigating the boundaries of human knowledge and space-time perception."),
        ("Being and Time", "Martin Heidegger", "9780061575594", "An inquiry into Dasein and the fundamental question of what it means to be."),
        ("Being and Nothingness", "Jean-Paul Sartre", "9780671867805", "The foundational text of existentialism detailing freedom, anguish, and bad faith."),
        ("The Myth of Sisyphus", "Albert Camus", "9780679733737", "Addressing the absurd and concluding that one must imagine Sisyphus happy."),
        ("The Stranger", "Albert Camus", "9780679720201", "Meursault navigates detachment and existential absurdity following a senseless murder."),
        ("The Prince", "Niccolò Machiavelli", "9780140449150", "A political treatise advising rulers on power retention through realism and cunning."),
        ("Leviathan", "Thomas Hobbes", "9780140431957", "The social contract theory and the necessity of an absolute sovereign."),
        ("Two Treatises of Government", "John Locke", "9780486277363", "Argues for natural rights to life, liberty, and property."),
        ("The Social Contract", "Jean-Jacques Rousseau", "9780140444254", "Man is born free, and everywhere he is in chains."),
        ("Ethics", "Baruch Spinoza", "9780140435719", "Pantheistic philosophy asserting God and nature are one substance."),
        ("Discourse on Method", "René Descartes", "9780140444513", "Introducing rationalism and the famous principle: Cogito, ergo sum."),
        ("Tao Te Ching", "Lao Tzu", "9780140441314", "Foundational text of Taoism offering wisdom on harmony and natural flow."),
        ("The Art of War", "Sun Tzu", "9781590302255", "Ancient military tactics and strategic wisdom applicable to all conflicts."),
        ("The Analects", "Confucius", "9780140443417", "Collection of sayings on morality, ritual, and good governance."),
        ("Zen and the Art of Motorcycle Maintenance", "Robert M. Pirsig", "9780060589462", "A motorcycle trip across America explores the metaphysics of Quality."),
        ("Justice: What's the Right Thing to Do?", "Michael J. Sandel", "9780374532505", "Exploring ethical dilemmas through utilitarianism, Kantian ethics, and civic virtue."),
        ("The Problems of Philosophy", "Bertrand Russell", "9780195115529", "An accessible introduction to epistemology and theories of truth."),
        ("A History of Western Philosophy", "Bertrand Russell", "9780671201586", "Comprehensive survey of philosophy from pre-Socratics to 20th century."),
        ("The Daily Stoic", "Ryan Holiday", "9780735211735", "366 meditations on wisdom, perseverance, and the art of living."),
        ("Obstacle Is the Way", "Ryan Holiday", "9781591846352", "Turning trials into triumph through Stoic philosophy."),
        ("Ego Is the Enemy", "Ryan Holiday", "9781591847816", "How suppressing ego leads to genuine mastery and resilience."),
        ("Letters from a Stoic", "Seneca", "9780140442106", "Epistles offering guidance on friendship, grief, and simple living."),
        ("Enchiridion and Discourses", "Epictetus", "9780140444537", "Core Stoic manual on controlling what is within your power."),
        ("Sophie's World", "Jostein Gaarder", "9780374530716", "A novel detailing the history of Western philosophy for young readers."),
        ("Tractatus Logico-Philosophicus", "Ludwig Wittgenstein", "9780415254083", "Investigating language, logic, and the limits of expressible thought."),
        ("Philosophical Investigations", "Ludwig Wittgenstein", "9781405159289", "Concepts of language-games and family resemblances."),
        ("The Second Sex", "Simone de Beauvoir", "9780307277787", "Landmark feminist analysis: One is not born, but rather becomes, a woman."),
        ("Utilitarianism", "John Stuart Mill", "9780486454145", "Promoting the greatest happiness principle for the greatest number."),
        ("On Liberty", "John Stuart Mill", "9780140432077", "Defending individual liberty against tyranny of the majority."),
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "A philosophical look at geographic determinism in human development.")
    ],

    "Young Adult": [
        ("The Hunger Games", "Suzanne Collins", "9780439023481", "Katniss Everdeen volunteers for a televised death tournament to save her sister."),
        ("Catching Fire", "Suzanne Collins", "9780439023498", "Katniss and Peeta become targets of the Capitol as rebellion stirs across Panem."),
        ("Mockingjay", "Suzanne Collins", "9780439023511", "Katniss becomes the symbol of full-scale revolution against President Snow."),
        ("The Fault in Our Stars", "John Green", "9780525478812", "Two cancer-stricken teens meet at a support group and fall in love in Amsterdam."),
        ("Looking for Alaska", "John Green", "9780142402511", "Miles seeks the 'Great Perhaps' at boarding school and falls for unpredictable Alaska."),
        ("Paper Towns", "John Green", "9780142414934", "Quentin searches for his eccentric neighbor Margo after she suddenly vanishes."),
        ("Divergent", "Veronica Roth", "9780062024039", "In a faction-based society, Tris Prior discovers she is Divergent and fits nowhere."),
        ("Insurgent", "Veronica Roth", "9780062024046", "Tris navigates war among factions while seeking the truth behind their ancestors."),
        ("The Maze Runner", "James Dashner", "9780385737951", "Thomas wakes up in a metal elevator with no memory, trapped inside a giant living maze."),
        ("Perks of Being a Wallflower", "Stephen Chbosky", "9780671027346", "Introverted freshman Charlie writes letters detailing his high school experience."),
        ("To All the Boys I've Loved Before", "Jenny Han", "9781442426702", "Lara Jean's secret love letters are accidentally mailed to all five of her crushes."),
        ("The Book Thief", "Markus Zusak", "9780375842207", "A young girl in Nazi Germany finds solace in stealing books and sharing them."),
        ("Eleanor & Park", "Rainbow Rowell", "9781250012579", "Two misfits meet on a high school bus and bond over comic books and 80s music."),
        ("Fangirl", "Rainbow Rowell", "9781250030955", "Cath navigates college life while writing massively popular fan fiction."),
        ("One of Us Is Lying", "Karen M. McManus", "9781524714680", "Detention turns deadly when a high school gossip creator is murdered."),
        ("The Hate U Give", "Angie Thomas", "9780062498533", "Starr witnesses the fatal shooting of her childhood best friend by a police officer."),
        ("On the Come Up", "Angie Thomas", "9780062498564", "Sixteen-year-old Bri fights for her hip-hop dreams amidst poverty and controversy."),
        ("Legend", "Marie Lu", "9780142422076", "A teenage prodigy and a famous criminal cross paths in futuristic Los Angeles."),
        ("Prodigy", "Marie Lu", "9780142424179", "June and Day flee to Vegas as rebellion against the Republic heats up."),
        ("Red Queen", "Victoria Aveyard", "9780062310637", "A Mare Barrow discovers she has electric powers despite having common Red blood."),
        ("Cinder", "Marissa Meyer", "9780312641894", "A gifted mechanic cyborg in New Beijing meets Prince Kai amidst a galactic plague."),
        ("Scarlet", "Marissa Meyer", "9780312641900", "Scarlet teams up with a street fighter to find her missing grandmother."),
        ("Throne of Glass", "Sarah J. Maas", "9781619630628", "Celaena Sardothien competes to become the King's Champion in exchange for freedom."),
        ("A Court of Thorns and Roses", "Sarah J. Maas", "9781619634459", "Feyre is taken to Prythian after killing a faerie wolf."),
        ("Shadow and Bone", "Leigh Bardugo", "9780805094596", "Alina Starkov summons sun power that could destroy the Shadow Fold."),
        ("Six of Crows", "Leigh Bardugo", "9781627791779", "Kaz Brekker leads six outcasts on an impossible heist."),
        ("Percy Jackson: The Lightning Thief", "Rick Riordan", "9780786838654", "Percy discovers he is a demigod son of Poseidon accused of stealing Zeus' master bolt."),
        ("Percy Jackson: The Sea of Monsters", "Rick Riordan", "9780786856862", "Percy sails into the Bermuda Triangle to retrieve the Golden Fleece."),
        ("The Giver", "Lois Lowry", "9780544336262", "Jonas is selected to receive all memories of pleasure and pain in a utopian world."),
        ("Eragon", "Christopher Paolini", "9780375826696", "A young farm boy raises a dragon and joins the rebellion against an evil king."),
        ("Holes", "Louis Sachar", "9780440414803", "Stanley Yelnats is sent to Camp Green Lake where boys dig holes in the desert."),
        ("Simon vs. the Homo Sapiens Agenda", "Becky Albertalli", "9780062348678", "Sixteen-year-old Simon navigates secret emails and coming out to his peers."),
        ("They Both Die at the End", "Adam Silvera", "9780062457790", "Two strangers receive news that today is their last day alive and spend it together."),
        ("An Ember in the Ashes", "Sabaa Tahir", "9780451470089", "A scholar girl and a martial soldier fight for freedom in a Roman-inspired empire."),
        ("Aristotle and Dante Discover the Secrets of the Universe", "Benjamin Alire Sáenz", "9781442408937", "Two Mexican-American teens form an unbreakable bond in 1980s El Paso.")
    ],

    "Poetry": [
        ("Leaves of Grass", "Walt Whitman", "9780486268781", "A landmark poetry collection celebrating democracy, nature, and the human spirit."),
        ("The Complete Poems of Emily Dickinson", "Emily Dickinson", "9780316184137", "Profound meditations on mortality, love, immortality, and inner solitude."),
        ("Milk and Honey", "Rupi Kaur", "9781449474256", "A collection of poetry and prose about survival, love, loss, trauma, and womanhood."),
        ("The Sun and Her Flowers", "Rupi Kaur", "9781449486792", "A vibrant journey about wilting, falling, rooting, rising, and blooming."),
        ("home body", "Rupi Kaur", "9781501175299", "Raw conversations with oneself on love, mental health, and acceptance."),
        ("Selected Poems", "T.S. Eliot", "9780156811255", "Includes landmark modernist works 'The Waste Land' and 'The Love Song of J. Alfred Prufrock'."),
        ("The Waste Land and Other Poems", "T.S. Eliot", "9780140449969", "Defining modern poetry in the aftermath of World War I."),
        ("Complete Poems", "E.E. Cummings", "9780393308945", "Innovative typography, unconventional syntax, and romantic lyricism."),
        ("Twenty Love Poems and a Song of Despair", "Pablo Neruda", "9780143039969", "Sensual and passionate love poetry by the Chilean Nobel laureate."),
        ("100 Love Sonnets", "Pablo Neruda", "9780292705005", "Sonnets dedicated to his beloved wife Matilde Urrutia."),
        ("Rumi: The Book of Love", "Coleman Barks", "9780060750503", "Ecstatic Sufi mystic poems on divine passion, surrender, and love."),
        ("The Essential Rumi", "Coleman Barks", "9780062509598", "Definitive translations of Jalal al-Din Rumi's spiritual verse."),
        ("The Prophet", "Kahlil Gibran", "9780394404288", "Poetic essays on life, freedom, pain, reason, and love by the Lebanese poet."),
        ("Devotions: The Selected Poems of Mary Oliver", "Mary Oliver", "9780399563249", "Beloved nature poetry honoring the natural world, mindfulness, and wonder."),
        ("Wild Geese", "Mary Oliver", "9780140587173", "Gentle reflections on finding one's place in the family of things."),
        ("Ariel", "Sylvia Plath", "9780060732608", "Fierce, brilliant, and intense poems written shortly before Plath's death."),
        ("The Collected Poems of W.B. Yeats", "W.B. Yeats", "9780684807317", "Mystical, political, and romantic Irish poetry spanning fifty years."),
        ("The Hill We Climb", "Amanda Gorman", "9780593465271", "The presidential inauguration poem celebrating hope, unity, and resilience."),
        ("Call Us What We Carry", "Amanda Gorman", "9780593465066", "Poetry exploring collective grief, memory, and healing after global crises."),
        ("Pillow Thoughts", "Courtney Peppernell", "9781449489755", "A cozy collection of prose and poetry for mendings of heart."),
        ("Shout", "Laurie Halse Anderson", "9780670012107", "A poetic memoir advocating for survivors of trauma and sexual assault."),
        ("Brown Girl Dreaming", "Jacqueline Woodson", "9780147515827", "Verse memoir of growing up as an African American girl in the 1960s and 70s."),
        ("Long Way Down", "Jason Reynolds", "9781481438254", "A sixty-second elevator ride written in verse as Will decides whether to seek revenge."),
        ("Clarity & Connection", "Yung Pueblo", "9781524860486", "Short poems on self-awareness, letting go, and personal growth."),
        ("Inward", "Yung Pueblo", "9781449495756", "Reflections on self-love and releasing emotional burdens."),
        ("Selected Poems of Langston Hughes", "Langston Hughes", "9780679728184", "Iconic poems of the Harlem Renaissance celebrating Black culture and resilience."),
        ("The Raven and Other Favorite Poems", "Edgar Allan Poe", "9780486266855", "Macabre, gothic, and rhythmic verse from the master of horror."),
        ("Sonnets", "William Shakespeare", "9780486266862", "154 sonnets exploring love, beauty, time, and mortality."),
        ("Paradise Lost", "John Milton", "9780140424393", "Epic blank-verse poem detailing the Fall of Man and Satan's rebellion."),
        ("The Divine Comedy", "Dante Alighieri", "9780142437223", "An epic journey through Inferno, Purgatorio, and Paradiso."),
        ("Selected Poems of Lord Byron", "Lord Byron", "9780140424454", "Romantic and Byronic verse filled with passion and rebellion."),
        ("Odes", "John Keats", "9780140424546", "Romantic odes exploring beauty, transience, and art."),
        ("Song of Myself", "Walt Whitman", "9780486447827", "Core epic poem celebrating cosmic unity and individual spirit."),
        ("Citizen: An American Lyric", "Claudia Rankine", "9781556594625", "Poetic commentary on microaggressions and racial injustice in modern society."),
        ("Night Sky with Exit Wounds", "Ocean Vuong", "9781556594953", "Moving poems on family, war, memory, and queer identity.")
    ],

    "Classic Literature": [
        ("Pride and Prejudice", "Jane Austen", "9780141439518", "Social commentary and romance in 19th-century Regency England."),
        ("Crime and Punishment", "Fyodor Dostoevsky", "9780143107637", "Raskolnikov commits murder to test a theory of extraordinary men and suffers guilt."),
        ("The Brothers Karamazov", "Fyodor Dostoevsky", "9780375761041", "Four brothers embody faith, doubt, passion, and morality in 19th-century Russia."),
        ("War and Peace", "Leo Tolstoy", "9780140447934", "Five aristocratic families navigate Napoleon's invasion of Russia."),
        ("Anna Karenina", "Leo Tolstoy", "9780143035008", "A tragic love affair between Anna and Count Vronsky amid Russian high society."),
        ("Moby-Dick", "Herman Melville", "9780142437247", "Captain Ahab's obsessive pursuit of the white whale Moby Dick."),
        ("The Odyssey", "Homer", "9780140268867", "Odysseus' ten-year struggle to return home to Ithaca after the Trojan War."),
        ("The Iliad", "Homer", "9780140275360", "The wrath of Achilles during the final weeks of the Trojan War."),
        ("Les Misérables", "Victor Hugo", "9780451419439", "Ex-convict Jean Valjean seeks redemption while pursued by relentless Inspector Javert."),
        ("The Hunchback of Notre-Dame", "Victor Hugo", "9780140443530", "The bell-ringer Quasimodo hides in Notre-Dame and loves the dancer Esmeralda."),
        ("The Count of Monte Cristo", "Alexandre Dumas", "9780140449266", "Edmond Dantès escapes from prison and seeks vengeance against those who betrayed him."),
        ("The Three Musketeers", "Alexandre Dumas", "9780140449266", "Young D'Artagnan joins Athos, Porthos, and Aramis to protect the King of France."),
        ("Don Quixote", "Miguel de Cervantes", "9780060934347", "An eccentric nobleman reads too many chivalric romances and sets out as a knight-errant."),
        ("Great Expectations", "Charles Dickens", "9780141439563", "The growth and moral development of orphan Pip under mysterious patronage."),
        ("A Tale of Two Cities", "Charles Dickens", "9780141439600", "London and Paris during the turmoil of the French Revolution."),
        ("David Copperfield", "Charles Dickens", "9780141439570", "The autobiographical journey of David from impoverished childhood to successful author."),
        ("Oliver Twist", "Charles Dickens", "9780141439747", "An orphan boy escapes a workhouse and falls in with London pickpockets."),
        ("The Picture of Dorian Gray", "Oscar Wilde", "9780141439570", "A young man remains youthful while his portrait ages and records his moral corruption."),
        ("Dracula", "Bram Stoker", "9780486411095", "The gothic vampire tale set in Transylvania and London."),
        ("Frankenstein", "Mary Shelley", "9780486282114", "A scientist creates life with devastating moral consequences."),
        ("Jane Eyre", "Charlotte Brontë", "9780141441146", "An independent governess falls for her mysterious employer."),
        ("Wuthering Heights", "Emily Brontë", "9780141439556", "Dark, passionate romance on the Yorkshire moors."),
        ("Madame Bovary", "Gustave Flaubert", "9780140449129", "Emma Bovary seeks romance to escape boring provincial marriage with tragic results."),
        ("The Scarlet Letter", "Nathaniel Hawthorne", "9780142437261", "Hester Prynne is forced to wear an 'A' for adultery in Puritan Boston."),
        ("Heart of Darkness", "Joseph Conrad", "9780141441825", "Marlow journeys up the Congo River in search of ivory trader Kurtz."),
        ("The Metamorphosis", "Franz Kafka", "9780553213690", "Gregor Samsa wakes up one morning transformed into a giant insect."),
        ("The Trial", "Franz Kafka", "9780805209990", "Josef K. is arrested and prosecuted by an inaccessible authority for an unknown crime."),
        ("The Sound and the Fury", "William Faulkner", "9780679732242", "The downfall of the aristocratic Compson family in Mississippi."),
        ("As I Lay Dying", "William Faulkner", "9780679732259", "The Bundren family journeys across Mississippi to bury their matriarch."),
        ("The Old Man and the Sea", "Ernest Hemingway", "9780684801223", "An aging Cuban fisherman battles a giant marlin in the Gulf Stream."),
        ("For Whom the Bell Tolls", "Ernest Hemingway", "9780684803357", "Robert Jordan fights with anti-fascist guerrillas in the Spanish Civil War."),
        ("The Sun Also Rises", "Ernest Hemingway", "9780684800714", "Expatriates travel from Paris to Pamplona for the running of the bulls."),
        ("Ulysses", "James Joyce", "9780141182803", "Leopold Bloom's day in Dublin on June 16, 1904, echoing Homer's Odyssey."),
        ("A Portrait of the Artist as a Young Man", "James Joyce", "9780141182605", "Stephen Dedalus rejects religious and national ties to pursue art."),
        ("The Stranger", "Albert Camus", "9780679720201", "An absurd murder on an Algerian beach leads to existential trial.")
    ],

    "Non-Fiction": [
        ("Thinking, Fast and Slow", "Daniel Kahneman", "9780374533557", "Two systems of thought: fast intuitive judgment vs. slow logical reasoning."),
        ("Sapiens: A Brief History of Humankind", "Yuval Noah Harari", "9780062316097", "How Homo sapiens conquered Earth through cognitive and agricultural revolutions."),
        ("Homo Deus: A Brief History of Tomorrow", "Yuval Noah Harari", "9780062464316", "Examining humanity's future in an era of AI and biotechnology."),
        ("21 Lessons for the 21st Century", "Yuval Noah Harari", "9780525512172", "Addressing pressing technological, political, and technological challenges today."),
        ("Outliers: The Story of Success", "Malcolm Gladwell", "9780316017930", "Environmental factors and practice hours behind high achievers."),
        ("The Tipping Point", "Malcolm Gladwell", "9780316346627", "How little things can make a big difference in social trends."),
        ("Blink", "Malcolm Gladwell", "9780316010665", "The power of split-second intuitive decision making."),
        ("Quiet: The Power of Introverts", "Susan Cain", "9780307352156", "How introverts shape a world that can't stop talking."),
        ("Freakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060731335", "A rogue economist explores the hidden side of everything."),
        ("SuperFreakonomics", "Steven D. Levitt & Stephen J. Dubner", "9780060889579", "Global cooling, patriotic prostitutes, and why suicide bombers should buy life insurance."),
        ("The Immortal Life of Henrietta Lacks", "Rebecca Skloot", "9781400052189", "The story of HeLa cells harvested without consent that revolutionized medicine."),
        ("Educated", "Tara Westover", "9780399590504", "A young woman leaves an isolated survivalist home to earn a Ph.D."),
        ("Becoming", "Michelle Obama", "9781524763138", "Memoir of the former First Lady navigating family and politics."),
        ("Born a Crime", "Trevor Noah", "9780399588174", "Growing up mixed-race in apartheid South Africa."),
        ("The Body Keeps the Score", "Bessel van der Kolk", "9780143127741", "Understanding trauma's effects on mind and body and paths to healing."),
        ("Bad Blood: Secrets and Lies in a Silicon Valley Startup", "John Carreyrou", "9781524731656", "The rise and scandalous fall of Elizabeth Holmes and Theranos."),
        ("Steve Jobs", "Walter Isaacson", "9781451648539", "Biography of Apple's visionary co-founder."),
        ("Guns, Germs, and Steel", "Jared Diamond", "9780393317558", "Geographic determinism in human historical progress."),
        ("The Emperor of All Maladies", "Siddhartha Mukherjee", "9781439170915", "A biography of cancer from ancient records to modern treatments."),
        ("The Gene: An Intimate History", "Siddhartha Mukherjee", "9781476733500", "The story of genetics and human heredity."),
        ("Fast Food Nation", "Eric Schlosser", "9780547750330", "The dark side of the all-American meal and industrial food production."),
        ("The Omnivore's Dilemma", "Michael Pollan", "9780143038580", "A natural history of four meals and food sourcing choices."),
        ("How to Change Your Mind", "Michael Pollan", "9781594204227", "What the new science of psychedelics teaches us about consciousness."),
        ("Atomic Habits", "James Clear", "9780735211292", "Small habits that deliver remarkable results over time."),
        ("The Design of Everyday Things", "Don Norman", "9780465050659", "Why usable design matters in human-centered products."),
        ("Zero to One", "Peter Thiel", "9780804139298", "Notes on startups and how to build the future."),
        ("The Lean Startup", "Eric Ries", "9780307887894", "How today's entrepreneurs use continuous innovation to build radically successful businesses."),
        ("The Hard Thing About Hard Things", "Ben Horowitz", "9780062273208", "Building a business when there are no easy answers."),
        ("Shoe Dog", "Phil Knight", "9781501135910", "Memoir by the creator of Nike."),
        ("Deep Work", "Cal Newport", "9781455586691", "Focused success in a distracted world."),
        ("Drive: The Surprising Truth About What Motivates Us", "Daniel H. Pink", "9781594488849", "Autonomy, mastery, and purpose as true motivators."),
        ("To Sell Is Human", "Daniel H. Pink", "9781594487156", "The surprising truth about moving others in work and life."),
        ("Predictably Irrational", "Dan Ariely", "9780061353246", "The hidden forces that shape our decisions."),
        ("Nudge", "Richard H. Thaler & Cass R. Sunstein", "9780143115267", "Improving decisions about health, wealth, and happiness."),
        ("The Power of Habit", "Charles Duhigg", "9780812981605", "Why we do what we do in life and business.")
    ]
}

def escape_sql_str(val):
    return val.replace("'", "''")

def main():
    target_path = r"c:\pdd1\database\seed_books.sql"
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    
    statements = []
    statements.append("-- PageMind Database Seed Script: 525 Books across 15 Genres\n")
    statements.append("USE pagemind_db;\n\n")
    statements.append("-- Disable checks for clean bulk insertion\n")
    statements.append("SET FOREIGN_KEY_CHECKS = 0;\n")
    statements.append("TRUNCATE TABLE books;\n")
    statements.append("SET FOREIGN_KEY_CHECKS = 1;\n\n")

    count = 0
    for genre, books in GENRE_DATA.items():
        statements.append(f"-- =======================================================\n")
        statements.append(f"-- Genre: {genre} ({len(books)} books)\n")
        statements.append(f"-- =======================================================\n")
        
        for title, author, isbn, desc in books:
            count += 1
            e_title = escape_sql_str(title)
            e_author = escape_sql_str(author)
            e_genre = escape_sql_str(genre)
            e_desc = escape_sql_str(desc)
            
            # Cover URL: OpenLibrary ISBN URL or generic placeholder fallback
            if isbn:
                cover_url = f"https://covers.openlibrary.org/b/isbn/{isbn}-L.jpg"
            else:
                cover_url = f"https://via.placeholder.com/300x450/1e1b4b/a5b4fc?text={urllib.parse.quote(title)}"
            e_cover_url = escape_sql_str(cover_url)
            
            # Construct buy links JSON
            amazon_url = f"https://www.amazon.in/s?k={urllib.parse.quote(f'{title} {author}')}"
            flipkart_url = f"https://www.flipkart.com/search?q={urllib.parse.quote(f'{title} {author}')}"
            
            buy_links_dict = {
                "amazon": amazon_url,
                "flipkart": flipkart_url
            }
            buy_links_json = json.dumps(buy_links_dict)
            e_buy_links_json = escape_sql_str(buy_links_json)
            
            pub_year = get_published_year(title, author, genre, desc, isbn)

            
            rating = get_rating(title, author)

            
            sql = f"INSERT INTO books (title, author, genre, description, cover_url, buy_links_json, published_year, rating) VALUES ('{e_title}', '{e_author}', '{e_genre}', '{e_desc}', '{e_cover_url}', '{e_buy_links_json}', {pub_year}, {rating});\n"
            statements.append(sql)
            
        statements.append("\n")

    with open(target_path, "w", encoding="utf-8") as f:
        f.writelines(statements)

    print(f"Successfully generated {target_path} with {count} book insert statements across {len(GENRE_DATA)} genres!")

if __name__ == "__main__":
    main()
